INRIA/spoon

src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/test/java/spoon/test/executable/ExecutableRefTest.java, src/test/java/spoon/test/executable/ExecutableRefTestSource.java
getActualMethod threw an OutOfBoundsException because it wasn't ensured that the java Method instance and the ExecutableRef have the same amount of parameters ([introduced here](https://github.com/INRIA/spoon/commit/ab6118bfd52e18cc5d296a70a89bebb1b222ea58#diff-21aad886cfe9c33552d811cbb87e539eL240)). Also fixes a bug that getActualMethod and getActualClass returned null because of using getActualTypeParameters instead of getParameters..
Also this PR refactors the code of the methods and removes a unnecessary variable
=> fixes two bugs introduces by ab6118b 

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/testclasses/ClientClass.java, src/test/java/spoon/test/imports/testclasses/internal/ChildClass.java, src/test/java/spoon/test/imports/testclasses/internal/SuperClass.java
Sets the declaring type of a class with its enclosing type if we have a correct visibility to it or uses the super class of the current class analyzed to access at the correct declaring type. And adds test case in ImportTest class.
=> fix #114 Import of an inner class in a class package.

src/main/java/spoon/reflect/declaration/ModifierKind.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
Remove uneeded toLowerCase() method call as the lower case version is cached in the Enum type instances and returned by toString().
=> Remove uneeded toLowerCase() method call as the lower case version is

src/main/java/spoon/reflect/declaration/CtAnnotation.java, src/main/java/spoon/support/compiler/jdt/ParentExiter.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/annotation/testclasses/Foo.java
Changes inheritance of the CtAnnotation interface from `CtElement` to `CtExpression`. So we can add a `CtAnnotation` inner another `CtAnnotation` or an array in a `CtAnnotation`. And adds the test case in `AnnotationTest` class.
=> fix #60 when there are array of annotations in an annotation.

src/main/java/spoon/reflect/reference/CtUnboundVariableReference.java, src/main/java/spoon/reflect/visitor/CtAbstractVisitor.java, src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/reflect/visitor/CtVisitor.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/main/java/spoon/support/reflect/eval/VisitorSymbolicEvaluator.java, src/main/java/spoon/support/reflect/reference/CtUnboundVariableReferenceImpl.java, src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/test/signature/SignatureTest.java
Modifying CtVisitor and its subtypes for managing UnboundVariableReference elements. This change allows us to modify Signature for printing correctly the signature of Unbound elements
=> modifying CtVisitor and its subtypes for managing UnboundVariableReference

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/testclasses/DefaultClientClass.java, src/test/java/spoon/test/imports/testclasses/internal/PublicSuperClass.java
For the issue #114, we have proposed a fix to access at a inner class in a super class with a default visibility. This fix works in this specific case but not in other cases. Waiting for a new PR about the issue concerned,
I propose this roll back.
=> revert #114 to rollback on a previous state of JDTTreeBuilder.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/reference/FooBar.java, src/test/java/spoon/test/reference/VariableAccessTest.java, src/test/java/spoon/test/secondaryclasses/ClassesTest.java
- Lets JDT computes anonymous class name.
- Gives a name for anonymous classes for elements and references.
- Fixes getDeclaration method in CtTypeReference to access at anonymous class elements.
=> fix #126 Declaration of an executable reference is null in anonymous class

src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java, src/test/java/spoon/test/fieldaccesses/testclasses/Foo.java
Target of `CtFieldAccess` can be `CtThisAccess` if there is a "this" explicit or null if there is none.
=> Adds test case about target of CtFieldAccess.

src/main/java/spoon/reflect/visitor/Filter.java, src/main/java/spoon/reflect/visitor/QueryVisitor.java, src/main/java/spoon/reflect/visitor/filter/AbstractFilter.java, src/main/java/spoon/reflect/visitor/filter/AnnotationFilter.java, src/main/java/spoon/reflect/visitor/filter/CompositeFilter.java, src/main/java/spoon/reflect/visitor/filter/FieldAccessFilter.java, src/main/java/spoon/reflect/visitor/filter/InvocationFilter.java, src/main/java/spoon/reflect/visitor/filter/ReturnOrThrowFilter.java, src/main/java/spoon/reflect/visitor/filter/TypeFilter.java, src/main/java/spoon/reflect/visitor/filter/VariableAccessFilter.java, src/main/java/spoon/support/template/SubstitutionVisitor.java, src/test/java/spoon/test/filters/FilterTest.java, src/test/java/spoon/test/filters/Foo.java, src/test/java/spoon/test/reference/ExecutableReferenceGenericTest.java
1) uses runtime reflection instead of explicit and duplicate static typing
2) consequently, removes one of the oldest todos of Spoon
2) simplifies the API of filters (now only one method "matches")
3) adds test cases for the untested filters
4) cleans FieldAccesFilter, now a subtype of VariableAccessFilter
=> refactors the filtering API

src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/test/comparison/EqualTest.java, src/test/java/spoon/test/signature/SignatureTest.java
The signature printer loses information by printing invocation and literals.
=> Changes in Signature Printer and Test Cases

src/test/java/spoon/test/visibility/VisibilityTest.java, src/test/java/spoon/test/visibility/testclasses/Float.java, src/test/java/spoon/test/visibility/testclasses/UseDouble.java, src/test/java/spoon/test/visibility/testclasses/internal/Double.java
A bug has been reported but it can't be reproduced in a test case.
testVisibilityOfClassesNamedByClassesInJavaLangPackage in VisibilityTest
class test custom Double and Float classes used in another class. We
check than these classes is well typed in the model and can be build.
Closes #163
=> test: Imports custom classes rather than java lang classes.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/generics/GenericsTest.java
When we build a CtClass, we check if we have a anonymous class with
a super interface and with generic types to put them in formal type
of the anonymous class.
Closes #156
=> fix: give an access of generic types in anonymous classes.

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ImportScanner.java, src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/support/StandardEnvironment.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java, src/test/java/spoon/test/prettyprinter/testclasses/AClass.java
Creates a new computeImports method in ImportScanner to compute imports
of all elements. So, for the future, if we would like qualified name
in toString of elements, we must to specify it in the environment.
Closes #162
=> fix: Prints toString of elements with imports (no qualified named).

src/main/java/spoon/support/visitor/TypeReferenceScanner.java, src/test/java/spoon/test/api/NoClasspathTest.java, src/test/java/spoon/test/api/testclasses/Bar.java
Before, in the TypeReferenceScanner, if the enclosing reference
of the current reference is already in the set of references,
we didn't add it in the set. Now, we add all in set and the Set
class remove all duplicate items.
Closes #174
=> fix: Adds all references via TypeReferenceScanner.

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/TestUtils.java, src/test/java/spoon/test/visibility/VisibilityTest.java, src/test/java/spoon/test/visibility/testclasses/A.java
When we visit CtTypeReference in DefaultJavaPrettyPrinter, we check if
the current reference doesn't use generic types, if it isn't declared
in a method, if the declaring type is a CtType and if this declaring
type use generic types to write the fully qualified name.
Closes #146
=> fix: Writes fully qualified names of CtTypeReferene when its declaring type uses generics.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/compiler/jdt/ParentExiter.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/annotation/testclasses/AnnotationDefaultAnnotation.java
Adds more context in the JDTTreeBuilder class to know when we initialize
a default expression for fields in annotations. This context is used in
ParentExiter to print default value when it is necessary.
=> fix(annotation): Adds a default expression for fields typed by an annotation

src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java, src/test/java/spoon/reflect/declaration/testclasses/ExtendsObject.java, src/test/java/spoon/reflect/declaration/testclasses/Subclass.java, src/test/java/spoon/reflect/declaration/testclasses/Subinterface.java, src/test/java/spoon/reflect/declaration/testclasses/TestInterface.java
Declaration was casted to a class object always, but an InterfaceTypeReference has the superclass method too and an interface isn't a class. In this case a ClassCastException occurred
=> fixes CtTypeInformation.getSuperclass bug

src/main/java/spoon/reflect/declaration/CtType.java, src/main/java/spoon/support/reflect/declaration/CtClassImpl.java, src/main/java/spoon/support/reflect/declaration/CtInterfaceImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java, src/test/java/spoon/reflect/declaration/testclasses/Subclass.java, src/test/java/spoon/reflect/declaration/testclasses/Subinterface.java, src/test/java/spoon/test/annotation/AnnotationTest.java
bug: ClassCastException for CtAnnotationType
boy scout rule:
- adds the missing tests
- clarifies the contract of getAllMethods
this bug was surfaced by @seintur in #210
=> fixes a bug in getAllMethods

src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/interfaces/InterfaceTest.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java, src/test/java/spoon/test/trycatch/TryCatchTest.java
uses the System.lineSeparator() method instead of \n. This fixes the windows test failures #208 
[The new windows console output looks like this](https://gist.github.com/boeserwolf91/193a9e8c9867adb50ef2). There are still thousands of warnings, but the tests do not fail anymore.
=> fixes bugs with wrong line separators

src/main/java/spoon/reflect/reference/CtTypeReference.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java, src/test/java/spoon/test/fieldaccesses/InternalSuperCall.java
1. Creates a SuperAccess node when we have a QualifiedSuperReference.
In this case, we create a CtTypeAccess for the target of the super access.
2. Removes useless methods in CtTypeReference to know if it is a super
reference or not. So, we remove its usafe in JDTTreeBuilder and
DefaultJavaPrettyPrinter.
3. Creates a test case to test than we have a SuperAccess node in these
cases.
=> fix(super): Gets a SuperAccess node in qualified super reference or not.

src/main/java/spoon/reflect/code/CtTargetedAccess.java
=> doc: Removes CtThisAccess reference in the javadoc of CtTargetedAccess.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/invocations/InvocationTest.java, src/test/java/spoon/test/invocations/testclasses/Foo.java
When we have: 
```java
String.valueOf(0);
java.lang.String.valueOf(0);
```
The target of the first one was a `CtTypeAccess` and the second one a `CtVariableAccess`. Now, both are a `CtTypeAccess`.
=> fix(invocation): Gets a CtTypeAccess for all static invocations.

pom.xml, src/main/java/spoon/support/reflect/code/CtCaseImpl.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
Removes usage of java 8 classes in the project and adds a maven plugin
to check if we don't use methods in java version higher than Java 1.6.
Closes #237
=> fix(jdk8): Makes spoon compatible with Java 1.6.

src/main/java/spoon/reflect/code/CtArrayRead.java, src/main/java/spoon/reflect/code/CtArrayWrite.java, src/main/java/spoon/reflect/code/CtFieldRead.java, src/main/java/spoon/reflect/code/CtFieldWrite.java, src/main/java/spoon/reflect/code/CtSuperAccess.java, src/main/java/spoon/reflect/code/CtTargetedAccess.java, src/main/java/spoon/reflect/code/CtVariableRead.java, src/main/java/spoon/reflect/code/CtVariableWrite.java, src/main/java/spoon/reflect/factory/CoreFactory.java
1. Adds deprecated information in CtTargetedAccess to explain that
methods have been moved in CtFieldAccess and the new class will be
CtTargetedExpression.
2. Adds examples code in Ct*Read and Ct*Write interfaces.
=> doc(access): Explains changes in the AST for access concepts.

src/main/java/spoon/support/reflect/code/CtAssertImpl.java, src/main/java/spoon/support/reflect/code/CtContinueImpl.java, src/main/java/spoon/support/reflect/code/CtFieldAccessImpl.java, src/main/java/spoon/support/reflect/code/CtForImpl.java, src/main/java/spoon/support/reflect/code/CtIfImpl.java, src/main/java/spoon/support/reflect/code/CtLocalVariableImpl.java, src/main/java/spoon/support/reflect/code/CtLoopImpl.java, src/main/java/spoon/support/reflect/code/CtReturnImpl.java, src/main/java/spoon/support/reflect/code/CtTargetedAccessImpl.java, src/main/java/spoon/support/reflect/code/CtTargetedExpressionImpl.java, src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java, src/test/java/spoon/test/targeted/TargetedExpressionTest.java
=> Allow to assign null AST childs after non-null

src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/test/annotation/AnnotationTest.java
Class#getName() returns a pattern of the form "_type_name_$nested" for nested types whereas CtAnnotation#getAnnotationType() returns a pattern of the form "_type_name.nested". The dollar character needs to be replaced by the dot character for the equality to match.
=> Bug fix for nested annotation types.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/resources/import-resources/fr/inria/MissingImport.java
I triggered an issue with packaging and incomplete sources.
For example if a class is missing (generated or something like that).
The file add a import
package com.abcd.project2
import com.abcd.project1.MyClass
void aa() {
new MyClass();
}
The MyClass object will be reported as com.abcd.project2.MyClass. Even if the class is not present we explicitly have an import. Shouldn't we use the import?
=> Fix Type package with incomplete sources

src/main/java/spoon/reflect/visitor/CtScanner.java, src/test/java/spoon/test/reflect/visitor/ReferenceQueryTest.java, src/test/java/spoon/test/reflect/visitor/ReferenceQueryTestEnum.java
* Additional change - Eclipse project file removed as without the
.classpath file the imported project is erroneous, the .classpath file
is subject to evolving 3rd party libraries therefore added instructions
to generate a valid Eclipse project using Maven.
=> Scanning of constructors in Enums added to CtScanner

src/main/java/spoon/reflect/ModelElementContainerDefaultCapacities.java, src/main/java/spoon/reflect/code/CtConstructorCall.java, src/main/java/spoon/reflect/factory/CoreFactory.java, src/main/java/spoon/reflect/reference/CtGenericElementReference.java, src/main/java/spoon/reflect/reference/CtImplicitTypeReference.java, src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/DefaultCoreFactory.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtImplicitTypeReferenceImpl.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses/IBurritos.java, src/test/java/spoon/test/generics/testclasses/ITacos.java, src/test/java/spoon/test/generics/testclasses/Tacos.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
With this PR, when the source code uses the diamond syntax, Spoon prints also the diamond syntax but saves expected types in the generic types.
So we let the compiler of the developer handle generic types in the diamond and we allow the possibility to Spoon users to manipule expected types.
=> Uses diamond syntax for elements with actual generics

pom.xml
the change fixes #308 
The problem was a type inference problem at [this point](https://github.com/CubeEngine/core/blob/sponge/coremodule/src/main/java/org/cubeengine/service/user/SpongeUserManager.java#L436)
The ecj compiler had problems with the reference ```Record1::value1```. The debugger showed this warning:
``` 
Filename : D:\Programmieren\CubeEngine\core\coremodule\src\main\java\org\cubeengine\service\user\SpongeUserManager.java
COMPILED type(s)    
2 PROBLEM(s) detected 
- Pb(201) Cannot make a static reference to the non-static method value1(Object) from the type Record1
- Pb(19) Type mismatch: cannot convert from Set<Object> to Set<UInteger>
```
changing the line to
```java
return database.getDSL().select(TABLE_USER.KEY).from(TABLE_USER).fetch().stream().map(Record1<UInteger>::va …
```
=> updates the ecj version

src/test/java/spoon/test/imports/ImportTest.java
This PR fixes a missing import which was introduced today with [this pr](https://github.com/INRIA/spoon/pull/315/files). I guess @GerardPaligot deleted the import and at the same time another PR used the import. Therefore travis succeed and the mistake wasn't noticed. Anyway. This adds the import again.
=> the TypeFilter import is missing in the ImportTest class

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java, src/test/java/spoon/test/prettyprinter/testclasses/AClass.java
This pull request removes the variable ignoreImport in DefaultJavaPrettyPrinter
which was used to force the use of qualified name for generics.
=> removes ingoreImport in DefaultJavaPrettyPrinter

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/testclasses/ClassWithInvocation.java
The ```ImportScanner``` ignored some elements of invocations such as invocation arguments.
With this pull request, ```ImportScanner``` scans annotations, cast, target and arguments of all invocations.
=> fixes the auto-import of CtInvocations

pom.xml, src/main/java/spoon/Launcher.java, src/main/java/spoon/SpoonAPI.java, src/main/java/spoon/SpoonModelBuilder.java, src/main/java/spoon/compiler/Environment.java, src/main/java/spoon/support/StandardEnvironment.java, src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/test/java/spoon/LauncherTest.java, src/test/java/spoon/test/api/APITest.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/intercession/IntercessionTest.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/methodreference/MethodReferenceTest.java, src/test/java/spoon/test/pkg/PackageTest.java, src/test/java/spoon/test/staticFieldAccess/StaticAccessTest.java, src/test/java/spoon/test/visibility/VisibilityTest.java
- Creates 4 new methods in SpoonAPI : `setSourceOutputDirectory(String | File)` and `setBinaryOutputDirectory(String | File)`.
- Creates 4 new methods in SpoonModelBuilder : `set/getSourceOutputDirectory()` and `set/getBinaryOutputDirectory()`.
- Deprecates older methods.
- Adds 2 test cases for the source output and the binary output.
=> Refactor source and binary outputs of Spoon.

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java, src/test/java/spoon/test/prettyprinter/testclasses/TypeIdentifierCollision.java, src/test/java/spoon/test/prettyprinter/testclasses/sub/TypeIdentifierCollision.java
- before the toString() method was simply used which does not take
account of the compilation unit's context.
* Removed the compute imports statement from CtElement's toString()
method as it has no context and therefore it cannot assume the
corresponding import is present that would allow it to be shown in
the shortened version.
* Added test to catch some edge cases in the shortening of identifiers
that may produce ambiguous/invalid code and updated ones that relied on
the toString() method to calculate the shorthand names.
* Made some minor modifications to remove some warnings in the code
as flagged by the IDE.
=> Added correct handling for enum's listed in an enum definition (CtEnum)

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/variable/AccessTest.java, src/test/java/spoon/test/variable/testclasses/ArrayAccessSample.java
Introduces test to validate if s[0] = s[1] has one write and one read.
Fixes the problem of considering all Ct{Variable, Field, Array}Access with an CtAssignment as a parent as Writes.
This is fixed by creating a context variable assigned that is turned on on the LHS of the assignment only.
=> Fixed array[index] on RHS of assignment being considered ArrayWrite

src/test/java/spoon/test/snippets/SnippetTest.java
=> test: Adds a test case to compile snippets several times.

.travis.yml
Now, Travis is using containers to build projects. To use this
new architecture, we must add "sudo: false". That's all.
And we change the mvn command from test to verify to apply
checkstyle plugin in travis builds.
=> chore: Updates travis to the new architecture and change mvn cmd.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/declaration/CtClassImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java, src/test/java/spoon/test/constructorcallnewclass/testclasses/Foo2.java, src/test/java/spoon/test/ctClass/CtClassTest.java, src/test/java/spoon/test/ctClass/testclasses/Foo.java
The anonymous classname was not correct when there are more than 9 anonymous per class.
The method CtClass.getConstructor did not return the correct constructor when there are serveral contructors with array/matrix parameter.
=> Fix anonymous classname and CtClass.getConstructor

src/main/java/spoon/reflect/factory/Factory.java, src/main/java/spoon/reflect/factory/FactoryImpl.java, src/main/java/spoon/reflect/factory/InternalFactory.java, src/main/java/spoon/reflect/internal/CtCircularTypeReference.java, src/main/java/spoon/reflect/visitor/CtAbstractVisitor.java, src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/reflect/visitor/CtVisitor.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/DefaultInternalFactory.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/main/java/spoon/support/reflect/internal/CtCircularTypeReferenceImpl.java, src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/java/spoon/test/reference/testclasses/Tacos.java
When you have an invocation to a method with this
kind of reference : <T extends Comparable<? extends T>>,
you got a circular reference and a StackOverflowException.
With this PR, we add a cache which detects circular references
in JDTTreeBuilder and uses this information in
CtScanner and DefaultJavaPrettyPrinter.
Closes #368
=> fix: Circular references with generic types.

src/main/java/spoon/reflect/factory/CoreFactory.java, src/main/java/spoon/reflect/factory/InternalFactory.java, src/main/java/spoon/reflect/internal/CtImplicitTypeReference.java, src/main/java/spoon/reflect/visitor/CtAbstractVisitor.java, src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/reflect/visitor/CtVisitor.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/support/DefaultCoreFactory.java, src/main/java/spoon/support/DefaultInternalFactory.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/main/java/spoon/support/reflect/internal/CtImplicitTypeReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/lambda/testclasses/Bar.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
From now, we don't re-print type of parameters of lambda
if original sources don't specify it. We print the name
of these parameters and we save the expected type in the
AST.
Issue #368
=> fix: Parameters in a lambda expression.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java, src/test/java/spoon/test/fieldaccesses/testclasses/Panini.java
Fix bug introduced by [this commit](https://github.com/INRIA/spoon/commit/0413f94fb680884f7dba05e2ebba54dd6510ea1c?diff=unified) about field read access.
=> fix(access): Writes correctly field access in anonymous type.

src/main/java/spoon/reflect/visitor/CtScanner.java, src/test/java/spoon/test/refactoring/RefactoringTest.java, src/test/java/spoon/test/refactoring/testclasses/AClass.java
When rewriting a type instanceof expressions are not updated with the new type.
=> Missing CtTypeReference for instanceof expressions when querying.

src/main/java/spoon/Launcher.java, src/main/java/spoon/SpoonModelBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/test/java/spoon/test/properties/PropertiesTest.java, src/test/java/spoon/test/staticFieldAccess/StaticAccessTest.java
In SpoonModelBuilder, we had two methods very semilar in their
signature. To avoid confusing these methods, we deprecates one of
them with a method name more explicit.
=> refactor(api): Deprecates process method for a new one.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/java/spoon/test/reference/testclasses/EnumValue.java
Hotfix for the version 4.4.0. This PR is on stable branch.
Closes #408
=> fix(circular): Supports circular type reference on declaring method.

src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/reference/ExecutableReferenceTest.java, src/test/java/spoon/test/reference/testclasses/Burritos.java
When the type reference doesn't have a parent, the method
throws a NPE.
Closes #409
=> fix: Avoid NPE in CtTypeReference#getAllExecutables.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
The  ```<T> ``` at https://github.com/apache/commons-lang/blob/740c0f95fbd99cb7c07bcf7c54bc077c3ab27bd1/src/main/java/org/apache/commons/lang3/SerializationUtils.java#L267 is automatically inferred to  ```Object ``` by JTD. 
Thus the JDT method ```messageSend.genericTypeArguments()``` return the class  ```Object ``` and not  ```<T> ```. This implies that the Spoon AST is not correct.
This PR fix the Spoon AST but I cannot reproduce this error with a test.
Fill free to complete this PR with a test.
=> Infered generic type

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/compiler/jdt/ParentExiter.java, src/test/java/spoon/test/TestUtils.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/constructor/ConstructorTest.java, src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/invocations/InvocationTest.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/methodreference/MethodReferenceTest.java, src/test/java/spoon/test/visibility/VisibilityTest.java, src/test/resources/new-class/IndexWriter.java
If the PR is ok for everyone, I can squash commits in only one.
Closes #406
=> Fix NPE in anonymous class in noclasspath mode.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/code/CtInvocationImpl.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
In CtInvocation#getType(), we use getExecutable().getType.
In CtInvocation#setType(), we throw an UnsupportedOperationException.
Closes #418
=> refactor: Use get/setType methods with executable in CtInvocation.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java, src/test/java/spoon/test/executable/ExecutableRefTest.java, src/test/resources/executable/CmiContext_1.2.java
=> fix(executable): Supports CtConstructorCall in noclasspath mode.

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/testclasses/Mole.java, src/test/java/spoon/test/imports/testclasses/Pozole.java, src/test/java/spoon/test/imports/testclasses/internal2/Chimichanga.java, src/test/java/spoon/test/imports/testclasses/internal2/Menudo.java
shouldn't import invoked method declaration classes
=> Fix a bug in ImportScannerImpl.visitCtInvocation

src/main/java/spoon/reflect/declaration/CtElement.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/test/delete/DeleteTest.java, src/test/java/spoon/test/delete/testclasses/Adobada.java
=> feat(delete): Allows delete any element in a Spoon AST.

src/main/java/spoon/support/reflect/declaration/CtAnonymousExecutableImpl.java, src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java, src/test/java/spoon/test/executable/ExecutableTest.java, src/test/java/spoon/test/executable/testclasses/AnonymousExecutableSample.java
=> refactor(getter): Never throw an UnsupportedOpException in getter.

src/main/java/spoon/reflect/declaration/CtElement.java, src/main/java/spoon/reflect/visitor/filter/AbstractFilter.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/test/parent/Foo.java, src/test/java/spoon/test/parent/ParentTest.java
This pull request adds the method ```getParent(Filter)``` in order to be able to select a specific parent.
The method ```return null``` if no match is found
=> Add getParent(Filter)

src/main/java/spoon/reflect/cu/SourcePosition.java, src/main/java/spoon/reflect/factory/CoreFactory.java, src/main/java/spoon/support/DefaultCoreFactory.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/cu/SourcePositionImpl.java, src/test/java/spoon/test/position/PositionTest.java, src/test/java/spoon/test/position/testclasses/FooMethod.java
The line number of a ```CtNamedElement``` is now the line where the developer declares the name.
=> [fix #431] Change the line number of all CtNamedElements

src/main/java/spoon/reflect/factory/ClassFactory.java, src/main/java/spoon/reflect/factory/PackageFactory.java, src/main/java/spoon/support/compiler/SnippetCompilationHelper.java, src/test/java/spoon/test/snippets/SnippetTest.java
=> [fix #304] Refactor Snippet helper

src/main/java/spoon/support/reflect/code/CtStatementImpl.java, src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/test/processing/ProcessingTest.java, src/test/java/spoon/test/processing/SampleForInsertBefore.java
There is the same bug on insertAfter, but i didn't succeed to fix it.
=> Fix bug related to "insertBefore()" and "getSignature()"

src/main/java/spoon/reflect/reference/CtExecutableReference.java, src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/test/signature/SignatureTest.java
When we are in noclasspath and don't have the information
about arguments of CtExecutableReference, we display
<unknown> in arguments.
Closes #454
=> feat(signature): Specify the display for executable ref.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/java/spoon/test/variable/AccessTest.java, src/test/resources/noclasspath/Demo.java
=> fix(noclasspath): Gets package of types in the class declaration.

doc/processor.md, src/main/java/spoon/processing/AbstractManualProcessor.java, src/main/java/spoon/processing/AbstractProcessor.java, src/main/java/spoon/processing/ProcessInterruption.java, src/main/java/spoon/processing/Processor.java, src/main/java/spoon/support/QueueProcessingManager.java, src/main/java/spoon/support/RuntimeProcessingManager.java, src/test/java/spoon/processing/ProcessingTest.java, src/test/java/spoon/processing/processors/MyProcessor.java
=> feat(process): Allows interruption of a processor.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/fieldaccesses/BUG20160112.java, src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java
=> fixed the FieldWrite bug in OperatorAssignment

src/main/java/spoon/reflect/factory/TypeFactory.java, src/test/java/spoon/test/secondaryclasses/ClassesTest.java, src/test/java/spoon/test/secondaryclasses/testclasses/Pozole.java
=> fix(anonymous): getDeclaration throws a NPE in anonymous class.

src/main/java/spoon/reflect/declaration/CtType.java, src/main/java/spoon/reflect/declaration/CtTypeInformation.java, src/main/java/spoon/reflect/factory/TypeFactory.java, src/main/java/spoon/reflect/reference/CtTypeReference.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/targeted/TargetedExpressionTest.java, src/test/java/spoon/test/targeted/testclasses/Tapas.java
Closes https://github.com/INRIA/spoon/issues/507
=> A class can be declared in a lambda expression.

src/main/java/spoon/reflect/declaration/CtType.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/resources/noclasspath/A.java
=> fix(noclasspath): NPE throws with annotations on primitive type.

src/main/java/spoon/reflect/declaration/CtElement.java, src/main/java/spoon/reflect/declaration/CtExecutable.java, src/main/java/spoon/reflect/factory/MethodFactory.java, src/main/java/spoon/reflect/visitor/CtAbstractVisitor.java, src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtVariableReferenceImpl.java, src/main/java/spoon/support/visitor/EqualVisitor.java, src/main/java/spoon/support/visitor/HashcodeVisitor.java, src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java, src/test/java/spoon/test/comparison/EqualTest.java, src/test/java/spoon/test/intercession/IntercessionTest.java, src/test/java/spoon/test/main/MainTest.java, src/test/java/spoon/test/parent/ParentTest.java, src/test/java/spoon/test/reference/ExecutableReferenceGenericTest.java, src/test/java/spoon/test/signature/SignatureTest.java, src/test/java/spoon/test/targeted/TargetedExpressionTest.java
Before:
The three responsibilities of equals/hashCode/signature were handled by the same code in SignaturePrinter,
with two major problems:
- no deep equality for package, class and method
- low performance of hashCode
Now:
The three responsibilities are handled by three different visitors:
- SignaturePrinter for signatures
- EqualVisitor for equal
- HashcodeVisitor for equal
=> refactors the three responsibilities of equal/hashcode/signature

src/main/java/spoon/reflect/declaration/CtType.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/test/java/spoon/test/field/FieldTest.java, src/test/java/spoon/test/field/testclasses/AddFieldAtTop.java, src/test/resources/expected/AddFieldAtTop.java
=> feat(field): Adds field at the top of a type.

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java, src/test/java/spoon/test/fieldaccesses/testclasses/Tacos.java, src/test/java/spoon/test/fieldaccesses/testclasses/internal/Bar.java, src/test/java/spoon/test/fieldaccesses/testclasses/internal/Foo.java, src/test/java/spoon/test/generics/GenericsTest.java
=> fix(visibility): Field access declared in a default class.

src/main/java/spoon/reflect/declaration/CtAnnotation.java, src/main/java/spoon/reflect/factory/AnnotationFactory.java, src/main/java/spoon/support/compiler/jdt/ParentExiter.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/test/java/spoon/test/annotation/AnnotationValuesTest.java, src/test/java/spoon/test/annotation/testclasses/AnnotationValues.java, src/test/java/spoon/test/factory/FactoryTest.java
=> annotation values with a Map<String,CtExpression>

src/main/java/spoon/support/compiler/jdt/TreeBuilderCompiler.java
Fix a bug in TreeBuilderCompiler.buildUnits() where a retured array is
longer then expected and the extra spaces are null. The method is updated
to use the **totalUnits** instance variable as the true element count in
the **unitsToProcess** array instead of the length of the array itself.
This bug broke processing of classes using method JDTBatchCompiler.getUnits() and
expecting every element in the returned array to be non-null.  The problem came up
when trying to process the source for a large GWT project.
=> fix bug: NPE when compilation units array contains null elements

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/comment/testclasses/InlineComment.java
=> fix(doc): Handles comments in CtNewArray and in CtConditional

src/main/java/spoon/reflect/visitor/CtScanner.java
Sorry I'm lazy to add a test for this because this is obviously a missing AST scanning branch, the test is going to be trivial from the source: "yes, we actually didn't visit execRef's parameters".
=> Add missing scanning of CtExecutableReference's parameters in CtScanner

src/main/java/spoon/Launcher.java, src/main/java/spoon/SpoonAPI.java, src/main/java/spoon/reflect/CtModel.java, src/main/java/spoon/reflect/CtModelImpl.java, src/main/java/spoon/reflect/declaration/CtPackage.java, src/main/java/spoon/reflect/factory/CompilationUnitFactory.java, src/main/java/spoon/reflect/factory/Factory.java, src/main/java/spoon/reflect/factory/FactoryImpl.java, src/main/java/spoon/reflect/factory/PackageFactory.java, src/main/java/spoon/reflect/factory/TypeFactory.java, src/main/java/spoon/reflect/visitor/filter/AbstractFilter.java, src/main/java/spoon/support/DefaultCoreFactory.java, src/main/java/spoon/support/reflect/declaration/CtNamedElementImpl.java, src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java, src/test/java/spoon/test/architecture/SpoonArchitectureEnforcer.java, src/test/java/spoon/test/factory/FactoryTest.java, src/test/java/spoon/test/factory/testclasses2/Baz.java, src/test/java/spoon/test/parent/ParentContractTest.java
Currently, the notion of "model" in Spoon is implicit, and the factory takes this role. However, it's not the way it should be. It's been a long time we wanted to introduce `CtModel`, #584 triggered it. 
The tentative interface is:
```
/** represents a Java program, modeled by a set of compile-time (Ct) objects
* where each objects is a program element (for instance, a CtClass represents a class).
*/
public interface CtModel {
/** returns the root package */
CtPackage getRootPackage();
/** returns all types of the model */
Collection<CtType<?>> getAllTypes();
/** returns all packages of the model */
Collection<CtPackage> getAllPackages();
/** process this model with the given processor */
void processWith(Processor<?> processor);
}
```
The workflow of #584 is tested in …
=> introduces CtModel for #584

src/main/java/spoon/reflect/declaration/CtGenericElement.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationTypeImpl.java, src/main/java/spoon/support/reflect/declaration/CtConstructorImpl.java, src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/constructor/ConstructorTest.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses/Mole.java, src/test/java/spoon/test/intercession/IntercessionTest.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/java/spoon/test/targeted/TargetedExpressionTest.java, src/test/java/spoon/test/type/TypeTest.java, src/test/java/spoon/test/variable/AccessTest.java
=> CtGenericElement#formalTypeParameters use CtTypeParameterReference

src/main/java/spoon/reflect/visitor/filter/VariableAccessFilter.java, src/test/java/spoon/test/filters/FilterTest.java, src/test/java/spoon/test/filters/testclasses/FieldAccessFilterTacos.java
=> fix(filter): fixes NPE in VariableAccessFilter when the getVariable()  is null (e.g. super)

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/support/DefaultCoreFactory.java, src/main/java/spoon/support/reflect/code/CtBlockImpl.java, src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java, src/main/java/spoon/support/reflect/code/CtLambdaImpl.java, src/main/java/spoon/support/reflect/declaration/CtClassImpl.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/main/java/spoon/support/reflect/declaration/CtInterfaceImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtIntersectionTypeReferenceImpl.java, src/main/java/spoon/support/util/EmptyClearableList.java, src/main/java/spoon/support/util/EmptyClearableSet.java, src/main/java/spoon/support/util/EmptyIterator.java
... because otherwise they cannot conform both java.util.List and java.util.Set equals()/hashCode() contract; never use Collections.unmodifiableCollection() (if wrapping list or set) because it narrows possible use on the client side without actual need; try to avoid creating unmodifiableList/Set(children) wrapper when the wrapped children is already an empty collection
=> Improvements to collections: Make CtElementImpl.emptyList() and emptySet() DIFFERENT objects

src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/test/parent/ParentContractTest.java
An interesting enhancement can be to add `CtGenericElementReference` on `CtInvocation` to write something like this : `ctInvocation.getActualTypeArguments()`. For now, you must  pass by the `CtExecutableReference`: `ctInvocation.getExecutable().getActualTypeArguments()`. It isn't really easy to use.
What do you think @monperrus?
Closes #599
=> refactor(api): Uses actual types of executable ref in constructor call.

doc/command_line.md, doc/comments.md, src/main/java/spoon/Launcher.java, src/main/java/spoon/compiler/Environment.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/StandardEnvironment.java, src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/test/java/spoon/reflect/visitor/CtScannerTest.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/javadoc/JavaDocTest.java
Fixes for a diabolical issue! :fire:
Closes #666
=> feat(comment): Avoid parsing javadoc when it isn't necessary.

src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/test/parent/ParentTest.java
=> fix(parent): Avoid NPE with CtElement#hasParent(CtElement)

src/main/java/spoon/reflect/factory/TypeFactory.java
=> feat(factory): Creates factory methods for primitives.

src/main/java/spoon/reflect/factory/AnnotationFactory.java
So that they don't try to get annotation class in Spoon's runtime, because the annotation type shouldn't be in the spoon's runtime
=> Refactor AnnotationFactory's factory methods

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/comment/CommentTest.java
=> fix(comment): Allows usage of the new flag only.

src/main/java/spoon/generating/CloneVisitorGenerator.java, src/main/java/spoon/support/visitor/clone/CloneBuilder.java, src/test/java/spoon/test/method/MethodTest.java
=> Copy collections in CloneBuilder.

src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/support/visitor/clone/CloneVisitor.java, src/main/java/spoon/support/visitor/equals/EqualsVisitor.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/test/reference/ExecutableReferenceGenericTest.java, src/test/java/spoon/test/reference/VariableAccessTest.java, src/test/resources/noclasspath/Foo2.java
=> fix(clone): Scan declaring executable of CtParameterRef.

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/visibility/VisibilityTest.java, src/test/resources/noclasspath/Solver.java
=> fix(noclasspath): Mark target as implicit if it's an anonymous class.

src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/support/visitor/clone/CloneVisitor.java, src/main/java/spoon/support/visitor/equals/EqualsVisitor.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/reflect/ast/CloneTest.java, src/test/resources/spoon/test/visitor/ConditionalRes.java
Hello, TypeCast on CtConditional are not cloned or used in equals. Here an example:
Snippet code:
```java
public class ConditionalRes {
byte [] b = new byte [] { true ? 1 : 2};
}
```
Spoon code:
```java
@Test
public void testCloneCastConditional() throws Exception {
final Launcher launcher = new Launcher();
launcher.setSourceOutputDirectory("./target/trash");
launcher.addInputResource("./src/test/resources/spoon/test/visitor/ConditionalRes.java");
launcher.addProcessor(new AbstractProcessor<CtConditional<?>>() {
@Override
public void process(CtConditional<?> conditional) {
conditional.addTypeCast(getFactory().Type().bytePrimitiveType());
CtConditional clone = conditional.clone();
System.out.println(conditional);
System.out.println(clone);
System.out.println(conditional.equals(clone));
} …
```
=> fix: typecast on conditional

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/literal/LiteralTest.java, src/test/resources/noclasspath/LiteralInForEach.java
In some cases (an example is given in #755) Literal#constant may
be `null` and, thus, causes a NullPointerException when calling
`localDeclaration.initialization.traverse(this, scope);`. This
patch fixes the issue by resolving Literal#constant if required.
=> Resolve Literal#constant if required. Fixes #755.

src/main/java/spoon/template/BlockTemplate.java, src/main/java/spoon/template/ExpressionTemplate.java, src/main/java/spoon/template/StatementTemplate.java
There are a lot of tests [here](https://github.com/INRIA/spoon/tree/master/src/test/java/spoon/test/template) for templates but everything seems okay when we remove the second call.
Maybe @petitpre knows historical reasons? But it seems no longer necessary.
Closes #754
=> refactor(template): Removes the second call to get the declaring class.

src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/test/java/spoon/test/annotation/AnnotationValuesTest.java, src/test/java/spoon/test/annotation/testclasses/BoundNumber.java
=> fix(annotation): Supports enum fields with Annotation#annotate() method.

src/main/java/spoon/generating/replace/CtListener.java, src/main/java/spoon/reflect/reference/CtCatchVariableReference.java, src/main/java/spoon/reflect/reference/CtLocalVariableReference.java, src/main/java/spoon/reflect/reference/CtParameterReference.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/ContextBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/reference/CtCatchVariableReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtFieldReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtLocalVariableReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtParameterReferenceImpl.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/test/reference/CloneReferenceTest.java, src/test/java/spoon/test/reference/VariableAccessTest.java, src/test/java/spoon/test/reference/testclasses/Tortillas.java, src/test/resources/noclasspath/A2.java
This PR is a proposal for the issue #756.
On the issue, the solution proposed @fedorov-s-n was good but have 2 problems (specified by him): change the API and can throw an exception `ParentNotInitializeException` if the model isn't complete.
Me, I propose a solution widely inspired by @fedorov-s-n (big thanks to him) but I remove disadvantages: I haven't any change in the API and I handle the exception.
What do you think about it?
=> Lookup dynamically the declaration of all variable references

src/main/java/spoon/reflect/declaration/CtType.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java, src/test/java/spoon/reflect/declaration/testclasses/ExtendsObject.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/comparison/EqualTest.java, src/test/java/spoon/test/interfaces/InterfaceTest.java, src/test/java/spoon/test/signature/SignatureTest.java
thanks to the new and great runtime reflection API, we can have at last a correct implementation of getAllMethods
=> fix: getAllMethods returns all methods, incl. those of libraries and java.lang.Object

src/main/java/spoon/support/reflect/declaration/CtEnumImpl.java, src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java, src/test/java/spoon/test/reference/Enum.java, src/test/java/spoon/test/reference/ExecutableReferenceTest.java, src/test/java/spoon/test/reference/TypeReferenceTest.java
Generating `values()` and `valueOf()` methods on request. Methods are not accessible through `getMethods()`, because they aren't declared, but are accessible through `getAllMethods()`
=> fix for https://github.com/INRIA/spoon/issues/793

src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/api/NoClasspathTest.java
…hen the parent class is not found in noClassPath-Mode
This tries to fix #775.
=> support of noClassPath in getFields

src/main/java/spoon/reflect/factory/ExecutableFactory.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java, src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/parameters/ParameterTest.java, src/test/resources/noclasspath/Tacos.java
=> fix(noclasspath): Builds reference of a parameter in a lambda.

src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/test/java/spoon/reflect/declaration/UnknownDeclarationTest.java, src/test/resources/noclasspath/UnknownCalls.java
According to JavaDoc, `getDeclaringType()` may return null. Until now,
`getDeclaration`, does not handle the null case and, therefore, may
throw a NullPointerException. This exception is thrown most likely in
noclasspath mode.  Fixes #808.
=> Avoid NullPointerException in CtExecutableReferenceImpl.

src/main/java/spoon/reflect/factory/ExecutableFactory.java, src/test/java/spoon/test/executable/ExecutableTest.java, src/test/java/spoon/test/executable/testclasses/A.java
The method `ExecutableFactory#createReference` now supports static method.
Fix #817
=> fix(executable): fix the method ExecutableFactory#createReference

src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java
This PR does not contains any test because I did not succeed to reproduce the the failing scenario in the test environment.
The bug is related to this eclipse issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=388042
```bash
org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required .class files
at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:135)
at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:201)
at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2132)
at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.isClassPathCorrect(ProblemReporter.java:4162)
at …
```
=> fix(noclasspath): tolerates missing annotation types

.travis.yml, chore/check-links-in-doc.py, doc/_release/Release.md, doc/about.md, doc/command_line.md, doc/comments.md, doc/doc_homepage.md, doc/first_analysis_processor.md
=> chore(website): add a link checker

doc/doc_homepage.md, doc/gradle.md
=> improves Gradle doc 

src/main/java/spoon/reflect/declaration/CtType.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/test/java/spoon/test/ctType/CtTypeTest.java, src/test/java/spoon/test/ctType/testclasses/X.java
Hey all,
As suggested on the mailing list, here is a PR to add a method in CtType to know whether a given type has a method (inherited or not, abstract or implemented). Look at the Javadoc for more details. Let me know if you want me to change the behaviour of the added method (replacing PR 870).
=> Added a method to know whether a given method is part of a CtType

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java
Unfortunately, I can't give you an example as I didn't manage to create a minimal version exploiting this error. However, it should be obvious that `currentPackage` may be null.
=> Fixes potential NullPointerException in JDTTreeBuilderQuery.

src/main/java/spoon/reflect/factory/CodeFactory.java, src/main/java/spoon/support/reflect/reference/CtLocalVariableReferenceImpl.java, src/test/java/spoon/test/reference/VariableAccessTest.java
=> Fix getReference and getDeclaration for local type

pom.xml, src/main/java/spoon/Launcher.java, src/main/java/spoon/SpoonAPI.java, src/main/java/spoon/SpoonModelBuilder.java, src/main/java/spoon/compiler/Environment.java, src/main/java/spoon/compiler/SpoonCompiler.java, src/main/java/spoon/reflect/CtModelImpl.java, src/main/java/spoon/reflect/declaration/CtClass.java, src/main/java/spoon/reflect/factory/TypeFactory.java, src/main/java/spoon/support/StandardEnvironment.java, src/main/java/spoon/support/compiler/SnippetCompilationHelper.java, src/main/java/spoon/support/compiler/jdt/CompilationUnitWrapper.java, src/main/java/spoon/support/compiler/jdt/FactoryCompiler.java, src/main/java/spoon/support/compiler/jdt/FileCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTSnippetCompiler.java, src/main/java/spoon/support/reflect/code/CtStatementImpl.java, src/main/java/spoon/support/reflect/declaration/CtClassImpl.java, src/test/java/spoon/support/compiler/jdt/ExtendedStringLiteralTest.java, src/test/java/spoon/support/compiler/jdt/JDTBatchCompilerTest.java, src/test/java/spoon/test/compilation/CompilationTest.java, src/test/java/spoon/test/compilation/Ifoo.java, src/test/java/spoon/test/main/MainTest.java, src/test/java/spoon/test/trycatch/TryCatchTest.java
```java
// contract: a ctclass can be instantiated, and each modification results in a new valid object
Factory factory = new Launcher().getFactory();
CtClass c = factory.Code().createCodeSnippetStatement(
"class X implements spoon.test.compilation.Ifoo { public int foo() {int i=0; return i;} }").compile();
c.addModifier(ModifierKind.PUBLIC); // required otherwise java.lang.IllegalAccessException at runtime when instantiating
CtBlock body = c.getElements(new TypeFilter<>(CtBlock.class)).get(1);
Object o = c.newInstance();
assertEquals(0, ((Ifoo)o).foo());
for (int i=1; i<=10; i++) {
body.getStatement(0).replace(factory.Code().createCodeSnippetStatement("int i = "+i+";"));
o = c.newInstance();
// each time the behavior has changed!
assertEquals(i, ((Ifoo)o).foo());
}
```
=> feature(runtime): allow to instantiate any class at any time

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java, src/test/java/spoon/test/prettyprinter/testclasses/A.java
When pretty printing several Java types with auto-import, only the imports of the last type were considered.
This fix permits to gather all the imports of all the types.
=> fix(prettyprinter): only the imports of the last type were considered

src/test/java/spoon/LauncherTest.java
MS Windows uses backslash in file system path therefore this:
assertTrue(inputSources.get(0).getPath().contains("src/main/java"));
always fails on MS Windows
=> fix LauncherTest, which fails on MS Windows

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/arrays/ArraysTest.java, src/test/java/spoon/test/arrays/testclasses/NewArrayWithComment.java
In case of comment the last character is the last character of the
comment and not the ",".
=> fixes bug in printing of new Array with comment #911

src/main/java/spoon/support/compiler/FileSystemFile.java, src/main/java/spoon/support/compiler/FileSystemFolder.java
Contains
1. test which measures performance of VirtualFolder.getAllFiles() 
2. test which measures performance of VirtualFolder.getSubFolders() 
3. code which improves that performance.
The performance improvement consists of these changes:
1. FileSystemFile calls slow File.getCanonicalFile() only once in constructor. It is not called later. I hope it breaks nothing. Please check it.
2. FileSystemFolder calls slow File.getCanonicalFile() only once in constructor. It is not called later. I hope it breaks nothing. Please check it.
3.  VirtualFolder getAllFiles() and getSubFolders() uses helper HashSet to collect distinct set of files
Note: Before the test needed 80s on 900 files. After performance fix it needs 0.2s
Note: The usage of helper HashSet would be enough to fix performance of …
=> improves performance of VirtualFolder.getAllFiles()

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
The current prettyprint of ternary expressions (CtConditional) adds parentheses around the condition only when the parent is an assignment. The added test show that parentheses are also required on variable declaration.
The test shows that the mandatory parentheses that originally surround the condition are removed when pretty-printing the spooned code. This leads to ambiguous code that does not compile.
The fix adds the parentheses when the parent is a variable declaration.
Maybe the parentheses should be always added.
=> fixed(prettyprint): parentheses are missing when pretty-pretting some ternary expressions

src/main/java/spoon/reflect/factory/CompilationUnitFactory.java, src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTSnippetCompiler.java, src/test/java/spoon/test/comment/CommentTest.java
The comments in snippet was always ignored. This PR includes this:
- Test case which fails when comments are lost in snippet
- Implementation of comments in snippet
- new method `CompilationUnit JDTSnippetCompiler.getSnippetCompilationUnit()`, which returns CompilationUnit of the compilet snippet. Note: I had to remember the CompilationUnit of the snippet in the CompilationUnit cache, otherwise JDTCommentBuilder was not able to add comments. And at the end I removed that CU from the cache ... so it is now possible to access that CU from the JDTSnippetCompiler too.
It is the first chunk of changes suggested by PR #929
=> support of comments in snippet

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTSnippetCompiler.java
New method  JDTBasedSpoonCompiler.buildModel() was created and called on 3 places instead of 3 times implemented/copied code.
This PR depends on #930
=> Refactor - use JDTBasedSpoonCompiler.buildModel()

src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java
The compilation is done in two phases.
1) treeBuilderCompiler.buildUnits()
2) parser.dietParse() this call is processed for each result of the `treeBuilderCompiler.buildUnits()` and needs a CompilationUnit with the same name ... it is the same file which was used to produce the `unit` ... so we can use the CompilationUnit which is directly stored here `unit.compilationResult.compilationUnit`
I would like to have this change because
1) it makes code more readable
2) it makes clear that same compilation unit is used. Before the treeBuilderCompiler.buildUnits() worked with different input files, then parser.dietParse() ... it took me several hours until I recognized that both inputs should be always same.
3) the parameter `files` of the method `CompilationUnitDeclaration[] …
=> simplify JDTBatchCompiler.getUnits(). Reuse existing CU

src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/api/NoClasspathTest.java, src/test/java/spoon/test/delete/DeleteTest.java, src/test/java/spoon/test/generics/testclasses/Spaghetti.java, src/test/java/spoon/test/parent/ParentTest.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java, src/test/java/spoon/test/template/CheckBound.java
There are some unused imports in tests. Please merge this fix, so my workspace does not report confusing errors.
=> remove unused imports so the compilation in workspace passes

doc/command_line.md, src/main/java/spoon/Launcher.java, src/main/java/spoon/support/QueueProcessingManager.java, src/main/java/spoon/support/RuntimeProcessingManager.java, src/main/java/spoon/support/compiler/jdt/FileCompiler.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/compilation/CompilationTest.java, src/test/resources/compilation/SimpleProcessor.java, src/test/resources/compilation/compilation-tests/Bar.java, src/test/resources/compilation/compilation-tests/IBar.java
Fixes bug reported at http://stackoverflow.com/questions/40341408/what-is-the-precompile-flag-supposed-to-do
=> fix(precompile): specifies and fixes precompile option

src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java, src/test/java/spoon/test/compilation/CompilationTest.java
Here are uncommented and fixed CompilationTest tests
=> update CompilationTest to match latest compiler changes

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTSnippetCompiler.java, src/test/java/spoon/support/compiler/jdt/ExtendedStringLiteralTest.java
I suggest to remove unused parameter of JDTBatchCompiler.getUnits().
=> refactor JDTBatchCompiler.getUnits() unused parameter removed

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
The collecting of comments seems to be slow in method 
``` java
JDTCommentBuilder$FindCommentParentScanner.scan(CtElement) 
...
element.getClass().getMethod("getBody")
```
Reason: Java reflection is slow. Throwing exception is slow. 
Solution: Cache the getBody method of classes in HashMap
I do not know how to make a test for that. But I see the visible improvement in building time of the model.
=> improves performance of FindCommentParentScanner

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTSnippetCompiler.java
I am trying to unify compilation process of snippets, templates and sources. I have found these facts:
- `JDTBasedSpoonCompiler.createTmpJavaFile(folder)` always creates empty file. **So nobody needs content of that file.**
- `JDTBasedSpoonCompiler` methods `buildSources` and `buildTemplates` does the same - compiles java files and fills the model. Just the classpath and files are different. But all other things related to compilation are same!
So there is no reason why `buildTemplates` is creating a temporary file next to zip or jar archives, while `buildSources` does not need that. 
This TMP file creation code is anyway wrong, it actually might produce many empty tmp files and deletes only one of them!
There is no test case, which would fail, if creation of tmp files here is omitted. …
=> refactor: avoid creation of JDT hacking TMP files

src/main/java/spoon/reflect/declaration/CtTypeInformation.java, src/main/java/spoon/reflect/visitor/filter/OverriddenMethodFilter.java, src/main/java/spoon/reflect/visitor/filter/OverridingMethodFilter.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/main/java/spoon/support/template/Parameters.java, src/main/java/spoon/support/template/SubstitutionVisitor.java, src/main/java/spoon/template/TemplateMatcher.java, src/test/java/spoon/test/architecture/SpoonArchitectureEnforcer.java, src/test/java/spoon/test/comment/CommentTest.java
Reasons for deprecation:
* it has the opposite behavior of java.lang.Class.isAssignableFrom, this is very confusing
* we already have {@link #isSubtypeOf(CtTypeReference)}
=> fix(isAssignableFrom): deprecate a method that is totally confusing

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
Errors of type `UndefinedType`, `UndefinedName` and `ImportNotFound` are irrelevant for noclasspath mode, they are not logged anymore.
Closes #788
=> fix: filter out some JDT errors on noclasspath

src/test/java/spoon/test/parent/ParentContractTest.java
Refactors ParentContractTest so that:
* it's more readable for @tdurieux 
* it accommodates setting intermediate nodes (for #943 to fix the problem of @pvojtechovsky )
It's actually much better than the previous test because we don't use a mock assertion anymore, we test the actual implementation.
=> test(ParentContractTest): improves contract about setting parents

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTSnippetCompiler.java
Compiler sources are now handled same like in `JDTBasedSpoonCompiler.compile()`. They are not needed at all.
=> refactor: JDTBatchCompiler arg.sources not needed

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
I am learning how DefaultJavaPrettyPrinter works, to make #913 fast again and I have found some little unused code.
@GerardPaligot please review this, if it is really unused, or I misunderstood something.
=> remove unused printer code of visitCtCatchVariable

src/main/java/spoon/reflect/declaration/CtTypeInformation.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/model/ClassWithSuperAndIFace.java, src/test/java/spoon/test/model/ClassWithSuperOutOfModel.java, src/test/java/spoon/test/model/InterfaceWrithFields.java, src/test/java/spoon/test/model/TypeTest.java
Here you are. New PR just for CtTypeInformation.getDeclaredOrInheritedField(fieldName). Including some tests.
=> add CtTypeInformation.getDeclaredOrInheritedField(fieldName)

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/SnippetCompilationHelper.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/main/java/spoon/support/util/RtHelper.java, src/test/java/spoon/test/staticFieldAccess2/ALong.java, src/test/java/spoon/test/staticFieldAccess2/AmbiguousImplicitFieldReference.java, src/test/java/spoon/test/staticFieldAccess2/ChildOfConstants.java, src/test/java/spoon/test/staticFieldAccess2/ChildOfGenericsWithAmbiguousStaticField.java, src/test/java/spoon/test/staticFieldAccess2/Constants.java, src/test/java/spoon/test/staticFieldAccess2/GenericsWithAmbiguousMemberField.java, src/test/java/spoon/test/staticFieldAccess2/GenericsWithAmbiguousStaticField.java, src/test/java/spoon/test/staticFieldAccess2/ImplicitFieldReference.java, src/test/java/spoon/test/staticFieldAccess2/ImplicitStaticClassAccess.java, src/test/java/spoon/test/staticFieldAccess2/ImplicitStaticFieldReference.java, src/test/java/spoon/test/staticFieldAccess2/ImplicitStaticFieldReferenceTest.java
Added test to reproduce bug in printing of Implicit access to static field
=> bug in printing of Implicit access to static field

src/main/java/spoon/template/StatementTemplate.java
Template engine should throw an exception when template is not part of model - when it is created using java reflection - without method bodies.
Without that exception, the clients might wonder why templates does not work for them ... like me :-)
If you agree, it is good idea, then I will add the check to all other templates too.
=> check that Template is on source path of builder

src/test/java/spoon/processing/CtGenerationTest.java
When the CtGenerationTest is run on MS Windows, then generated files contains CRLF as end of line. But Spoon repository expects linux (LF) line endings, so the contributor who wants to update generated file in repository delivers wrong line ending.
This fix should force expected line endings on all platforms.
=> generate expected EOL even on Windows

src/main/java/spoon/reflect/code/CtBodyHolder.java, src/main/java/spoon/reflect/code/CtCatch.java, src/main/java/spoon/reflect/code/CtLoop.java, src/main/java/spoon/reflect/code/CtTry.java, src/main/java/spoon/reflect/declaration/CtAnnotationMethod.java, src/main/java/spoon/reflect/declaration/CtExecutable.java, src/main/java/spoon/reflect/factory/CodeFactory.java, src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/main/java/spoon/support/reflect/code/CtCatchImpl.java, src/main/java/spoon/support/reflect/code/CtLambdaImpl.java, src/main/java/spoon/support/reflect/code/CtLoopImpl.java, src/main/java/spoon/support/reflect/code/CtTryImpl.java, src/main/java/spoon/support/reflect/declaration/CtExecutableImpl.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/test/ctBodyHolder/CtBodyHolderTest.java, src/test/java/spoon/test/ctBodyHolder/testclasses/CWBStatementTemplate.java, src/test/java/spoon/test/ctBodyHolder/testclasses/ClassWithBodies.java, src/test/java/spoon/test/factory/FactoryTest.java, src/test/java/spoon/test/intercession/IntercessionContractTest.java
Note! I had to rollback `CtExecutable.getBody` declaration made by 
> GerardPaligot <gerard.paligot@gmail.com> on 7.8.15 14:20
to make it compilable with new `CtBodyHolder`. I have not found a way how to declare `CtBodyHolder` to have it compilable with origin `CtExecutable.getBody` declaration.
I have no idea whether my changes are correct. It might have some impact to Spoon templates!
=> add interface CtBodyHolder

src/main/java/spoon/Launcher.java, src/test/java/spoon/test/snippets/SnippetTest.java
works almost out of the box, just one visibility issue.
closes #981
=> fix(launcher): easy way to parse a complete class with package

src/main/java/spoon/template/Substitution.java
I just moved duplicated code to shared functions and fixed little inconsistencies (different implementations of the same thing)
=> refactor: remove code duplicity and fix inconsistencies of class Substitution

src/main/java/spoon/support/StandardEnvironment.java, src/test/java/spoon/test/compilation/CompilationTest.java, src/test/resources/classloader-test/spoontest/Foo.java, src/test/resources/classloader-test/spoontest/IFoo.java
This PR improves performance of MainTest.testMain() test on MS Windows 10 to 50% of origin time. From 45s to 22s.
=> performance: cache URLs of sourceClasspath

src/main/java/spoon/support/template/Parameters.java, src/main/java/spoon/template/TemplateMatcher.java
I am learning how TemplateMatcher works. I suggest some little code improvements.
There is a bug fix too, int this PR, in `isParameterSource` method, which returned before true, in some cases, even when `ref.getDeclaration()` was null. It might be OK in this method, but it would fail immediately on NullPointerException in `Parameters.getParameterName()` on `f.getDeclaration().getAnnotation(...)' so I think the change in the `isParameterSource` expression is correct.
I replaced `Launcher.LOGGER.error(...)` by throwing of exception. I guess that spoon should visibly fail if client wants to use a template, but something bad happens. The writing to log is not enough in such case. But here I am not sure, so if you do not agree, then I gladly rollback this change.
=> Template matcher improvements

src/main/java/spoon/support/reflect/reference/CtArrayTypeReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java, src/test/java/spoon/test/arrays/ArraysTest.java, src/test/java/spoon/test/constructorcallnewclass/ConstructorCallTest.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/java/spoon/test/varargs/VarArgsTest.java
java.lang.reflect.Array only contains static utility methods and is not all all a superclass of arrays.
`(new int[0]).getClass().getCanonicalName()` gives `int[]` which should be the result of Spoon.
the removal of the defensive exception is required, because of the presence of another cryptic yet not critical bug (a `TypeReference` which should be a a `TypeParameterReference` while cloning). 
this fix is also a prerequisite to another fix on equality to come later.
=> fix(array): the qualified name of an array is not java.lang.reflect.Array

src/main/java/spoon/reflect/declaration/CtTypeInformation.java, src/main/java/spoon/reflect/reference/CtTypeReference.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/targeted/TargetedExpressionTest.java
After short googling, I have not found any java specification about access path yet (so I am really not a guru for that), anyway I understood that:
> C1: Spoon needs access path from class A to super class B to be able to print the declaration of the class A correctly.
> C2: There is no other place, where access path is needed
> C3: Access path from class A to class B is not the qualified name of class B. 
> C4: the class B can have many access paths ~ one for each inheritance branch, but there is always only one qualified name of class B.
> C5: the access path cannot be used to load the class using class loader. It can be done only using qualified name.
Please correct me, if I am wrong.
The solution I would like to discuss consists of S1 and S2:
> S1: To remove the hack in …
=> Solution for access path problem

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/PrintingContext.java, src/main/java/spoon/reflect/visitor/TypeContext.java, src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java
The new PrintingContext assures that boolean states like [noTypeDecl, ignoreGenerics, ...] are always set to origin value.
=> refactor(printerContext): assure correct restore of state

src/main/java/spoon/generating/CloneVisitorGenerator.java, src/main/java/spoon/support/reflect/declaration/CtClassImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/visitor/clone/CloneBuilder.java, src/main/java/spoon/support/visitor/clone/CloneVisitor.java, src/main/java/spoon/support/visitor/equals/EqualsVisitor.java, src/test/java/spoon/processing/CtGenerationTest.java, src/test/java/spoon/test/comparison/EqualTest.java, src/test/java/spoon/test/intercession/IntercessionContractTest.java, src/test/java/spoon/test/main/MainTest.java, src/test/java/spoon/test/replace/ReplaceTest.java, src/test/java/spoon/test/targeted/TargetedExpressionTest.java
this fixes a very old and deep bug, which was enforced in certain existing assertions.
but now we have the expected:
```
CtLocalVariable var = factory.Code().createCodeSnippetStatement("java.util.List<String> l ").compile();
CtLocalVariable var2 = factory.Code().createCodeSnippetStatement("java.util.List<Object> l ").compile();
assertNotEquals(var2, var); // the generics are taken into account
```
(this holds for any actual type parameter).
=> fix(equal): actual type refs must be part of equality

src/main/java/spoon/reflect/declaration/CtTypeMember.java, src/main/java/spoon/support/reflect/declaration/CtAnonymousExecutableImpl.java, src/main/java/spoon/support/reflect/declaration/CtConstructorImpl.java, src/main/java/spoon/support/reflect/declaration/CtExecutableImpl.java, src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java, src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/test/java/spoon/test/parent/TopLevelTypeTest.java
I have added new method 
```java
interface CtTypeMember
/**
* Returns top level declaring type of this. 
* If this is already a TopLevelType, then it returns this
*/
<T> CtType<T> getTopLevelType();
```
I need it for next PR, which brings some new Refactoring methods for changing of the name of the CtVariable based elements.
Please give me feedback, if such method is acceptable. If yes, then I will add test case too.
Note: I also moved some getDeclaringType to more common place in the hierarchy of CtExecutableImpl, so I did not had to copy the implementation of getTopLevelType 3 times.
=> add CtTypeMember.getTopLevelType()

src/main/java/spoon/reflect/factory/TypeFactory.java
The class not found exception can be thrown by JavaReflectionTreeBuilder too. Handle it
=> fix ClassNotFound when building shadow class by reflection

src/main/java/spoon/reflect/reference/CtTypeReference.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/reflect/visitor/PrintingContext.java, src/main/java/spoon/reflect/visitor/TypeContext.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/testclasses2/AbstractMapBasedMultimap.java, src/test/java/spoon/test/imports/testclasses2/Interners.java, src/test/java/spoon/test/imports/testclasses2/StaticWithNested.java
=> fix typed parameters in access path

src/main/java/spoon/reflect/factory/CodeFactory.java, src/main/java/spoon/support/compiler/jdt/ParentExiter.java, src/test/java/spoon/test/delete/DeleteTest.java, src/test/java/spoon/test/delete/testclasses/Adobada.java, src/test/java/spoon/test/prettyprinter/QualifiedThisRefTest.java, src/test/java/spoon/test/targeted/TargetedExpressionTest.java, src/test/java/spoon/test/targeted/testclasses/Foo.java
fixes #1006.
Note that #1006 was neither in clone, nor in pretty-printer, but in the model.
This is the problem when implicit=true, the model can be incorrect and one does not see it.
=> fix(ThisAccess): the type access associated to a this must be the type containing the this

src/main/java/spoon/reflect/visitor/QueryVisitor.java, src/main/java/spoon/reflect/visitor/filter/AbstractFilter.java, src/main/java/spoon/reflect/visitor/filter/AbstractReferenceFilter.java, src/main/java/spoon/support/reflect/reference/CtLocalVariableReferenceImpl.java, src/main/java/spoon/support/util/RtHelper.java, src/test/java/spoon/test/filters/FilterTest.java
The type of the Filter does not have to be specified in constructor, but is computed by reflection from the matches parameter type.
This PR is based on #1013, so I have to rebase it after you merge #1013. Just have a look if code like this OK, or we can make it even simpler?
```java
List<CtNewClass<?>> elements = foo.getElements(new AbstractFilter<CtNewClass<?>>() {
@Override
public boolean matches(CtNewClass<?> element) {
return true;
}
});
```
=> Type of filter by reflection

src/main/java/spoon/reflect/declaration/CtTypeInformation.java, src/main/java/spoon/support/comparator/SignatureComparator.java, src/main/java/spoon/support/reflect/declaration/CtClassImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/test/interfaces/InterfaceTest.java, src/test/java/spoon/test/model/TypeTest.java, src/test/java/spoon/test/reference/ExecutableReferenceTest.java
now common implementation between `CtType` and `CtTypeReference`.
and fix a bug on `getAllMethods` for interfaces (interfaces don't extend `Object`).
=> fix: fix inconsistencies between interface contract and double implementations of getAllExecutables

src/main/java/spoon/generating/CloneVisitorGenerator.java, src/main/java/spoon/support/visitor/clone/CloneBuilder.java, src/main/java/spoon/support/visitor/clone/CloneVisitor.java, src/test/java/spoon/test/prettyprinter/QualifiedThisRefTest.java
=> fix(clone): clone preserves comments and implicitness

doc/jenkins/build.sh
It avoids using an old Spoon snapshots when doing tests and force resolving the dependency.
=> Change the build.sh to purge local repository from Spoon snapshots

src/main/java/spoon/reflect/declaration/CtAnnotation.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/test/java/spoon/test/annotation/AnnotationValuesTest.java, src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java, src/test/java/spoon/test/template/SubTemplate.java, src/test/java/spoon/test/template/TemplateTest.java
Change the contract of getValues in CtAnnotation in order to keep the order of annotation parameters.
=> Fix a bug with annotation values order

doc/comments.md
Improve readability by fixing typos and wording.
=> Typo and wording fixes

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/comment/testclasses/Comment1.java, src/test/java/spoon/test/comment/testclasses/Comment2.java, src/test/java/spoon/test/comment/testclasses/InlineComment.java
Multiple comments placed before a catch block were ignored, see #1073. This PR contains test to spot the bug and a fix.
=> Fix for a bug concerning multiples comments before a catch block

doc/matcher.md, src/main/java/spoon/template/TemplateMatcher.java, src/test/java/spoon/test/template/CheckBound.java, src/test/java/spoon/test/template/CheckBoundMatcher.java, src/test/java/spoon/test/template/TemplateTest.java
=> test(TemplateMatcher): add tests for named template matchers (uncovered cases)

src/main/java/spoon/support/compiler/jdt/FileCompilerConfig.java
When I analyze elasticsearch (600k, core package is 280k and is buildable), I get an NoFileFoundException saying that too many open files exist.
By closing every input stream when creating compilation units this can be prevented.
=> Allow to analyze big projects (>500k LOC) by preventing TooManyOpenFilesException

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java, src/test/java/spoon/test/reference/VariableAccessTest.java, src/test/resources/noclasspath/org/elasticsearch/indices/analysis/HunspellService.java
`createVariableAccessNoClasspath` throws a NullPointerException if a
variable access is resolved for parameters in constructors as the parent
of constructor node is not available at this point.
=> Fix NullPointerException resulting from variable accesses in ctors.

src/main/java/spoon/reflect/factory/ExecutableFactory.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java, src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/parameters/ParameterTest.java, src/test/resources/noclasspath/lambdas/MultiParameterLambda.java
This PR also contains a fix for a minor bug introduced in #1098.
=> Set the type of a parameter declared in a lambda to Object instead of ommitting them when unknown.

pom.xml, src/main/java/spoon/SpoonModelBuilder.java, src/main/java/spoon/reflect/code/CtArrayRead.java, src/main/java/spoon/reflect/code/CtAssignment.java, src/main/java/spoon/reflect/code/CtBlock.java, src/main/java/spoon/reflect/code/CtBreak.java, src/main/java/spoon/reflect/code/CtCase.java, src/main/java/spoon/reflect/code/CtConditional.java, src/main/java/spoon/reflect/code/CtContinue.java, src/main/java/spoon/reflect/code/CtDo.java, src/main/java/spoon/reflect/code/CtFor.java, src/main/java/spoon/reflect/code/CtForEach.java, src/main/java/spoon/reflect/code/CtLambda.java, src/main/java/spoon/reflect/code/CtNewClass.java, src/main/java/spoon/reflect/code/CtOperatorAssignment.java, src/main/java/spoon/reflect/code/CtReturn.java, src/main/java/spoon/reflect/code/CtSuperAccess.java, src/main/java/spoon/reflect/code/CtSwitch.java, src/main/java/spoon/reflect/code/CtThisAccess.java, src/main/java/spoon/reflect/code/CtUnaryOperator.java, src/main/java/spoon/reflect/code/CtVariableRead.java, src/main/java/spoon/reflect/declaration/CtAnnotation.java, src/main/java/spoon/reflect/factory/Factory.java, src/main/java/spoon/reflect/visitor/chain/CtFunction.java, src/main/java/spoon/reflect/visitor/chain/CtQuery.java, src/main/java/spoon/reflect/visitor/chain/CtQueryable.java, src/main/java/spoon/reflect/visitor/filter/AbstractReferenceFilter.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/test/java/spoon/test/comment/CommentTest.java
Fix all errors encountered while launching ```mvn javadoc:javadoc``` on Spoon. Lot of warnings are still remaining but don't block the goal.
=> doc: Fix issues related to javadoc in java 8 #1104

pom.xml
Remove the -Xdoclint parameter in pom.xml to show errors related to javadoc using java 8 rules. Travis should fail when those errors occured. Fix #1106
=> travis: Remove the -Xdoclint parameter in pom.xml fix #1106

doc/matcher.md, src/main/java/spoon/template/TemplateMatcher.java, src/test/java/spoon/test/template/TemplateTest.java
As discussed in #1080, there is `TemplateMatcher` implemented as `Filter`
=> Template matcher implemented as Filter

doc/filter.md, src/main/java/spoon/reflect/factory/Factory.java, src/main/java/spoon/reflect/factory/FactoryImpl.java, src/main/java/spoon/reflect/factory/QueryFactory.java, src/main/java/spoon/reflect/visitor/chain/CtQuery.java, src/main/java/spoon/support/SerializationModelStreamer.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/main/java/spoon/template/TemplateMatcher.java, src/test/java/spoon/test/filters/FilterTest.java
Implements
```java
launcher.getFactory().Query().createQuery().map...
launcher.getFactory().Query().createQuery(anInput).map...
```
This PR is based on #1090. I will rebase it after #1090 is finished and merged.
=> Query factory

src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java, src/test/java/spoon/test/filters/FilterTest.java
test and fix contract: If the query produces elements, which cannot be cast to forEach consumer, then they are ignored.
Current behavior: the new test `testClassCastExceptionOnForEach` fails with NullPointerException
=> fix CCE on Query#forEach call of CtConsumer#apply

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/ParentExiter.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/comment/testclasses/InlineComment.java
=> fix(comment): support comment on string concatenation

src/main/java/spoon/reflect/visitor/filter/DirectReferenceFilter.java
The DirectReferenceFilter should first call `super.matches(...)`, which fast checks whether visited element is of required type. Then it can check equality of that element.
Otherwise the equality is tested for each child element and it is useless.
=> improve performance of DirectReferenceFilter

src/main/java/spoon/reflect/visitor/chain/CtQuery.java, src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java, src/test/java/spoon/test/filters/FilterTest.java
Actually Filter can be used as mapping function this way:
```java
Filter filter = new SomeFilter();
element.map(new CtFunction<R, Boolean>() {
@Override
public Boolean apply(R input) {
return filter.matches(input);
}
}).failurePolicy(QueryFailurePolicy.IGNORE);
```
There are these problems:
* I needed 2 minutes to write it and 1h to found that failurePolicy must be added too - and as a author I know the queries the best - so current way how legacy filters can be used is ugly and error prone.
* the failurePolicy is set to whole query, but it should be set only to the query step which uses the filter. Internally there is already a `CtQueryImpl#stepFailurePolicy`, which should be therefore called instead, but then the code would be even more ugly.
So this PR allows to write:
```java …
```
=> feature CtQuery#select(Filter)

src/main/java/spoon/reflect/visitor/chain/CtQuery.java, src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java, src/test/java/spoon/test/filters/FilterTest.java
Support for calling filterChildren without filter. It returns all visited elements.
=> feature CtQuery#filterChildren(null)

README.md, doc/ecosystem.md
thanks @pvojtechovsky for noting that Diversify-project/syringe was missing
=> update ecosystem (one single file to maintain + added syringe)

src/main/java/spoon/reflect/visitor/filter/ParameterReferenceFunction.java, src/main/java/spoon/reflect/visitor/filter/ParameterScopeFunction.java, src/test/java/spoon/test/query_function/QueryTest.java, src/test/java/spoon/test/query_function/testclasses/packageA/ClassA.java
First query of the set of PRs, which will be produced from #1114. It is the simplest one - good one to discuss basic topics.
Please decide:
Q1) Is the package `spoon.reflect.visitor.query` OK?
Q2) I am not sure with the `filter` field, which does filtering of elements in scope of parameter visibility. It would be simpler to have query, which simply returns all elements in scope of parameter. And if somebody wants to filter them then s/he can apply `CtQuery#map` in next query step. But it is true that actually I need filtering in all use cases of `ParameterScopeQuery`, so may be it is correct.
Any other feedback/idea?
=> review ParameterReferenceFunction, ParameterScopeFunction

src/main/java/spoon/reflect/visitor/filter/LocalVariableReferenceFunction.java, src/main/java/spoon/reflect/visitor/filter/LocalVariableScopeFunction.java, src/test/java/spoon/test/query_function/QueryTest.java
This PR contains LocalVariableReferenceFunction, LocalVariableScopeFunction.
The main purpose is LocalVariableReferenceFunction, which returns all the references to the local variable. The second on is helper classes which might be useful for others so it is public.
It depends on PR `CtQuery#filterChildren(null)` #1140 
The tests will be added later, because they share a lot with tests of #1136
=> review LocalVariableReferenceFunction, LocalVariableScopeFunction

src/main/java/spoon/reflect/visitor/filter/FieldReferenceFunction.java, src/main/java/spoon/reflect/visitor/filter/FieldScopeFunction.java, src/main/java/spoon/reflect/visitor/filter/SubtypeFilter.java, src/test/java/spoon/test/query_function/QueryTest.java, src/test/java/spoon/test/query_function/testclasses/ClassC.java, src/test/java/spoon/test/query_function/testclasses/packageA/ClassA.java, src/test/java/spoon/test/query_function/testclasses/packageA/ClassB.java, src/test/java/spoon/test/query_function/testclasses/packageB/ClassA.java
This PR contains FieldReferenceFunction, FieldScopeFunction, SubtypeFilter.
The main purpose is FieldReferenceFunction, which returns all the references to the field. Other two are helper classes which might be useful for others so they are public.
It depends on these PRs
* CtQuery#filter(Filter) #1142
* CtQuery#filterChildren(null) #1140
The tests will be added later, because they share a lot with tests of #1136
=> review FieldReferenceFunction, FieldScopeFunction, SubtypeFilter

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/reflect/visitor/MinimalImportScanner.java, src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java, src/test/java/spoon/test/prettyprinter/PrinterTest.java, src/test/java/spoon/test/prettyprinter/testclasses/ImportStatic.java, src/test/java/spoon/test/prettyprinter/testclasses/sub/Constants.java
Avoid to import static elements such as `java.lang.System.out` when using `System.out.println`. 
Fix #1152.
=> Improve pretty-printer and import mechanism with static imports

.travis.yml, chore/revapi_tpl.ftl, chore/revapy.py, pom.xml, revapi.json, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
Use revapi to compare Spoon API against the last published snapshot. Fix #1023.
Thanks a lot @metlos for the support and quick changes on revapi.
Launched today and obtain the following result:
```
[INFO] Comparing [fr.inria.gforge.spoon:spoon-core:jar:5.6.0-20170112.234557-2] against [fr.inria.gforge.spoon:spoon-core:jar:5.6.0-SNAPSHOT] (including their transitive dependencies).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.682 s
[INFO] Finished at: 2017-01-13T09:22:53+01:00
[INFO] Final Memory: 117M/857M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal …
```
=> WiP: chore(maven): Change pom.xml to add revapi 

src/main/java/spoon/reflect/CtModelImpl.java, src/main/java/spoon/reflect/visitor/filter/ParentFunction.java, src/test/java/spoon/test/filters/FilterTest.java
Implements new mapping functions, which visits all the parents of current element. 
It is needed by to LocalVariableScopeFunction to detect scope of local variable, by searching for a parent which matches some rules... will be used in next PR, which fixes LocalVariableScopeFunction for variables used in CtLoop expressions and CtTryWithResource.
Note: I have one question to the scanning of all parents. It is "Which parent is the top parent?"
If I visit parents until the getParent()==null, then I get to helper annonymous class based on CtElementImpl, which is declared in CtModelImpl$CtRootPackage$1. I guess it is not correct ... Your opinion please?
The test actually fails because the scanning does not end on RootPackage, but one level below...
=> review: feature: ParentFunction

src/main/java/spoon/reflect/visitor/filter/VariableReferenceFunction.java, src/main/java/spoon/reflect/visitor/filter/VariableScopeFunction.java, src/test/java/spoon/test/query_function/QueryTest.java
This is the query, which returns all the references to the CtVariable based elements.
Your opinion?
=> review: feature: VariableReferenceFunction, VariableScopeFunction

src/main/java/spoon/reflect/declaration/CtTypeInformation.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationTypeImpl.java, src/main/java/spoon/support/reflect/declaration/CtClassImpl.java, src/main/java/spoon/support/reflect/declaration/CtEnumImpl.java, src/main/java/spoon/support/reflect/declaration/CtInterfaceImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeParameterImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java, src/test/java/spoon/test/ctType/CtTypeTest.java, src/test/java/spoon/test/ctType/testclasses/X.java
There are two implementations of  `CtTypeInformation#isSubtypeOf(CtTypeReference)`, which has following comment:
> Returns true if the referenced type is a sub-type of the given type.
and two implementations:
1) `CtTypeReferenceImpl#isSubtypeOf`
2) `CtTypeImpl#isSubtypeOf`
There is bug that each implementation behaves different. See the failing test of this PR.
```java
//contract: x.isSubtypeOf(x)==true
//using CtTypeReference implementation - test pass
assertTrue(xCtType.getReference().isSubtypeOf(xCtType.getReference()));
//using CtType implementation - test fails
assertTrue(xCtType.isSubtypeOf(xCtType.getReference()));
```
Which behavior is correct? I personally thought that x.isSubtypeOf(x)==true is correct. But I have seen code which expected opposite...
Should we fix it? How?
=> fix bug in isSubtypeOf (broken contract X.isSubtypeOf(X)==true)

src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java, src/main/java/spoon/support/visitor/java/reflect/RtMethod.java, src/test/java/spoon/test/interfaces/InterfaceTest.java
This PR contains failing test, which reproduces issue #1163
=> fix: Consumer#andThen isDefaultMethod()

src/main/java/spoon/reflect/code/CtLambda.java, src/main/java/spoon/reflect/factory/ExecutableFactory.java, src/main/java/spoon/support/reflect/code/CtLambdaImpl.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/lambda/testclasses/Foo.java
This PR fixes issue #1159. The issue #1159 is caused by wrong return type of CtExecutableReference created for lambda. Therefore this code failed too:
```java
assertTrue(lambdaRef.getDeclaringExecutable().getType()
.equals(paramRef.getDeclaringExecutable().getType()));
``` 
Now there is a question whether solution of this PR is correct.
In current spoon model the interface `CtLambda` represents both:
* `CtExpression`, which returns an instance, which implements a type defined by result of `CtLambda.getType()`
* `CtExecutable`, which represents an executable element. It means it has parameters, body, thrownTypes ... and **return type** 
The problem was that **return type** of executable element was not accessible. Therefore during creation of CtExecutableReference of lambda expression, …
=> feature: CtLambda#getMethod() and fix of #1159

src/main/java/spoon/support/reflect/code/CtLambdaImpl.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/lambda/testclasses/LambdaRxJava.java
Ignore static modifiers in `CtLambda:getOverriddenMethod()`
=> fix: bug regression with lambda expression when extending Function

src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/testclasses/ClientClass.java, src/test/java/spoon/test/imports/testclasses/internal/PublicInterface2.java, src/test/java/spoon/test/imports/testclasses/internal/SuperClass.java
=> fix CtTypeReferenceImpl#canAccess of protected and interface members

src/test/java/spoon/test/intercession/IntercessionTest.java
=> test: reduce the scope of the testSettersAreAllGood test

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/test/java/spoon/LauncherTest.java
Fix a funny bug which happens when launching Spoon in an empty working directory: we have a NPE because JDT cannot find a .java file... We fix it by passing as argument to JDT the list of java files we want to Spoon. It should then fix #1116
=> Fix NPE when empty working dir

src/main/java/spoon/reflect/visitor/chain/CtQuery.java, src/main/java/spoon/reflect/visitor/chain/CtQueryAware.java, src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java, src/main/java/spoon/reflect/visitor/filter/CtScannerFunction.java, src/test/java/spoon/test/filters/FilterTest.java
As I mentioned in #1005 it is sometime needed to 
* R1 to know when query step of type filterChildren enter/exit an element on one selected query step.
* R2 to be able to skip processing of children of current element 
* R3 to be able to skip processing of siblings and children of current elements
* R4 to be able to make mapping functions aware of query processing state (actually mainly whether query is terminated)
There is already a Query Execution Context (QEC) impelemented by class `CtQueryImpl$CurrentStep`. 
There are needed these two things to implement this PR:
1.  to get access to the QEC, or to provide own extension of that context
2.  to define API of that QEC, which can be used to
* drive execution of query 
* or to get query processing state.
* the list of all Functions of the …
=> review: introduction of CtScannerFunction

src/main/java/spoon/reflect/visitor/filter/ParentFunction.java
The ParentFunction can now early terminate too. 
This PR is ready for review
=> review: feature: Parent function

src/main/java/spoon/reflect/visitor/filter/AllTypeMembersFunction.java, src/main/java/spoon/reflect/visitor/filter/SuperHierarchyFunction.java, src/main/java/spoon/reflect/visitor/filter/SuperInheritanceHierarchyFunction.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
This PR Introduces two new mapping functions:
* `SuperHierarchyFunction` - which produces all super classes and super interfaces of input `CtType`
* `AllTypeMembersFunction` - which produces all `CtTypeMember` of input `CtType` and all super classes and super interfaces.
The `AllTypeMembersFunction` is then used, as example, to implement CtTypeImpl#getAllFields` in a nicer and more correct way.
This PR is ready for review.
=> review: feature: All type members function

src/main/java/spoon/reflect/visitor/filter/PotentialVariableDeclarationFunction.java, src/test/java/spoon/test/prettyprinter/QualifiedThisRefTest.java, src/test/java/spoon/test/prettyprinter/testclasses/QualifiedThisRef.java
Add a unit test to reproduce regression seen in #1207 and propose a fix by verifying parent initialization in PotentialVariableDeclarationFunction.
=> review: Fix regression spotted in Casper project

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/filter/PotentialVariableDeclarationFunction.java, src/main/java/spoon/support/reflect/reference/CtLocalVariableReferenceImpl.java
This PR is refactoring of `PotentialVariableDeclarationFunction`. There are following changes
1) There is new constructor which accepts variable name. Such mapping function then returns only `CtVariable` instances with that name. It simplifies usage of `PotentialVariableDeclarationFunction`, because on all 3 places where I am using that function it is needed to filter by variable name too. See simplified code of `DefaultJavaPrettyPrinter` and `CtLocalVariableReferenceImpl`, which are part of this PR
2) It now returns only instances of `CtVariable`. Before it returned all `CtElements`, which were on the way from mapping function input to the found variable declaration. It is change in behavior! I hope it is OK, because the PotentialVariableDeclarationFunction is not in spoon for long time, …
=> review: improve PotentialVariableDeclarationFunction, simplify its usage

src/main/java/spoon/reflect/declaration/CtTypeParameter.java, src/main/java/spoon/reflect/factory/TypeFactory.java, src/main/java/spoon/support/reflect/declaration/CtTypeParameterImpl.java, src/test/java/spoon/test/generics/ClassThatBindsAGenericType.java, src/test/java/spoon/test/generics/ClassThatDefinesANewTypeArgument.java, src/test/java/spoon/test/generics/GenericsTest.java
During work with `CtTypeParameter` I always needed to know where this parameter is declared. I suggest to introduce this new API method into `CtTypeParameter`.
```java
/**
* @return the {@link CtFormalTypeDeclarer}, which declares this {@link CtTypeParameter}
*/
@DerivedProperty
CtFormalTypeDeclarer getTypeDeclarer();
```
This PR fixes bug in `TypeFactory#createReference(CtTypeParameter)`, which created reference without parent, so there was lost information about type parameter declarer. CtTypeParameterReference without declarer is useless.
=> review 1: feature: CtTypeParameter#getTypeDeclarer()

src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/test/java/spoon/test/filters/FilterTest.java
I think that `CtExecutableReferenceImpl#isOverriding` handles wrong anonymous types.
I think that anonymous classs
```java
public abstract class AbstractTostada implements ITostada {
@Override
public ITostada make() {
//following anonymous class extends Tostada (not ITostada!), therefore it overrides Tostada#make and prepare
//---->
return new Tostada() {
@Override
public void prepare() {
super.prepare();
}
@Override
public ITostada make() {
return super.make();
}
};
}
public abstract void prepare();
}
```
The origin code 
```java
if (getDeclaringType().isAnonymous()) {
if (!getDeclaringType().getDeclaringType().isSubtypeOf(executable.getDeclaringType())) {
return false;
}
} 
```
is not understandable for me. So I think it is buggy. May be there was some special case which has to be …
=> review 1: fix CtExecutableReference#isOverriding on anonymous class

src/main/java/spoon/support/reflect/code/CtBlockImpl.java, src/test/java/spoon/test/ctBlock/TestCtBlock.java, src/test/java/spoon/test/ctBlock/testclasses/Toto.java, src/test/java/spoon/test/snippets/SnippetTest.java
I propose a fix using a loop for which check on instances instead of using equals for removeStatement.
=> review: Add a unit test to show issue #1221. Propose a simple fix.

src/main/java/spoon/generating/CloneVisitorGenerator.java, src/main/java/spoon/refactoring/Refactoring.java, src/main/java/spoon/support/compiler/SnippetCompilationHelper.java, src/main/java/spoon/support/reflect/declaration/CtNamedElementImpl.java, src/main/java/spoon/support/reflect/reference/CtFieldReferenceImpl.java, src/test/java/spoon/test/field/FieldTest.java, src/test/java/spoon/test/field/testclasses/A.java, src/test/java/spoon/test/field/testclasses/BaseClass.java, src/test/java/spoon/test/reference/CloneReferenceTest.java
The issue #1213 shows that in some cases dynamic lookup just fail to find the right class. Then we propose to remove the dynamic lookup, and to improve the setName instead. 
According to @tdurieux dynamic lookup was introduced to support the clone operations: we propose instead to always use renaming operation after using clone, and then to improve renaming to also rename children of a type. 
A mandatory change is then needed: to use the `setName` operation *after* putting a type in the package.
=> review: fix: Dynamic lookup issues by removing dynamic lookup

src/main/java/spoon/reflect/visitor/filter/CatchVariableReferenceFunction.java, src/main/java/spoon/reflect/visitor/filter/CatchVariableScopeFunction.java, src/main/java/spoon/reflect/visitor/filter/FieldReferenceFunction.java, src/main/java/spoon/reflect/visitor/filter/LocalVariableReferenceFunction.java, src/main/java/spoon/reflect/visitor/filter/LocalVariableScopeFunction.java, src/main/java/spoon/reflect/visitor/filter/ParameterReferenceFunction.java, src/main/java/spoon/reflect/visitor/filter/ParameterScopeFunction.java, src/main/java/spoon/reflect/visitor/filter/VariableReferenceFunction.java
There are two things:
* The classes `XxxScopeFunction` have constructor with `CtScannerListener` parameter.
* The classes `XxxReferenceFunction` have constructor with <T extends CtVariable> `var` parameter. Such functions will search for references of `var` in children of mapping function input `CtElement`
The classes `LocalVariableReferenceFunction` , `CatchVariableReferenceFunction`, `ParameterReferenceFunction` has similar algorithm, so they inherit from `AbstractVariableReferenceFunction`. The `FieldReferenceFunction` is implemented individually, because java field references behaves different.
These improvements are needed by  #1005.
=> review 1: feature: search for CtVariableReference in defined scope

src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java
Replaced
```java
getFactory().Type().createReference(Object.class);
```
by
```java
getFactory().Type().OBJECT;
```
=> fix: use TypeFactory#OBJECT

src/main/java/spoon/reflect/cu/CompilationUnit.java, src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java, src/test/java/spoon/test/compilationunit/GetBinaryFilesTest.java
This is a proposal to fix #1230. I decided to use `File#listFiles` to detect all available .class files instead of traversing all sub types one after another in order to return existing files only. Did I miss something (except of tests which I will add if you think this method is worth adding to Spoon).
=> Add 'getBinaryFiles' to CompilationUnit. Fixes #1230.

src/main/java/spoon/reflect/declaration/CtFormalTypeDeclarer.java
What about this small change in spoon model?
=> refactor: CtFormalTypeDeclarer extends CtTypeMember

src/main/java/spoon/reflect/visitor/filter/SuperInheritanceHierarchyFunction.java, src/test/java/spoon/test/imports/ImportTest.java
refactoring of SuperInheritanceHierarchyFunction.
* can be configured if it returns CtTypeReferences (new implementation) or CtType (old implementation)
* can register CtScannerListener
=> review1: feature SuperInheritanceHierarchyFunction supports references and listener

src/main/java/spoon/reflect/factory/TypeFactory.java, src/main/java/spoon/reflect/reference/CtTypeParameterReference.java, src/main/java/spoon/reflect/reference/CtTypeReference.java, src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/generics/GenericsTest.java
A baby step. The TypeFactory method which creates a CtTypeReference, which has initialized actual type arguments following formal type parameters of the input CtType.
I need it to simplify architecture of CtTypeParameter resolving algorithm. This algorithm can be theoretically applied to
A) CtTypeReference - which has actual type arguments
B) CtType - which has formal type parameters
The new method of this PR let's me simplify it to A) only, because B) can be easily covered to A) by:
```java
CtTypeReference typeRef = fatory.Type().createReference(type, true);
```
=> Depends on #1238. feature: TypeFactory#createReference(type,includingFormalTypeParams)

src/main/java/spoon/reflect/declaration/CtTypeInformation.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeParameterImpl.java, src/main/java/spoon/support/reflect/reference/CtIntersectionTypeReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/ctType/CtTypeParameterTest.java, src/test/java/spoon/test/ctType/testclasses/ErasureModelA.java
Adds new method:
* CtTypeParamer#getTypeErasure() - returns type erasure of generic parameter
This method and #1225  are needed to correctly detect whether method overrides another method following [specification](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.2)
=> review1: feature: CtTypeParameter#getTypeErasure()

src/main/java/spoon/reflect/factory/ExecutableFactory.java, src/main/java/spoon/reflect/factory/Factory.java, src/main/java/spoon/reflect/factory/FactoryImpl.java, src/main/java/spoon/reflect/factory/TypeFactory.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeParameterImpl.java, src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/main/java/spoon/support/visitor/ClassTypingContext.java, src/main/java/spoon/support/visitor/GenericTypeAdapter.java, src/main/java/spoon/support/visitor/MethodTypingContext.java, src/test/java/spoon/test/ctType/CtTypeParameterTest.java, src/test/java/spoon/test/ctType/CtTypeTest.java, src/test/java/spoon/test/ctType/testclasses/SubtypeModel.java, src/test/java/spoon/test/ctType/testclasses/X.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses/CelebrationLunch.java, src/test/java/spoon/test/generics/testclasses/Lunch.java
Implements #1160.
The implementation of isSubtypeOf on type parameters is quite complex task, which needs all the basic steps below, which fits to commits of this PR.
There are:
BS1) new interface GenericTypeAdapter
BS2) CtSuperTypeHierarchy - adapts generic types to Type scope
BS3) CtMethodSuperTypeHierarchy - adapts generic types to Method/Constructor scope
BS4) CtFormalTypeDeclarer#getGenericTypeAdapter(), which creates instance of CtSuperTypeHierarchy  or CtMethodSuperTypeHierarchy for the scope of this declarer
BS5) CtTypeParameterImpl#isSubtypeOf - finally the implementation of isSubtypeOf  - the target of this PR
BS6) simpler and more correct implementation of `CtTypeParameterImpl#isSubtypeOf(CtTypeReference)`, based on new algorithms
+ first and incomplete tests ... the testing of …
=> review1: feature: CtTypeParameter#isSubtypeOf

src/main/java/spoon/support/visitor/ClassTypingContext.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses/Banana.java
=> fix actual type arguments resolving

src/main/java/spoon/support/visitor/AbstractTypingContext.java, src/main/java/spoon/support/visitor/ClassTypingContext.java, src/main/java/spoon/support/visitor/GenericTypeAdapter.java, src/main/java/spoon/support/visitor/MethodTypingContext.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses/Orange.java
Here are fixed other bugs found during implementing of CtMethod#isOverriding(CtMethod).
Following problems are tested and fixed by this PR:
* The generic types are now adapted recursive into actual type arguments. E.g. `List<List<T>>` is adapted to `List<List<M>>`
* The generic types are now adapted recursive into their bounds. E.g. `List<? extendsT>` is adapted to `List<? extends M>`
* The adapting of wildcard type E.g. `List<? extendsT>` does not fail with NullPointerException
* The MethodTypingContext correctly detects isOverriding for child method whose generic types are replaced by concrete types.
=> review1: fix generic type adapting

chore/revapi_tpl.ftl, revapi.json
Bug: the classes directly in package "spoon" were not considered
+
Improvement: only the main type of breakage is shown as Github comment for simplifying understanding
=> chore: fix revapi bug

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/test/java/spoon/test/api/APITest.java, src/test/java/spoon/test/support/ResourceTest.java, src/test/resources/spoon/test/api/CommentedClass.java
=> Create a new unit test for #1274 and propose a fix

src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java, src/test/java/spoon/test/methodreference/MethodReferenceTest.java, src/test/java/spoon/test/methodreference/testclasses/Cloud.java
should fix #1256, but I am not sure that it is correct solution. May be we should think about having reference to Formal Type declarer directly in `CtTypePareameterReference` (which would be added by compiler?) instead of searching for the declarer in all possible contexts where it might occur. How many place we need to fix next to this one?
=> fix failing CtExecutableReference#getActualMethod

src/main/java/spoon/reflect/visitor/filter/SuperInheritanceHierarchyFunction.java, src/main/java/spoon/support/visitor/ClassTypingContext.java, src/test/java/spoon/test/imports/ImportTest.java
This PR improves algorithm of SuperInheritanceHierarchyFunction by way it works better in no class path mode. 
This fix is needed to pass tests of #1220
=> Fix SuperInheritanceHierarchyFunction in noClassPath mode

src/main/java/spoon/reflect/declaration/CtMethod.java, src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java, src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/main/java/spoon/support/visitor/MethodTypingContext.java, src/test/java/spoon/test/filters/FilterTest.java, src/test/java/spoon/test/method_overriding/MethodOverriddingTest.java, src/test/java/spoon/test/method_overriding/testclasses/A.java, src/test/java/spoon/test/method_overriding/testclasses/B.java, src/test/java/spoon/test/method_overriding/testclasses/C.java, src/test/java/spoon/test/method_overriding/testclasses/D.java, src/test/java/spoon/test/method_overriding/testclasses/IA.java
New API `CtMethod#isOverriding(CtMethod)`, which works better on generic methods, then legacy `CtExecutableReference#isOverriding(CtExecutableReference)`
This PR actually fails on wrong legacy implementation of `CtExecutableReference#isOverriding(CtExecutableReference)`
I would like to discuss with you: "How to fix that legacy implementation?"
I did not understood:
1) why isOverriding method was implemented on CtExecutableReference and not on CtMethod since beginning?
2) how Template engine works with `CtExecutableReference#isOverriding` ... I do not know how to replace that code with `CtMethod#isOverriding` ... because I do not understand that code yet...
=> review1: feature: CtMethod#isOverriding(CtMethod)

src/main/java/spoon/reflect/visitor/filter/OverriddenMethodFilter.java, src/main/java/spoon/reflect/visitor/filter/OverridingMethodFilter.java, src/main/java/spoon/reflect/visitor/filter/SuperInheritanceHierarchyFunction.java
New MethodTypingContext is used to implement these two filters.
I added also method `#includingSelf(boolean)`, which can be used to configure the behavior of these filters.
=> review1: refactor Method overriding/overriden filters

src/main/java/spoon/reflect/visitor/filter/AllTypeMembersFunction.java
AllTypeMembersFunction accepts now CtTypeInformation. Before it accepted only CtType.
Some comments were added too.
=> review: refactor AllTypeMembersFunction

src/main/java/spoon/support/visitor/MethodTypingContext.java, src/test/java/spoon/test/generics/GenericsTest.java
I am implementing the algorithm, which searches for all methods, which has to be modified when changing method signature (e.g. remove method parameter). This algorithm needs to be able to search in all super types of sub types of declaring type of target methods, for methods with equal `sub signature`... yes, it is tricky sentence ... so see Example:
```java
class A {
void method() {}
}
interface IB {
void method();
}
class B extends A implements IB {
//note that B does not declares `method`. It inherits it from `A`.
}
class C implements IB {
void method();
}
```
If `A#method()` has to be refactored, then that algorithm has to found `C#method()` too. But note that `C#method()`, does not overrides `A#method()`, so it is not enough to use existing overriding filter.
The algorithm first …
=> review: feature: MethodTypingContext#adaptMethod

src/main/java/spoon/support/visitor/ClassTypingContext.java, src/main/java/spoon/support/visitor/MethodTypingContext.java, src/test/java/spoon/test/generics/GenericsTest.java
As discussed in #1292. Here is C1 + C2. It was simplest.
`MethodTypingContext#adaptMethod` moved to ClassTypingContext#adaptMethod`
=> review: refactor MethodTypingContext#adaptMethod moved to ClassTypingContext

src/main/java/spoon/reflect/visitor/filter/OverriddenMethodFilter.java, src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java, src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/main/java/spoon/support/visitor/ClassTypingContext.java, src/main/java/spoon/support/visitor/MethodTypingContext.java, src/test/java/spoon/test/ctType/CtTypeParameterTest.java, src/test/java/spoon/test/generics/GenericsTest.java
=> review: refactor MethodTypingContext#isOverriding moved to ClassTypingContext

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/ctClass/CtClassTest.java, src/test/java/spoon/test/filters/CUFilterTest.java, src/test/resources/noclasspath/issue1293/com/cristal/ircica/applicationcolis/userinterface/fragments/CompletableFragment.java, src/test/resources/noclasspath/issue1293/com/cristal/ircica/applicationcolis/userinterface/fragments/TransporteurFragment.java
=> review bug: in noClasspath type without import should be considered in the same package as current class

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/resources/noclasspath/Initializer.java
=> review:add support for receiver parameter

src/main/java/spoon/reflect/visitor/filter/SubInheritanceHierarchyFunction.java, src/test/java/spoon/test/refactoring/MethodsRefactoringTest.java, src/test/java/spoon/test/refactoring/parameter/testclasses/IFaceB.java, src/test/java/spoon/test/refactoring/parameter/testclasses/IFaceK.java, src/test/java/spoon/test/refactoring/parameter/testclasses/IFaceL.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TestHierarchy.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeA.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeB.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeC.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeK.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeL.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeM.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeR.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeS.java
The `SubInheritanceHierarchyFunction` is created and configured with one or more types. This mapping function returns all sub types of configured types, which are found in packages, which are input for this mapping function.
This mapping function is more efficient then filtering all types using 'SubtypeFilter', because:
* it allows searching for subtypes of more then one super type
* it visits each type of spoon model only once, during inheritance hierarchy checking.
* if new super type is added (configured), then next scanning always returns only newly found sub types
This new mapping function is used by #1291, which
* needs to scan sub inheritance hierarchy of more types in more iterations, where each iteration needs to scan similar sub hierarchy,  but with some new types.
* each next …
=> review: feature sub inheritance hierarchy function

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/resources/noclasspath/annotation/issue1307/SpecIterator.java
In some anonymous inner classes, in noClassPath, JDT does not provide information about Override annotation: by default the ReferenceBuilder assume that if a type does not have any import and has no package, it belongs to the current package. 
So I added a check to verify if the current type belongs to the java.lang package.
Fix #1307
=> review bug: some Override annotations are retrieved without information by JDT 

src/main/java/spoon/reflect/reference/CtExecutableReference.java, src/main/java/spoon/reflect/visitor/JavaIdentifiers.java, src/main/java/spoon/support/reflect/code/CtStatementImpl.java, src/main/java/spoon/support/reflect/declaration/CtConstructorImpl.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java
replaces all "<init>" by CtExecutableReference.CONSTRUCTOR_NAME.
replaces all "lambda$" by CtExecutableReference.LAMBDA_NAME_PREFIX.
=> review: replace string literals by constants

src/main/java/spoon/support/visitor/SubInheritanceHierarchyResolver.java, src/test/java/spoon/test/filters/FilterTest.java
After simplifications of SubInheritanceHierarchyResolver (remove of `#returnTypeReferences(boolean)` method) there remained `CtConsumer<CtTypeInformation>`, but there should be `CtConsumer<CtType>`
=> review: fix: replace wrong CtTypeInformation by CtType

src/main/java/spoon/reflect/visitor/filter/LambdaFilter.java, src/test/java/spoon/test/lambda/LambdaTest.java
This Filter matches all CtLambdas which are implementing one of defined interfaces.
It will be used by #1291 to found all lambdas of all methods with same signature.
=> review: feature LambdaFilter

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/reflect/visitor/MinimalImportScanner.java, src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java, src/test/java/spoon/test/imports/ImportScannerTest.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/testclasses2/JavaLangConflict.java, src/test/java/spoon/test/variable/AccessFullyQualifiedFieldTest.java
Improve ImportScanner to fix collision with `java.lang` when a variable is called `java`. The entire mechanism has also been improved to import types instead of fields/executable when possible which explains the changes in some tests (`import static spoon.Launcher.SPOONED_CLASSES;` replaced to `import spoon.Launcher`).
=> fix(#1320): Improve ImportScanner mechanism to support collision with java.lang 

src/main/java/spoon/reflect/visitor/filter/AllMethodsSameSignatureFunction.java, src/test/java/spoon/test/refactoring/MethodsRefactoringTest.java, src/test/java/spoon/test/refactoring/parameter/testclasses/IFaceT.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeB.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeR.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeS.java
Whenever anybody needs to refactor method signature, it is necessary to found all methods and lambdas in sub and super class/interface hierarchies, which overrides/are overridden by the refactored method.
Note: it is not primitive operation, because it needs to correctly detect generic methods and methods in related inheritance hierarchies.
Example:
```java
class A {
void toBeRefactored(InputStream is) {}
}
class IFace<T> {
void toBeRefactored(T param) {}
}
class B extends A implements IFaceC {}
class D implements IFaceC<Writer> {
void toBeRefactored(Writer w) {}
}
class E {
void toBeRefactored(InputStream is) {}
}
```
Note that there are 2 inheritance hierarchies with roots:
1) A, with sub type B
2) IFaceC, with sub types B and D
But they are related because they share type B. If one …
=> review: feature: all executables same signature function

pom.xml, src/main/java/spoon/support/reflect/declaration/CtClassImpl.java
remove 
[WARNING] /home/martin/martin-no-backup/spoon/spoon-core/src/main/java/spoon/support/reflect/declaration/CtClassImpl.java:[259,64] toURL() in java.io.File has been deprecated
=> refactor: remove call to deprecated File#toURL

src/main/java/spoon/support/template/SubstitutionVisitor.java, src/test/java/spoon/test/template/InvocationTemplate.java, src/test/java/spoon/test/template/TemplateTest.java
There was not possible to substitute name of invoked method.
Example template:
```java
public class InvocationTemplate extends ExtensionTemplate {
IFace iface;
void invoke() {
//this method name was not substituted. This PR fixes it
iface.$method$();
}
@Local
public InvocationTemplate(CtTypeReference<?> ifaceType, String methodName) {
this.ifaceType = ifaceType;
this.methodName = methodName;
}
@Parameter("IFace")
CtTypeReference<?> ifaceType;
@Parameter("$method$")
String methodName;
@Local
interface IFace {
void $method$();
}
}
```
=> fix Template substitution of CtExecutableReference#simpleName

src/test/java/spoon/test/template/CheckBoundMatcher.java, src/test/java/spoon/test/template/TemplateTest.java
There is test, which should check contract
> together with the appropriate @Parameter f, this means
> we match all methods with name f*
but there is no such contract in TemplateMatcher and test is wrong. See the new test code, which shows the real contract, which is implemented.
=> bug in test testTemplateMatcher

src/main/java/spoon/reflect/visitor/filter/ExecutableReferenceFilter.java, src/test/java/spoon/test/refactoring/MethodsRefactoringTest.java
A `ExecutableReferenceFilter` provides fast matching for all `CtExecutableReference`s of defined set of `CtExecutable`s.
It is used to found all invocations of `CtExecutable`s in future method refactoring PRs.
This filter is much faster and has different contract then legacy InvocationFilter, which 
1) is able to search only for one CtExecutable
2) searches not only for exact reference to one executable (like ExecutableReferenceFilter), but it matches each reference, which overrides input executable.
If you do not like contract of ExecutableReferenceFilter, then optional solution would be to refactor legacy InvocationFilter by way it can be configured to support contract of this ExecutableReferenceFilter - to return (if configured so) exact (not overriding) invocations of more then one …
=> review: feature ExecutableReferenceFilter

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java, src/main/java/spoon/reflect/visitor/printer/PrinterHelper.java, src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java, src/test/java/spoon/test/prettyprinter/LinesTest.java
the line preservation mode can do a better job in preserving indentation of ending brackets.
here is a solution for this.
=> fix: improve line preservation mode

src/main/java/spoon/support/template/Parameters.java, src/main/java/spoon/template/TemplateMatcher.java
I am trying to understand how TemplateMatcher works and here are some
* javadoc added - which helps me and others to understand it better
* comments added about bugs - to plan future refactoring
* refactoring (removed some useless calls of `CtType#getReference`, which is immediately followed by `CtTypeReference#getDeclaringType`
@monperrus please have a look at it, even if it is WiP. This PR is more like list of TODO topics for future PRs. Are my changes on good way?
=> review: fix, improve and document TemplateMatcher

src/main/java/spoon/refactoring/CtParameterRemoveRefactoring.java, src/test/java/spoon/test/refactoring/MethodsRefactoringTest.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeB.java, src/test/java/spoon/test/refactoring/parameter/testclasses/TypeS.java
Implements a "method parameter remove refactoring function". It expects a CtParameter as input - it is the parameter, which has to be removed by this refactoring. 
The refactoring function:
**in preparation phase:**
* searches for all executables (methods and lambdas), which overrides/are overridden by the executable whose parameter has to be removed
* searches for all invocations to all found executables
**in validation phase:**
* reports an issue (stops refactoring) if to be removed parameter from any found executable is used
* reports an issue (stops refactoring) if to be removed argument from any found invocation is not a readonly literal (is not safe to remove it).
**in refactoring phase**
* removes appropriate argument from all found invocations
* removes appropriate parameter from …
=> review: feature Parameter remove refactoring

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ImportScanner.java, src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/test/java/spoon/test/imports/ImportScannerTest.java, src/test/java/spoon/test/imports/ImportTest.java
This PR fixes #1329 by adding a new method `getAllImports` and by deprecating `computeImports` and `computeAllImports` because their return type will change in the future to void.
=> refactor: change ImportScanner interface to add getAllImports

src/test/java/spoon/test/template/TemplateTest.java, src/test/java/spoon/test/template/testclasses/ArrayAccessTemplate.java
a Test of template which uses array access - should increase coverage ... and shows me how such template behaves.
=> review: test Template array access

checkstyle.xml
Too much convention is useless and no fun.
Julien Duribreux (@?) was right, we have to do something.
=> chore: remove checkstyle rule

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses/rxjava/BehaviorSubject.java, src/test/java/spoon/test/generics/testclasses/rxjava/Observable.java, src/test/java/spoon/test/generics/testclasses/rxjava/Processor.java, src/test/java/spoon/test/generics/testclasses/rxjava/Publisher.java, src/test/java/spoon/test/generics/testclasses/rxjava/PublisherRedo.java, src/test/java/spoon/test/generics/testclasses/rxjava/Subject.java, src/test/java/spoon/test/generics/testclasses/rxjava/Subscriber.java, src/test/java/spoon/test/generics/testclasses/rxjava/ToNotificationSubscriber.java, src/test/java/spoon/test/generics/testclasses/rxjava/Try.java
=> review fix: issue related with ReferenceBuilder and generics

src/main/java/spoon/support/visitor/ClassTypingContext.java, src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java
ClassTypingContext early finishes scanning of class hierarchy when a target supertype is found. That worked well. But this PR fixes bugs, which was visible when ClassTypingContext was asked to continue scanning.
There is a failing test case in it. 
This PR fixes problem originally found by Simon in PR #1375
=> review: fix continue algorithm of ClassTypingContext

doc/_data/sidebar_doc.yml, doc/faq.md, doc/reflection.md, src/main/java/spoon/Metamodel.java, src/test/java/spoon/test/api/MetamodelTest.java
=> feature: add first metamodel support

src/main/java/spoon/support/template/Parameters.java, src/main/java/spoon/support/template/SubstitutionVisitor.java, src/main/java/spoon/template/StatementTemplate.java, src/main/java/spoon/template/Substitution.java, src/test/java/spoon/test/template/TemplateArrayAccessTest.java, src/test/java/spoon/test/template/TemplateClassAccessTest.java, src/test/java/spoon/test/template/TemplateInvocationSubstitutionTest.java, src/test/java/spoon/test/template/TemplateReplaceReturnTest.java, src/test/java/spoon/test/template/TemplateTest.java, src/test/java/spoon/test/template/testclasses/ArrayAccessTemplate.java, src/test/java/spoon/test/template/testclasses/InvocationSubstitutionByExpressionTemplate.java, src/test/java/spoon/test/template/testclasses/InvocationSubstitutionByStatementTemplate.java, src/test/java/spoon/test/template/testclasses/LoggerModel.java, src/test/java/spoon/test/template/testclasses/SubstituteArrayLengthTemplate.java, src/test/java/spoon/test/template/testclasses/SubstituteRootTemplate.java, src/test/java/spoon/test/template/testclasses/inheritance/SubTemplate.java, src/test/java/spoon/test/template/testclasses/types/AClassModel.java, src/test/java/spoon/test/template/testclasses/types/AnEnumModel.java, src/test/java/spoon/test/template/testclasses/types/AnIfaceModel.java
Here is refactored SubstitutionVisitor. There are following changes:
C1) The SubstitutionVisitor can be used on any Spoon model and Map<String, Object> parameters. It does not need `Template`, `TemplateParameter`, `Parameter`. Of course they may be still used if it makes sense for client. See new constructor `SubstitutionVisitor(Factory f, Map<String, Object> templateParameters)`
C2) The SubstitutionVisitor can substitute the root node of substitution model by zero, one or more nodes.
See new method `<E extends CtElement> List<E> SubstitutionVisitor#substitute(E element)`
C3) There is possible to directly generate new Class, Interface, Enum, ... thanks to (C1). See
`CtType<T> Substitution#insertType(CtPackage targetPackage, String typeName, CtType<T> templateOfType, Map<String, Object> …
=> review: refactor SubstitutionVisitor

src/main/java/spoon/Metamodel.java, src/main/java/spoon/generating/CloneVisitorGenerator.java, src/main/java/spoon/reflect/code/CtBreak.java, src/main/java/spoon/reflect/code/CtContinue.java, src/main/java/spoon/reflect/code/CtLabelledFlowBreak.java, src/main/java/spoon/reflect/path/CtRole.java, src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java, src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/support/reflect/code/CtBreakImpl.java, src/main/java/spoon/support/reflect/code/CtContinueImpl.java, src/main/java/spoon/support/visitor/clone/CloneVisitor.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/test/labels/TestLabels.java, src/test/java/spoon/test/labels/testclasses/ManyLabels.java
The property labelledStatement was always equals to null.
Fix #1381
=> review: refactor(label): remove labelledStatement that was not used

src/main/java/spoon/support/template/SubstitutionVisitor.java, src/test/java/spoon/test/template/TemplateTest.java, src/test/java/spoon/test/template/testclasses/SubstituteLiteralTemplate.java
=> review: feature: Substitute string literals

src/main/java/spoon/reflect/factory/ExecutableFactory.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/visitor/ClassTypingContext.java, src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java
`getAllMethods` should not retrieve a parent method if an overridden method is defined, even if the signature is different. 
For example, if a class implements the method `public int compareTo(T o);` with object it will have the following signature: `public int compareTo(Object o)` and `getAllMethod` should only retrieve this one.
=> review: fix issue related with overridden methods retrieved from getAllMethods

.travis.yml
We can now use the Trusty image proposed by Travis, see: https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2
Fix #1414
=> review:Fix travis issue by using the last image on Travis #1414

src/main/java/spoon/reflect/annotations/MetamodelPropertyField.java, src/main/java/spoon/reflect/code/CtCase.java, src/main/java/spoon/reflect/code/CtCatch.java, src/main/java/spoon/reflect/code/CtConstructorCall.java, src/main/java/spoon/reflect/code/CtNewClass.java, src/main/java/spoon/reflect/declaration/CtCodeSnippet.java, src/main/java/spoon/reflect/declaration/CtModifiable.java, src/main/java/spoon/support/reflect/code/CtCaseImpl.java, src/main/java/spoon/support/reflect/code/CtNewClassImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/test/java/spoon/test/api/MetamodelTest.java
=> Review fix(role): fix wrong roles

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/exceptions/ExceptionTest.java, src/test/resources/noclasspath/UnionCatch.java
This PR fix a NPE we had when spooning a catch with multi exception inside a lambda in no classpath mode, as explained in #1415. 
However the bug is not completely solved in that PR, in that sense that the model is not exactly the same as if the try catch was outside the lambda. I decided to concentrate on getting information from multi types (which was causing the NPE). But to complete it, we should also compute the type of CtCatchVariable from the multitypes (it's normally done by JDT). I opened an issue for that and I propose to solve it in a separate PR (see #1420)
=> review: Fix NPE with union catch inside lambda in noclasspath

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java, src/main/java/spoon/reflect/visitor/printer/ListPrinter.java, src/main/java/spoon/reflect/visitor/printer/PrinterHelper.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/annotation/AnnotationValuesTest.java, src/test/java/spoon/test/arrays/ArraysTest.java, src/test/java/spoon/test/filters/FilterTest.java, src/test/java/spoon/test/reference/TypeReferenceTest.java
I am thinking of some enhancements of DefaultJavaPrettyPrinter and this would be the first BS.
@monperrus , do not merge this PR now, but please give me first a feedback whether you will merge the similar refactorings on all 16 places where `PrinterHelper#removeLastChar` is used.
Why to like it? ;-)
* it is shorter code - 6 lines instead of 11.
* there is less places for mistakes
* the PrinterHelper is not asked to print something and then to remove it - this bad approach makes future extensions of PrinterHelper more complicated...
Why to not like it?
* developer must know how the ListPrinter works to understand how it works. But then I think it is much more readable... so I hope it is not an issue.
WDYT? 
The suggestions for better names of new classes and methods are always welcome ;-)
=> review: refactor printing of lists in Spoon pretty printer

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/comment/CommentTest.java
The comments were printed wrong on MS Windows, when java source lines are separated by "\n" (it is case of sources which are checked out from GIT), while MS Windows EOL is "\n\r".
The new algorithm should split lines of comments independent on current OS.
=> fix printing of comments on MS Windows

src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java, src/test/java/spoon/test/imports/ImportTest.java
The imports generated by Spoon pretty printer are sorted alphabetically now.
The main advantage is that Spoon produces same content with each printing now. Before the imports were randomly mixed (because of HashSet).
=> review: feat: sort imports alphabetically

src/main/java/spoon/support/template/SubstitutionVisitor.java
This can happen when another Spoon code is buggy and delivers null strings instead of "". See #1442.
There is not possible to create test if other code is fixed
=> review: Fix null in substitution visitor

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/prettyprinter/PrinterTest.java, src/test/java/spoon/test/prettyprinter/testclasses/MissingVariableDeclaration.java
If the pretty printer fails now, It throws and SpoonException with position of the element, which caused problem now.
It helps to fix the problem without need to debug printer.
=> review: fix NPE in Pretty Printer on missing variable declaration

src/main/java/spoon/reflect/declaration/CtTypeMember.java
=> feature CtTypeMember extends CtNamedElement

src/main/java/spoon/template/Parameter.java, src/main/java/spoon/template/Substitution.java, src/test/java/spoon/test/template/TemplateTest.java, src/test/java/spoon/test/template/testclasses/EnumAccessTemplate.java, src/test/java/spoon/test/template/testclasses/InvocationSubstitutionByStatementTemplate.java, src/test/java/spoon/test/template/testclasses/InvocationTemplate.java, src/test/java/spoon/test/template/testclasses/SubStringTemplate.java, src/test/java/spoon/test/template/testclasses/SubstituteLiteralTemplate.java
@pvojtechovsky in #1444 has uncovered foggy parts in the template engine.
this PR is a first clarification about proxy template parameters (those with a value, eg `@Parameter("$name$")`.
=> fix: clarifies the contract of proxy template parameters

src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java, src/test/java/spoon/test/filters/FilterTest.java
If the client's code called in query callback fails with ClassCastException then this exception is actually silently ignored, because of one Spoon query contract.
This PR fixes this behavior by way that it distinguish between expected CCE in spoon code, which is still ignored as specified in contract, but client's CCEs are not ignored - s/he need to know about them, of course.
Something similar should be implemented into all Query callbacks too.
=> review: fix: ignore only expected ClassCastException

src/main/java/spoon/template/Substitution.java
It can be used without need to cast return value now.
=> fix Substitution#createTypeFromTemplate return type

CONTRIBUTING.md
The great Spoon community keeps growing, and we need to explain how to recognize a top-contributor as integrator.
What do you think of this?
=> community: add the integrator code of conduct

src/main/java/spoon/support/template/SubstitutionVisitor.java
The SubstitutionVisitor throws DoNotFurtherTemplateThisElement, which internally pretty printed the to be skipped element. It is not good idea because:
* it needs time to pretty print that element - why to do it that if nobody ever needs this information?
* it happened to me that printing failed, because the model is substituted only partially at this time. It happened during development of #1444, but it was probably side effect of bug fixed by #1477, so it does not fail anymore. Therefore I am not able to create failing test for this PR.
=> review: performance of DoNotFurtherTemplateThisElement

src/main/java/spoon/support/compiler/jdt/FileCompilerConfig.java, src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
This is the implementation of FileCompilerConfig constructor which was originally called:
```java
public FileCompilerConfig(SpoonFolder folder) {
this(folder.getAllJavaFiles());
}
```
That call can be avoided because we already have a list of all files in variable `sourceFiles`.
=> perf: Collect list of source files only once

CONTRIBUTING.md
I propose that Pavel @pvojtechovsky gets write access to the repo, so that he can review and merge other PRs.
For months, Pavel has done deep contributions to Spoon, and knows the design, the testing practices and the way we communicate and find consensus in the community.
I'm sure that Pavel will do a great integrator job.
@pvojtechovsky do you agree with the [integrator code of conduct](https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md) ?
@tdurieux @surli @danglotb do you agree that @pvojtechovsky joins the integrator committee?
=> community: @pvojtechovsky gets merge honor and responsibility

src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java
let JDK compiler parse comments only if they are needed.
Note: the CompilationUnitDeclaration#comments are needed only by JDTCommentBuilder whose usage is already restricted by ...getEnvironment().isCommentsEnabled()
=> perf: compile comments only if needed

src/main/java/spoon/support/template/Parameters.java, src/test/java/spoon/test/template/TemplateTest.java, src/test/java/spoon/test/template/testclasses/ObjectIsNotParamTemplate.java
```java
public class ObjectIsNotParamTemplate extends ExtensionTemplate {
//this is normal field of type Object - it must not be considered as template parameter automatically
Object o = "XXX";
//the "o" in the method name must not be substituted
void method() {}
@Local
public ObjectIsNotParamTemplate() {
}
}
```
This template generated method with name `methXXXd` and it is of course wrong. This PR fixes this behavior.
May be the origin idea of the author was that each field whose type is subtype of TemplateParameter is automatically a template parameter. If you think that this contract is correct then implement it in another PR. I will have no time to continue on this PR in near future, so please merge it as it is - with fix only.
=> review: fix object is not an template parameter implicitly

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/PrettyPrinter.java
This method is unused and unusable. It's existence avoids refactoring of PrettyPrinter concerning #1460 too.
=> review: refactor: remove unused and wrong PrettyPrinter#getPackageDeclaration

src/main/java/spoon/reflect/code/CtComment.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/comment/testclasses/WildComments.java, src/test/java/spoon/test/comment/testclasses/WindowsEOL.java
The RegExp for splitting of comments by EOL was wrong. MS Windows is using `\r\n` and not `\n\r` like it was wrong before
=> review: fix splitting of comment by EOL

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/PrettyPrinter.java, src/main/java/spoon/reflect/visitor/printer/PrinterHelper.java, src/main/java/spoon/support/JavaOutputProcessor.java
Added method `DefaultJavaPrettyPrinter#setLineSeparator(String)`, as one step of the solution suggested in #1460 - to be able to define line separator used by spoon pretty printer.
This PR contains also necessary refactoring and cleaning of DefaultJavaPrettyPrinter.
=> review: feat: DefaultJavaPrettyPrinter#setLineSeparator(String)

src/main/java/spoon/Launcher.java, src/main/java/spoon/SpoonModelBuilder.java, src/main/java/spoon/compiler/Environment.java, src/main/java/spoon/support/StandardEnvironment.java, src/main/java/spoon/support/compiler/jdt/FileCompilerConfig.java, src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java, src/test/java/spoon/test/compilationunit/TestEncoding.java, src/test/resources/noclasspath/IsoEncoding.java
Add encoding in Environment and use it in CompilationUnit#getOriginalSourceCode() 
Fix #1497
=> review: refactor Environment to add encoding

src/main/java/spoon/reflect/visitor/filter/NameFilter.java, src/main/java/spoon/reflect/visitor/filter/NamedElementFilter.java, src/test/java/spoon/test/filters/FilterTest.java
There is a global problem with generic which prevent from type checking: you cannot use at runtime information about generic types and we often lose the generic type inside operation in Spoon. 
So I propose to solve a bug with generic type in NameFilter by adding a new constructor with a parameter wich is the class of the type we finally want. It's the only solution I can see to prevent an eventual ClassCastException when iterating on the result list. 
I also deprecate the old NameFilter constructor as it cannot guarantee the type of the results.
=> review fix: NameFilter of T also return elements of other types

src/main/java/spoon/support/StandardEnvironment.java, src/test/java/spoon/test/compilation/CompilationTest.java
setInputClassLoader was failing when the URLs retrieved from the specified URLClassLoader were file URLs. The URLs were transmitted to verifySourceClasspath that is expected path elements, not URLs.
This PR fixes this bug by retrieving path elements from the file URLs.
=> review: Bug fix when using a URLClassLoader with file: URLs.

src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java, src/test/java/spoon/test/reference/ElasticsearchStackoverflow.java, src/test/java/spoon/test/reference/ElasticsearchStackoverflowTest.java, src/test/resources/noclasspath/elasticsearch-stackoverflow/BroadcastShardResponse.java, src/test/resources/noclasspath/elasticsearch-stackoverflow/TransportBroadcastAction.java
As you can see, getDeclaration causes a stack overflow. I have no idea why this is happening.
=> review: fix a stack overflow when calling getDeclaration on a CtExecutableReference related to a CtTypeParameter in noclasspath

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
Wrap the output streams for the generated files inside a try-with-resources. Was preventing generated files from being deleted/moved while Spoon was still executing.
=> Fixes file resource leak

src/main/java/spoon/reflect/visitor/CommentHelper.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/printer/LiteralHelper.java, src/main/java/spoon/reflect/visitor/printer/OperatorHelper.java, src/main/java/spoon/reflect/visitor/printer/PrinterHelper.java
First basic refactoring step needed to implement all the changes needed by #1494.
=> review: refactor: PrinterHelper to CommentHelper, LiteralHelper and OperatorHelper

pom.xml
This JDT is newer and has published sources in maven repository, so it is easier to debug...
=> chore: Upgrade to org.eclipse.jdt:org.eclipse.jdt.core:3.12.3

src/main/java/spoon/reflect/visitor/CommentHelper.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ListPrinter.java, src/main/java/spoon/reflect/visitor/LiteralHelper.java, src/main/java/spoon/reflect/visitor/OperatorHelper.java, src/main/java/spoon/reflect/visitor/PrinterHelper.java, src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java
=> review: refactor: use LiteralHelper in DefaultJavaPrettyPrinter

src/main/java/spoon/reflect/visitor/CtAbstractVisitor.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
=> add simple support for enter/exit in DJPP as in CtScanner

src/main/java/spoon/template/Substitution.java, src/test/java/spoon/test/template/TemplateTest.java, src/test/java/spoon/test/template/testclasses/TypeReferenceClassAccessTemplate.java
As found by implementation of #1454, there is not possible to implement Templates, which are using template parameter of type CtTypeReference, which should substitute local class.
This PR relaxes the constraint by way the CtTypeReference may use proxy parameter value too
=> review: Fix template parameter constraint

src/main/java/spoon/reflect/CtModelImpl.java, src/test/java/spoon/test/pkg/PackageTest.java, src/test/java/spoon/test/pkg/testclasses/ElementProcessor.java, src/test/resources/noclasspath/app/Test.java
=> review: fix: prevent renaming CtRootPackage

src/test/java/spoon/test/main/MainTest.java
I would like to use lambdas in spoon code now, but this test fails on it.
=> fix: java compliance to 8 - allow lambdas in spoon code

src/main/java/spoon/Launcher.java, src/main/java/spoon/support/StandardEnvironment.java
Can then be used in #1533 (see https://github.com/INRIA/spoon/pull/1533/files/f3a15395c3c2fdc11b4bbd1783fd585a449d5f82#diff-3aaab37f1a98ef87283c1ec4104bcf41R324)
=> review: feat: Create launcher constant for code compliance level

src/test/java/spoon/MavenLauncherTest.java
The ant dependency was removed so the test should be changed
=> fix(test): wrong number of dependency MavenLauncherTest

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java, src/main/java/spoon/reflect/visitor/ListPrinter.java
* ElementPrinterHelper moved next to DJPP - it belongs there some like others.
* ListPrinter made package protected too
=> refactor: Move ElementPrinterHelper

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/PrinterHelper.java
* DefaultJavaPrettyPrinter uses OperatorHelper instead of now deprecated PrinterHelper methods
* Some code of DefaultJavaPrettyPrinter is more friendly to future PrinterTokenWriter #1494
=> refactor: DefaultJavaPrettyPrinter better uses OperatorHelper

src/test/java/spoon/test/api/APITest.java, src/test/java/spoon/test/compilation/CompilationTest.java, src/test/java/spoon/test/main/MainTest.java
because no need to build the model for the whole src/main/java for certain tests
=> test: faster test execution 

src/main/java/spoon/reflect/visitor/filter/PotentialVariableDeclarationFunction.java, src/test/java/spoon/MavenLauncherTest.java, src/test/java/spoon/test/main/MainTest.java, src/test/java/spoon/test/query_function/VariableReferencesTest.java, src/test/java/spoon/test/query_function/testclasses/VariableReferencesFromStaticMethod.java
As reported in #1513 the `PotentialVariableDeclarationFunction` returns non static field `test` as potential variable declaration of local variable reference declared in static method.
```java
int test = 0;  //this one should not be returned, because it is not static
public static void main(String[] args)
{
int test = 1; 
assertEqualst(1, test); //reference to local test variable
}
```
=> review: fix PotentialVariableDeclarationFunction ignoring the static scope

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java, src/main/java/spoon/reflect/visitor/PrintingContext.java, src/test/java/spoon/test/template/TemplateTest.java, src/test/java/spoon/test/template/testclasses/TypeReferenceClassAccessTemplate.java
Here is the failing test, which shows that Spoon prints actual type arguments in class access: `List<Object>.class`
Is it problem of pretty printer or SubstitutionVisitor?
=> review fix: Invalid use of type access generics

src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java, src/main/java/spoon/support/util/RtHelper.java, src/test/java/spoon/test/api/APITest.java, src/test/java/spoon/test/filters/FilterTest.java
I wanted to debug `MainTest#testMain` and I have found that it is terribly slow (needs nearly 19 min) in debug mode. 18 min is spent in creation of ClassCastException stacktraces.
This PR detects acceptable type from message of first CCE and then checks whether class of input is acceptable - so it avoids throwing of CCE - performs faster in debug (52s)
The performance improvement is only little in non debug mode (28s origin, 25s after improvement).
Actually this PR fails on java 7/8 source compliance (will be fixed by #1539)
=> review: perf: Avoid slow CCE. Check acceptable type when possible

src/main/java/spoon/reflect/declaration/CtExecutable.java, src/main/java/spoon/reflect/reference/CtExecutableReference.java, src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/support/template/SubstitutionVisitor.java, src/main/java/spoon/support/util/SignatureBasedSortedSet.java, src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/test/api/NoClasspathTest.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/main/MainTest.java, src/test/java/spoon/test/reference/ExecutableReferenceGenericTest.java, src/test/java/spoon/test/reference/ExecutableReferenceTest.java, src/test/java/spoon/test/replace/ReplaceTest.java, src/test/java/spoon/test/secondaryclasses/ClassesTest.java, src/test/java/spoon/test/signature/SignatureTest.java
We have problems regarding method signatures:
* 1) the current signatures of method references are completely different which is particularly confusing. One contains the declaring type which is about method links in Javadoc, not about signatures. 
* 2) There is no clear definition of method signatures in the Java specification (while usually the return type is not  considered as part of the signature, there are cases with generics where it actually matters).
This PR fixes 1) and makes a sensible choice for 2)
Fix #1483
=> fix: cleaning of method signature computation

src/main/java/spoon/reflect/visitor/CommentHelper.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/DefaultTokenWriter.java, src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java, src/main/java/spoon/reflect/visitor/PrinterHelper.java, src/main/java/spoon/reflect/visitor/TokenWriter.java, src/test/java/spoon/test/enums/EnumsTest.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java, src/test/java/spoon/test/prettyprinter/PrinterTest.java
PrinterHelper can print tabs automatically. So all TokenWriter.writeTabs and related calls are useless and can be removed - simpler code!
=> review: refactor: PrinterHelper prints tabs automatically

src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/testclasses/StaticNoOrdered.java
=> review: test: check if static imports are placed after type imports

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/PrinterHelper.java, src/test/java/spoon/test/prettyprinter/PrinterTest.java
=> get rid of snapshotLength and hasNewContent

src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java, src/test/java/spoon/test/filters/FilterTest.java
This is an alternative solution to #1578
=> alternative fix: the query engine is broken on some JVM because it relies on stack trace elements

src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/testclasses/DumbClassUsingInternal.java
=> review: fix: ImportBuilder to check visibility when importing starred imports

src/test/java/spoon/test/main/MainTest.java
Should solve OutOfMemoryException in CI
=> fix: MainTest#checkModelIsTree needs less memory

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/annotation/AnnotationValuesTest.java, src/test/java/spoon/test/template/TemplateArrayAccessTest.java
```java
String[] field = new String[]{ "a" , "b" , "c" }; //old printing
String[] field = new String[]{ "a", "b", "c" }; //new printing
```
... needed to pass Spoon checkstyle in generated `ModelRoleHandlers` of #1582
=> fix: pretty printer adds no space before comma in new array expression

src/main/java/spoon/reflect/declaration/CtCodeSnippet.java, src/main/java/spoon/reflect/path/CtRole.java, src/main/java/spoon/support/reflect/code/CtCodeSnippetExpressionImpl.java, src/main/java/spoon/support/reflect/code/CtCodeSnippetStatementImpl.java
This PR introduces new CtRole.SOURCE_CODE, which is used for value of CtCodeSnippet. Before there was CtRole.EXPRESSION, which has different meaning.
=> refactor(role): CtCodeSnippet has CtRole.SOURCE_CODE

src/main/java/spoon/MavenLauncher.java
Optional dependencies are used to prevent exporting dependencies, but they're not optional for current project (it's a really bad keyword...). 
Then IMHO we should not pass them everytime for building the classpath in SpoonMavenLauncher.
=> fix: Optional maven dependencies should not be pass in SpoonMavenLauncher

src/main/java/spoon/reflect/code/CtTypeAccess.java, src/main/java/spoon/reflect/path/CtRole.java, src/main/java/spoon/support/reflect/code/CtTypeAccessImpl.java
There was conflict with CtTypeAccess#getType(), which returns different value, but had same role CtRole.TYPE
=> review1: fix(role): CtTypeAccess getTypeAccess uses CtRole.TYPE_ACCESS

src/main/java/spoon/support/DerivedProperty.java
per our discussion on #1586,  PropertyGetter can be used for @DerivedProperty as well
=> doc: clarifies contracts of @DerivedProperty

src/main/java/spoon/support/visitor/ClassTypingContext.java, src/main/java/spoon/support/visitor/MethodTypingContext.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses2/SameSignature2.java
The method with this declaration
```java
<U> void visitCtConditional(final CtConditional<U> conditional)
```
defined in class and inteface returned false for ClassTypingContext#isSameSignature(methodFromIface, methodFromClass).
=> fix: ClassTypingContext#isSameSignature for generic methods

src/main/java/spoon/support/visitor/MethodTypingContext.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses2/SameSignature3.java
The method like this caused StackOverflowError
```java
<U, K extends U void visitCtConditional(final CtConditional<U> conditional, K k)
```
=> review1: fix: StackOverflowError in MethodTypingContext on <T, U extends T>

src/main/java/spoon/reflect/factory/Factory.java, src/main/java/spoon/reflect/factory/FactoryImpl.java, src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
=> review: feat: add missing create method in Factory

src/main/java/spoon/reflect/factory/TypeFactory.java
I often needs CtTypeReferences of List, Set, Map, ... may be they might be available as constansts?
WDYT?
=> feature: TypeFactory LIST, SET, MAP, ... constant type references

src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses2/LikeCtClass.java, src/test/java/spoon/test/generics/testclasses2/LikeCtClassImpl.java
If CtTypeParameterReference#getBoundingType() returns null or Object, then it has same meaning - there is no bound = java.lang.Object is a bound.
The problem is that some type references returns Object and some returns null. I do not have test case yet, but it happened to me that 2 CtTypeReferences with exactly same printed representation were not equal because one of them had bounding type = null and second had Object.
For future I would prefer to fix it opposite way: to always return Object reference in such case (never null), but this solution needs much more changes in Spoon code, because it expects on many places null value.
So this PR is fast fix to be able to finish other PRs related to CtScanner, etc.
WDYT?
=> review1: fix: CtTypeParameterReference#getBoundingType() Object -> null

src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/support/compiler/jdt/ContextBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java, src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java, src/main/java/spoon/support/visitor/clone/CloneVisitor.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/test/trycatch/TryCatchTest.java
=> review1: fix: CtCatchVariable merge type and multiType

src/main/java/spoon/reflect/declaration/CtField.java, src/main/java/spoon/reflect/reference/CtIntersectionTypeReference.java, src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/support/reflect/code/CtLocalVariableImpl.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationMethodImpl.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationTypeImpl.java, src/main/java/spoon/support/reflect/declaration/CtAnonymousExecutableImpl.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/main/java/spoon/support/reflect/declaration/CtEnumImpl.java, src/main/java/spoon/support/reflect/declaration/CtEnumValueImpl.java, src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java, src/main/java/spoon/support/reflect/declaration/CtParameterImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeParameterImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtUnboundVariableReferenceImpl.java, src/main/java/spoon/support/visitor/clone/CloneVisitor.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/reflect/visitor/CtScannerTest.java
This PR contains fixes of CtScanner, CtScanner test and Spoon model annotations related to CtScanner.
=> review: fix: better tests for CtScanner

src/main/java/spoon/support/compiler/jdt/ParentExiter.java, src/test/java/spoon/test/position/PositionTest.java, src/test/java/spoon/test/position/testclasses/ImplicitBlock.java
=> feat: add position to implicit block in CtIf

src/main/java/spoon/MavenLauncher.java
=> feat: MavenLauncher Warning when a provided dependency is not loaded 

src/main/java/spoon/generating/CloneVisitorGenerator.java, src/main/java/spoon/generating/CtBiScannerGenerator.java, src/main/java/spoon/generating/replace/ReplaceScanner.java, src/main/java/spoon/reflect/visitor/CtAbstractBiScanner.java, src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/reflect/visitor/EarlyTerminatingScanner.java, src/main/java/spoon/support/template/SubstitutionVisitor.java, src/main/java/spoon/support/visitor/ProcessingVisitor.java, src/test/java/spoon/reflect/visitor/CtScannerTest.java, src/test/java/spoon/test/SpoonTestHelpers.java
This is an alternative to #1631 which directly modifies CtScanner ... to see how much Spoon will be broken...
=> review: refactor: CtScanner to report CtRole of scanned element

doc/first_analysis_processor.md
first improvement for https://stackoverflow.com/questions/47003274/starting-off-with-spoon
=> doc: improve getting started

chore/revapy.py
=> chore: Revapi now deletes its own comments before commenting

chore/revapi_tpl.ftl
I played with Freemarker macros and was able to implement class name shortening - i.e. leaving out the package names and type parameters.
I was not able to test on spoon itself (I didn't see the rendered output as you have it on github) but I tested the macros with a number of changes for which it produced desirable output.
=> chore: Implement class name shortening by a bunch of Freemarker macros.

src/main/java/spoon/support/compiler/jdt/ContextBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java, src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/modifiers/TestModifiers.java, src/test/java/spoon/test/modifiers/testclasses/MethodVarArgs.java
This PR fix a bug brings by @seintur : a method with varargs is currently printed out with transient modifier. 
This happens because of the recent usage of methodDeclaration.binding.modifier and the fact that varargs have the same modifier flag than varargs. See: https://stackoverflow.com/questions/16233910/can-transient-keywords-mark-a-method
The fix is an exception made when computing modifiers for methods.
=> review fix: method should never be transient 

src/main/java/spoon/reflect/declaration/CtModifiable.java, src/main/java/spoon/support/reflect/CtModifierHandler.java, src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java, src/main/java/spoon/support/reflect/code/CtLocalVariableImpl.java, src/main/java/spoon/support/reflect/declaration/CtAnonymousExecutableImpl.java, src/main/java/spoon/support/reflect/declaration/CtConstructorImpl.java, src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java, src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java, src/main/java/spoon/support/reflect/declaration/CtParameterImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeParameterImpl.java, src/test/java/spoon/test/modifiers/TestModifiers.java
Fix the documentation for `CtModifiable#addModifier` (Fix #1616)
Change the signature of `CtModifiable#removeModifier` to be consistent
=> review refactor: CtModifiable add/removeModifier

doc/filter.md, src/main/java/spoon/reflect/declaration/CtElement.java, src/main/java/spoon/reflect/meta/ContainerKind.java, src/main/java/spoon/reflect/meta/RoleHandler.java, src/main/java/spoon/reflect/meta/impl/AbstractRoleHandler.java, src/main/java/spoon/reflect/meta/impl/ModelRoleHandlers.java, src/main/java/spoon/reflect/meta/impl/RoleHandlerHelper.java, src/main/java/spoon/reflect/meta/impl/RoleHandlerProvider.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/MavenLauncherTest.java, src/test/java/spoon/generating/RoleHandlersGenerator.java, src/test/java/spoon/generating/meta/ModelRoleHandlerTemplate.java, src/test/java/spoon/generating/meta/RoleHandlerTemplate.java, src/test/java/spoon/processing/CtGenerationTest.java, src/test/java/spoon/reflect/ast/AstCheckerTest.java, src/test/java/spoon/test/reflect/meta/MetaModelTest.java
Early implementation of spoon model CtRole based access to element attributes. See discussion in #1581
=> review: feat: Spoon CtRole based attributes access

src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java, src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java, src/main/java/spoon/support/visitor/java/internal/AnnotationRuntimeBuilderContext.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/annotation/testclasses/spring/AliasFor.java
=> review fix: issue when using recursively defined annotation in shadow class

src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java
Travis move from Java 1.8.0_144 to Java 1.8.0_151 for their JDK8. 
Our assertion no longer pass on CtTypeInformationTest, this PR fixes it.
=> review: Fix test assertion with JDK8 on Travis

src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/generating/CloneVisitorGenerator.java, src/test/java/spoon/generating/RoleHandlersGenerator.java, src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java, src/test/java/spoon/test/metamodel/MMType.java
=> review refactor: all non-leaf interfaces of the metamodel should be visited by CtInheritanceScanner

src/main/java/spoon/support/visitor/HashcodeVisitor.java, src/test/java/spoon/test/reference/ExecutableReferenceTest.java
It seems that Spoon make no distinction between reference hashcode: they all have a value to 1.
=> review fix: CtExecutableReference have all the same hashcode

src/main/java/spoon/reflect/factory/AnnotationFactory.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/annotation/testclasses/notrepeatable/StringAnnot.java, src/test/java/spoon/test/annotation/testclasses/repeatable/Repeated.java, src/test/java/spoon/test/annotation/testclasses/repeatable/Tag.java, src/test/java/spoon/test/annotation/testclasses/repeatable/Tags.java, src/test/java/spoon/test/annotation/testclasses/repeatandarrays/RepeatedArrays.java, src/test/java/spoon/test/annotation/testclasses/repeatandarrays/TagArrays.java, src/test/java/spoon/test/annotation/testclasses/repeatandarrays/TagsArrays.java
=> review fix: fix bug with repeatable annotations

src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/processing/CtGenerationTest.java
This PR fixes an issue creating in #1647 
After moving everything in test, we forget to update pathes for ReplacementVisitorGeneration: then the old visitor was always pretty-printed from its own definition, the test then would always return true. This PR fixes that. Maybe for the future we should consider computing and inserting a unique value in order to avoid this kind of error.
=> review: fix: ReplacementVisitorGeneration only copy existing ReplacementVisitor file

src/main/java/spoon/reflect/declaration/CtModifiable.java, src/main/java/spoon/support/reflect/CtModifierHandler.java, src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java, src/main/java/spoon/support/reflect/code/CtLocalVariableImpl.java, src/main/java/spoon/support/reflect/declaration/CtAnonymousExecutableImpl.java, src/main/java/spoon/support/reflect/declaration/CtConstructorImpl.java, src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java, src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java, src/main/java/spoon/support/reflect/declaration/CtParameterImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/test/java/spoon/test/modifiers/TestModifiers.java, src/test/java/spoon/test/modifiers/testclasses/AbstractClass.java, src/test/java/spoon/test/modifiers/testclasses/ConcreteClass.java
=> review feat: Add helpers methods in CtModifiable

src/test/java/spoon/generating/CloneVisitorGenerator.java, src/test/java/spoon/generating/CtBiScannerGenerator.java, src/test/java/spoon/generating/replace/ReplaceScanner.java, src/test/java/spoon/reflect/visitor/CtScannerTest.java
CtGenerationTest and CtScannerTest were buggy with the changes bring by adding roles in CtScanner: if no role were provided, the test were erroring with either a NPE (for CtScannerTest) or an OutOfBoundException (for CtGenerationTest).
This PR throws directly a RuntimeException with a proper message in CtGenerationTest and stack the problem in the list of problems in CtScannerTest.
=> review test: improve CtGenerationTest and CtScannerTest

src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
@surli would you have a look at this one?
=> review test: add test for getAnnotation().value() on shadow classes

src/main/java/spoon/reflect/meta/impl/ModelRoleHandlers.java, src/main/java/spoon/reflect/path/CtRole.java, src/test/java/spoon/generating/RoleHandlersGenerator.java, src/test/java/spoon/test/role/TestCtRole.java
I need that in new TemplateMatcher to distinguish between derived attributes and real attributes.
E.g. `CtRole.CONSTRUCTOR.getSuperRole() == CtRole.TYPE_MEMBER`
=> feature: CtRole#getSuperRole(), CtRole#getSubRole()

src/test/java/spoon/test/template/testclasses/bounds/CheckBoundMatcher.java
I suggest to change this test, because the new template matcher (#1686), which collects matching parameter values, fails on this. Note: left and right expression are not same in the matching examples, so there should be different variables (_x_ and _y_) and not only one, like it is now.
=> fix(test): CheckBoundMatcher

.travis.yml
See: https://docs.travis-ci.com/user/languages/java/#Maven-Dependency-Management
=> review chore: Travis: Skip checkstyle when calling mvn install for installing dependencies

src/test/java/spoon/test/template/TemplateReplaceReturnTest.java, src/test/java/spoon/test/template/testclasses/ReturnReplaceTemplate.java
Improves a test of substitution of `return expression.S()`, which actually substitutes
A) `return expression.S()` if the parameter value is CtBlock
B) `expression.S()` if the parameter value is an expression
The case B) was not tested before, so I would like to add this test before #1686 so it visible that this contract is still working and did not changed.
=> test: substitution of `return expression.S()`

src/test/java/spoon/test/metamodel/MMField.java, src/test/java/spoon/test/reflect/meta/MetaModelTest.java
Value type of MMField `CtLiteral#value` was Object with implicit = true, which caused problem in new template substitution and then invalid pretty printing of such type references... DJPP doesn't prints such TypeReferences, even if they are on place where they cannot be implicit.
=> fix: test meta model - MMField value(Item)Type is not implicit

src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java
The new Templating engine (#1686) uses CtQuery a lot and Java runtime decided to optimize exception handling in runtime. It was the reason why many tests started to fail with strange exception without the stacktrace.
This PR handles such "preallocated exceptions" well.
See java [release notes](http://www.oracle.com/technetwork/java/javase/relnotes-139183.html#vm) for details:
> The compiler in the server VM now provides correct stack backtraces for all "cold" built-in exceptions.
For performance purposes, when such an exception is thrown a few times, the method may be recompiled. After recompilation, the compiler may choose a faster tactic using preallocated exceptions that do not provide a stack trace. To disable completely the use of preallocated exceptions, use this new flag: …
=> fix: CtQueryImpl handling of preallocated exceptions

src/main/java/spoon/reflect/factory/Factory.java, src/main/java/spoon/reflect/factory/FactoryImpl.java, src/main/java/spoon/reflect/factory/QueryFactory.java, src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java, src/test/java/spoon/test/filters/FilterTest.java
Possibility to create query on Collection of elements. No need to create helper array, just to convert collection to format acceptable by API.
=> feature: Factory#createQuery(Iterable)

src/main/java/spoon/Launcher.java, src/main/java/spoon/compiler/Environment.java, src/main/java/spoon/support/StandardEnvironment.java
This PR aims at simplifying the usage of API for defining output type: until now the only way to specify the output type was using the argument "output-type" or using its own call of `JDTSpoonCompiler#generateProcessedSourceFiles`. Now it can be done simply by setting `Environment#setOutputType`
=> review refactor(api): OutputType available in Environment

src/main/java/spoon/reflect/factory/TypeFactory.java
=> fix: TypeFactory type arguments of constants

src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/test/java/spoon/test/eval/EvalTest.java, src/test/java/spoon/test/eval/ToEvaluate.java
Several fixes are here:
* the simplification of invocation to literal can be done only when parent accepts CtExpression
* the simplification of invocation to literal can be done only when returned value is a primitive object
* the handling of try/catch control flow was fixed - it removed statements after catch(... e){throw e;}
* the type casts are kept
=> fix: VisitorPartialEvaluator

src/main/java/spoon/support/visitor/equals/CloneHelper.java
The `CloneHelper#addClone(...)` methods let's us implement Substitution (#1686) as part of cloning process.
=> feature: CloneHelper#addClone - support of clone process customization

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/prettyprinter/PrinterTest.java
In case  of some model inconsistency (missing field declaration) the DJPP failed before. It is much more debugging friendly if there is no failure, but if it prints the comment with error description instead.
WDYT?
=> fix: DefaultJavaPrettyPrinter prints an ERROR comment instead of failure

doc/template_definition.md, src/main/java/spoon/support/template/Parameters.java, src/test/java/spoon/test/template/TemplateInvocationSubstitutionTest.java, src/test/java/spoon/test/template/testclasses/SubstitutionByExpressionTemplate.java
Each field whose type extends TemplateParameter is a template parameter now.
For example this is template parameter.
```java
CtExpression<String> _expression_;
```
=> fix: detection of TemplateParameter in Parameters#isParameterSource

src/main/java/spoon/support/gui/SpoonModelTree.java
new constructor  SpoonModelTree(CtElement rootElement) allows to visualize spoon model of subtree.
=> feature: SpoonModelTree can be created with custom root element

src/main/java/spoon/reflect/visitor/filter/AbstractFilter.java
This PR intends to fix the bug introduced in #1798 which make projects using JDK7 and custom filters fail. The error comes from the usage of a default method: overriding it in AbstractFilter fixes the bug.
=> review fix: Filter extends Predicate is now working with projects in JDK7

src/main/java/spoon/reflect/meta/impl/RoleHandlerHelper.java, src/test/java/spoon/test/reflect/meta/MetaModelTest.java
Some helper methods which allows generically access Spoon model
=> feature: RoleHandlerHelper#getRoleHandlers(Class), forEachRoleHandler, getParentRoleHandler

src/main/java/spoon/support/reflect/code/CtJavaDocImpl.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/comment/testclasses/OtherJavaDoc.java
=> fix: CtJavadoc#getShortDescription

src/main/java/spoon/support/visitor/ClassTypingContext.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses/OuterTypeParameter.java
fix of #1835
The problem was caused by type parameters, which were declared out of the scope of ClassTypingContext. Such type parameters must be kept as they are. It is not model inconsistency or reason to fail.
=> fix: ClassTypingContext resolveTypeParameter of outer parameters

src/main/java/spoon/support/reflect/code/CtJavaDocTagImpl.java, src/test/java/spoon/test/javadoc/JavaDocTest.java
Added toString() method to CtJavaDocImpl.java to handle getDocComment()
=> fix: getDocComment() returns asterisk (*) and spaces before comment

src/main/java/spoon/compiler/builder/SourceOptions.java, src/main/java/spoon/reflect/factory/CoreFactory.java, src/main/java/spoon/reflect/factory/Factory.java, src/main/java/spoon/reflect/visitor/CtVisitor.java, src/main/java/spoon/reflect/visitor/chain/CtConsumer.java, src/main/java/spoon/reflect/visitor/chain/CtFunction.java, src/main/java/spoon/support/visitor/SignaturePrinter.java, src/main/java/spoon/testing/utils/ProcessorUtils.java
(a documentation enforcing test is coming)
=> doc: add missing javadoc on public methods

src/main/java/spoon/support/visitor/equals/EqualsChecker.java, src/test/java/spoon/test/visitor/AssignmentsEqualsTest.java, src/test/resources/spoon/test/visitor/Assignments.java
Hi! I have found a bug, in `EqualsChecker` class, and this PR is a possible fix.
The problem is that `.equals` method called on `CtAssignment` and `CtOperatorAssignment` (which extends `CtAssignment`) returns true, once rhs and lhs statements are the same. But this is not correct.
For example, statements `x = 42` and `x += 42` are not the same thing at all.
To fix that, I implemented `visitCtAssignment` method.
Also, I provided some tests (second assert fails, without this fix).
=> fix EqualsChecker for assignments

src/main/java/spoon/support/reflect/cu/position/SourcePositionImpl.java, src/test/java/spoon/test/serializable/SourcePositionTest.java, src/test/resources/serialization/SomeClass.java
Hi! I found out that filename from `SourcePosition` is lost during serialization (it's null). Although line number, column, etc. are present in deserialized model.
This happens because `getFile()` uses `compilationUnit`, which is null in deserialized model.
I fixed that by introducing field '`file`' in `SourcePosition`.
Also, I provided some tests. Particularly, without this fix the following assertions fail:
```
assertTrue(type.getPosition().getFile().equals(typeFromFile.getPosition().getFile()));
....
assertTrue(elem1.getPosition().getFile().equals(elem2.getPosition().getFile()));
```
Really want this fix, because without it we can't get any filename from SourcePosition from deserialized model.
=> fix getFile() for serialization

src/main/java/spoon/reflect/declaration/CtMethod.java, src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java, src/test/java/spoon/test/filters/FilterTest.java, src/test/java/spoon/test/filters/testclasses/AbstractTostada.java, src/test/java/spoon/test/filters/testclasses/ITostada.java, src/test/java/spoon/test/filters/testclasses/Tostada.java
=> feat: add method CtMethod#getTopDefinitions

src/main/java/spoon/support/reflect/declaration/CtClassImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/test/java/spoon/test/ctClass/CtClassTest.java
=> feat: one could add a type member that already exists (equals but not same) and modify it afterwards

chore/revapi_tpl.ftl, chore/revapy.py, src/main/java/spoon/reflect/visitor/CtAbstractBiScanner.java
=> Review: chore: fix revapi commenting bot

src/main/java/spoon/support/visitor/clone/CloneBuilder.java, src/main/java/spoon/support/visitor/clone/CloneVisitor.java, src/main/java/spoon/support/visitor/equals/CloneHelper.java, src/test/java/spoon/generating/CloneVisitorGenerator.java, src/test/java/spoon/generating/clone/CloneBuilderTemplate.java
We want to be able, in the future, to slightly adapt the cloning behavior without touching the generator of cloning code.
In particular, it will be useful for #1869
=> review: refactor: refactor cloning code to increase extendability

src/main/java/spoon/refactoring/Refactoring.java, src/main/java/spoon/reflect/declaration/CtElement.java, src/main/java/spoon/reflect/declaration/CtMethod.java, src/main/java/spoon/reflect/declaration/CtType.java, src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/test/java/spoon/reflect/ast/CloneTest.java, src/test/resources/noclasspath/A2.java
plus changeMethodName as useful bonus, see testCopyMethod
Advanced cloning usages requires more than only copying all metamodel fields. For instance, it also requires to update references and to set a parent (for future resolving with `getDeclaration`).
This is what is done here.
=> feature: add methods Refactoring#copyType and Refactoring#copyMethod

src/main/java/spoon/reflect/factory/TypeFactory.java, src/test/java/spoon/test/factory/TypeFactoryTest.java, src/test/resources/dollar-and-nested-classes/$Poor$Name.java
As mentioned in the name of the PR, this would refactor `TypeFactory.get(String qualifiedName)`. Instead of looking in existing packages for the wanted type only if it is not resolve otherwise, it starts by that.
It prevent to resolve recursively nested type from their root type as a first option. If you look for `A$B$C` it won't resolve `A` then `A$B` and then `A$B$C`. if `A$B` is already reachable, it will stop there.
This allow the resolution of class whose name contains `$`. The current behavior can't resolve a class named `A$B` if it's not a class `B` nested in `A`.
=> refactor(TypeFactory#get(String qualifiedName)): Look for type in factory.Package() first, and not at the end. Workaround for #1889

src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/reflect/visitor/EarlyTerminatingScanner.java, src/main/java/spoon/reflect/visitor/filter/CtScannerFunction.java, src/test/java/spoon/reflect/visitor/CtScannerTest.java
The main purpose of this PR is, to be able to handle scanning of whole collection or whole map. It is needed for #1686 for the matching algorithms which matches a sequence of elements. For example in list of 5 commands match first `if` followed by `for`
=> review: feat: CtScanner#scan of Collection and Map

pom.xml
As you may have noticed, all sources are always recompiled. This is due to a bug in Maven.
See https://issues.apache.org/jira/browse/MCOMPILER-205 and https://issues.apache.org/jira/browse/MCOMPILER-209
=> chore: enables incremental compilation

src/main/java/spoon/reflect/code/CtCatchVariable.java, src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java, src/main/java/spoon/support/reflect/code/CtLambdaImpl.java, src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java, src/test/java/spoon/test/replace/ReplaceParametrizedTest.java
Here is the test, which reports inconsistencies in Spoon model role get/set.
Generally there are these issues:
P1) Unsettable property CtXxxReference#comment<java.util.List<spoon.reflect.code.CtComment>> sets the value
P2) UnsettableProperty CtEnumValue|CtLocalVariable|CtField#assignment<spoon.reflect.code.CtExpression<T>> sets the value into different role defaultExpression
P3) UnsettableProperty CtLambda#thrown<java.util.Set<spoon.reflect.reference.CtTypeReference<? extends java.lang.Throwable>>> sets the value
P4) Settable field CtCatchVariable#type<spoon.reflect.reference.CtTypeReference<T>> is accessible by multiType too
I am not sure whether we should solve these problems. May be they are features for somebody?
Solutions might be 
>P1
to implement empty CtReference#setComment().
> …
=> review: fix: Unsettable properties sets no value or sets different primary value

src/main/java/spoon/reflect/visitor/filter/SiblingsFunction.java
fix bad exception in DJPP after heavy transformation, no way to reproduce in a test case.
=> fix: fix a bad exception in DJPP

src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java, src/main/java/spoon/reflect/visitor/CtScanner.java, src/main/java/spoon/support/visitor/clone/CloneVisitor.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/test/metamodel/MetamodelProperty.java, src/test/java/spoon/test/reflect/meta/MetaModelTest.java
Examples are CtTypeReference#MODIFIER and COMMENT. Before they were derived==false unsettable==true. Now they are derived==true unsettable==true
WDYT?
=> fix: all unsettable properties are derived too

README.md, doc/doc_homepage.md, doc/jenkins/build.sh, pom.xml
Fix #1900 
⚠️ This PR might breaks for some time the snapshot deployment: I should have fixed it in the CI but I did not tested it, as I need this changes in the pom.xml file. Nervertheless I already deployed manually a first snapshot in order to avoid complete service discontinuity.
=> review chore:Use Maven INRIA instead of Gforge to deploy snapshots

pom.xml
Last revapi report are comparing Spoon against last release version instead of last snapshot version. It's because we removed the repositories section from pom.xml. So I pushed it back.
=> chore: fix revapi comparison against Snapshot

src/main/java/spoon/support/reflect/declaration/CtClassImpl.java, src/main/java/spoon/support/reflect/declaration/CtEnumImpl.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
As discussed in #1917 and detected by #1922, this PR fixes all main derived properties of Spoon model by way they return unmodifiable collections.
Before they were modifiable, but detached. So the modifications had no influence to the model. Now they are unmodifiable, so client is warn early that modifications makes no sense here.
=> fix: derived properties return unmodifiable collections

src/main/java/spoon/reflect/code/CtCatchVariable.java, src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java, src/test/java/spoon/test/trycatch/TryCatchTest.java, src/test/resources/spoon/test/noclasspath/exceptions/Foo.java
Hi! I found out that `IndexOutOfBoundsException` is occurred in cases when `getType()` is called on parameter of a catch with multiple exception types, some of which is unknown (noclasspath mode):
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
at spoon.support.reflect.code.CtCatchVariableImpl.getType(CtCatchVariableImpl.java:109)
....
```
I think it would be better to return null from getType() in such cases instead, so I provided this PR.
=> fix IndexOutOfBoundsException in getType()

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/comment/testclasses/InlineComment.java
This PR fixes this situation.
```java
class A
// this comment belongs to class
extends B /* this comment belongs to class too*/ { /* but this comment is comment of first member*/
int firstMember;
}
```
Before all the comments from the example above were associated to the `firstMember`
=> review: fix: comments after class name and before type members

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/sourcePosition/SourcePositionTest.java, src/test/java/spoon/test/sourcePosition/testclasses/Brambora.java
The type references to primitive types like `void` sometime copied the source position from another type reference. See test for details.
=> help: fix: always create new type reference for primitive type

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/test/java/spoon/test/position/PositionTest.java, src/test/java/spoon/test/position/testclasses/FooClazzWithComments.java, src/test/java/spoon/test/position/testclasses/PositionParameterTypeWithReference.java
I am experimenting with another approach to implement Sniper mode and have found a bug:
Class with sources like this
```java
public class /*comment*/ Test {}
```
has wrong DeclarationSourcePosition#modifier end.
The problem is in code 
/spoon-core/src/main/java/spoon/support/compiler/jdt/PositionBuilder.java (line 137)
because it doesn't count with comments. So we need some comment aware parser/tokenizer here.
I guess, I can fix it. But if anybody else would like to implement that comment parser, I would gladly do something else ;-)
=> review: fix class with comments has invalid DeclarationSourcePosition#modifier

src/main/java/spoon/compiler/Environment.java, src/main/java/spoon/support/StandardEnvironment.java
This PR aims at avoiding issues like #1933
=> review Add a new warning in verifySourceClasspath

src/main/java/spoon/reflect/declaration/CtAnnotation.java, src/main/java/spoon/reflect/declaration/CtElement.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/annotation/AnnotationValuesTest.java, src/test/java/spoon/test/annotation/testclasses/shadow/ClassRetention.java, src/test/java/spoon/test/annotation/testclasses/shadow/DumbKlass.java, src/test/java/spoon/test/annotation/testclasses/shadow/RuntimeRetention.java, src/test/java/spoon/test/annotation/testclasses/shadow/StandardRetention.java
This PR intends to fix the contract defined after discussion in #1928
=> review fix: contract CtAnnotation and array of values

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java, src/test/java/spoon/test/prettyprinter/PrinterTest.java
This code is a side effect of my experiments with printing of changes #1927. I though that I will need to know, which list is actually printed by DJPP, so I implemented that `ElementPrinterHelper#printList`.
Now I see it is not needed, but the code of this PR doesn't look bad from my point of view.
So if you like it, take it. Otherwise close this PR - I do not need that.
This PR also moves printing of method modifier "default" into `ElementPrinterHelper#writeModifiers`
=> refactor: printing of lists in DefaultJavaPrettyPrinter

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/main/java/spoon/support/reflect/cu/position/BodyHolderSourcePositionImpl.java, src/main/java/spoon/support/reflect/cu/position/DeclarationSourcePositionImpl.java, src/main/java/spoon/support/reflect/cu/position/SourcePositionImpl.java, src/test/java/spoon/test/sourcePosition/SourcePositionTest.java
this new `checkArgsAreAscending` found many problems in PositionBuilder...
I guess it should be always activated... or do you think it should be possible to switch it off ... temporarily, so clients can use spoon until we fix all the `PositionBuilder x JDK compiler` problems?
WDYT?
Yes and there are some new helper methods in SourcePositions ... I was lazy to make new PR for them. I hope it is BS enough :-)
=> review: feature: SourcePosition checks validity and displays origin source code

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/test/java/spoon/test/position/PositionTest.java, src/test/java/spoon/test/position/testclasses/PositionTry.java
=> fix(position): fix the position of catch variable

src/main/java/spoon/support/visitor/equals/EqualsChecker.java
If I need to know what attribute is not equal, then this PR is very helpful, because one can put breakpoint into new method setNotEqual()
=> refactor: EqualsChecker#setNotEqual can be used to debug non-equality

src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java
Fix https://github.com/INRIA/spoon/issues/1991
=> Silently return in case of CNFE.

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/arrays/ArraysTest.java, src/test/java/spoon/test/arrays/testclasses/VaragParam.java
I guess I have found a bug in actual type arguments of array type reference.
The problem is that array type reference like `List<?>[]` has set wildcard `<?>` actual type arguments on 2 places
1) on List type: `List<?>` - here it is OK
2) in List array type: `List[]` - here it is wrong. Or WDYT is it bug or feature?
I added two failing test, which both actually fails on last test line.
=> review fix: actualTypeArguments of array type reference

src/main/java/spoon/support/visitor/equals/EqualsChecker.java, src/main/java/spoon/support/visitor/equals/EqualsVisitor.java, src/main/java/spoon/support/visitor/equals/NotEqualException.java, src/test/java/spoon/test/comparison/EqualTest.java
please check if performance of Spoon changes with that change. Equals visitor is called very often, so it must be really fast ... and I am not sure about performance impact of this PR
=> review: feat: EqualsVisitor can report which attribute is not equal

src/main/java/spoon/support/comparator/QualifiedNameComparator.java, src/main/java/spoon/support/reflect/code/CtBlockImpl.java, src/main/java/spoon/support/reflect/code/CtJavaDocImpl.java, src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java, src/main/java/spoon/support/util/ModelList.java, src/main/java/spoon/support/util/ModelSet.java, src/main/java/spoon/support/visitor/equals/CloneHelper.java, src/test/java/spoon/generating/CloneVisitorGenerator.java, src/test/java/spoon/reflect/ast/AstCheckerTest.java, src/test/java/spoon/test/intercession/RemoveTest.java
A prototype of solution for #1916 and #1633
... at the beginning only for CtBlock#statements
... later the same solution should be applied to each List, Set and Map of Spoon model
WDYT?
=> review: refactor: mutable collections of Spoon model handles parent and fire change events

src/main/java/spoon/support/compiler/SnippetCompilationHelper.java, src/main/java/spoon/support/reflect/code/CtCaseImpl.java, src/main/java/spoon/support/reflect/code/CtStatementImpl.java, src/main/java/spoon/support/reflect/code/CtStatementListImpl.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/main/java/spoon/support/util/ModelList.java, src/test/java/spoon/generating/CtBiScannerGenerator.java, src/test/java/spoon/generating/ReplacementVisitorGenerator.java, src/test/java/spoon/test/signature/SignatureTest.java, src/test/java/spoon/test/staticFieldAccess/InsertBlockProcessor.java, src/test/java/spoon/testing/CtPackageAssertTest.java
There is basic spoon concept: each element of AST has 0 or 1 parent and is in children collection of exactly one parent.
When some element which is already part of AST is added into another part of AST, then this rule concept is not true and Spoon can behave unpredictable.
This PR assures that element add will fail in such situation.
=> review: feature: fail when element is added twice

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
fix npe in #2014
No idea how to reproduce it in a failing test-case.
=> fix(reference): fix npe in getTypeReference when the reference is null

src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java
fix #2014#issuecomment-393946572
=> fix(reference): fix npe in getExecutableDeclaration when declaring type is null

src/main/java/spoon/support/visitor/ClassTypingContext.java
@pvojtechovsky can you check the semantic of what I did.
I'm not sure if it is correct
=> fix: npe in getEnclosingType when getTypeDeclaration is null

src/main/java/spoon/reflect/factory/MethodFactory.java, src/main/java/spoon/support/reflect/code/CtLambdaImpl.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/lambda/testclasses/Foo.java
From [FunctionalInterface](https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html)'s JavaDoc:
> If an interface declares an abstract method overriding one of the public methods of java.lang.Object, that also does not count toward the interface's abstract method count since any implementation of the interface will have an implementation from java.lang.Object or elsewhere.
[CtLambdaImpl](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/reflect/code/CtLambdaImpl.java#L126-L134) doesn't take this into account resulting in Exceptions whenever an Interface declaring one or more of `java.lang.Object`'s methods is used in combination with a Lambda Expression.
- Fixes https://github.com/INRIA/spoon/issues/2003
=> Fix Interface method handling

src/main/java/spoon/reflect/factory/AnnotationFactory.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java, src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/annotation/testclasses/Main.java
=> REVIEW fix: CtAnnotation#getValue returns the default value if one exists

src/main/java/spoon/template/BlockTemplate.java, src/main/java/spoon/template/ExpressionTemplate.java, src/main/java/spoon/template/StatementTemplate.java, src/test/java/spoon/test/template/TemplateInvocationSubstitutionTest.java, src/test/java/spoon/test/template/TemplateTest.java
regression captured in the tests of https://github.com/SpoonLabs/spoon-examples
see https://ci.inria.fr/sos/job/spoon-examples/499/console
=> review: fix regression due to #2009

src/main/java/spoon/reflect/declaration/CtAnnotation.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/test/java/spoon/test/annotation/AnnotationTest.java
Two advantages:
* this eases the API: direct `annot.getValueAsObject("foo") ` instead of  `((CAST)annot.getActualAnnotation()).foo()`
* this enables getting the annotation value even if the annotation binary class file is not in the classpath
=> feature: one can get annotation values directly

pom.xml, src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java, src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
It is a little bit dirty, do you have better idea how to do it?
Fix #2038
=> fix(shadow): fix the creation of a partial shadow class

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/test/java/spoon/test/position/PositionTest.java, src/test/java/spoon/test/position/testclasses/ArrayArgParameter.java
Position of parameter `arg` is incorrect in this code
```java
void method(String arg[])
```
=> review: fix: position of (String arg[])

src/test/java/spoon/generating/MetamodelGenerator.java, src/test/java/spoon/test/api/Metamodel.java, src/test/java/spoon/test/api/MetamodelTest.java
The values of derived and unsettable attributes of MetamodelProperties of MetamodelConcepts of spoon.metamodel.Metamodel are compared to the hardcoded expected values
It is a way how to fix #2047
=> test: derived and unsettable of spoon.metamodel.Metamodel

src/main/java/spoon/pattern/PatternParameterConfigurator.java
> There is a regression on the template side, in https://github.com/SpoonLabs/spoon-examples, see https://ci.inria.fr/sos/job/spoon-examples/507/console
It fixes problem reported in #1686
=> fix: Legacy template TypeReference matches Type optionally

src/main/java/spoon/metamodel/MetamodelProperty.java
=> fix: init RoleHandler lazily to pass when RoleHandler is generated

src/main/java/spoon/compiler/Environment.java, src/main/java/spoon/support/JavaOutputProcessor.java, src/main/java/spoon/support/QueueProcessingManager.java, src/main/java/spoon/support/StandardEnvironment.java, src/main/java/spoon/support/compiler/ProgressLogger.java, src/main/java/spoon/support/compiler/SpoonProgress.java, src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java, src/main/java/spoon/support/compiler/jdt/TreeBuilderCompiler.java
fix #1778 
I notice with this feature that printing the model is the slowest task.
JTD takes: 4794 ms
Spoon model: 4098 ms
Printing: 5507 ms
It surprised me
=> review feat: add the ability to follow the process of the creation of the Spoon model

src/main/java/spoon/reflect/factory/ModuleFactory.java, src/main/java/spoon/reflect/factory/PackageFactory.java, src/main/java/spoon/support/compiler/jdt/FileCompilerConfig.java, src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/compiler/jdt/TreeBuilderCompiler.java, src/test/java/spoon/test/module/TestModule.java
Fix #1769 
This PR changes the internal mechanism of `JDTBatchCompiler` to process CU in order to attach the information of modules.
The process might be encapsulated in a condition to check if we are using Java 9 or more, but I want first to check that everything works with it. 
And kudos @abourdon for the valuable co-debugging with me on this one! 👏
=> review fix(module): Spoon is now able to build module in full classpath

src/main/java/spoon/pattern/PatternBuilder.java, src/main/java/spoon/pattern/PatternParameterConfigurator.java, src/test/java/spoon/generating/RoleHandlersGenerator.java
It is temporary/dirty solution for #2076 until the discussion in #2077 brings some concept.
`PatternParameterConfiguration#byType(String)` now marks as Pattern parameters all CtTypeReferences with same qualified name (ignoring actual type arguments) - before it marked only CtTypeReferences without actual type arguments.
The change in RoleHandlersGenerator was needed too.
=> fix(pattern): improve Pattern parameters of CtTypeReference

src/main/java/spoon/pattern/internal/ValueConvertor.java, src/main/java/spoon/pattern/internal/ValueConvertorImpl.java, src/main/java/spoon/pattern/internal/parameter/AbstractParameterInfo.java
If Pattern parameter is mandatory and it is missing, then it throws SpoonException with better explanation
=> feat(Pattern): report missing Pattern parameter value

src/main/java/spoon/Launcher.java, src/main/java/spoon/support/StandardEnvironment.java, src/main/java/spoon/testing/utils/ModelUtils.java, src/test/java/spoon/reflect/visitor/CtScannerTest.java, src/test/java/spoon/test/annotation/AnnotationValuesTest.java, src/test/java/spoon/test/api/NoClasspathTest.java, src/test/java/spoon/test/javadoc/JavaDocTest.java, src/test/java/spoon/test/main/MainTest.java, src/test/java/spoon/test/prettyprinter/PrinterTest.java
This PR is a proposal to change a default behaviour in Spoon: until now, the default was to **not** take into account the comments.
I assume this behaviour was used because the comments were not properly parsed then. But I think it's not the case anymore and we got more users using Spoon for parsing comments: very recently we got a question on Stackoverflow linked to that: https://stackoverflow.com/questions/50780598/how-to-get-comments-using-spoon/ and I know we also got issues related to that.
So in the same way we decided to use `noclasspath` mode by default, I propose that we parse comments by default. WDYT?
=> review feat: Enable comments by default

src/main/java/spoon/reflect/factory/CodeFactory.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/comment/testclasses/WithIfBlock.java
This PR is a proposal for the following problem: when trying to comment all statements of a method, I created an inline comment for a CtIf, and it produces an uncompilable source code, before it only added a `//` before the content.
I propose that we detect automatically the presence of new lines in the content of a comment when trying to create it and to apply an action. 
Here my proposed action is to change the comment type to create a block comment.
Another possibility is to throw an exception in that kind of case. WDYT?
=> review fix(comment): Creating an inline comment with line separators throws an exception

src/main/java/spoon/metamodel/Metamodel.java, src/main/java/spoon/metamodel/MetamodelProperty.java, src/test/java/spoon/processing/CtGenerationTest.java
Fix of problem reported in #2085 
When the Spoon model is changed, then we have to generate RoleHandlers which fits to such modified Spoon model. But role handlers generator internally uses Pattern which uses Metamodel which uses RoleHandlers - expects that they fit to the model - ... so it fails if RoleHandlers are not fitting... and it is then not possible to generate new RoleHandlers.
Solution -> this PR: In case of generating of RoleHandlers the Metamodel is switched to special mode where RoleHandlers are not used, but it uses slow Java reflection instead to access Spoon model attributes.
=> fix(test): CtGenerationTest#testGenerateRoleHandler egg/chicken problem

src/main/java/spoon/reflect/cu/CompilationUnit.java, src/main/java/spoon/reflect/visitor/ImportScanner.java, src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java
This PR intends to prepare the field for incoming PR such as #2100 
It's breaking to be included in release 7 and then to avoid breaking anything in future releases.
=> review refactor: prepare import API for future development

src/test/java/spoon/processing/CtGenerationTest.java, src/test/java/spoon/test/api/MetamodelTest.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/template/PatternTest.java
This PR is a first one in order to fix test on windows: when we set `line.separator` we need to reset it to its old value afterwards.
This alone won't fix all tests on windows: we also need to remove all `\n` usage and to use systematically `System.getProperty("line.separator");`. This will be done in another PR.
=> review test: fix line separators in test

src/main/java/spoon/reflect/cu/position/BodyHolderSourcePosition.java, src/main/java/spoon/reflect/cu/position/CompoundSourcePosition.java, src/main/java/spoon/reflect/cu/position/DeclarationSourcePosition.java, src/main/java/spoon/reflect/factory/CoreFactory.java, src/main/java/spoon/support/DefaultCoreFactory.java, src/main/java/spoon/support/reflect/cu/position/CompoundSourcePositionImpl.java
first baby step to fix #2055 
* CompoundSourcePosition extends SourcePosition
* DeclarationSourcePosition extends CompoundSourcePosition
* part of fields and code of DeclarationSourcePositionImpl was moved to CompoundSourcePositionImpl
=> feat(position): CompoundSourcePosition extends SourcePosition

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
This PR only intends to prepare the field for #2100 
I really want to remove the import state from the DJPP and to put it in CompilationUnit, it certainly won't be properly done for release 7, so I want at least to inform that the imports method of DJPP will be removed soon.
=> review refactor: Deprecate import method from DJPP

src/main/java/spoon/support/compiler/jdt/ContextBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/position/PositionTest.java, src/test/java/spoon/test/position/testclasses/Expressions.java
=> review2: fix: expression type cast source positions

src/main/java/spoon/Launcher.java, src/test/java/spoon/test/api/APITest.java, src/test/java/spoon/test/refactoring/RefactoringTest.java
This PR shows that the current behaviour is to never reset the model, even if the same launcher is called twice with different arguments.
My current test shows that `model` and `model2` are the same and they contain 2 types at the end of the test.
I don't know if it's an expected behaviour or not, but it looks very dangerous to me. WDYT?
=> review fix: launcher#setArgs cannot be called twice

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/test/java/spoon/test/position/PositionTest.java, src/test/java/spoon/test/position/testclasses/PositionParameterTypeWithReference.java
fix of another problem found by Sniper mode tests
=> fix: position of nested type arguments like List<List<?>>

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/test/java/spoon/test/position/PositionTest.java, src/test/java/spoon/test/position/testclasses/ArrayArgParameter.java, src/test/java/spoon/test/position/testclasses/FooLambda.java
The computation of position of `String arg[]` was not correct for lambda parameters. So fixing of this algorithm fixed position of lambda parameters too.
There are also other not-testable fixes which sets correctly maxOffset of findPrevNonWhitespace.
=> review: fix: position of `String arg[]` and lambda parameter

src/test/java/spoon/test/casts/CastTest.java, src/test/java/spoon/test/casts/testclasses/Castings.java
=> refactor: move Castings.java to testclasses

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/test/java/spoon/test/position/PositionTest.java
The modifiers were on two places before
1) CtCatch - wrong
2) CtCactchVariable - OK
So this PR removes them from CtCatch
Note: CtCatch would need a bettet source position structure. I actually I used BodyHolderSourcePosition, but it is may be not fitting well here. WDYT? Can we live with that or we make new structure for that?
=> fix(position): CtCatch has no modifiers, they are in CatchVariable

src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java, src/test/java/spoon/test/fieldaccesses/testclasses/BCUBug20140402.java, src/test/java/spoon/test/fieldaccesses/testclasses/BUG20160112.java, src/test/java/spoon/test/fieldaccesses/testclasses/Mouse.java, src/test/java/spoon/test/fieldaccesses/testclasses/MyClass.java, src/test/java/spoon/test/fieldaccesses/testclasses/TargetedAccessPosition.java, src/test/java/spoon/test/fieldaccesses/testclasses/internal/MyClass.java
=> refactor: move resources to testclasses in fieldaccesses

src/test/java/spoon/test/prettyprinter/LinesTest.java, src/test/java/spoon/test/prettyprinter/PrinterTest.java, src/test/java/spoon/test/prettyprinter/testclasses/Validation.java
=> refactor: move Validation.java to testclasses in prettyprinter

src/main/java/spoon/reflect/cu/CompilationUnit.java, src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java, src/main/java/spoon/support/reflect/cu/position/SourcePositionImpl.java
Why?
* line separator positions (array of offsets of EOLs) are conceptually related to CompilationUnit
* SourcePositionImpl needs less storage now, because it takes line separator positions from it's compilation unit
=> review: refactor: store line separator positions in CompilationUnit

src/main/java/spoon/reflect/visitor/PrinterHelper.java, src/main/java/spoon/reflect/visitor/TokenWriter.java
The changes in PrinterHelper are needed for sniper mode, which needs low level access to the print buffer and some printer helper state.
The TokenWriter#writeSpace is needed for sniper mode too. The direct call of PrinterHelper (as written in old comment) would kill the concept of Sniper mode.
=> review: refactor: PrinterHelper can be extended to support direct writing

src/main/java/spoon/support/compiler/jdt/ParentExiter.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/main/java/spoon/support/visitor/equals/EqualsVisitor.java
Verbose or redundant code constructs
- Unnecessary return statement
Rationale
Simpler, more readable code. Less clutter.
=> refactor: remove unnecessary 'return' statement

src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
- Java language level migration aids | Java 5 | 'while' loop replaceable with 'foreach'
Rationale: foreach is shorter, more readable and easier understand. While with iterator should be avoided if possible.
=> refactor: Code inspection: Use modern foreach loop

src/main/java/spoon/Launcher.java, src/main/java/spoon/refactoring/Refactoring.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
Performance
- String concatenation in loop
This is also SonarQube checker (Use a StringBuilder instead.).
Rationale
String concatenation in loop is orders of magnitude slower than StringBuilder.
=> refactor: Code inspection: String concatenation in loop

src/main/java/spoon/reflect/declaration/CtElement.java
By making CtElement serializable, a total of 83 sonarqube bugs will be removed from spoon because every part of the Spoon model inherits from the CtElement. As recommended by @surli in https://github.com/INRIA/spoon/pull/2117 .
=> Repair of sonarqube bug, made CtElement Serializable

src/main/java/spoon/metamodel/Metamodel.java, src/main/java/spoon/reflect/cu/SourcePositionHolder.java, src/main/java/spoon/reflect/declaration/CtElement.java, src/main/java/spoon/support/reflect/CtExtendedModifier.java
CtElement and CtExtendedModifier now both implements SourcePositionHolder.
It is needed for Sniper mode which needs a generic access to Position of CtExtendedModifier.
=> review: feat(position): new interface SourcePositionHolder

src/main/java/spoon/pattern/InlinedStatementConfigurator.java, src/main/java/spoon/pattern/PatternBuilder.java, src/main/java/spoon/pattern/PatternParameterConfigurator.java, src/main/java/spoon/pattern/internal/matcher/TobeMatched.java, src/main/java/spoon/pattern/internal/node/ElementNode.java, src/main/java/spoon/reflect/factory/SubFactory.java, src/main/java/spoon/reflect/factory/TypeFactory.java, src/main/java/spoon/reflect/meta/impl/SingleHandler.java
SonarQube rationale
> Programmers should not comment out code as it bloats programs and reduces readability.
Unused code should be deleted and can be retrieved from source control history if required.
See
MISRA C:2004, 2.4 - Sections of code should not be "commented out".
MISRA C++:2008, 2-7-2 - Sections of code shall not be "commented out" using C-style comments.
MISRA C++:2008, 2-7-3 - Sections of code should not be "commented out" using C++ comments.
MISRA C:2012, Dir. 4.4 - Sections of code should not be "commented out"
Commented code is always availabe in repository.
There is no need to keep it (*waiting for better times*).
=> fix: sonarqube remove commented code

src/main/java/spoon/reflect/cu/CompilationUnit.java, src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java, src/test/java/spoon/test/compilationunit/TestCompilationUnit.java
`CompilationUnit` extends `SourcePositionHolder` now, so it can act as root of source fragments - as needed for sniper mode pretty printer as discussed in #2254.
=> review: feat: CompilationUnit extends SourcePositionHolder

src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
This PR improves error message of `SpoonArchitectureEnforcerTest#testStaticClasses`, which now reports which class has to be fixed
=> test: improve error message of SpoonArchitectureEnforcerTest#testStaticClasses

src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/generating/replace/ReplacementVisitor.java
I had hard time to found a reason for a strange problem ... until I found that ReplacementVisitor eats exceptions. 
May be before there was not much code running in scope of this exception block, but now with integrated Change collector and sniper mode, there makes sense to report exceptions, which happens here.
@monperrus, do you have any idea why it was caught and ignored?
=> fix: ReplacementVisitor doesn't eat exceptions

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java, src/main/java/spoon/reflect/visitor/PrintingContext.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/template/TemplateTest.java
The sniper printing mode algorithm expects that all source code of an element is printed in scope of it's `DJPP#scan` method.
But it was not the case of CtStatement, which printed suffix semicolon and after comment later... after living the scan method.
I hope this kind of DJPP refactoring is acceptable.
Advantage: the CtStatement#toString should now print after comment too - as expected.
=> review: refactor: print statement's semicolon and after comment in scope of scan

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/comment/testclasses/CommentsOnStatements.java
This PR contains a text which reproduces this problem:
```java
//c1
if (value == null) {
//c2 belongs to toto
value = "toto";
} else if (value.equals("x")) {
//c3 belongs to getClass
this.getClass();
}
```
The comment `//c3` is incorectly placed to root if statements
=> review: fix: comment on nested else if statement

src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java, src/main/java/spoon/testing/utils/ModelUtils.java, src/test/java/spoon/test/position/PositionTest.java
CtImport has source position now. It is needed for Sniper mode printer.
... and I improved test `ModelUtils` here too, to allow configuration of Launcher before model is built. I guess it doesn't need separate PR. Or?
=> fix(position): CtImport has source position now

src/main/java/spoon/pattern/PatternParameterConfigurator.java, src/main/java/spoon/reflect/path/impl/CtRolePathElement.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java, src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/main/java/spoon/support/compiler/jdt/TreeBuilderCompiler.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/main/java/spoon/support/visitor/TypeReferenceScanner.java, src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java, src/main/java/spoon/template/Substitution.java, src/test/java/spoon/test/query_function/VariableReferencesTest.java
- PR fixes some SonarQube violations: *This block of commented-out lines of code should be removed.*
- Remove not thrown exceptions in test - VariableReferencesTest.java
- Fix formatting
**Substitution.java**
I paid attention not to remove:
```
//if (!f.getSimpleName().equals("_" + f.getAnnotation(Parameter.class).value())) {
//	throw new TemplateException("the field name of a proxy template parameter must be called _" + f.getSimpleName());
//}
```
**CtRolePathElement.java** (line 112)
```//No element found for name.```
Is this commented needed?
=> refactor: remove commented code (SonarQube defect fix)

src/main/java/spoon/reflect/visitor/PrintingContext.java, src/main/java/spoon/support/compiler/jdt/ContextBuilder.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
instanceof checks for null.
In other places in code (in 259 Java files), there is no null check before instanceof, so these 3 redundant null checks are to be removed.
=> refactor: fix code inspection: unnecessary null check

src/test/java/spoon/test/comment/CommentTest.java
=> fix: CommentTest#testStatementComments uses OS specific EOL

src/main/java/spoon/reflect/factory/CompilationUnitFactory.java, src/main/java/spoon/reflect/visitor/PrintingContext.java, src/main/java/spoon/support/compiler/jdt/CompilationUnitWrapper.java, src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java, src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/main/java/spoon/support/visitor/AbstractTypingContext.java, src/main/java/spoon/template/BlockTemplate.java, src/main/java/spoon/template/ExpressionTemplate.java
Data flow
- Redundant local variable
Rationale: make code clean and easy to read.
=> refactor: fix code inspection redundant local variable

src/main/java/spoon/Launcher.java, src/main/java/spoon/metamodel/MetamodelProperty.java, src/main/java/spoon/pattern/internal/node/ForEachNode.java, src/main/java/spoon/reflect/factory/TypeFactory.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ModelConsistencyChecker.java, src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/main/java/spoon/support/compiler/jdt/TreeBuilderCompiler.java, src/main/java/spoon/support/gui/SpoonModelTree.java, src/main/java/spoon/support/reflect/cu/position/SourcePositionImpl.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java, src/main/java/spoon/support/template/Parameters.java, src/main/java/spoon/support/util/ByteSerialization.java
Probable bugs
- Unused assignment
Unused assignment are confusing because we lost value later (it is overwritten line down or in ctr).
Example
int a = 1;
...
a = 0;
If the value is lost/overwritten, it is not needed.
The logic in src/main/java/spoon/support/template/Parameters.java is problematic. Should it be fixed?
=> refactor: fix code inspection - remove unused assignment

doc/path.md, src/test/java/spoon/test/filters/FilterTest.java, src/test/java/spoon/test/filters/testclasses/FooLine.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses3/ClassThatBindsAGenericType.java, src/test/java/spoon/test/path/PathTest.java, src/test/java/spoon/test/path/testclasses/Foo.java, src/test/java/spoon/test/strings/StringTest.java, src/test/java/spoon/test/strings/testclasses/Main.java
I moved 4 resources to test classes.
@surli 
@monperrus 
Please verify changed assertions (7 -> 8) and changed doc.
Of course I did not want to change assertions, but because of moved class, it was required.
- FooLine (test/filters) -> I was forced to modify assertions in FilterTest.java (7 -> 8) https://github.com/INRIA/spoon/commit/9aeddfda093ebf7b8e40d4050a97fb61e2bb52fc
- ClassThatBindsAGenericType (test/generics)
- Foo (test/path) -> please check if doc is ok - https://github.com/INRIA/spoon/pull/2277/commits/a6f1785c847080d88e554e4cd840cb7afb971e1f
- Main (test/strings)
=> refactor: move resources to testclasses

src/test/java/spoon/test/api/NoClasspathTest.java, src/test/java/spoon/test/model/SwitchCaseTest.java, src/test/java/spoon/test/parent/ParentTest.java, src/test/java/spoon/test/pkg/PackageTest.java, src/test/java/spoon/test/position/PositionTest.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/java/spoon/test/reference/VariableAccessTest.java, src/test/java/spoon/test/reflect/visitor/ReferenceQueryTest.java, src/test/java/spoon/test/signature/SignatureTest.java, src/test/java/spoon/test/sourcePosition/SourcePositionTest.java, src/test/java/spoon/test/targeted/TargetedExpressionTest.java, src/test/java/spoon/test/trycatch/TryCatchTest.java, src/test/java/spoon/test/type/TypeTest.java
I tried to avoid any testclasses.
=> refactor: use modern syntax for types - use diamonds

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
=> Sonarqube-repair : remove useless assignments in ReferenceBuilder.java

src/test/java/spoon/test/exceptions/ExceptionTest.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/replace/ReplaceParametrizedTest.java
It looks like that is is fixed/obsolete
```
// for now the type of CtCatchVariable is not the same
// this should be fix in the future (see: https://github.com/INRIA/spoon/issues/1420)
//assertEquals(variable2, variable1);
```
But if it is needed, I will restore it.
@surli 
?
=> refactor: remove commented code from tests

src/test/java/spoon/test/processing/ProcessingTest.java, src/test/java/spoon/test/processing/processors/CtClassProcessor.java, src/test/java/spoon/test/processing/processors/CtInterfaceProcessor.java, src/test/java/spoon/test/processing/processors/CtTypeProcessor.java, src/test/java/spoon/test/processing/processors/GenericCtTypeProcessor.java
I have noticed that some processors are wrongly placed in testclasses.
Moved to *processors* directory.
=> refactor: move processor classes to processors directory

src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/main/MainTest.java, src/test/java/spoon/test/path/PathTest.java, src/test/java/spoon/test/properties/PropertiesTest.java, src/test/java/spoon/test/reference/ExecutableReferenceGenericTest.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/java/spoon/test/reference/VariableAccessTest.java
Order in JUnit assertions in counter-intutive. So mistakes happen from time to time. Fixed!
=> refactor: fix order in assertions

src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java, src/test/java/spoon/generating/replace/ReplacementVisitor.java, src/test/java/spoon/reflect/ast/AstCheckerTest.java, src/test/java/spoon/reflect/visitor/CtInheritanceScannerTest.java, src/test/java/spoon/test/api/MetamodelTest.java, src/test/java/spoon/test/condition/ConditionalTest.java, src/test/java/spoon/test/imports/ImportScannerTest.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/java/spoon/test/type/TypeTest.java
=> refactor: use modern foreach loop

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java
Let the equals() do the job (without NPE risk).
=> refactor: remove redundant null check

src/test/java/spoon/reflect/ast/AstCheckerTest.java
Of course instanceof checks for null.
Similar to: refactor: remove redundant null check #2317
Let the Java do the job.
=> refactor: remove redundant null check in AstCheckerTest.java

src/main/java/spoon/IncrementalLauncher.java, src/main/java/spoon/compiler/builder/JDTBuilderImpl.java, src/main/java/spoon/compiler/builder/Options.java, src/main/java/spoon/pattern/internal/PatternPrinter.java, src/main/java/spoon/pattern/internal/node/StringNode.java, src/main/java/spoon/support/compiler/jdt/FactoryCompilerConfig.java, src/main/java/spoon/support/compiler/jdt/TreeBuilderCompiler.java, src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java, src/main/java/spoon/support/util/RtHelper.java, src/main/java/spoon/support/visitor/java/reflect/RtMethod.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java
Use modern way to convert collection to array.
old: (mSourceClasspath.toArray(new String[mSourceClasspath.size()]));
new: (mSourceClasspath.toArray(new String[0]));
benefits:
- more readable
- faster to understand
- a bit faster
=> refactor: fix code inspection - collection to array

src/main/java/spoon/reflect/meta/impl/RoleHandlerHelper.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/main/java/spoon/support/template/Parameters.java, src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java
- Unqualified static access: 408 cases
- Unnecessarily qualified static access: 5 cases
There is no need to prefix static fields&methods inside its own class.
All Spoon classes use direct static acces *static_method_invocation()*,
not prefixed: *X.static_method_invocation()*.
I normalized 5 cases with not needed prefixes.
Inside BlockTemplate class:
BlockTemplate.getBlock(c) -> getBlock(c)
=> refactor: fix code inspection - qualified static access

src/main/java/spoon/MavenLauncher.java, src/main/java/spoon/metamodel/MMMethodKind.java, src/main/java/spoon/pattern/PatternParameterConfigurator.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/support/StandardEnvironment.java, src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/main/java/spoon/support/template/Parameters.java
Code style issues
- 'expression.equals("literal")' rather than '"literal".equals(expression)'
Motivation: use popular coding style to reduce risk of null pointer exceptions (NPEs).
=> refactor: flip literals to reduce risk of NPE

src/test/java/spoon/test/filters/FilterTest.java
Use assertSame to improve tests readability (express clearly intention of checking).
=> refactor: use assertSame in FilterTest.java

src/test/java/spoon/test/annotation/AnnotationTest.java
Use assertSame to improve tests readability (express clearly intention of checking).
=> refactor: use assertSame in AnnotationTest.java

src/test/java/spoon/test/annotation/AnnotationLoopTest.java, src/test/java/spoon/test/api/MetamodelTest.java, src/test/java/spoon/test/compilation/CompilationTest.java, src/test/java/spoon/test/constructorcallnewclass/ConstructorCallTest.java, src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java, src/test/java/spoon/test/enums/EnumsTest.java, src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/interfaces/InterfaceTest.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/limits/utils/InternalTest.java, src/test/java/spoon/test/methodreference/MethodReferenceTest.java, src/test/java/spoon/test/model/SwitchCaseTest.java, src/test/java/spoon/test/pkg/PackageTest.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/java/spoon/test/secondaryclasses/ClassesTest.java, src/test/java/spoon/test/targeted/TargetedExpressionTest.java, src/test/java/spoon/test/template/TemplateTest.java, src/test/java/spoon/test/type/TypeTest.java, src/test/java/spoon/test/visibility/VisibilityTest.java
Use assertSame to improve tests readability (express clearly intention of checking).
=> refactor: use assertSame in rest of tests

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java
Change access level from 'public' to 'private'.
Use accessor in other places.
I even did not add an accessor - it existed so I used it. I assume that this public accessor (getContext()) was added to have this field private. Should not be a compatibility issue.
=> refactor: fix SonarQube - make field 'private', use accessor

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/prettyprinter/LinesTest.java
1. Remove toString() on String
2. Simplify: poolName.substring(poolName.lastIndexOf(..., poolName.length());
`poolName.length()` is not needed, there is a method *substring(int beginIndex)* that processes string to the last element
=> refactor: remove redundant string operation

src/test/java/spoon/MavenLauncherTest.java
One test has been added by @nharrand in #2112 to show the usage of the new dependency resolver. However this test consumes too much memory on our CI, on the job used to deploy maven artefacts: 
> [ERROR] Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 68.03 s <<< FAILURE! - in spoon.MavenLauncherTest
[ERROR] testTypeResolution(spoon.MavenLauncherTest)  Time elapsed: 38.801 s  <<< ERROR!
java.lang.OutOfMemoryError: GC overhead limit exceeded
at spoon.MavenLauncherTest.testTypeResolution(MavenLauncherTest.java:25)
https://ci.inria.fr/sos/job/Spoon-Snapshot-Deployer/1689/console
I propose to ignore the test for now.
=> review fix: ignore a test for memory issues on the CI

src/main/java/spoon/support/compiler/VirtualFolder.java
Using a List here results in extremely long runtimes when the source
folder is large because the contains() call is O(n). The logic
ends up placing this List into a Set anyway so just use a Set here
and make contains() checks cheap.
=> Convert from List to Set to speed up contains() logic.

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
CtTypeParameter can never have qualified name and it can never use `super` as a bound type. It is also not needed to create reference to print CtTypeParameter.
=> refactor(printer): simplify printing of CtTypeParameter

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
@surli 
It looks that local variable *parameterTypesOfExecutable* is unused.
WDYT?
=> refactor: remove unused variable from JDTTreeBuilderHelper.java

src/test/java/spoon/test/main/MainTest.java
=> refactor: split variables declaration in test

src/main/java/spoon/support/visitor/SignaturePrinter.java, src/test/java/spoon/test/method/MethodTest.java, src/test/java/spoon/test/reference/ExecutableReferenceGenericTest.java
Signature shouldn't contain name of type parameter reference, because these three methods declarations:
```java
<T extends String> void m(T a);
<S extends String> void m(S b);
void m(String c)
```
Should have the same signature: `m(String)`
WDYT?
=> review: refactor: SignaturePrinter prints type parameter bounds, no name

src/test/java/spoon/test/method/MethodTest.java, src/test/java/spoon/test/method/testclasses/Methods.java
test which assures contract discussed in #2410 -
```java
<T extends List<String>> void m(T a);
<T extends List<Integer>> void m(T b);
<T extends List> void m(T c);
void m(List<String> d);
void m(List<?> e);
void m(List f);
```
all of them should have same signature: m(List)
... it looks like Spoon already works like that
=> review: test: Method SignaturePrinter uses type erasure of parameter types

src/main/java/spoon/support/reflect/reference/CtArrayTypeReferenceImpl.java, src/test/java/spoon/test/ctType/CtTypeParameterTest.java, src/test/java/spoon/test/ctType/testclasses/ErasureModelA.java
fixes type erasure of array in methods like: `public <I extends String> void methodWithArray(I[] param)` where type erasure should be `String[]`
=> review: fix: CtArrayTypeReference type erasure

src/test/java/spoon/test/prettyprinter/PrinterTest.java
Use straightforward assertion - assertEquals for testing equality.
```
assertTrue(Character.isWhitespace(c)==true);
```
-->
```
assertEquals(true, Character.isWhitespace(c));
```
=> refactor: simplify assertions in PrinterTest.java

src/main/java/spoon/internal/mavenlauncher/InheritanceModel.java, src/main/java/spoon/internal/mavenlauncher/TreeDependency.java, src/main/java/spoon/internal/mavenlauncher/Version.java, src/main/java/spoon/reflect/factory/CodeFactory.java, src/main/java/spoon/reflect/factory/ExecutableFactory.java, src/main/java/spoon/reflect/factory/FieldFactory.java, src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java, src/main/java/spoon/support/reflect/code/CtJavaDocImpl.java, src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java, src/test/java/spoon/test/imports/ImportScannerTest.java
SonarQube checker: *An indexOf or lastIndexOf call with a single letter String can be made more performant by switching to a call with a char argument.*
=> refactor: fix SonarQube - change 'String' to 'char' in string functions

src/test/java/spoon/test/ctType/CtTypeTest.java
fix #2288
(#2406 has probably fixed it.)
=> review: shows that #2288 has already been fixed 

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/parameters/ParameterTest.java, src/test/java/spoon/test/refactoring/MethodsRefactoringTest.java, src/test/java/spoon/test/replace/ReplaceParametrizedTest.java, src/test/java/spoon/test/staticFieldAccess/StaticAccessTest.java
Casts from 'x' to 'x' (the same).
=> refactor: remove redundant casts

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
Fix unreachable code (#2483 Warning 2)
I'm not quite sure what to do with that one, but there is definitely an error here (unreachable code):
```
if (content[off] == '\r') {
if (content[off] == '\n') {
```
=> fix: Unreachable code

src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
Fix incorrect comparison (#2483 Warning 3)
When I fixed equals arguments, tests failed:
```
java.lang.AssertionError: Found 3 problems:
Diff on path: #[modifier]
Shadow: final enum RequiresModifier {
STATIC,
TRANSITIVE;}
Normal: enum RequiresModifier {
STATIC,
TRANSITIVE;}
Diff on path: #[modifier]
Shadow: final enum CommentType {
FILE,
JAVADOC,
INLINE,
BLOCK;}
Normal: enum CommentType {
/**
* before the package line (typically the license)
*/
FILE,
/**
* JavaDoc comment: before methods, fields, types
*/
JAVADOC,
/**
* Inline comment (//)
*/
INLINE,
/**
* Block comment (/* *\/)
*/
BLOCK;}
Diff on path: #[modifier]
Shadow: final enum TagType {
AUTHOR,
DEPRECATED,
EXCEPTION,
PARAM,
RETURN,
SEE,
SERIAL,
SERIAL_DATA,
SERIAL_FIELD,
SINCE,
THROWS,
VERSION,
UNKNOWN;
public boolean hasParam() {
} …
```
=> fix: Incorrect comparison

src/main/java/spoon/reflect/declaration/CtType.java, src/main/java/spoon/support/compiler/SnippetCompilationHelper.java, src/test/java/spoon/test/snippets/SnippetTest.java, src/test/resources/snippet/SnippetResources.java
fix #2238
compileAndReplaceSnippetsIn was not tested at all, and probably broken due to a change in `CtPackage#addType` at some point.
=> review: fix: fix compileAndReplaceSnippetsIn that was broken

src/main/java/spoon/reflect/path/CtPath.java, src/main/java/spoon/reflect/path/impl/CtPathImpl.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/test/path/PathTest.java
add support for relative path with CtPath#relativePath with a functional style
=> feature: add support for relative path with CtPath#relativePath

src/main/java/spoon/support/compiler/SnippetCompilationHelper.java
*keySet()* is obsolete and slower construct, use *entrySet()* instead
https://stackoverflow.com/questions/8962459/java-collections-keyset-vs-entryset-in-map
This is SonarQube fix - Iterate over the "entrySet" instead of the "keySet".
=> refactor: change keySet to entrySet to improve performance (SonarQube fix)

src/main/java/spoon/reflect/visitor/filter/SuperInheritanceHierarchyFunction.java
2 problems solved:
- static import per se
- importing statically a class, then using it as a qualifier, e.g.
1. statically importing *NORMAL*: import static spoon.reflect.visitor.chain.ScanningMode.NORMAL;
2. use fully qualified name: ScanningMode.NORMAL;
https://carlosbecker.com/posts/avoid-static-imports/
=> refactor: remove static imports in SuperInheritanceHierarchyFunction.java

src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java
Some elements are statically imported (import static X.Y), then full name is used: X.Y.
I removed static imports and added missing classes.
Consistent syntax is used: CtRole.[something].
Previously there was mixed: CtRole.Value and Value (while 'Value' was statically imported).
=> refactor: remove static imports from CtAnnotationImpl.java

src/test/java/spoon/test/path/PathTest.java
I checked the CtPath string parser and duplicated ## is understood as #. I think that it is mistake to have ## there.
@nharrand WDYT?
=> fix(test): remove ignored # from the path

src/main/java/spoon/pattern/PatternBuilder.java
PatternBuilder now accepts List of any elements. No need to type cast.
=> refactor: PatternBuilder accepts List<? extends CtElement>

src/main/java/spoon/support/reflect/code/CtBlockImpl.java
We had mix of:
- CtRole.STATEMENT
- STATEMENT
The same cleaning like https://github.com/INRIA/spoon/pull/2541
=> refactor: remove static imports from CtBlockImpl.java

src/main/java/spoon/pattern/PatternParameterConfigurator.java, src/main/java/spoon/pattern/internal/parameter/ComputedParameterInfo.java, src/main/java/spoon/pattern/internal/parameter/ParameterComputer.java, src/main/java/spoon/pattern/internal/parameter/SimpleNameOfTypeReferenceParameterComputer.java, src/test/java/spoon/test/template/PatternTest.java
During writing test for #2530, I tried to make Pattern which matches whole type and have found that it doesn't work.
Reason: AST of type consists of at least 2 related parameters:
1) String CtType#simpleName - in the name of the type
2) CtTypeReference qualifiedName - in each self reference to the type
Until this PR Pattern made only one parameter with type CtTypeReference. It was ok as long as Pattern is used for generating of types, because generator is able to convert CtTypeReference to `String simpleName`.
But when we match such Pattern, it doesn't work/matches because there is no way how to create CtTypeReference (with fully qualified name) from the simple name of the type.
This PR contains solution which introduces new internal `ParameterInfo` ...  `ComputedParameterInfo`, whose …
=> fix: Pattern can match a Type

src/main/java/spoon/JarLauncher.java
Additional question:
Should lines
- (117) throw new SpoonException("Jar " + jar.getPath() + "not found.");
- (136) throw new SpoonException("Pom " + srcPom.getPath() + "not found.");
be changed to:
- (117) throw new SpoonException("Jar " + jar.getPath() + **" not found."**);
- (136) throw new SpoonException("Pom " + srcPom.getPath() + **" not found."**);
?
=> refactor: fix documentation errors in JarLauncher.java

src/main/java/spoon/pattern/Pattern.java, src/main/java/spoon/pattern/internal/PatternPrinter.java, src/test/java/spoon/test/template/PatternTest.java
Now it is possible to print pattern without parameter comments. This use case makes sense in PatternDetector reports, where parameter comments are not interesting ... and just make result less readable.
=> feature: print Pattern without parameter comments

src/main/java/spoon/pattern/PatternParameterConfigurator.java, src/test/java/spoon/test/template/PatternTest.java
Extends API of PatternParameterConfigurator, by way individual CtElements may be substituted by pattern parameter. It is similar like `PatternParameterConfigurator#byFilter`, just elements are explicitly listed.
It is needed by `PatternDetector` feature ... coming soon.
=> review: feat: PatternParameterConfigurator substitute by element

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java
Fix SonarQube warning: *Remove this conditional structure or edit its code blocks so that they're not all the same.*
=> sonarqube: fix SonarQube warning in JDTTreeBuilderQuery.java

src/main/java/spoon/JarLauncher.java
In Java constructors never return "null" value so SonarQube reported this 'if' condition.
I also corrected string message, confirmed by @nharrand here: https://github.com/INRIA/spoon/pull/2575
=> sonarqube: remove dead condition jarlauncher.java

doc/path.md, src/main/java/spoon/reflect/path/CtElementPathBuilder.java, src/main/java/spoon/reflect/path/CtPathStringBuilder.java, src/main/java/spoon/reflect/path/impl/AbstractPathElement.java, src/main/java/spoon/reflect/path/impl/CtNamedPathElement.java, src/main/java/spoon/reflect/path/impl/CtRolePathElement.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/test/main/MainTest.java, src/test/java/spoon/test/path/PathTest.java, src/test/java/spoon/test/path/testclasses/Foo.java
I like the idea of CtPath for locating of nodes in AST (I plan to use it in Patterns and PatternDetector). But in my use cases it is problem that automatically generate path is not readable. For example :
```
#subPackage[name=testclasses]#containedType[name=Foo]#typeMember[index=2]
```
...typeMember with index 2 says nothing usefull.
This PR provides more readable automatically generated paths like
```
#subPackage[name=testclasses]#containedType[name=Foo]#field[name=someField]
#subPackage[name=testclasses]#containedType[name=Foo]#method[signature=someMethod()]
#subPackage[name=testclasses]#containedType[name=Foo]#constructor[signature=(int,java.lang.String)]
```
I like it a lot now, but there is little problem - the evaluation of such path is slower then before, because nothing is so fast …
=> feature: CtPath accepts names and signatures on List

src/main/java/spoon/metamodel/MetamodelProperty.java
@monperrus, you made it in #1852 and I need it too ;-)
=> feature: MetamodelProperty#getMethods()

src/main/java/spoon/support/modelobs/SourceFragmentCreator.java
SniperPrinter change collector listens on changes ... but spoon produces many ... many change events during normal analyzing tasks (no real changing of model). For example just creation of type references or adapting generic types creates many temporary AST node instances, which are not really connected to the AST... but they produce change requests.
This PR tries to filter out at least those events whose element has no parent.
... but there are still other temporary elements which has set parent, but has no connection from parent to temporary element. This check is more expensive ... so it is better to run analyzing code using `ChangeCollector.runWithoutChangeListener`... without that change collector soon eats many GB of memory and fails.
=> fix: ignore changes on elements without parent

src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java
The references (mainly type references) often calls `#equals(Object)` method. This optimization improves performance, because simple names are often not equal.
=> perf: faster CtReference#equals(Object)

src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java
This code is called quite often so the building of useless message has bad influence to query engine performance.
=> perf: CtQuery create log message only when log is enabled

src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java, src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentContext.java, src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
When the code
```java
<T> T method();
```
is refactored to
```java
AClass method();
//but sniper prints
AClass method();
```
bug: SniperPrinter keeps space after `<T>`
expected: SniperPrinter removes space which as after removed `<T>`
=> fix(sniper): skip separator after removed element

src/main/java/spoon/reflect/path/CtPathStringBuilder.java, src/main/java/spoon/reflect/path/impl/CtNamedPathElement.java
- use contains() to clearly say intentions (both commits)
- simplify method *canBeRegExpPattern* (one commit)
=> refactor: use contains() to improve readability

src/main/java/spoon/support/StandardEnvironment.java
- Fixed 2 SonarQube warnings (use StringBuilder because it is faster than StringBuffer [it has synchronized methods])
- order imports (re-sort)
- order fields (delete space)
I tried to obtain proper balance between: [exactly one change]<->[set of small changes].
If you review commit-by-commit, everything will be clear for sure ;-)
=> refactor: fix sonarqube: StandardEnvironment.java

src/main/java/spoon/reflect/path/CtPathStringBuilder.java
CtPathElement pathElement = null;
This null assignment value is lost in:
- pathElement = new CtNamedPathElement(token, false); or
- pathElement = new CtTypedNameElement(load(token)); or
- pathElement = new CtRolePathElement(CtRole.fromName(token));
This time null is overriden by another values (returned from ctrs). Null is not useful anyhow in this case. It is confusing and (sometimes) dangerous (NPE risk).
To be deleted.
=> refactor: remove redundant initialization

src/main/java/spoon/reflect/visitor/CommentHelper.java
=> refactor: remove static imports of enums in CommentHelper.java

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/testclasses/Kun.java
When printer prints the code like
```java
import static spoon.reflect.path.CtRole.NAME;
...
String field = NAME.toString();
```
then it shouldn't add `import spoon.reflect.path.CtRole;`
=> fix: CtImportScanner shouldn't import type when static field is imported

src/main/java/spoon/support/reflect/code/CtExpressionImpl.java
Problem: call of `setTypeCasts(null)` changes property value but change listener is not called.
I do not plan to write a test for that bug. I am working on refactoring of all such methods, so such test would be thrown away later anyway.
But that bug has to be fixed to have Sniper mode working.
=> fix: CtExpressionImpl#setTypeCasts(null) calls change listener now

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/comment/testclasses/TestClassWithComments.java, src/test/java/spoon/test/comment/testclasses/testClassWithComments.java
For Issue #2482. Added a test class for the following issues:
1. Comment association are mixed up
2. And the comment at the end of the file is not printed
=> added a test for Comment Association and Printing

src/main/java/spoon/reflect/factory/TypeFactory.java, src/test/java/spoon/test/compilation/CompilationTest.java
JavaReflectionTreeBuilder used factory with default environment instead of current environment, therefore it used wrong class loader - it was not possible to define the class loaded of JavaReflectionTreeBuilder
=> fix: use correct classloader during shadow type building

src/main/java/spoon/reflect/path/CtPathStringBuilder.java
SonarQube fix.
Private method is unused and may be removed - *private String getNextToken()*.
There is a package level method that is used - *String getNextToken(String delimiters)*.
```
=> refactor: remove unused private method (fix SonarQube waraning)

src/test/java/spoon/test/comment/CommentTest.java
Make clear what exactly is called.
Fix few grammar errors.
https://carlosbecker.com/posts/avoid-static-imports/
=> refactor: remove static import from CommentTest.java

src/main/java/spoon/reflect/path/impl/CtRolePathElement.java
Remove redundant cast from *CtElement* to *CtElement*.
Checker: Redundant type cast
*Reports unnecessary cast expressions.*
This is also SonarQube fix - Remove this unnecessary cast to "CtIf".
=> refactor: remove redundant cast - CtRolePathElement.java

src/main/java/spoon/pattern/InlinedStatementConfigurator.java
Remove cast from CtIf to CtIf.
Checker: Redundant type cast
*Reports unnecessary cast expressions.*
=> refactor: remove redundant cast - InlinedStatementConfigurator.java

src/main/java/spoon/support/compiler/ZipFolder.java, src/test/java/spoon/test/jar/JarTest.java
Make sure a resource is properly released.
@pvojtechovsky 
Pavel could you take a look on *public List<SpoonFile> getFiles()* and tell me if this algorithm is correct *before* and *after* change.
=> refactor: close resource in ZipFolder.java

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/test/java/spoon/test/enums/EnumsTest.java, src/test/java/spoon/test/enums/testclasses/EnumWithMembers.java
Hi. I found out that Spoon is probably wrong about the 'final' and 'public' modifiers of enum members.
Consider the following code:
```
public enum MyEnum {
ONE,
TWO,
THREE;
private static int len = -1; // Spoon says that len is final and public, but it is not!
public static void f() {
len = 44;
}
}
```
BTW, If I do the same in a class it works fine:
```
public class MyClass {
private static int len = -1; // len is not final and is not public (as expected)
public static void f() {
len = 44;
}
}
```
This PR contains failing test cases (see `lenField.isFinal()` and `lenField.isPublic()`).
Any ideas how to fix this?
Thanks.
=> bug: Invalid enum members modifiers

src/main/java/spoon/reflect/factory/TypeFactory.java
I remember not to use isEmpty in more complex cases (that produce negation etc.).
=> refactor: use isEmpty() - fix sonarqube

src/main/java/spoon/pattern/PatternParameterConfigurator.java
Deprecated in Pattern's code replaced by better javadoc - see request in #2649
=> fix(javadoc): replace deprecated by better javadoc

src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/main/java/spoon/support/util/internal/MapUtils.java, src/test/java/spoon/test/compilation/CompilationTest.java
`ClassLoader#loadClass` is slower then reading from Map.
I am using internal `MapUtils` class for PatternDetector ... Can we add `MapUtils` now, or you want special PR for that internal class?
=> review: perf: cache result of CtTypeReference#findClass()

src/test/java/spoon/test/main/MainTest.java
This should fix timout issues on travis. It is only a quick fix that print and flush() a message after each package testing for the one test that takes a long time.
The offending test is `MainTest#testElementToPathToElementEquivalency()` and we might want to rework it. _(Keeping in mind that we should not blame whoever wrote it... :innocent:)_
I suggest that we select a meaningful subset of the sources on which it runs. (So far it runs on the complete spoon AST).
=> fix(MaintTest): quickfix of ci timeout issues

doc/launcher.md, pom.xml, src/main/java/spoon/decompiler/FernflowerDecompiler.java, src/test/java/spoon/JarLauncherTest.java
As I am unsure how reliable is `CFRDecompiler`, and that it might make `SpoonClassFileTransformer` a little tricky to use, I suggest to add at least a second option. [Fernflower](https://github.com/JetBrains/intellij-community/tree/master/plugins/java-decompiler/engine) is IntelliJ's decompiler, which is open source (Apache v2) but not distributed as a standalone project. But JBoss is distributing it as a Maven dependency.
This change only increase slightly the jar-with-dependencies (16M -> 17M).
=> feat(FernflowerDecompiler)

src/test/java/spoon/JarLauncherTest.java, src/test/java/spoon/test/refactoring/CtRenameLocalVariableRefactoringTest.java
- Control flow statement without braces inspection
*Reports any if, while or for statements without braces. Braces make the code easier to read and help prevent errors when modifying the code.*
=> refactor: add missing braces to tests

src/test/java/spoon/test/enums/EnumsTest.java, src/test/java/spoon/test/jar/JarTest.java, src/test/java/spoon/test/main/MainTest.java
- 'expression.equals("literal")' rather than 'literal.equals("expression")'
*Reports calls to .equals() whose arguments are String literals. Some coding standards specify that String literals should be the target of .equals(), rather than argument, thus minimizing NullPointerExceptions.*
=> refactor: flip order of comparison - put literal first to lower risk of NPE

src/main/java/spoon/metamodel/Metamodel.java, src/main/java/spoon/pattern/Match.java, src/main/java/spoon/reflect/declaration/CtClass.java, src/main/java/spoon/reflect/visitor/chain/CtQuery.java, src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java, src/main/java/spoon/support/reflect/code/CtLiteralImpl.java, src/main/java/spoon/support/reflect/declaration/CtClassImpl.java
- Type parameter explicitely extends 'java.lang.Object' inspection
Every Java class extends Object class OR another class.
Extending Object does not provide any value (it is like invoking "super()" in ctr) and makes code longer.
=> refactor: remove redundant type (extending Object)

src/test/java/spoon/reflect/ast/CloneTest.java, src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java, src/test/java/spoon/reflect/visitor/CtInheritanceScannerTest.java, src/test/java/spoon/support/compiler/classpath/ComputeClasspathTest.java, src/test/java/spoon/test/OutputTypeTest.java, src/test/java/spoon/test/api/MetamodelTest.java, src/test/java/spoon/test/factory/FieldFactoryTest.java, src/test/java/spoon/test/imports/ImportAndExtendWithPackageNameTest.java, src/test/java/spoon/test/intercession/IntercessionTest.java, src/test/java/spoon/test/jar/JarTest.java, src/test/java/spoon/test/pkg/PackageTest.java, src/test/java/spoon/test/reflect/visitor/ReferenceQueryTest.java, src/test/java/spoon/test/replace/ReplaceTest.java
Preparation for https://github.com/INRIA/spoon/issues/2609
=> refactor: use static import for asserts in tests

src/main/java/spoon/pattern/PatternBuilder.java
Fix SonarQube warning: *Remove the parentheses around the "tobeUsedNode" parameter*
=> refactor: remove redundant parentheses (SonarQube fix)

src/test/java/spoon/test/main/MainTest.java
Alternative solution to #2681 following @pvojtechovsky 's idea.
This actually works well on my machine. The offending test goes from 3min 30s to a bit more than 1min.
Let's see if it helps with travis!
Whatever direction we choose, I think we could apply this to other tests.
It also make me think about something that might be silly (or at least uninformed) but does spoon provides some sort of parallel visitor/scanner that visit brother nodes in a parallel way?
=> perf(MainTest): parallelize 

src/main/java/spoon/reflect/annotations/MetamodelPropertyField.java
- Declaration has problems in Javadoc references inspection
*Symbol 'simpleName' is inacessible from here*
```
/**
* Tells that a field is a property of the metamodel
* For instance {@link CtClassImpl#simpleName} is the property name of {@link CtNamedElement}
*
*/
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD })
public @interface MetamodelPropertyField {
CtRole[] role();
}
```
Maybe a correct solution is reference to:
{@link spoon.support.reflect.declaration.CtNamedElementImpl#getSimpleName}
?
@pvojtechovsky 
Could you take a look on WHOLE comment? ;-)
=> doc: fix javadoc in MetamodelPropertyField.java

src/main/java/spoon/pattern/internal/PatternPrinter.java
Please suggest missing Javadoc for PatternPrinter:
```
/**
*/
public class PatternPrinter extends DefaultGenerator {
```
=> doc: add missing javadoc for PatternPrinter 

src/main/java/spoon/reflect/factory/TypeFactory.java
SonarQube: *Remove this unnecessary cast to "CtElement".*
=> doc: fix javadoc in TypeFactory.java

src/test/java/spoon/test/intercession/IntercessionTest.java
Relax contract of IntercessionTest#testSettersAreAllGood so the new Spoon API (e.g. #2702) can be made in correct way.
=> fix: relax intercession test to fit #2615 - new fluent API return types

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/resources/ConfigPlugin.java
fix #2209 
Note that it's a partial fix, the comment should be added to the expression inside the annotation, but it's still much better than the dirty exception in logs of before.
=> fix: comment of CtAnnotation value

doc/jenkins/build.sh
Will allow to investigate better on #2721
=> review chore: Change jenkins/build.sh to allow passing maven parameters

src/main/java/spoon/ContractVerifier.java, src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java, src/main/java/spoon/testing/utils/Check.java, src/test/java/spoon/test/executable/ExecutableTest.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/main/MainTest.java, src/test/java/spoon/test/parent/ParentTest.java, src/test/java/spoon/test/variable/AccessFullyQualifiedFieldTest.java, src/test/java/spoon/test/variable/AccessTest.java
and the rest will move to Jenkins, see plan in #2662 
WDYT?
=> review: Generic contracts are run only on **.testclasses.**

doc/pattern.md, src/main/java/spoon/pattern/internal/node/ElementNode.java, src/test/java/spoon/test/template/TemplateTest.java
The `isImplicit` attribute is ignored by pattern matcher now. It means that these two lines:
```java
java.lang.String x;
String x;
```
are same from pattern matcher point of view.
It will be tested by #2683 which correctly sets isImplicit attributes and therefore two lines above has different values. Actually the values are same so it is not easily testable.
=> fix: PatternMatcher ignores isImplicit

src/main/java/spoon/reflect/visitor/EarlyTerminatingScanner.java, src/main/java/spoon/reflect/visitor/chain/CtScannerListener.java
Information about role of the scanned element is now available in `CtScannerListener`.
It makes algorithms of import validators easier and faster.
=> feat: CtScannerListener knows role of scanned element

src/main/java/spoon/support/reflect/reference/CtFieldReferenceImpl.java
we all crawled through this stack trace in Travis logs.
that's over now.
```
spoon.support.SpoonClassNotFoundException: cannot load class: daikon.Runtime
at spoon.support.reflect.reference.CtTypeReferenceImpl.lambda$findClass$9(CtTypeReferenceImpl.java:170)
at spoon.support.util.internal.MapUtils.getOrCreate(MapUtils.java:43)
at spoon.support.util.internal.MapUtils.getOrCreate(MapUtils.java:33)
at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:163)
at spoon.support.reflect.reference.CtTypeReferenceImpl.getActualClass(CtTypeReferenceImpl.java:143)
at spoon.support.reflect.reference.CtFieldReferenceImpl.getActualField(CtFieldReferenceImpl.java:63)
at spoon.support.reflect.reference.CtFieldReferenceImpl.getModifiers(CtFieldReferenceImpl.java:227)
at …
```
=> refactor: error handling of CtFieldReference#getActualField

src/main/java/spoon/reflect/declaration/CtImport.java, src/main/java/spoon/reflect/visitor/CtImportVisitor.java, src/main/java/spoon/support/reflect/declaration/CtImportImpl.java, src/test/java/spoon/test/imports/ImportTest.java
Simplifies work with different kinds of imports -> `CtImportVisitor`
=> feat: CtImportVisitor

src/test/java/spoon/processing/CtGenerationTest.java
Surefire displays ComparisonFailure ... which is not bad for short strings, but completely breaks the output if CtGenerationTest fails eg https://travis-ci.org/INRIA/spoon/jobs/452050077
=> test: remove long logs fof CtGenerationTest which makes CI log unreadable

src/main/java/spoon/Launcher.java, src/main/java/spoon/support/JavaOutputProcessor.java
The pretty printer of JavaOutputProcessor printer ignored Environment settings, because it was created before Launcher configured is finished.
This PR by default creates JavaOutputProcessor with lazily created PrettyPrinter
=> refactor: JavaOutputProcessor uses Environment#createPrinter() by default

src/main/java/spoon/support/compiler/SpoonPom.java, src/test/java/spoon/MavenLauncherTest.java, src/test/resources/maven-launcher/java-11/pom.xml
If the java version does not start with `1.` in pom.xml, a `NumberFormatException` is thrown when creating a new `MavenLauncher`. (issue #2714)
We check if the java version number contains a `.` before removing it.
I added an Assert in `MavenLauncherTest`. 
I haven't done many PRs so feel free to tell me if I did anything wrong.
=> fix: java version not starting with "1." in pom.xml

src/main/java/spoon/reflect/visitor/CommentHelper.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/test/javadoc/JavaDocTest.java
=> refactor: getDocComment uses the same implementation as pretty-printer

src/main/java/spoon/compiler/Environment.java, src/main/java/spoon/compiler/SpoonFile.java, src/main/java/spoon/compiler/builder/EncodingProvider.java, src/main/java/spoon/support/StandardEnvironment.java, src/main/java/spoon/support/compiler/VirtualFile.java, src/main/java/spoon/support/compiler/jdt/FileCompilerConfig.java, src/test/java/spoon/test/api/FileSystemFolderTest.java, src/test/java/spoon/test/compilationunit/TestCompilationUnit.java, src/test/resources/encodings/Cp1251.java, src/test/resources/encodings/Utf8.java
This PR provides ability to specify user-defined callback, which could be used to detect encoding for each file separately. See #2781.
For example I use juniversalchardet lib:
```
private Charset detectEncoding(byte[] fileBytes) {
final int maxLength = 4096;
UniversalDetector detector = new UniversalDetector(null);
detector.handleData(fileBytes, 0, Math.min(fileBytes.length, maxLength));
detector.dataEnd();
String encoding = detector.getDetectedCharset();
detector.reset();
if (encoding != null) {
return Charset.forName(encoding);
}
return Charset.forName("UTF-8");
}
```
Spoon api:
```
final Launcher launcher = new Launcher();
launcher.getEnvironment().setEncodingDetectionCallback(bytes -> detectEncoding(bytes));
// ...
CtModel model = launcher.buildModel();
```
It helps to have correct …
=> Add encoding detection callback

src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentContext.java, src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentContextCollection.java
This is a little fix of Sniper printer, whose correctness will be tested in #2683
=> fix: sniper printer leaves child context when empty

src/main/java/spoon/reflect/code/CtTypeAccess.java, src/main/java/spoon/support/reflect/code/CtTypeAccessImpl.java, src/test/java/spoon/test/api/Metamodel.java, src/test/java/spoon/test/type/TypeTest.java
`CtTypeAccess` derives value of property `implict` from it's type.
It makes no sense that `CtTypeAccess` would have different value then it's `type`.
=> refactor: CtTypeAccess#implicit is derived now

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/test/java/spoon/test/position/PositionTest.java
The position of CtPackageDeclaration never contains top comment of file. Next comments belongs to package declaration
```java
/* file comment, belongs to compilation unit */
/* every other comment belongs to package declaration */
package a.b.C;
```
=> fix: CtPackageDeclaration position doesn't include top file comment

src/main/java/spoon/reflect/visitor/filter/AllTypeMembersFunction.java, src/test/java/spoon/test/model/TypeTest.java
AllTypeMembersFunction can now return
A) all type members
B) only these type members which are visible in input type. It means inherited private type members are not returned
=> feature: AllTypeMembersFunction mode=[All, SKIP_PRIVATE]

CONTRIBUTING.md
The current rule for granting the integrator role suffers from that it's unclear how active developers can join and non-active integrators can leave easily.
This reformulation makes explicit that Spoon is based on meritocracy: all contributors with significant contributions over the past year can become integrator.
The goal is to be welcoming, and at the same time, that contributors who have shifted their interests do not feel bound to any duty.
=> governance: explicit rule on how integrators are chosen

src/main/java/spoon/reflect/reference/CtTypeReference.java, src/main/java/spoon/support/reflect/reference/CtArrayTypeReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtIntersectionTypeReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/reference/TypeReferenceTest.java
During refactoring of import handling #2683, I often needed to know whether type reference 
A) shows only simple name and it's parent is implicit
B) shows fully qualified name (it's parent is not implicit)
Therefore I found useful these two new API methods.
WDYT?
=> feature: new property CtTypeReference#implicitParent

src/main/java/spoon/support/compiler/SpoonProgress.java, src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
It allows to assign comments on the imports
```java
//comment
import a.b.C;
```
The test will be in #2683.
It is ready for merge
=> fix: JDT spoon compiler builds imports and then comments

src/test/java/spoon/test/main/MainTest.java
The MS Windows paths with backslash are not matching the carpet debugging rules
=> fix: MainTest#testGenericContract on MS Windows

README.md, doc/_config.yml, doc/_includes/sidebar.html
=> doc: remove all hard coded version numbers to simplify release

src/main/java/spoon/refactoring/Refactoring.java
When the model is more complicated then the origin code failed, because the checking of the model consistency in the middle of renaming cannot work.
So this PR first changes names and then checks that everything is consistent
=> fix: Refactoring#copyType()

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/test/java/spoon/test/condition/ConditionalTest.java, src/test/java/spoon/test/condition/testclasses/Foo2.java
Hello.
I was trying to migrate from spoon 7.0 to 7.2, and encountered some mode build failures due to the recent changes. (We have a large test base with ~80 open-source projects).
Spoon 7.2 failed to build a model with NPE for the following code (it's from [sakai](https://github.com/sakaiproject/sakai) open-source project):
```
if (itemGrading.getAttemptsRemaining() == null){
// this is not possible unless the question is submitted without the
// attempt set correctly
if ((item.getTriesAllowed()).intValue() >= 9999)
attemptsRemaining = 9999;  
} else{
if ((item.getTriesAllowed()).intValue() >= 9999 )
attemptsRemaining = 9999;
else if (itemGrading.getAttemptsRemaining().intValue() > 0);
// We're now getting the applet to tell us how many attempts remain
// attemptsRemaining = …
```
=> fix: NPE in JDTCommentBuilder

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java, src/main/java/spoon/support/compiler/jdt/PositionBuilder.java, src/test/java/spoon/test/position/PositionTest.java, src/test/java/spoon/test/position/testclasses/TestCommentedOutClass.java
This is alternative to #2823
Thank You Egor for the failing test. I added it as part of this PR.
Then I fixed it by way the compilation unit has correct lineSeparatorPositions even when it is empty.
=> fix: CompilationUnit has lineSeparatorPositions even for empty class

CONTRIBUTING.md
Dear all,
I'd like to nominate Nicolas Harrand (@nharrand) to become an integrator in Spoon. Nicolas has done several key contributions over the past year:
* he has added support for paths in order to uniquely identify AST nodes (#1874), this feature is unique (to my knowledge, it does not exist in any other source code analysis library for Java), and enables original source code analysis over time and versions.
* he has added support for analysis of binary files with decompilation (#2455)
* he has laid down the foundations of a modularized Spoon (#2766), which will likely be key in the future
* he has ported Spoon to JDK 11 (#2789). This kind of infrastructure contribution is also very important in the long term.
In addition, Nicolas has proven his ability to communicate constructively …
=> community: Nicolas Harrand becomes integrator

chore/travis/travis-verify.sh, spoon-control-flow/LICENSE.txt, spoon-control-flow/README.md, spoon-control-flow/pom.xml, spoon-control-flow/src/main/java/fr/inria/controlflow/AllBranchesReturn.java, spoon-control-flow/src/main/java/fr/inria/controlflow/BranchKind.java, spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowBuilder.java, spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowEdge.java, spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowGraph.java, spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowNode.java, spoon-control-flow/src/main/java/fr/inria/controlflow/GraphVisPrettyPrinter.java, spoon-control-flow/src/main/java/fr/inria/controlflow/NotFoundException.java, spoon-control-flow/src/main/java/fr/inria/controlflow/TransferFunctionVisitor.java, spoon-control-flow/src/main/java/fr/inria/controlflow/Value.java, spoon-control-flow/src/main/java/fr/inria/dataflow/AbstractControlFlowVisitor.java, spoon-control-flow/src/main/java/fr/inria/dataflow/ControlFlowVisitor.java, spoon-control-flow/src/main/java/fr/inria/dataflow/ControlFlowVisitorBackwards.java, spoon-control-flow/src/main/java/fr/inria/dataflow/ControlFlowVisitorForward.java, spoon-control-flow/src/main/java/fr/inria/dataflow/InitializedVariables.java, spoon-control-flow/src/main/java/fr/inria/dataflow/UselessAssignmentAnalysis.java, spoon-control-flow/src/test/java/fr/inria/controlflow/AllBranchesReturnTest.java, spoon-control-flow/src/test/java/fr/inria/controlflow/ControlFlowGraphTests.java, spoon-control-flow/src/test/java/fr/inria/controlflow/ForwardFlowBuilderVisitorTest.java, spoon-control-flow/src/test/java/fr/inria/controlflow/SpoonMetaFactory.java, spoon-control-flow/src/test/java/fr/inria/dataflow/InitializedVariablesTest.java, spoon-control-flow/src/test/java/fr/inria/dataflow/UselessAssignmentTest.java, spoon-control-flow/src/test/resources/control-flow/ControlFlowArithmetic.java, spoon-control-flow/src/test/resources/initialized/ComplexFlow.java
=> feat: add module for control-flow analysis

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java, src/test/java/spoon/test/condition/testclasses/Foo2.java
I think that refactoring of JDTCommentBuilder in #2822 did not go so well :|
This PR is to fix IndexOutOfBoundsException during model build for the following code:
```
void bug3() {
if (false) {} // some comment
else if (false) {}
}
```
```
java.lang.IndexOutOfBoundsException: Index: 0
at spoon.support.util.EmptyClearableList.get(EmptyClearableList.java:90)
at spoon.support.util.ModelList.get(ModelList.java:55)
at spoon.support.reflect.code.CtBlockImpl.getStatement(CtBlockImpl.java:78)
at spoon.support.compiler.jdt.JDTCommentBuilder$1.visitCtIf(JDTCommentBuilder.java:378)
at spoon.support.reflect.code.CtIfImpl.accept(CtIfImpl.java:45)
at spoon.reflect.visitor.CtInheritanceScanner.scan(CtInheritanceScanner.java:184)
at spoon.support.compiler.jdt.JDTCommentBuilder$1.scan(JDTCommentBuilder.ja …
```
=> fix: OOB in JDTCommentBuilder

doc/first_analysis_processor.md
For some reason the text between the `{{site.data.alerts.note}}` and the closing tag was not rendered as markdown. The links were interpreted as HTML and rendered as e.g. `<http: spoon.gforge.inria.fr="" code_elements.html="">...</http:>`, which isn't a link. Visually, the links appeared to  be missing in the text, see [this page](http://spoon.gforge.inria.fr/first_analysis_processor). I couldn't get markdown to work in this syntactic context, but using HTML links fixes it.
=> fix: unrendered link in doc

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
=> fix: fix regression #2846 #2842

doc/launcher.md
fix #2868. (the reason is that only module spoon-core is deployed as maven site with javadoc)
=> doc: fix broken link

src/main/java/spoon/reflect/factory/Factory.java, src/main/java/spoon/reflect/factory/FactoryImpl.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/exceptions/ExceptionTest.java, src/test/resources/spoon/test/noclasspath/exceptions/Bar.java
=> fix: fix NPE for multicatch qualified exceptions

src/main/java/spoon/reflect/declaration/CtTypeInformation.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/arrays/ArraysTest.java
I'm not satisfied by this answer. Do you see another working solution?
@pvojtechovsky would you have a look at the bug in isSubTypeOf?
=> feat: check if a CtType is an array type

README.md
`mvn eclipse:eclipse` has been deprecated for many years now. Importing a Maven project in Eclipse IDE is usually better done by the File > Import > Maven > Existing Maven project... wizard.
=> Remove deprecated `mvn eclipse:eclipse` in README

src/main/java/spoon/javadoc/internal/JavadocDescription.java
Fix link to missing class which breaks the Javadoc linter
```
[ERROR] /home/travis/build/SpoonLabs/spoon-deploy/spoon/src/main/java/spoon/javadoc/internal/JavadocDescription.java:17: error: reference not found
[ERROR] 	* <p>For example <code>This class is totally unrelated to {@link com.github.javaparser.Range}
```
=> doc: fix doc JavadocDescription.java

src/main/java/spoon/support/compiler/jdt/ContextBuilder.java, src/test/java/spoon/test/position/PositionTest.java
=> fix(ContextBuilder): catch PositionBuilder exception and log them instead of crashing

spoon-control-flow/src/main/java/fr/inria/controlflow/AllBranchesReturn.java, spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowBuilder.java, spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowGraph.java, spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowNode.java, spoon-control-flow/src/main/java/fr/inria/controlflow/GraphVisPrettyPrinter.java, spoon-control-flow/src/main/java/fr/inria/controlflow/TransferFunctionVisitor.java, spoon-control-flow/src/main/java/fr/inria/controlflow/Value.java, spoon-control-flow/src/main/java/fr/inria/dataflow/InitializedVariables.java, spoon-control-flow/src/main/java/fr/inria/dataflow/UselessAssignmentAnalysis.java
continuation of #2910 (merged a bit too early)
prepare for #2911
=> doc(spoon-control-flow): fix javadoc errors

src/test/java/spoon/reflect/reference/CtTypeReferenceTest.java
Fix #1842 : Add test for methods spoon.support.reflect.reference.CtTypeReference#unbox() and box()
=> Fix #1842 : Add test for methods CtTypeReference#unbox() and box()

doc/examples.md
* In the title, `usages` should be `Usages` according to other pages
* Bound example points to the wrong page
* Some other examples' links are not to the root folder, which seems a bit confusing
=> Doc: fix links in doc page "Examples of Spoon Usages"

src/main/java/spoon/reflect/declaration/CtPackage.java, src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java, src/test/java/spoon/test/pkg/PackageTest.java
=> feat(CtPackage): add two utility methods #isEmpty() and #hasPackageInfo()

src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/eval/EvalTest.java, src/test/java/spoon/test/eval/testclasses/Foo.java
=> fix: handling of String const in getCorrespondingRuntimeObject/convertElementToRuntimeObject

src/main/java/spoon/reflect/declaration/CtTypeInformation.java, src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/generics/testclasses5/A.java, src/test/java/spoon/test/generics/testclasses5/B.java
fix #1565
Implements `CtTypeInformation#isParametrized()`
=> Add isParameterized method

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java, src/test/java/spoon/test/compilation/CompilationTest.java, src/test/resources/duplicateClass/DuplicateInnerClass.java
This code is decompilation of the bytecode file, but as I understand parser should never throw exception when it tries to build AST. I would prefer if it would just skip the second class, if it's possible. Or maybe you prefer another way for it? Thanks.
stacktrace:
java.lang.NullPointerException
at spoon.support.compiler.jdt.JDTTreeBuilderHelper.createType(JDTTreeBuilderHelper.java:623)
at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1663)
at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1485)
=> fix NPE with duplicate inner class

src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java, src/test/java/spoon/test/generics/GenericsTest.java
=> Fix isGenerics for top-level types

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java, src/test/java/spoon/reflect/ast/AstCheckerTest.java, src/test/resources/noclasspath/A4.java
Executable reference return type should match actual executable.
Reproduce, test and fix #2966
=> fix(JDTTreeBuilderHelper): executable reference return type

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/resources/import-resources/fr/inria/PageButtonNoClassPath.java
fix #2996
As far as I understand from debugging, the problem is that when the binding of some unknown method in chain is null, it is not set to static by default (like for `ProblemMethodBinding`), which affects how `ImportsScanner` processes it. 
So my workaround is to set static = true here as well.
=> Possible fix for auto imports (issue #2996)

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/eval/EvalTest.java, src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/prettyprinter/PrinterTest.java, src/test/java/spoon/test/query_function/VariableReferencesTest.java, src/test/java/spoon/test/strings/StringTest.java, src/test/java/spoon/test/template/TemplateReplaceReturnTest.java, src/test/java/spoon/test/template/TemplateTest.java, src/test/java/spoon/test/visibility/VisibilityTest.java
fix #3021
I think there is no need to wrap any `CtTargetedExpression` in parentheses when it is used in binary / unary operations (precedence is higher anyway).
=> fix: Remove parentheses around targeted expr in binary or unary op

src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/reference/TypeReferenceTest.java, src/test/resources/noclasspath/A5.java
fix #2845
I managed to reproduce NPE inside `canAccess()` and `isInSamePackage()` in noclasspath mode.
It turned out that NPE occurs if the `type` is null or if `type.getPackage()` returns null (it's a generic type for example).
So this PR is to fix that.
=> fix: NPE in isInSamePackage() and canAccess()

spoon-pom/pom.xml
Sonatype has added a new validation rule. We need this otherwise deployment fails with `ReasonPhrase:Forbidden. and 'parent.relativePath' points at no local POM @ fr.inria.gforge.spoon:spoon-pom:1.0, /home/travis/build/SpoonLabs/spoon-deploy/spoon/spoon-pom/pom.xml, line 4, column 13`
See https://travis-ci.org/SpoonLabs/spoon-deploy/builds/549038609
=> chore: fix automatic deploy

src/main/java/spoon/reflect/factory/TypeFactory.java
=> doc: clarify the contract of get(String)

doc/_data/sidebar_doc.yml
Just spent 5 minutes to find the template documentation on the website. It means that we have discoverability problem. Fixed here.
=> doc: fix discoverability of templates

src/main/java/spoon/ContractVerifier.java
(one day we'll have 0 class with 0% coverage)
=> Test: add test for untested class JavaIdentifiers

src/main/java/spoon/reflect/factory/ClassFactory.java, src/main/java/spoon/reflect/factory/InterfaceFactory.java, src/main/java/spoon/support/compiler/jdt/ContextBuilder.java, src/test/java/spoon/test/position/PositionTest.java, src/test/resources/noclasspath/lambdas/InheritedClassesWithLambda1.java, src/test/resources/noclasspath/lambdas/InheritedClassesWithLambda2.java, src/test/resources/noclasspath/lambdas/InheritedInterfacesWithLambda.java
Fix #3052.
Here is why this bug is happening:
Eclipse jdt tells us that the binding of the `listener` variable inside the lambda is null in noclasspath mode, 
so we run `createVariableAccessNoClasspath()`, it calls `getVariableDeclaration()`, which uses `classFactory.create()` for inner classes improperly. This leads to the creation of a new top-level class `Failing` (with unknown position), so references get messed up and we get this new class with no position instead of the original `Failing`.
More specifically the problem was that the description of the `classFactory.create()` said that it can handle both `.` and `$`, but its implementation handles only `$`, so I added `getNormalQualifiedName()` and fixed context builder. By the way, it's not possible to handle them both in …
=> fix: Fix issue #3052

doc/doc_homepage.md, pom.xml
Thanks to all contributors and special kudos to @Egor18!
* Add support for Java 11 local variable syntax. (PR: #3029)
* Add CtTypeInformation#isParameterized method. (PR: #2995)
* Add support for dataflow analysis in new module spoon-dataflow. (PR: #2970)
* LiteralBase: Add literal base. (PR: #3014)
* CtPackage: Add two utility methods #isEmpty() and #hasPackageInfo(). (PR: #2957)
* CtUnresolvedImport: Keep all imports in noClassPath mode. (PR: #2936)
* Fix autoimports for unknown methods in noclasspath. (PR: #3019)
* Fix missing position in rare cases. (PR: #3056)
* Add missing comments in catch. (PR: #3025)
* Fix Problems with javadoc parameters @exception and others. (PR: #3035)
* Fix ClassCastException in getTypeParameterDeclaration. (PR: #3042)
* Fix NPE in canAccess(). (PR: #3032)
* …
=> chore: release 7.5.0

src/main/java/spoon/support/reflect/cu/position/SourcePositionImpl.java, src/test/java/spoon/test/position/PositionTest.java
Test added to spot the issue #3068 (parsing a one-line class may produce incorrect line number).
=> fix(core): Parsing a one-line class may produce incorrect line number #3068

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/test/java/spoon/test/initializers/InitializerTest.java, src/test/resources/noclasspath/initializer/Utf8HttpResponse.java
* Patch proposal
* Unit test for bug reproduction
=> review fix: don't check modifiers when CtVariable#getDeclaringType() returns null #3065

src/main/java/spoon/support/compiler/jdt/ParentExiter.java, src/test/java/spoon/test/type/TypeTest.java, src/test/java/spoon/test/type/testclasses/Foo.java
Hi!
I found out that Spoon returns null type for 2 or more concatenations of string literals.
For example:
`String s = "one" + "two" + "three";`
Spoon says that the type of "two" + "three" is null, but it's actually String.
I provided the test that demonstrates that.
Moreover, I'm sure that the problem is here:
https://github.com/INRIA/spoon/blob/f2ecd5def520d0e8fb5f7c43a8889affd1347aa2/src/main/java/spoon/support/compiler/jdt/ParentExiter.java#L421-L432
We create a new `CtBinaryOperator` but do not set its type.
So I tried to fix that by adding setType call:
`op.setType((CtTypeReference) operator.getFactory().Type().STRING);`
This fix works and type appears, but `AstParentConsistencyChecker` does not like it, because `setType` sets parent of the reference to `op`, so I'm getting:
``` …
```
=> bug: Type of string concatenation is null

pom.xml
It seems that the security notification from github has been dismissed, but as upgrading cost nothing...
=> fix(pom.xml): upgrade jackson-databind version to 2.9.9.3

src/main/java/spoon/experimental/CtUnresolvedImport.java, src/main/java/spoon/reflect/visitor/CtAbstractImportVisitor.java, src/main/java/spoon/reflect/visitor/CtImportVisitor.java, src/main/java/spoon/reflect/visitor/NameScopeImpl.java, src/main/java/spoon/reflect/visitor/TypeNameScope.java, src/test/java/spoon/test/imports/ImportTest.java
The type members names must be visited before Type name itself.
Will be tested by GenericsWithAmbiguousStaticField after #2683 is merged.
=> review2 fix: order of processing LexicalScope elements of Type

src/main/java/spoon/Launcher.java, src/main/java/spoon/compiler/Environment.java, src/main/java/spoon/reflect/declaration/CtElement.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/support/StandardEnvironment.java, src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/main/java/spoon/support/reflect/declaration/CtElementImpl.java, src/test/java/spoon/test/annotation/AnnotationTest.java, src/test/java/spoon/test/api/APITest.java, src/test/java/spoon/test/comment/CommentTest.java, src/test/java/spoon/test/condition/ConditionalTest.java, src/test/java/spoon/test/executable/ExecutableTest.java, src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java, src/test/java/spoon/test/generics/GenericsTest.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/imports/name_scope/NameScopeTest.java, src/test/java/spoon/test/intercession/IntercessionTest.java, src/test/java/spoon/test/interfaces/InterfaceTest.java, src/test/java/spoon/test/lambda/LambdaTest.java, src/test/java/spoon/test/loop/LoopTest.java, src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java, src/test/java/spoon/test/template/TemplateTest.java
`toString` was dependent on the environment config of autoimport, it's again the case.
this is the first PR towards having the builds of client projects passing again.
=> fix: improve backward compatibility of toString

spoon-pom/pom.xml
requires for coveralls to work on JDK 11
=> chore: fix coveralls 

src/main/java/spoon/support/compiler/jdt/ParentExiter.java, src/test/java/spoon/test/loop/LoopTest.java, src/test/java/spoon/test/loop/testclasses/EmptyLoops.java
Hi! I found out that Spoon generates incorrect model for the following code:
```
for (;;)
x = 5;
```
But the model is:
`for (; x = 5; );`
This PR provides corresponding test and possible fix.
=> fix: Incorrect model for empty for loop

src/main/java/spoon/reflect/reference/CtTypeReference.java, src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java, src/main/java/spoon/reflect/visitor/ForceFullyQualifiedProcessor.java, src/main/java/spoon/reflect/visitor/ForceImportProcessor.java, src/main/java/spoon/reflect/visitor/ImportCleaner.java, src/main/java/spoon/reflect/visitor/ImportConflictDetector.java, src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java, src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java, src/main/java/spoon/support/reflect/reference/CtArrayTypeReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtIntersectionTypeReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java, src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java, src/test/java/spoon/test/imports/ImportTest.java, src/test/java/spoon/test/reference/TypeReferenceTest.java
in most cases, `setImplicitParent` meant NOT changing the implicitness of the parent.
=> refactor: rename internal method with particularly confusing name

spoon-decompiler/pom.xml, spoon-decompiler/src/main/java/spoon/JarLauncher.java, spoon-decompiler/src/main/java/spoon/decompiler/FernflowerDecompiler.java, spoon-decompiler/src/main/java/spoon/decompiler/ProcyonDecompiler.java, spoon-decompiler/src/test/java/spoon/JarLauncherTest.java, spoon-decompiler/src/test/java/spoon/decompiler/SpoonClassFileTransformerTest.java
This PR adds support for procyon. It also deprecate fernflower (as it was based on a repackaging of fernflower that was not updated since 2015).
=> feat(ProcyonDecompiler): add support for procyon

src/main/java/spoon/reflect/factory/CodeFactory.java
Hi,
This resolves a bug reported by Sonarqube regarding calling toString() on arrays.
The bug in question: https://rules.sonarsource.com/java/RSPEC-2116
=> fix: Calling toString() on an array

src/main/java/spoon/reflect/cu/position/NoSourcePosition.java, src/main/java/spoon/reflect/factory/CompilationUnitFactory.java, src/main/java/spoon/support/modelobs/SourceFragmentCreator.java, src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
should fix the failing build of juliac
=> refactor: applies the null design pattern to compilation units

src/main/java/spoon/reflect/factory/CodeFactory.java, src/main/java/spoon/reflect/factory/Factory.java, src/main/java/spoon/reflect/factory/FactoryImpl.java, src/test/java/spoon/test/factory/CodeFactoryTest.java
Related to https://github.com/INRIA/spoon/issues/3155 .
createVariableWrite methods were creating CtVariableAccesses as CtVariableRead instead of CtVariableWrite. Replaced it usages with createVariableWrite and createFieldWrite. And added new methods which they are symmetrical implementations of write-access generator methods.
=> fix(CodeFactory): createVariableAssignment now creates a CtVariableWrite

pom.xml
With the recent major overhaul of imports, there are many cases of changed behavior, so we'll release 8.0.0.
=> chore: next release will be 8.0.0
