INRIA/spoon

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
src/test/java/spoon/test/imports/ImportScannerTest.java
src/test/java/spoon/test/imports/testclasses/MultiCatch.java

Fix multicatch import

---

src/main/java/spoon/support/reflect/code/CtStatementImpl.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/test/java/spoon/test/reference/TypeReferenceTest.java
src/test/java/spoon/test/replace/Foo.java
src/test/java/spoon/test/replace/ReplaceTest.java

Fix some bugs encountered in template engine.

Template fixes

---

src/main/java/spoon/reflect/code/CtConstructorCall.java
src/main/java/spoon/reflect/code/CtNewClass.java
src/main/java/spoon/reflect/factory/CoreFactory.java
src/main/java/spoon/reflect/visitor/CtAbstractVisitor.java
src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java
src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/reflect/visitor/CtVisitor.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/DefaultCoreFactory.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/compiler/jdt/ParentExiter.java
src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java
src/main/java/spoon/support/reflect/code/CtNewClassImpl.java
src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
src/main/java/spoon/support/visitor/SignaturePrinter.java
src/test/java/spoon/test/constructorcallnewclass/ConstructorCallTest.java
src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java
src/test/java/spoon/test/constructorcallnewclass/testclasses/Foo.java
src/test/java/spoon/test/executable/ExecutableRefTest.java
src/test/java/spoon/test/generics/Bar.java
src/test/java/spoon/test/generics/Foo.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/initializers/InitializerTest.java
src/test/java/spoon/test/secondaryclasses/ClassesTest.java

Creates a new class `CtConstructorCall` to represent a call of a constructor and keeps `CtNewClass` to represent an anonymous class.

Split CtNewClass in CtConstructorCall and CtNewClass

---

src/main/java/spoon/refactoring/Refactoring.java
src/test/java/spoon/test/refactoring/RefactoringTest.java
src/test/java/spoon/test/refactoring/ThisTransformationProcessor.java
src/test/java/spoon/test/refactoring/testclasses/AClass.java
src/test/java/spoon/test/refactoring/testclasses/AbstractClass.java

When a developer would like rename a class, he must used `Refactoring`
class to change name of the class in all references.
Closes #166

feat: Refactors name of a CtClass.

---

src/main/java/spoon/support/reflect/declaration/CompilationUnitVirtualImpl.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/main/java/spoon/support/util/ByteSerialization.java
src/test/java/spoon/test/serializable/SerializableTest.java

Adding a test case for testing the byte serialization. Additionally, a class for support this serialization and deserialization is provided.
For providing serialization, it was necessary to change the mechanism
for knowing if a parent is a root.

Serialization of CtElements

---

README.md

If you would like to see how it looks, check on my repo : https://github.com/GerardPaligot/spoon

Updates readme to show all activities around spoon

---

src/main/java/spoon/reflect/reference/CtTypeReference.java

Redefine the getDeclaration() method with a more specialized return type.

---

src/main/java/spoon/reflect/factory/ConstructorFactory.java
src/test/java/spoon/test/factory/ConstructorFactoryTest.java

get().add() throws UnsupportedOperationException because the returned collection is non
mutable.

Use addConstructor method instead of get().add()

---

src/main/java/spoon/reflect/factory/ExecutableFactory.java
src/test/java/spoon/test/factory/ExecutableFactoryTest.java

Fix also the corresponding test.

Fix the executable factory: fix mismatch between parameters and actual type arguments.

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/compiler/jdt/ParentExiter.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/annotation/testclasses/AnnotationDefaultAnnotation.java

Cannot be merged before PR https://github.com/INRIA/spoon/pull/206 (commit necessary in this PR, present in this PR too).

fix(annotations): Prints type annotations on fully qualified name

---

src/main/java/spoon/support/reflect/code/CtStatementImpl.java
src/test/java/spoon/test/constructor/ConstructorTest.java
src/test/java/spoon/test/constructor/testclasses/Tacos.java

Throws an exception when we try to insert statement before super invocation.

---

src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/test/java/spoon/test/model/Foo.java
src/test/java/spoon/test/model/TypeTest.java

Throws NPE when inner types are used.

Test and bug fix for CtTypeImpl#getUsedTypes

---

src/main/java/spoon/processing/XMLAnnotationProcessor.java
src/main/java/spoon/reflect/declaration/CtElement.java
src/main/java/spoon/reflect/declaration/CtModifiable.java
src/main/java/spoon/reflect/declaration/CtTypeInformation.java
src/main/java/spoon/reflect/factory/EnumFactory.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/compiler/SnippetCompilationHelper.java
src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java
src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/main/java/spoon/support/template/Parameters.java
src/main/java/spoon/support/util/ByteSerialization.java
src/main/java/spoon/template/ExtensionTemplate.java
src/main/java/spoon/template/TypedBlockTemplateParameter.java
src/test/java/spoon/test/TestUtils.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/methodreference/MethodReferenceTest.java
src/test/java/spoon/test/methodreference/testclasses/Foo.java
src/test/java/spoon/test/visibility/VisibilityTest.java

Remove unused imports.
Improve type checkings.
Remove uneeded casts.

Code cleanup

---

pom.xml
src/main/java/spoon/Launcher.java
src/test/java/spoon/test/main/MainTest.java

fix(usage): Prints usage when there aren't arguments.

---

src/test/java/spoon/test/replace/ReplaceTest.java

test: Improves tests for the replace refactoring to check the parent.

---

src/main/java/spoon/template/BlockTemplate.java
src/main/java/spoon/template/ExpressionTemplate.java
src/main/java/spoon/template/StatementTemplate.java

By construction this is an instance of Template.

Remove unreachable code.

---

src/main/java/spoon/reflect/reference/CtReference.java
src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java
src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java

Removes all deprecated methods from old versions.

---

src/main/java/spoon/reflect/code/CtTargetedExpression.java
src/main/java/spoon/reflect/factory/CodeFactory.java
src/test/java/spoon/test/invocations/InvocationTest.java
src/test/java/spoon/test/invocations/testclasses/Bar.java

Closes previous PR https://github.com/INRIA/spoon/pull/255

Fix NullPointerException in setTarget for calls to static methods

---

src/main/java/spoon/support/gui/SpoonModelTree.java

Hello, this is my first PR in spoon.
I implement a new feature "Expand all" to GUI.
The feature, in SpoonModelTree, expands all child nodes of a selected node recursively.
Thanks for your review.
Regards.

add SpoonModelTree.expandAll

---

src/main/java/spoon/reflect/factory/AnnotationFactory.java
src/test/java/spoon/test/factory/AnnotationFactoryTest.java

Use method addValue since put on an unmodifiable map throws an exception.

Bug fix when adding an annotation.

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/visibility/VisibilityTest.java
src/test/java/spoon/test/visibility/testclasses/Tacos.java

fix(visibility): Variable access in sub classes

---

src/test/java/spoon/reflect/visitor/CtInheritanceScannerTest.java

contract is now:
if a method visitX exists, it must be invoked
if a method scanX exists, it must be invoked
(change: we don't force to write empty visitX and scanX methods for new metamodel elements)
for example, the failure message is now:
visitCtCodeSnippetExpression does not call scanCtExpression

purifies the contract of CtInheritanceScanner, documents it and improves its error message

---

src/main/java/spoon/reflect/code/CtAssignment.java
src/main/java/spoon/reflect/code/CtLocalVariable.java
src/main/java/spoon/reflect/code/CtRHSReceiver.java
src/main/java/spoon/reflect/declaration/CtField.java
src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java
src/main/java/spoon/support/reflect/code/CtLocalVariableImpl.java
src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java
src/main/java/spoon/support/reflect/declaration/CtParameterImpl.java
src/test/java/spoon/test/TestUtils.java
src/test/java/spoon/test/fieldaccesses/BCUBug20140402.java
src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java
src/test/java/spoon/test/parent/ParentContractTest.java
src/test/java/spoon/test/variable/AccessTest.java
src/test/java/spoon/test/variable/testclasses/RHSSample.java
src/test/java/spoon/test/variable/testclasses/StackedAssignmentSample.java

This new element is useful for easily writing transformations on all assignment-like elements

introduces CtRHSReceiver to factorize all assignment-like elements

---

src/main/java/spoon/processing/XMLAnnotationProcessor.java
src/main/java/spoon/support/reflect/code/CtStatementImpl.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java

By construction, the tested variables are of the tested types.

Remove unnecessary tests.

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/TestUtils.java
src/test/java/spoon/test/lambda/LambdaTest.java
src/test/java/spoon/test/lambda/testclasses/JavaFx.java

fix(lambda): Generates right types for parameters in a lambda.

---

src/main/java/spoon/support/StandardEnvironment.java
src/test/java/spoon/test/properties/PropertiesTest.java
src/test/java/spoon/test/properties/Sample.java
src/test/java/spoon/test/properties/SimpleProcessor.java

getXmlRootFolder().listFiles() can return null
which will cause an NPE in the for loop

Fix NPE with properties directory is empty

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/main/MainTest.java
src/test/java/spoon/test/variable/AccessFullyQualifiedFieldTest.java
src/test/java/spoon/test/variable/AccessTest.java
src/test/java/spoon/test/variable/testclasses/Tacos.java
src/test/resources/spoon/test/variable/Tacos.java

fix(access): Handles ProblemBinding for variable accesses.

---

src/main/java/spoon/SpoonTask.java

Updates the Ant Task with two new features that are in the Launcher: with-imports and no-classpath.

Added imports and noclasspath to Ant Task

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java

- Made some minor modifications to remove some warnings in the code
as flagged by the IDE.

Minor code corrections.

---

src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java
src/test/java/spoon/test/api/APITest.java
src/test/java/spoon/test/api/NoClasspathTest.java
src/test/java/spoon/test/main/MainTest.java
src/test/java/spoon/test/refactoring/RefactoringTest.java
src/test/java/spoon/test/staticFieldAccess/StaticAccessTest.java
src/test/java/spoon/test/trycatch/TryCatchTest.java
src/test/java/spoon/test/variable/AccessTest.java
src/test/java/spoon/test/visibility/VisibilityTest.java

Before, spoon create some directory during test in the root directory.
Now, all test directory are generated in the maven build directory : "target"

Generate all test files in target directory

---

src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java

feat: Prints always an element with its toString method.

---

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
src/test/java/spoon/test/imports/ImportTest.java
src/test/java/spoon/test/imports/testclasses/internal/ChildClass.java

fix: Prints only imports used in classes in with-imports mode.

---

src/main/java/spoon/Launcher.java
src/main/java/spoon/SpoonAPI.java
src/main/java/spoon/SpoonModelBuilder.java
src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/test/java/spoon/test/api/APITest.java
src/test/java/spoon/test/api/AwesomeProcessor.java

feat: Adds addProcessor(Processor) method in SpoonAPI.

---

src/main/java/spoon/reflect/declaration/CtElement.java
src/main/java/spoon/reflect/factory/PackageFactory.java
src/main/java/spoon/reflect/path/CtPath.java
src/main/java/spoon/reflect/path/CtPathBuilder.java
src/main/java/spoon/reflect/path/CtPathException.java
src/main/java/spoon/reflect/path/CtPathRole.java
src/main/java/spoon/reflect/path/CtPathStringBuilder.java
src/main/java/spoon/reflect/path/impl/AbstractPathElement.java
src/main/java/spoon/reflect/path/impl/CtNamedPathElement.java
src/main/java/spoon/reflect/path/impl/CtPathElement.java
src/main/java/spoon/reflect/path/impl/CtPathImpl.java
src/main/java/spoon/reflect/path/impl/CtRolePathElement.java
src/main/java/spoon/reflect/path/impl/CtTypedNameElement.java
src/main/java/spoon/support/DefaultCoreFactory.java
src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java
src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/test/java/spoon/test/path/Foo.java
src/test/java/spoon/test/path/PathTest.java

Create a new API to select easily some nodes in the Spoon AST.

start new CtPath Api

---

src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java

This PR should be merge quickly. The master is broken!

fix: Creates a class without a parent in the failing test case.

---

src/main/java/spoon/processing/AbstractAnnotationProcessor.java
src/main/java/spoon/reflect/visitor/TypeAnnotationVisitor.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/annotation/testclasses/ClassProcessed.java
src/test/java/spoon/test/annotation/testclasses/GlobalAnnotation.java

annotation processor includes Java 8 annotations.

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/methodreference/MethodReferenceTest.java
src/test/java/spoon/test/parent/Foo.java
src/test/java/spoon/test/parent/NullParentTest.java
src/test/java/spoon/test/parent/ParentTest.java
src/test/java/spoon/test/replace/ReplaceTest.java
src/test/resources/executable-reference-expression/Bar.java

Adds noclasspath mode for CtExecutableReferenceExpression

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/imports/ImportTest.java
src/test/resources/import-static/Tacos.java
src/test/resources/spoon/test/noclasspath/Foo.java

fix(noclasspath): handles invocations in noclasspath mode.

---

src/test/java/spoon/test/intercession/UnsupportedOperationTest.java

test: Check defaultExpression of CtCatchVariable and CtParameter.

---

src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java
src/test/java/spoon/test/fieldaccesses/MyClass.java

test: Field access in lambda doesn't throw an NPE.

---

src/main/java/spoon/support/QueueProcessingManager.java
src/test/java/spoon/test/processing/ProcessingTest.java

feat: Throws a SpoonException when the processor is not found.

---

src/main/java/spoon/support/visitor/SignaturePrinter.java
src/test/java/spoon/test/reference/TypeReferenceTest.java

test: Check the equality between two type references.

---

pom.xml
src/main/java/spoon/reflect/code/CtInvocation.java
src/test/java/spoon/test/casts/CastTest.java
src/test/java/spoon/test/casts/Castings.java

Updates JDT and fix a casting bug from JDT

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/enums/EnumsTest.java
src/test/java/spoon/test/enums/testclasses/Burritos.java

fix: Writes always ";" in an enum for their fields.

---

src/main/java/spoon/reflect/factory/CoreFactory.java
src/main/java/spoon/reflect/factory/InternalFactory.java
src/main/java/spoon/reflect/internal/CtImplicitArrayTypeReference.java
src/main/java/spoon/reflect/internal/CtImplicitTypeReference.java
src/main/java/spoon/reflect/visitor/CtAbstractVisitor.java
src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java
src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/reflect/visitor/CtVisitor.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
src/main/java/spoon/support/DefaultCoreFactory.java
src/main/java/spoon/support/DefaultInternalFactory.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
src/main/java/spoon/support/reflect/internal/CtImplicitArrayTypeReferenceImpl.java
src/main/java/spoon/support/reflect/internal/CtImplicitTypeReferenceImpl.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/main/java/spoon/support/visitor/SignaturePrinter.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/constructorcallnewclass/ConstructorCallTest.java
src/test/java/spoon/test/constructorcallnewclass/testclasses/Panini.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/lambda/LambdaTest.java
src/test/java/spoon/test/lambda/testclasses/Bar.java
src/test/java/spoon/test/lambda/testclasses/Panini.java
src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java

Thing to merge before https://github.com/INRIA/spoon/pull/378
Issue #368

Fix implicit array in diamond operator and lambda parameter.

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/generics/testclasses/Panini.java

fix: CtTypeParameterReference doesn't print always full generic.

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/lambda/LambdaTest.java
src/test/java/spoon/test/lambda/testclasses/Tacos.java

Fix bug introduced by https://github.com/INRIA/spoon/pull/379 about primitive types.

fix(lambda): Creates implicit type for primitive types.

---

README.md
appveyor.yml
checkstyle.xml
pom.xml
src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java

test(windows): Fixes a test case on Windows.

---

CONTRIBUTING.md
doc/_release/Checklist.md
doc/faq.md

Updates Checklist file to explain how to maintain the stable branch
and updates CONTRIBUTING file to explain at the community how to
create a pull request which contains a bug fix of the current
release.
Closes #203

doc(release): Explains how to maintain the stable branch.

---

.travis.yml
README.md
pom.xml
src/test/java/spoon/test/reference/TypeReferenceTest.java

- Adds coveralls in the project with a badge and a build status in the bottom of each PR.
- Adds a maven cache in Travis.  [This is recommended by Travis](http://docs.travis-ci.com/user/caching/#Things-not-to-cache).
- Adds a badge to show easily the last version of Spoon on Maven Central.

Improves build process of the project

---

src/main/java/spoon/template/TemplateMatcher.java
src/test/java/spoon/test/template/CheckBound.java
src/test/java/spoon/test/template/CheckBoundMatcher.java
src/test/java/spoon/test/template/TemplateTest.java

TemplateMatcher is an old and great feature of Spoon, that needed to be cleaned and tested. This is the beginning, see test case.

first revival of TemplateMatcher

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/variable/AccessTest.java
src/test/resources/variable/PropPanelUseCase_1.40.java

fix(access): Supports field access in no classpath mode.

---

src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java
src/main/java/spoon/support/reflect/code/CtInvocationImpl.java

fix(api): Delegates type to the executable.

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java
src/test/java/spoon/test/literal/LiteralTest.java
src/test/resources/noclasspath/SecondaryIndexManager.java

fix(noclasspath): Computes char value of literals in noclasspath.

---

src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/reflect/visitor/CtStackScanner.java
src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
src/main/java/spoon/reflect/visitor/ModelConsistencyChecker.java
src/main/java/spoon/support/DefaultCoreFactory.java
src/main/java/spoon/support/SerializationModelStreamer.java
src/main/java/spoon/support/gui/SpoonTreeBuilder.java
src/main/java/spoon/support/template/SubstitutionVisitor.java
src/main/java/spoon/support/visitor/TypeReferenceScanner.java

fix(scanner): Changes all enter/exitReferences inv to enter/exit.

---

src/main/java/spoon/support/template/DefaultParameterMatcher.java
src/main/java/spoon/support/template/ParameterMatcher.java
src/test/java/spoon/test/template/CheckBound.java
src/test/java/spoon/test/template/CheckBoundMatcher.java
src/test/java/spoon/test/template/TemplateTest.java

everything works now, incredible!
a side-effect on the recent work on references?

adds new tests for TemplateMatcher

---

src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java
src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/reflect/visitor/CtVisitor.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
src/main/java/spoon/support/DefaultCoreFactory.java
src/main/java/spoon/support/compiler/jdt/ParentExiter.java
src/main/java/spoon/support/reflect/code/CtAnnotationFieldAccessImpl.java
src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
src/main/java/spoon/support/template/SubstitutionVisitor.java
src/main/java/spoon/support/visitor/SignaturePrinter.java
src/main/java/spoon/support/visitor/TypeReferenceScanner.java
src/test/java/spoon/reflect/visitor/CtInheritanceScannerMethodsTest.java
src/test/java/spoon/reflect/visitor/CtInheritanceScannerTest.java
src/test/java/spoon/reflect/visitor/CtVisitorTest.java
src/test/java/spoon/reflect/visitor/processors/CheckModelProcessor.java
src/test/java/spoon/reflect/visitor/processors/CheckVisitorProcessor.java

test(scanner): Check scan and visit methods in CtInheritanceScanner.

---

src/main/java/spoon/reflect/declaration/CtType.java
src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/test/java/spoon/test/field/FieldTest.java

feat(field): Adds a field at a position given.

---

src/main/java/spoon/reflect/visitor/CtScanner.java
src/test/java/spoon/reflect/visitor/CtScannerTest.java
src/test/java/spoon/reflect/visitor/processors/CheckScannerProcessor.java
src/test/java/spoon/test/main/MainTest.java

test(scanner): specify the contract of CtScanner.

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/type/TypeTest.java
src/test/java/spoon/test/type/testclasses/Pozole.java

In conflict with https://github.com/INRIA/spoon/pull/470, please merge this one first.

fix(type): Uses CtTypeAcces for type array.

---

src/main/java/spoon/reflect/code/CtTypeAccess.java
src/main/java/spoon/reflect/factory/CodeFactory.java
src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/reflect/code/CtTypeAccessImpl.java
src/main/java/spoon/support/visitor/SignaturePrinter.java
src/test/java/spoon/test/parent/ParentContractTest.java

doc(type): Adds documentation on getType in CtTypeAccess.

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/type/TypeTest.java
src/test/java/spoon/test/type/testclasses/Pozole.java

Fixes test case MainTest#testTest in IDE.
Closes #425

feat(type): Partial support of type intersection.

---

src/main/java/spoon/reflect/code/CtArrayRead.java
src/main/java/spoon/reflect/code/CtArrayWrite.java
src/main/java/spoon/reflect/code/CtFieldRead.java
src/main/java/spoon/reflect/code/CtFieldWrite.java
src/main/java/spoon/reflect/code/CtVariableAccess.java
src/main/java/spoon/reflect/code/CtVariableWrite.java
src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java
src/test/java/spoon/test/fieldaccesses/testclasses/Panini.java

test(field): Specify what is a field++ and ++field.

---

CONTRIBUTING.md

"The pull request contains a single bug fix or a single feature."

adds a missing pull request guideline

---

src/main/java/spoon/reflect/code/CtArrayWrite.java
src/main/java/spoon/reflect/code/CtFieldWrite.java
src/main/java/spoon/reflect/code/CtVariableWrite.java
src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java
src/test/java/spoon/test/fieldaccesses/testclasses/Panini.java

test(access): Specify var += value for Array/Field/VarWrite.

---

src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java
src/main/java/spoon/support/reflect/cu/SourcePositionImpl.java
src/test/java/spoon/test/serializable/Dummy.java
src/test/java/spoon/test/serializable/SerializableTest.java

my fix to serialization problem with simple testcases

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java
src/test/java/spoon/test/reference/TypeReferenceTest.java
src/test/resources/noclasspath/Demo2.java

fix(noclasspath): Creates type reference from string and JDT ref.

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/variable/AccessTest.java

fix: Rwrite i++.toString() to (i++).toString().

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/reference/TypeReferenceTest.java
src/test/resources/noclasspath/Demo3.java

fix(noclasspath): Arguments of an inv should be a CtFieldRead.

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/reference/TypeReferenceTest.java
src/test/resources/noclasspath/Demo4.java
src/test/resources/noclasspath/TestBot.java

fix(noclasspath): FieldAccess in an invocation.

---

src/main/java/spoon/reflect/declaration/CtElement.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/main/java/spoon/support/template/SubstitutionVisitor.java
src/test/java/spoon/test/template/Logger.java
src/test/java/spoon/test/template/LoggerTemplate.java
src/test/java/spoon/test/template/LoggerTemplateProcessor.java
src/test/java/spoon/test/template/TemplateTest.java

Fixes BlockTemplate and adds replace in CtElement

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/javadoc/JavaDocTest.java
src/test/java/spoon/test/javadoc/testclasses/Bar.java
src/test/java/spoon/test/pkg/PackageTest.java

This PR fix two issues:
* it handles tab indentation
* it fixes the indentation of the documented elements

Improove the JavaDoc support

---

doc/faq.md
src/main/java/spoon/SpoonModelBuilder.java
src/main/java/spoon/compiler/builder/AdvancedOptions.java
src/main/java/spoon/compiler/builder/AnnotationProcessingOptions.java
src/main/java/spoon/compiler/builder/ClasspathOptions.java
src/main/java/spoon/compiler/builder/ComplianceOptions.java
src/main/java/spoon/compiler/builder/JDTBuilder.java
src/main/java/spoon/compiler/builder/JDTBuilderImpl.java
src/main/java/spoon/compiler/builder/Options.java
src/main/java/spoon/compiler/builder/SourceOptions.java
src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/main/java/spoon/support/compiler/jdt/JDTSnippetCompiler.java
src/test/java/spoon/support/compiler/classpath/ComputeClasspathTest.java
src/test/java/spoon/support/compiler/jdt/JDTBuilderTest.java

feat(compiler): Allows developers to specify their parameters.

---

.travis.yml

I don't know why but this modification fixes travis builds.

Fixes travis builds.

---

pom.xml

chore(license): Updates configuration of license-maven-plugin.

---

src/main/java/spoon/reflect/declaration/CtEnum.java
src/main/java/spoon/reflect/declaration/CtEnumValue.java
src/main/java/spoon/reflect/factory/CoreFactory.java
src/main/java/spoon/reflect/visitor/CtAbstractVisitor.java
src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java
src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/reflect/visitor/CtVisitor.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/DefaultCoreFactory.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/compiler/jdt/ParentExiter.java
src/main/java/spoon/support/reflect/declaration/CtEnumImpl.java
src/main/java/spoon/support/reflect/declaration/CtEnumValueImpl.java
src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
src/main/java/spoon/support/visitor/SignaturePrinter.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/enums/EnumsTest.java

refactor(enum): Uses CtEnumValue for field values.

---

.travis.yml
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/ctClass/CtClassTest.java
src/test/java/spoon/test/ctClass/testclasses/Pozole.java

Note: This PR is done on the stable branch.

fix(local): Shouldn't start the name of a local type with its id.

---

.travis.yml
src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java
src/test/java/spoon/test/factory/FactoryTest.java
src/test/java/spoon/test/factory/testclasses/Foo.java

Closes #523
Note: This PR is done on the stable branch.

fix(annotation): Uses CtFieldRead for class access in annotations.

---

src/main/java/spoon/reflect/declaration/CtElement.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/ctElement/MetadataTest.java
src/test/java/spoon/test/ctElement/testclasses/Returner.java
src/test/java/spoon/test/intercession/IntercessionTest.java

Uses an Internal HashMap inside CtElement to store objects as metadata slots.

Added Metadata slots. Fixes #422.

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/test/java/spoon/test/annotation/AnnotationTest.java

feat(type): Exclude annotations in fully qualified name of types.

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/generics/testclasses/Tacos.java

fix(constructor): Generics in declaring types of a constructor call.

---

.travis.yml
pom.xml

- Travis doesn't fail with coveralls.
- Check checkstyle at the start of the project in travis.
- Check license on files at the start of the project in travis.
Closes #539

fix(travis): Improve Travis and project configuration.

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/reference/TypeReferenceTest.java
src/test/resources/noclasspath/Demo5.java

fix(noclasspath): NPE in a scope usage.

---

src/main/java/spoon/support/reflect/declaration/CtElementImpl.java

In my application this single line change reduced run time by 45%.

Optimize CtElement.equals()

---

src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java
src/test/java/spoon/test/executable/ExecutableRefTest.java
src/test/java/spoon/test/executable/testclasses/Pozole.java

fix(performance): Rewrite CtExecutableReference#isOverriding.

---

src/main/java/spoon/reflect/reference/CtTypeParameterReference.java
src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java
src/test/java/spoon/test/reference/TypeReferenceTest.java

refactor(api): Handles null and empty list for setBounds(List).

---

src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/test/java/spoon/test/type/TypeTest.java

fix(unbox): Don't throw a SCNFException with #unbox().

---

src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/parent/ParentTest.java

fix(getparent): getParent(Filter) does not return the current element when it matches the filter

---

src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java
src/test/java/spoon/test/reference/TypeReferenceTest.java

Throws a SpoonException when we set ? in CtTypeRef.

---

ROADMAP.md

chore(roadmap): Adds task about generics in the roadmap.

---

src/main/java/spoon/reflect/code/CtTargetedExpression.java

doc(target): Specify behavior of CtTargetedExpression#getTarget.

---

appveyor.yml
set-maven-proxy.ps1

Should fix AppVeyor: http://help.appveyor.com/discussions/problems/4567-dependencies-could-not-be-resolved

chore(appveyor): Adds a proxy to download dependency.

---

src/main/java/spoon/reflect/declaration/CtTypeInformation.java
src/test/java/spoon/test/reference/ExecutableReferenceTest.java
src/test/java/spoon/test/reference/testclasses/Bar.java
src/test/java/spoon/test/reference/testclasses/Foo.java
src/test/java/spoon/test/reference/testclasses/Kuu.java
src/test/java/spoon/test/reference/testclasses/SuperFoo.java

doc(executable): Specify executable returns by getAllExecutables.

---

src/main/java/spoon/reflect/factory/TypeFactory.java
src/main/java/spoon/reflect/reference/CtIntersectionTypeReference.java
src/main/java/spoon/support/reflect/reference/CtIntersectionTypeReferenceImpl.java
src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java
src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java
src/test/java/spoon/test/constructor/ConstructorTest.java
src/test/java/spoon/test/type/TypeTest.java

refactor(api): Changes bounds from List to Set.

---

src/main/java/spoon/support/reflect/declaration/CtAnnotationTypeImpl.java
src/main/java/spoon/support/visitor/SignaturePrinter.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/main/MainTest.java
src/test/java/spoon/test/reference/AnnotationFieldReferenceTest.java
src/test/java/spoon/test/reference/testclasses/Mole.java
src/test/java/spoon/test/reference/testclasses/Parameter.java

feat(annot): Reference of an annotation field invocation.

---

src/main/java/spoon/reflect/factory/ExecutableFactory.java
src/test/java/spoon/test/lambda/LambdaTest.java
src/test/java/spoon/test/lambda/testclasses/Kuu.java

fix(lambda): Builds executable ref from a lambda.

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/condition/ConditionalTest.java
src/test/java/spoon/test/condition/testclasses/Foo.java

fix(conditional): Puts parenthesis when it is necessary.

---

src/main/java/spoon/reflect/factory/TypeFactory.java
src/main/java/spoon/testing/utils/ModelUtils.java
src/test/java/spoon/test/factory/TypeFactoryTest.java
src/test/java/spoon/test/factory/testclasses3/Cooking.java
src/test/java/spoon/test/factory/testclasses3/Prepare.java

fix(factory): Gets inner type from Class/InterfaceFactory.

---

doc/command_line.md
src/main/java/spoon/Launcher.java
src/main/java/spoon/compiler/Environment.java
src/main/java/spoon/support/StandardEnvironment.java
src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java

feat(checks): Disable AST checks.

---

src/main/java/spoon/reflect/visitor/CtAbstractBiScanner.java
src/main/java/spoon/reflect/visitor/CtDequeScanner.java
src/main/java/spoon/reflect/visitor/CtStackScanner.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/ModelConsistencyChecker.java
src/main/java/spoon/support/DefaultCoreFactory.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/gui/SpoonTreeBuilder.java
src/main/java/spoon/support/util/Timer.java
src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
src/test/java/spoon/test/parent/ParentTest.java

feat: Switch all usages of Stack to Deque.

---

pom.xml

hotfix(jdt): Updates remote repository to download JDT.

---

src/main/java/spoon/generating/CloneVisitorGenerator.java
src/main/java/spoon/generating/clone/CloneBuilderTemplate.java
src/main/java/spoon/generating/clone/CloneVisitorTemplate.java
src/main/java/spoon/generating/clone/GetterTemplateMatcher.java
src/main/java/spoon/generating/clone/SetterTemplateMatcher.java
src/main/java/spoon/reflect/factory/CoreFactory.java
src/main/java/spoon/reflect/factory/PackageFactory.java
src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java
src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java
src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/support/DefaultCoreFactory.java
src/main/java/spoon/support/reflect/code/CtLambdaImpl.java
src/main/java/spoon/support/reflect/declaration/CtAnnotationTypeImpl.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java
src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/main/java/spoon/support/visitor/EqualVisitor.java
src/main/java/spoon/support/visitor/clone/CloneBuilder.java
src/main/java/spoon/support/visitor/clone/CloneVisitor.java
src/main/java/spoon/support/visitor/equals/CloneHelper.java
src/main/java/spoon/support/visitor/equals/EqualsVisitor.java
src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java
src/test/java/spoon/reflect/visitor/CtScannerTest.java
src/test/java/spoon/test/main/MainTest.java

refactor(clone): Creates CloneVisitor and CloneBuilder.

---

src/main/java/spoon/reflect/factory/FieldFactory.java
src/test/java/spoon/test/main/MainTest.java

fix(clone): Clone type when create a field reference.

---

src/main/java/spoon/reflect/factory/ExecutableFactory.java
src/test/java/spoon/test/reference/VariableAccessTest.java
src/test/resources/noclasspath/Foo3.java

fix(reference): Declaring type of a executable reference of a lambda.

---

src/main/java/spoon/reflect/factory/EnumFactory.java
src/main/java/spoon/reflect/factory/InterfaceFactory.java
src/test/java/spoon/test/type/TypeTest.java

fix(factory): Gets declaration from element created by factory.

---

src/main/java/spoon/reflect/factory/ExecutableFactory.java
src/test/java/spoon/test/reference/ExecutableReferenceTest.java
src/test/resources/noclasspath/Foo4.java

fix(reference): Allow creation of a reference from CtAnonymousExecutable.

---

src/main/java/spoon/reflect/cu/CompilationUnit.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/PrettyPrinter.java
src/main/java/spoon/support/JavaOutputProcessor.java
src/main/java/spoon/support/compiler/jdt/ContextBuilder.java
src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java
src/test/java/spoon/test/api/APITest.java
src/test/java/spoon/test/comparison/EqualTest.java
src/test/java/spoon/test/pkg/PackageTest.java
src/test/java/spoon/test/pkg/testclasses/internal/package-info.java

fix(package): Handle packages with only one file, a package-info.java.

---

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java

feat(log): Hide logs from JDT if log level is set to OFF.

---

src/main/java/spoon/reflect/declaration/CtAnnotationMethod.java
src/main/java/spoon/reflect/factory/AnnotationFactory.java
src/main/java/spoon/reflect/factory/CoreFactory.java
src/main/java/spoon/reflect/visitor/CtAbstractVisitor.java
src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java
src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java
src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/reflect/visitor/CtVisitor.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/DefaultCoreFactory.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/compiler/jdt/ParentExiter.java
src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java
src/main/java/spoon/support/reflect/declaration/CtAnnotationMethodImpl.java
src/main/java/spoon/support/reflect/declaration/CtAnnotationTypeImpl.java
src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
src/main/java/spoon/support/visitor/EqualVisitor.java
src/main/java/spoon/support/visitor/ShortRepresentationPrinter.java
src/main/java/spoon/support/visitor/clone/CloneBuilder.java
src/main/java/spoon/support/visitor/clone/CloneVisitor.java
src/main/java/spoon/support/visitor/equals/EqualsVisitor.java
src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java
src/test/java/spoon/reflect/ast/IntercessionScanner.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/annotation/testclasses/SuperAnnotation.java
src/test/java/spoon/test/reference/AnnotationFieldReferenceTest.java

Question: Maybe we should create new methods in `CtAnnotationType` to get methods typed by `CtAnnotationMethod`?

feat(annotation): Supports annotation method declaration.

---

src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java
src/main/java/spoon/support/reflect/code/CtInvocationImpl.java
src/main/java/spoon/support/reflect/code/CtStatementImpl.java
src/main/java/spoon/support/reflect/code/CtUnaryOperatorImpl.java
src/test/java/spoon/test/replace/ReplaceTest.java
src/test/java/spoon/test/replace/testclasses/Mole.java

fix(replace): Use generic replace with CtStatementList elements.

---

src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/test/java/spoon/test/model/TypeTest.java

fix: Used types in a snippet statement.

---

src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/main/java/spoon/support/visitor/DeepRepresentationVisitor.java

refactor(visitor): Rename EqualVisitor to DeepRepresentationVisitor.

---

src/main/java/spoon/reflect/code/CtConstructorCall.java
src/main/java/spoon/reflect/code/CtInvocation.java
src/main/java/spoon/reflect/code/CtNewClass.java

docs(type): Informs that some classes delegate the actual types to CtExecutableRef

---

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
src/test/java/spoon/test/type/TypeTest.java
src/test/resources/noclasspath/ternary-bug/data/IssueType.java
src/test/resources/noclasspath/ternary-bug/data/entities/Issue.java
src/test/resources/noclasspath/ternary-bug/transformators/IssueTransformator.java

fix(type): Creates an Object type for PolyTypeBinding.

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java
src/test/java/spoon/test/fieldaccesses/testclasses/A.java
src/test/java/spoon/test/fieldaccesses/testclasses/B.java

fix(fieldaccess): static field access in anonymous executable

---

src/main/java/spoon/reflect/CtModelImpl.java
src/test/java/spoon/test/factory/FactoryTest.java

fix and specifies CtModel.processWith()

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java
src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
src/main/java/spoon/support/compiler/jdt/ParentExiter.java
src/main/java/spoon/support/reflect/code/CtBlockImpl.java
src/main/java/spoon/support/reflect/code/CtStatementImpl.java
src/main/java/spoon/template/TemplateMatcher.java
src/test/java/spoon/test/condition/ConditionalTest.java
src/test/java/spoon/test/condition/testclasses/Foo.java
src/test/java/spoon/test/control/ControlTest.java
src/test/java/spoon/test/intercession/IntercessionTest.java
src/test/java/spoon/test/intercession/insertBefore/InsertMethodsTest.java

refactor(ast): Uses block for CtIf and CtLoop.

---

src/main/java/spoon/reflect/code/CtConstructorCall.java
src/main/java/spoon/reflect/code/CtInvocation.java
src/main/java/spoon/reflect/code/CtNewClass.java
src/main/java/spoon/reflect/reference/CtActualTypeContainer.java
src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java
src/main/java/spoon/support/reflect/code/CtInvocationImpl.java
src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java
src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/test/java/spoon/test/reference/TypeReferenceTest.java

refactor(ast): Improves generic parameter type of setActualTypeReferences.

---

src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java
src/main/java/spoon/template/TemplateMatcher.java

refactor: Removes all useless conditions with CtReference.

---

src/main/java/spoon/reflect/factory/TypeFactory.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/test/java/spoon/test/reference/TypeReferenceTest.java

fix(npe): Handles null parameter Type#createReference(Class).

---

src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/test/java/spoon/test/method/MethodTest.java

fix(method): Avoid Concurrent modification with CtType#addMethod.

---

pom.xml

chore(pom): Updates commons-io from 1.3.2 to 1.4.

---

src/main/java/spoon/reflect/cu/SourcePosition.java
src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java
src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java
src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
src/main/java/spoon/support/reflect/cu/SourcePositionImpl.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/support/compiler/jdt/JDTBatchCompilerTest.java
src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/pkg/PackageTest.java
src/test/java/spoon/test/position/PositionTest.java
src/test/java/spoon/test/position/testclasses/FooClazz2.java

It much simplifies client code (no more not-null checks)

No more null source positions

---

src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/test/java/spoon/test/method/MethodTest.java
src/test/resources/noclasspath/A3.java

fix: getAllMethods in noclasspath return when encounter an unknown class

---

src/main/java/spoon/support/reflect/reference/CtLocalVariableReferenceImpl.java
src/test/java/spoon/test/reference/VariableAccessTest.java
src/test/resources/reference-test/ChangeScanner.java
src/test/resources/reference-test/MultipleDeclarationsOfLocalVariable.java

This should handle all kinds of elements, such as loops, lambdas and so on. Fixes #868.

getDeclaration of CtLocalVariable 

---

src/main/java/spoon/support/compiler/jdt/CompilationUnitWrapper.java
src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java
src/test/java/spoon/support/compiler/jdt/JDTBatchCompilerTest.java
src/test/java/spoon/test/compilation/CompilationTest.java
src/test/resources/noclasspath/Simple.java

fix(compilation): always uses the content of the ast to compile the ast

---

src/main/java/spoon/support/QueueProcessingManager.java
src/test/java/spoon/test/processing/ProcessingTest.java

manager propagate exception inside a SpoonException

---

src/main/java/spoon/support/compiler/FileSystemFolder.java
src/main/java/spoon/support/compiler/FilteringFolder.java
src/main/java/spoon/support/compiler/VirtualFolder.java
src/test/java/spoon/LauncherTest.java
src/test/java/spoon/processing/ProcessingTest.java
src/test/java/spoon/test/support/ResourceTest.java

support for filtering out input java files

---

src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java

It always fails with exception instead of writing log.
It looks like it is not intentional to fail there. I would also prefer to write log instead of exception

fix bug in writing of log error.

---

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java

Hi Martin,
do you like PR like this too? It just simplifies the code. No change in behavior.
Best regards
Pavel

simplify code of JDTCommentBuilder - same behavior

---

src/test/java/spoon/test/comment/CommentTest.java

Hi Martin, is it OK for you, if I produce PRs like this, or should I change configuration of my workspace to ignore unused code in tests.
Thanks ;-)

fix unused imports

---

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/main/java/spoon/support/compiler/jdt/JDTSnippetCompiler.java

The 3 model building functions were merged into one.

refactor: same algorithm for building of sources, templates and snippet

---

src/main/java/spoon/reflect/CtModel.java
src/main/java/spoon/reflect/CtModelImpl.java
src/main/java/spoon/reflect/factory/FactoryImpl.java
src/main/java/spoon/support/SerializationModelStreamer.java
src/test/java/spoon/test/serializable/SerializableTest.java

SerializationModelStreamer does not work

---

src/main/java/spoon/reflect/declaration/CtElement.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java

a better solution than #961 IMHO

fix(parent): stops furious useless exceptions

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/comment/testclasses/package-info.java

I tried spooning of guava with comments enabled and the result had compilation errors. Here is the fix,

fix comments in package-info.java

---

src/main/java/spoon/reflect/eval/PartialEvaluator.java
src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java
src/main/java/spoon/support/reflect/declaration/CtClassImpl.java
src/main/java/spoon/support/reflect/eval/InlinePartialEvaluator.java
src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
src/test/java/spoon/test/eval/EvalTest.java
src/test/java/spoon/test/eval/Foo.java

feature(evaluation): can simplify whole classes based on static evaluation (first support)

---

src/main/java/spoon/support/compiler/jdt/ContextBuilder.java
src/test/java/spoon/test/position/PositionTest.java
src/test/java/spoon/test/position/testclasses/Foo.java

fix(position): implicit elements do not have position

---

src/main/java/spoon/reflect/factory/ExecutableFactory.java
src/main/java/spoon/support/compiler/jdt/ParentExiter.java
src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
src/test/java/spoon/test/reference/TypeReferenceTest.java
src/test/java/spoon/test/reference/testclasses/ParamRefs.java

Fix #1094
Small PR to begin the week

fix(reference): fix reference ctconstructor

---

src/main/java/spoon/reflect/visitor/chain/CtConsumableFunction.java
src/main/java/spoon/reflect/visitor/chain/CtQuery.java

doc: Fix javadoc respecting JDK8 rules for the last PR.

---

doc/_data/sidebar_doc.yml

doc: fixes broken menu (closes #1121)

---

doc/doc_homepage.md

doc: add links to changelogs (closes #1083)

---

chore/revapy.py

chore:only publish revapi report if the PR is edited or opened.

---

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
src/test/java/spoon/test/imports/ImportScannerTest.java
src/test/java/spoon/test/imports/testclasses2/ImportSameName.java
src/test/java/spoon/test/imports/testclasses2/toto/ImportSameName.java

Should fix the broken jobs on Jenkins CI.

review: fix bugs related to import mechanism

---

doc/_includes/footer.html
doc/about.md
doc/code_elements.md
doc/code_elements_header.md
doc/command_line.md
doc/comments.md
doc/examples.md
doc/factories.md
doc/faq.md
doc/filter.md
doc/first_analysis_processor.md
doc/first_transformation.md
doc/gradle.md
doc/matcher.md
doc/maven.md
doc/papers.md
doc/path.md
doc/processor.md
doc/processor_annotations.md
doc/references.md
doc/structural_elements.md
doc/testing_assertions.md
doc/testing_quickstart.md

chore: Remove last updated information on pages.

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java

feature: automatic explicit ThisAccess for fields

---

src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/ctElement/MetadataTest.java

review: fix NPE with CtElement#getMetadataKeys (fix #1239)

---

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/test/java/spoon/test/compilation/CompilationTest.java

This PR is really similar to https://github.com/INRIA/spoon/pull/1208 and is proposed to fix https://github.com/INRIA/spoon/issues/1246

review: consider the sources when calling compile in JDTBasedSpoonCompiler

---

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
src/test/java/spoon/test/imports/ImportTest.java
src/test/resources/import-resources/fr/inria/AnotherMissingImport.java

review: Fix a bug related to method signature of invocation when noclasspath and generics

---

src/test/java/spoon/test/SpoonTestHelpers.java

fix of bug in tests found by PR #1218

fix SpoonTestHelpers#getAllSetters not returning #setParent

---

pom.xml
revapi.json

Solution from https://github.com/revapi/revapi/issues/78
Close #1229

chore: revapi check should fail only for breaking changes

---

doc/doc_homepage.md

doc: fix link mix

---

doc/examples.md

First commit is to fix #1185 but to finish it properly we should also do #1184

review: Update examples links

---

src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/prettyprinter/LinesTest.java
src/test/java/spoon/test/trycatch/TryCatchTest.java

fix Casper regression: https://ci.inria.fr/sos/job/casper/196/

fix behavioral in line-preservation mode: newlines should not pollute toString

---

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
src/test/java/spoon/test/methodreference/MethodReferenceTest.java
src/test/java/spoon/test/methodreference/testclasses/AssertJ.java

review fix: bug in ReferenceBuilder leading to infinite recursion

---

src/main/java/spoon/generating/replace/ReplacementVisitor.java
src/main/java/spoon/reflect/declaration/CtElement.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java
src/test/java/spoon/test/replace/ReplaceTest.java

Support for replacing of one element by multiple.
Needed to implement more powerful `SubstitutionVisitor` ;-)

review: feature: CtElement#replace(Collection<CtElement>)

---

chore/revapi_tpl.ftl
revapi.json

less and better revapi feedback

chore: change revapi config for more relevant messages

---

src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/generics/testclasses/ExtendedPaella.java
src/test/java/spoon/test/lambda/LambdaTest.java

It is the copy of #1382 with modified solution. May be it pass all tests now?

review: Fix issue related to CtTypeParameterReference and getDeclaration

---

ROADMAP.md

doc: update roadmap

---

src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java

review: Change handlingErrorPolicy of JDT in noClasspath mode

---

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/comment/testclasses/JavaDocEmptyCommentAndTags.java

review: fix null comment content

---

src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/ctElement/ElementTest.java

review: fix: getFactory should never return null

---

src/main/java/spoon/reflect/code/CtBlock.java
src/main/java/spoon/reflect/code/CtStatementList.java
src/main/java/spoon/support/reflect/code/CtBlockImpl.java
src/main/java/spoon/support/reflect/code/CtCaseImpl.java
src/main/java/spoon/support/reflect/code/CtStatementListImpl.java
src/test/java/spoon/test/api/MetamodelTest.java

Move some CtBlock methods to CtStatementList and add roles. Fix #1425

review: refactor: move CtBlock methods to CtStatementList

---

src/test/java/spoon/test/filters/FilterTest.java

review: doc: FilterTest is failing with JDK <= 8.0.40

---

src/main/java/spoon/template/Substitution.java
src/test/java/spoon/test/template/TemplateTest.java
src/test/java/spoon/test/template/testclasses/InnerClassTemplate.java

Failing test and fix is part of this PR. The problem was found during development of PR #1444, which contains this fix too.

review: fix substitution of references to target type in inner type

---

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
src/test/java/spoon/test/reference/TypeReferenceTest.java
src/test/resources/noclasspath/Attachment.java

fix(reference): fix getTypeReference of an unknown class that has the same name that an existing class

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/annotation/AnnotationLoopTest.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/annotation/AnnotationValuesTest.java
src/test/java/spoon/test/filters/FilterTest.java

ref #1484
* only "value" member Annotation converts SingleMemberAnnotation in pretty print.
* fix tests

support single member annotation

---

src/test/java/spoon/test/refactoring/CtRenameLocalVariableRefactoringTest.java

The test method which should check that refactored code can be pretty printed and compiled was buggy - it had no Types in the model, because it used empty Launcher.
Now it really pretty prints and compiles the type.

fix: CtRenameLocalVariableRefactoringTest#testRenameAllLocalVariablesOfRenameTestSubject

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
src/test/java/spoon/test/prettyprinter/PrinterTest.java
src/test/resources/noclasspath/orwall/BackgroundProcess.java
src/test/resources/noclasspath/orwall/PreferencesActivity.java

review fix: NPE with FieldAccess in pretty printer in no-classpath

---

pom.xml
src/main/java/spoon/reflect/cu/CompilationUnit.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/printer/ElementPrinterHelper.java
src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java
src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java
src/test/java/spoon/test/imports/ImportTest.java
src/test/java/spoon/test/imports/testclasses/internal4/Constants.java
src/test/java/spoon/test/jdtimportbuilder/ImportBuilderTest.java
src/test/java/spoon/test/jdtimportbuilder/testclasses/StarredImport.java
src/test/java/spoon/test/jdtimportbuilder/testclasses/StaticImport.java
src/test/java/spoon/test/jdtimportbuilder/testclasses/fullpack/A.java
src/test/java/spoon/test/jdtimportbuilder/testclasses/fullpack/B.java
src/test/java/spoon/test/jdtimportbuilder/testclasses/fullpack/C.java
src/test/java/spoon/test/jdtimportbuilder/testclasses/staticimport/Dependency.java
src/test/java/spoon/test/variable/testclasses/MultiBurritos.java

Use the imports from source code in auto-import mode should fix #1453

review feat: get imports from source code at first in auto-import mode

---

pom.xml

Change to use JDK8 for compilation

---

pom.xml

This PR intends to fix the error with project like casper (see https://ci.inria.fr/sos/job/casper/297/console)

Fix potential issue regarding commonsio version

---

pom.xml

easier maintenance and slightly faster build

chore: remove maven reporting plugins that we never use

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
src/test/java/spoon/test/main/MainTest.java

Adds a test which checks that Spoon model is a tree - not a latice. It means no node is shared by two attributes of same parent node.
It fixes problems too

fix: Spoon model is a tree not a latice

---

src/main/java/spoon/reflect/declaration/CtPackage.java
src/main/java/spoon/reflect/path/CtRole.java
src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java

Here is the change of role of  CtPackage.types as suggested by @monperrus in #1582

fix(role): CtPackage.types is CtRole.CONTAINED_TYPE

---

src/main/java/spoon/reflect/code/CtTypeAccess.java

PropertyGetter and PropertySetter annotations was missing there

review1: fix(role): CtTypeAccess.getAccessedType has CtRole.TYPE

---

src/main/java/spoon/Launcher.java

chore: Change default log level to error

---

src/main/java/spoon/reflect/factory/PackageFactory.java
src/main/java/spoon/reflect/reference/CtPackageReference.java
src/main/java/spoon/support/reflect/reference/CtPackageReferenceImpl.java
src/test/java/spoon/test/pkg/PackageTest.java
src/test/java/spoon/test/pkg/testclasses/Foo.java

review: feat: add CtPackage#getQualifiedName 

---

src/main/java/spoon/compiler/Environment.java
src/main/java/spoon/support/StandardEnvironment.java

fix(env): remove the useless factory in the env

---

src/main/java/spoon/generating/CloneVisitorGenerator.java
src/main/java/spoon/support/reflect/CtModifierHandler.java
src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java
src/main/java/spoon/support/reflect/code/CtLocalVariableImpl.java
src/main/java/spoon/support/reflect/declaration/CtAnonymousExecutableImpl.java
src/main/java/spoon/support/reflect/declaration/CtConstructorImpl.java
src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java
src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java
src/main/java/spoon/support/reflect/declaration/CtParameterImpl.java
src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/test/java/spoon/reflect/ast/AstCheckerTest.java

refactor(modifier): createCtModifierHandler that handles the modifiers

---

src/main/java/spoon/reflect/code/CtBlock.java
src/main/java/spoon/reflect/code/CtExpression.java
src/main/java/spoon/reflect/code/CtStatement.java
src/main/java/spoon/reflect/declaration/CtField.java
src/main/java/spoon/reflect/declaration/CtMethod.java
src/main/java/spoon/reflect/reference/CtExecutableReference.java
src/main/java/spoon/reflect/reference/CtPackageReference.java
src/main/java/spoon/reflect/reference/CtTypeReference.java
src/main/java/spoon/reflect/reference/CtVariableReference.java
src/main/java/spoon/support/reflect/code/CtAssignmentImpl.java
src/main/java/spoon/support/reflect/code/CtBlockImpl.java
src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java
src/main/java/spoon/support/reflect/code/CtExpressionImpl.java
src/main/java/spoon/support/reflect/code/CtInvocationImpl.java
src/main/java/spoon/support/reflect/code/CtStatementImpl.java
src/main/java/spoon/support/reflect/code/CtUnaryOperatorImpl.java
src/main/java/spoon/support/reflect/declaration/CtClassImpl.java
src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java
src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java
src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java
src/main/java/spoon/support/reflect/reference/CtPackageReferenceImpl.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/main/java/spoon/support/reflect/reference/CtVariableReferenceImpl.java

review refactor: Remove replace methods which were using CtElement#replace

---

src/main/java/spoon/support/gui/SpoonTreeBuilder.java

feature: Spoon GUI - SpoonModelTree - shows roles of nodes

---

src/main/java/spoon/reflect/factory/PackageFactory.java
src/test/java/spoon/processing/CtGenerationTest.java
src/test/java/spoon/test/metamodel/SpoonMetaModel.java

feature: SpoonMetaModel checks whether provided model is complete

---

pom.xml
src/main/java/spoon/processing/ProcessorPropertiesImpl.java
src/main/java/spoon/testing/utils/ProcessorUtils.java
src/test/java/spoon/MavenLauncherTest.java
src/test/java/spoon/test/processing/ProcessingTest.java

review feat: Propose a way to provide processorProperties as string

---

src/main/java/spoon/reflect/declaration/CtElement.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/SpoonTestHelpers.java

(+ boy scout refactoring in annotation code)

review feat: add method hasAnnotation 

---

src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java
src/test/java/spoon/reflect/declaration/testclasses/ExtendsArrayList.java
src/test/java/spoon/reflect/declaration/testclasses/ExtendsObject.java
src/test/java/spoon/reflect/declaration/testclasses/Subclass.java
src/test/resources/noclasspath/ExtendsObject.java

review: test: refactor TestInformation to be independent from JDK version

---

src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java
src/main/java/spoon/reflect/visitor/ListPrinter.java
src/test/java/spoon/test/prettyprinter/PrinterTest.java

review fix: start prefix space in ElementPrinterHelper

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java

Allow subclasses of DefaultJavaPrettyPrinter to print tokens too.

feature: DefaultJavaPrettyPrinter#getPrinterTokenWriter

---

src/main/java/spoon/testing/utils/ModelUtils.java
src/test/java/spoon/test/template/TemplateReplaceReturnTest.java

test support for assertions on multiline code - EOL, TAB is replaced by "" and sequence of spaces is replaced by one space. I will use that extensively in TemplateTests

test feature: ModelUtils#getOptimizedString

---

src/main/java/spoon/MavenLauncher.java
src/test/java/spoon/MavenLauncherTest.java
src/test/resources/maven-launcher/pac4j/pac4j-config/pom.xml

review fix: NPE when using MavenLauncher on module containing dependency with variable

---

src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/main/java/spoon/support/visitor/MethodTypingContext.java

Hi! I was working on static analysis tool prototype, and it probably found few nasty misprints in spoon.
So, I fixed them.

fix some small bugs

---

src/test/java/spoon/test/SpoonTestHelpers.java
src/test/java/spoon/test/metamodel/SpoonMetaModel.java

test: move metamodel related method to class SpoonMetaModel for better discoverability

---

src/test/java/spoon/test/ctClass/CtClassTest.java

due to the order or commits and merge, that interaction was not tested in the PR

test: fix CI failure due to interaction between #1864 and #1787

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java

simple fix for #1865 
@leventov WDYT?

refactor: restore DJPP#writeHeaders that clients can override

---

src/main/java/spoon/reflect/declaration/CtMultiTypedElement.java
src/main/java/spoon/reflect/meta/impl/ModelRoleHandlers.java
src/main/java/spoon/reflect/path/CtRole.java
src/main/java/spoon/reflect/visitor/CtBiScannerDefault.java
src/main/java/spoon/reflect/visitor/CtScanner.java
src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java
src/test/java/spoon/test/main/MainTest.java

fix: CtCatchVariable#multiType role TYPE changed to MULTI_TYPE

---

src/main/java/spoon/Launcher.java
src/main/java/spoon/SpoonModelBuilder.java
src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/main/java/spoon/support/compiler/jdt/JDTSnippetCompiler.java

This mechanism aims at be replacing by the PR #1905 It's marked as breaking as it changes the interfaces.

review refactor: Remove old mechanism "buildOnlyOutdatedFiles" as it was broken.

---

src/main/java/spoon/support/StandardEnvironment.java
src/test/java/spoon/test/exceptions/ExceptionTest.java

review Set default no classpath as true and trigger a warning when it's not set

---

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
src/test/java/spoon/test/position/PositionTest.java
src/test/java/spoon/test/position/testclasses/NoMethodModifiers.java
src/test/java/spoon/test/position/testclasses/SomeEnum.java
src/test/java/spoon/test/position/testclasses/TypeParameter.java

next 3 fixes of position builder.
* TypeParameter `<T extends List<T>>`
* annonymous class
* method without modifiers
See tests for details

fix: position of TypeParameter, annonymous class, method without modifiers

---

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java
src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java

I did not succeed to reproduce it with spoon dependencies

Handle NoClassDefFoundError when trying to load a class

---

src/test/java/spoon/test/factory/FactoryTest.java

test: remove testIncrementalModel

---

src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java
src/main/java/spoon/support/reflect/code/CtInvocationImpl.java

fix: set parent of auto-created CtExecutableReference

---

src/main/java/spoon/reflect/reference/CtTypeReference.java
src/main/java/spoon/support/SpoonClassNotFoundException.java
src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/main/java/spoon/support/visitor/ClassTypingContext.java

REVIEW: refactor: getTypeDeclaration cannot crash in noclasspath mode

---

README.md

The README of Spoon always fear me when seeing the whole bibtex citation on the first lines: I think it does not encourage its usage and the "getting started" is currently not immediately viewable.
This PR intends to propose another first impression for the repo.

chore: Change README to encourage usage/contribution

---

src/main/java/spoon/support/compiler/ZipFolder.java
src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java
src/main/java/spoon/support/reflect/declaration/CtClassImpl.java

This PR intends to improve our score on SonarQube
See: https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&resolved=false&severities=BLOCKER&types=BUG

review refactor: Fix the blocker smells reported by SonarQube with try-with-resources

---

src/main/java/spoon/reflect/declaration/CtAnonymousExecutable.java
src/main/java/spoon/reflect/declaration/CtClass.java
src/main/java/spoon/reflect/declaration/CtConstructor.java
src/main/java/spoon/reflect/declaration/CtTypeParameter.java
src/main/java/spoon/reflect/reference/CtWildcardReference.java
src/test/java/spoon/generating/CloneVisitorGenerator.java

fix of #2047 ... but without tests ... see question in #2047 about testing of that.

review: fix(metamodel): mark unsetable setters of name, modifier and label

---

src/main/java/spoon/support/Experimental.java

The `@experimental` tag should be usable on a single method.

feat: Allow to use experimental on a single method

---

src/main/java/spoon/support/reflect/declaration/CtEnumImpl.java
src/test/java/spoon/test/executable/ExecutableTest.java
src/test/java/spoon/test/executable/testclasses/WithEnum.java
src/test/java/spoon/test/main/MainTest.java

This PR fixes a bug introduced after #794

review 1 fix: Enum#valueOf is not well shadowed

---

src/test/java/spoon/support/compiler/jdt/ExtendedStringLiteralTest.java
src/test/java/spoon/support/compiler/jdt/testclasses/ExtendedStringLiteralTestClass.java

refactor: move ExtendedStringLiteralTestClass to testclasses

---

src/test/java/spoon/test/arrays/ArraysTest.java
src/test/java/spoon/test/arrays/testclasses/ArrayClass.java

refactor: move ArrayClass.java to testclasses

---

src/test/java/spoon/test/compilation/CompilationTest.java
src/test/java/spoon/test/compilation/Ifoo.java
src/test/java/spoon/test/compilation/testclasses/Ifoo.java

refactor: move Ifoo.java to testclasses

---

src/test/java/spoon/test/ctCase/SwitchCaseTest.java
src/test/java/spoon/test/ctCase/testclasses/ClassWithSwitchExample.java

refactor: move ClassWithSwitchExample.java to testclasses

---

src/test/java/spoon/test/enums/EnumsTest.java
src/test/java/spoon/test/enums/testclasses/OpCode.java
src/test/java/spoon/test/enums/testclasses/Performable.java
src/test/java/spoon/test/enums/testclasses/Regular.java

refactor: move OpCode.java, Performable.java and Regular.java to testclasses

---

src/test/java/spoon/test/initializers/InitializerTest.java
src/test/java/spoon/test/initializers/testclasses/InstanceInitializers.java
src/test/java/spoon/test/initializers/testclasses/InternalClassStaticFieldInit.java

refactor: move resources to testclasses in initializers

---

src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/generics/testclasses3/Bar.java
src/test/java/spoon/test/generics/testclasses3/BugCollection.java
src/test/java/spoon/test/generics/testclasses3/ClassThatDefinesANewTypeArgument.java
src/test/java/spoon/test/generics/testclasses3/ComparableComparatorBug.java
src/test/java/spoon/test/generics/testclasses3/Foo.java
src/test/java/spoon/test/generics/testclasses3/GenericConstructor.java
src/test/java/spoon/test/generics/testclasses3/GenericMethodCallWithExtend.java
src/test/java/spoon/test/generics/testclasses3/InstanceOfMapEntryGeneric.java
src/test/java/spoon/test/generics/testclasses3/SimilarSignatureMethodes.java
src/test/java/spoon/test/generics/testclasses3/Tree.java

refactor: move resources to testclasses in generics

---

src/test/java/spoon/test/serializable/Dummy.java
src/test/java/spoon/test/serializable/SerializableTest.java
src/test/java/spoon/test/serializable/testclasses/Dummy.java

refactor: move Dummy to testclasses in serializable

---

src/main/java/spoon/reflect/factory/TypeFactory.java

fix: Change the type of shadowCache to ConcurrentHashMap

---

src/test/java/spoon/test/processing/processors/ArrayResizeProcessor.java
src/test/java/spoon/test/processing/processors/TestProcessor.java

It looks like that 2 processors are in the wrong location. I moved them to *processors*.

refactor: move TestProcessor and ArraySizeProcessor to processors

---

src/test/java/spoon/test/varargs/VarArgsTest.java
src/test/java/spoon/test/varargs/testclasses/VarArgsSample.java

refactor: move VarArgsSample.java to testclasses in varargs

---

src/test/java/spoon/support/compiler/classpath/ComputeClasspathTest.java

Step by step, oh, checkstyle, you're always on my mind
Step by step, oh, checkstyle, I really think it's just a matter of time
- ComputeClasspathTest.java
I am ready to merge. With style!

refactor: fix checkstyle violations in ComputeClasspathTest.java

---

src/test/java/spoon/LauncherTest.java
src/test/java/spoon/MavenLauncherTest.java
src/test/java/spoon/generating/CtBiScannerGenerator.java
src/test/java/spoon/generating/RoleHandlersGenerator.java
src/test/java/spoon/processing/CtGenerationTest.java
src/test/java/spoon/processing/ProcessingTest.java
src/test/java/spoon/reflect/ast/CloneTest.java
src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java
src/test/java/spoon/reflect/visitor/CtInheritanceScannerMethodsTest.java
src/test/java/spoon/reflect/visitor/CtInheritanceScannerTest.java
src/test/java/spoon/reflect/visitor/CtScannerTest.java
src/test/java/spoon/reflect/visitor/CtVisitorTest.java
src/test/java/spoon/support/compiler/jdt/JDTBatchCompilerTest.java
src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
src/test/java/spoon/test/OutputTypeTest.java
src/test/java/spoon/test/SpoonTestHelpers.java
src/test/java/spoon/test/annotation/AnnotationLoopTest.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/testing/CtPackageAssertTest.java

[**No broken windows**](https://en.wikipedia.org/wiki/Broken_windows_theory)
> The broken windows theory is a criminological theory that visible signs of crime, anti-social behavior and civil disorder create an urban environment that encourages further crime and disorder, including serious crimes. The theory thus suggests that policing methods that target minor crimes such as vandalism, public drinking and fare evasion help to create an atmosphere of order and lawfulness, thereby preventing more serious crimes.
So... remove defects to encourage other developers to keep code as clean as possible.
**Honesty in small things is not a small thing. Small things matter - Clean Code (Robert C. Martin)**
> One of our favorite candies here in Denmark is Ga-Jol, whose strong licorice vapors are a …

refactor: cleanup of minor issues - Honesty in small things is not a small thing

---

src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java

Step by step, oh, checkstyle, you're always on my mind
Step by step, oh, checkstyle, I really think it's just a matter of time
- CtTypeInformationTest.java

refactor: fix checkstyle violations in CtTypeInformationTest.java

---

src/test/java/spoon/reflect/visitor/CtInheritanceScannerTest.java
src/test/java/spoon/reflect/visitor/CtScannerTest.java

Step by step, oh, checkstyle, you're always on my mind
Step by step, oh, checkstyle, I really think it's just a matter of time
- CtInheritanceScannerTest.java
- CtScannerTest.java
I am ready to merge. With style!

refactor: fix checkstyle violations in reflect visitor

---

src/main/java/spoon/compiler/builder/Options.java

refactor: fix SonarQube: Make this final field static too

---

src/main/java/spoon/reflect/visitor/JavaIdentifiers.java

refactor: fix sonarqube in java identifiers.java

---

src/main/java/spoon/metamodel/Metamodel.java

refactor curly braces to fix SonarQube violation

---

src/main/java/spoon/reflect/code/CtArrayRead.java
src/main/java/spoon/reflect/code/CtArrayWrite.java
src/main/java/spoon/reflect/code/CtFieldRead.java
src/main/java/spoon/reflect/code/CtFieldWrite.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
src/main/java/spoon/testing/AbstractAssert.java
src/test/java/spoon/test/position/PositionTest.java
src/test/java/spoon/test/position/testclasses/FooGeneric.java
src/test/java/spoon/test/position/testclasses/FooMethod.java
src/test/java/spoon/test/query_function/VariableReferencesTest.java

Don't worry about modified test class. It's ok!

refactor: fix some typos

---

src/main/java/spoon/reflect/visitor/PrintingContext.java

Formatting + ordering constants.
Sorry for small PR, but I separated this to avoid mess & conflicts.

refactor: clean file PrintingContext.java

---

src/main/java/spoon/support/template/Parameters.java
src/main/java/spoon/support/visitor/java/reflect/RtParameter.java
src/main/java/spoon/template/Substitution.java

refactor: use isEmpty() for better readability

---

src/test/java/spoon/test/visibility/VisibilityTest.java
src/test/java/spoon/test/visibility/testclasses/MethodeWithNonAccessibleTypeArgument.java

Please review with caution. I hope it does not break anything.

refactor: move MethodeWithNonAccessibleTypeArgument to testclasses

---

src/test/java/spoon/test/intercession/OneCanCallSetterWithNullParameterizedTest.java
src/test/java/spoon/test/intercession/RemoveTest.java
src/test/java/spoon/test/invocations/InvocationTest.java
src/test/java/spoon/test/javadoc/JavaDocTest.java
src/test/java/spoon/test/jdtimportbuilder/ImportBuilderTest.java
src/test/java/spoon/test/literal/LiteralTest.java
src/test/java/spoon/test/main/MainTest.java
src/test/java/spoon/test/method/MethodTest.java
src/test/java/spoon/test/method_overriding/MethodOverriddingTest.java
src/test/java/spoon/test/parameters/ParameterTest.java
src/test/java/spoon/test/pkg/PackageTest.java
src/test/java/spoon/test/strings/StringTest.java

refactor: fix even more checkstyle in tests (small PR for easy review)

---

src/test/java/spoon/test/visitor/VisitorFake.java

Ahoj! I am ready to merge.
Please read https://github.com/INRIA/spoon/pull/2278

add warning notice to Visitor

---

src/test/java/spoon/generating/MetamodelGenerator.java
src/test/java/spoon/support/compiler/jdt/JDTBuilderTest.java
src/test/java/spoon/test/api/MetamodelTest.java
src/test/java/spoon/test/ctBodyHolder/CtBodyHolderTest.java
src/test/java/spoon/test/ctClass/CtClassTest.java
src/test/java/spoon/test/ctElement/ElementTest.java
src/test/java/spoon/test/ctElement/MetadataTest.java
src/test/java/spoon/test/delete/DeleteTest.java
src/test/java/spoon/test/field/FieldTest.java
src/test/java/spoon/test/intercession/IntercessionScanner.java
src/test/java/spoon/test/intercession/IntercessionTest.java
src/test/java/spoon/test/interfaces/TestInterfaceWithoutSetup.java

refactor: fix more checkstyle in tests (small PR for easy review)

---

src/test/java/spoon/MavenLauncherTest.java
src/test/java/spoon/support/compiler/jdt/ExtendedStringLiteralTest.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/annotation/AnnotationValuesTest.java
src/test/java/spoon/test/api/MetamodelTest.java
src/test/java/spoon/test/arrays/ArraysTest.java

refactor: fix checkstyle in tests (small PR for easy review)

---

src/main/java/spoon/refactoring/CtRenameLocalVariableRefactoring.java

refactor: SonarQube - add final keyword to static field

---

src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/api/APITest.java
src/test/java/spoon/test/api/AwesomeProcessor.java
src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/condition/ConditionalTest.java
src/test/java/spoon/test/constructorcallnewclass/ConstructorCallTest.java
src/test/java/spoon/test/control/ControlTest.java
src/test/java/spoon/test/ctClass/CtClassTest.java
src/test/java/spoon/test/factory/ConstructorFactoryTest.java
src/test/java/spoon/test/model/AnonymousExecutableTest.java
src/test/java/spoon/test/model/BlockTest.java
src/test/java/spoon/test/secondaryclasses/ClassesTest.java

refactor: fix more diamonds in tests

---

src/test/java/spoon/test/api/MetamodelTest.java
src/test/java/spoon/test/factory/FieldFactoryTest.java
src/test/java/spoon/test/field/FieldTest.java
src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java
src/test/java/spoon/test/filters/FilterTest.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/initializers/InitializerTest.java
src/test/java/spoon/test/intercession/insertBefore/InsertMethodsTest.java
src/test/java/spoon/test/lambda/LambdaTest.java
src/test/java/spoon/test/limits/utils/InternalTest.java
src/test/java/spoon/test/literal/LiteralTest.java
src/test/java/spoon/test/main/MainTest.java
src/test/java/spoon/test/method/MethodTest.java

refactor: fix last diamonds in tests

---

src/test/java/spoon/test/executable/ExecutableRefTest.java
src/test/java/spoon/test/executable/ExecutableTest.java
src/test/java/spoon/test/factory/FactoryTest.java
src/test/java/spoon/test/reference/ElasticsearchStackoverflowTest.java
src/test/java/spoon/test/reference/ExecutableReferenceGenericTest.java

refactor: fix the last diamonds in tests

---

src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/comparison/EqualTest.java
src/test/java/spoon/test/exceptions/ExceptionTest.java
src/test/java/spoon/test/factory/FactoryTest.java
src/test/java/spoon/test/parent/ContractOnSettersParametrizedTest.java
src/test/java/spoon/test/parent/SetParentTest.java
src/test/java/spoon/test/template/TemplateReplaceReturnTest.java
src/test/java/spoon/testing/FileAssertTest.java

refactor: fix unused exceptions in tests - leftovers

---

src/test/java/spoon/test/jdtimportbuilder/ImportBuilderTest.java
src/test/java/spoon/test/literal/LiteralTest.java
src/test/java/spoon/test/refactoring/MethodsRefactoringTest.java

Minor improvements:
- sort modifiers in ImportBuilderTest.java
- use contains for readability
- 'l' -> 'L' to improve readability

refactor: minor cleanup

---

src/main/java/spoon/reflect/visitor/filter/RegexFilter.java
src/main/java/spoon/support/RuntimeProcessingManager.java

refactor: add override in RegexFilter

---

src/main/java/spoon/reflect/meta/impl/SingleHandler.java
src/main/java/spoon/support/SerializationModelStreamer.java
src/main/java/spoon/support/StandardEnvironment.java
src/main/java/spoon/support/gui/SpoonModelTree.java
src/main/java/spoon/support/gui/SpoonObjectFieldsTable.java
src/main/java/spoon/support/reflect/cu/position/SourcePositionImpl.java
src/main/java/spoon/template/StatementTemplate.java

refactor: add override in SingleHandler.java

---

src/main/java/spoon/support/compiler/jdt/TreeBuilderRequestor.java
src/main/java/spoon/template/TypedBlockTemplateParameter.java
src/main/java/spoon/template/TypedStatementListTemplateParameter.java

refactor: add override annotation in TreeBuilderRequestor

---

src/main/java/spoon/support/compiler/VirtualFile.java
src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java

refactor: add override annotation in virtualfile

---

src/main/java/spoon/support/compiler/ZipFile.java
src/main/java/spoon/support/compiler/ZipFolder.java

refactor: add override annotation in zipfile and zipfolder

---

src/main/java/spoon/pattern/PatternParameterConfigurator.java
src/main/java/spoon/processing/ProcessorPropertiesImpl.java
src/main/java/spoon/support/QueueProcessingManager.java
src/main/java/spoon/support/template/Parameters.java

@surli 
Some `@Override` break tests, so I created separate PRs to avoid un-mergable PRs.
Sorry for that.

refactor: add override annotation in Parameters

---

src/test/java/spoon/generating/CloneVisitorGenerator.java
src/test/java/spoon/generating/replace/ReplaceScanner.java
src/test/java/spoon/reflect/ast/AstCheckerTest.java
src/test/java/spoon/reflect/ast/CloneTest.java
src/test/java/spoon/reflect/visitor/CtScannerTest.java
src/test/java/spoon/reflect/visitor/processors/CheckVisitorTestProcessor.java
src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
src/test/java/spoon/test/SpoonTestHelpers.java
src/test/java/spoon/test/api/APITest.java
src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/ctClass/CtClassTest.java
src/test/java/spoon/test/filters/FilterTest.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/lambda/LambdaTest.java
src/test/java/spoon/test/main/MainTest.java
src/test/java/spoon/test/method_overriding/MethodOverriddingTest.java
src/test/java/spoon/test/model/IncrementalLauncherTest.java
src/test/java/spoon/test/parent/ParentTest.java
src/test/java/spoon/test/query_function/VariableReferencesTest.java
src/test/java/spoon/test/refactoring/MethodsRefactoringTest.java
src/test/java/spoon/test/reference/ExecutableReferenceGenericTest.java
src/test/java/spoon/test/replace/ReplaceParametrizedTest.java
src/test/java/spoon/test/replace/ReplaceTest.java

refactor: use isEmpty() for better readability also in tests

---

src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java

refactor: fix diamonds in test (DefaultPrettyPrinterTest.java)

---

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/main/java/spoon/support/reflect/cu/position/SourcePositionImpl.java
src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java

Code style issues
- Multiple variables in one declaration

refactor: fix code inspection - split declarations

---

src/test/java/spoon/test/casts/CastTest.java
src/test/java/spoon/test/change/ChangeCollectorTest.java
src/test/java/spoon/test/comment/CommentTest.java

- fixed checkstyle violations
- minor formatting fixes

refactor: fix checkstyle in tests

---

src/main/java/spoon/MavenLauncher.java

Fix a regression following the PR #2112

fix(MavenLauncher): regression with MavenLauncher on windows

---

src/main/java/spoon/internal/mavenlauncher/InheritanceModel.java

refactor: use modern foreach loop in InheritanceModel.java

---

src/test/java/spoon/test/ctCase/SwitchCaseTest.java
src/test/java/spoon/test/field/FieldTest.java
src/test/java/spoon/test/parent/SetParentTest.java
src/test/java/spoon/test/reference/CloneReferenceTest.java
src/test/java/spoon/test/signature/SignatureTest.java

refactor: remove unused imports from tests

---

src/main/java/spoon/MavenLauncher.java
src/test/java/spoon/MavenLauncherTest.java
src/test/java/spoon/test/comparison/EqualTest.java
src/test/java/spoon/test/compilation/CompilationTest.java
src/test/java/spoon/test/compilationunit/GetBinaryFilesTest.java

refactor: fix checkstyle in maven launcher

---

src/test/java/spoon/test/query_function/VariableReferencesTest.java

I uncommented it and it worked. Should it be permanently enabled?
@surli 
WDYT?
I am ready to merge technically. But politically?

refactor: uncomment a test in VariableReferencesTest.java

---

src/main/java/spoon/MavenLauncher.java

refactor: remove unused initializer in MavenLauncher.java

---

src/main/java/spoon/pattern/internal/node/ForEachNode.java
src/test/java/spoon/reflect/ast/CloneTest.java

refactor: fix spelling in contract (and typos)

---

src/main/java/spoon/MavenLauncher.java

refactor: remove redundant super from MavenLauncher.java

---

src/main/java/spoon/internal/mavenlauncher/InheritanceModel.java
src/main/java/spoon/internal/mavenlauncher/RangeVersion.java

refactor: use isEmpty() in RangeVersion.java

---

src/main/java/spoon/MavenLauncher.java
src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
src/test/java/spoon/test/api/Metamodel.java

refactor: remove unused 'super'

---

src/main/java/spoon/pattern/internal/parameter/AbstractParameterInfo.java
src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java
src/test/java/spoon/reflect/visitor/CtScannerTest.java
src/test/java/spoon/support/compiler/jdt/JDTBasedSpoonCompilerTest.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/api/MetamodelTest.java
src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/compilationunit/GetBinaryFilesTest.java
src/test/java/spoon/test/executable/ExecutableTest.java
src/test/java/spoon/test/filters/FilterTest.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/initializers/InitializerTest.java
src/test/java/spoon/test/intercession/IntercessionTest.java
src/test/java/spoon/test/lambda/LambdaTest.java
src/test/java/spoon/test/main/MainTest.java
src/test/java/spoon/test/method/MethodTest.java
src/test/java/spoon/test/methodreference/MethodReferenceTest.java
src/test/java/spoon/test/model/IncrementalLauncherTest.java
src/test/java/spoon/test/module/TestModule.java
src/test/java/spoon/test/pkg/PackageTest.java
src/test/java/spoon/test/processing/processors/TestProcessor.java
src/test/java/spoon/test/query_function/VariableReferencesTest.java
src/test/java/spoon/test/refactoring/CtRenameLocalVariableRefactoringTest.java
src/test/java/spoon/test/reference/ElasticsearchStackoverflowTest.java
src/test/java/spoon/test/reference/ExecutableReferenceGenericTest.java
src/test/java/spoon/test/reference/ExecutableReferenceTest.java
src/test/java/spoon/test/reference/TypeReferenceTest.java
src/test/java/spoon/test/replace/ReplaceParametrizedTest.java

Reduce risk of null pointers (NPE).
The same changes like in https://github.com/INRIA/spoon/pull/2365

refactor: change literals order in tests

---

src/main/java/spoon/reflect/path/impl/AbstractPathElement.java
src/main/java/spoon/reflect/path/impl/CtNamedPathElement.java
src/main/java/spoon/reflect/path/impl/CtTypedNameElement.java

refactor: rename getChilds to getChildren

---

src/test/java/spoon/test/enums/EnumsTest.java

refactor: fix checkstyle violations in EnumsTest.java

---

src/test/java/spoon/test/ctType/CtTypeTest.java

refactor: fix checkstyle violations in CtTypeTest.java

---

src/test/java/spoon/test/ctType/CtTypeParameterTest.java

refactor: fix checkstyle violations in CtTypeParameterTest.java

---

src/test/resources/visibility/YamlRepresenter.java

refactor: fix checkstyle violations in YamlRepresenter.java

---

src/test/java/spoon/test/factory/FactoryTest.java

checkstyle: FactoryTest.java

---

src/test/java/spoon/test/factory/ExecutableFactoryTest.java

checkstyle: ExecutableFactoryTest.java

---

src/test/java/spoon/test/factory/ConstructorFactoryTest.java

checkstyle: ConstructorFactoryTest.java

---

src/test/java/spoon/test/exceptions/ExceptionTest.java

checkstyle: ExceptionTest.java

---

chore/travis/travis-verify.sh

tentative solution from https://github.com/conda-forge/recommonmark-feedstock/issues/2

review: chore: fix broken travis due to library change

---

src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java

Cast is from: CtTypeReference to: CtTypeReference (the same).

refactor: JavaReflectionTreeBuilderTest.java

---

src/main/java/spoon/reflect/visitor/filter/SuperInheritanceHierarchyFunction.java

- simplify logic (but with the same result)
- instanceof checks for null

refactor: simplify element check - SuperInheritanceHierarchyFunction.java

---

src/main/java/spoon/pattern/internal/node/AbstractRepeatableMatcher.java

refactor: fix formatting in AbstractRepeatableMatcher.java

---

revapi.json

fix(revapi.json): Exclude internal packages from revapi bot

---

chore/travis/travis-coverage.sh

chore: fix broken Coveralls due to 0b1a09da9

---

src/main/java/spoon/pattern/PatternParameterConfigurator.java
src/main/java/spoon/pattern/internal/parameter/AbstractParameterInfo.java
src/main/java/spoon/reflect/factory/InterfaceFactory.java
src/main/java/spoon/reflect/meta/impl/SingleHandler.java
src/main/java/spoon/support/reflect/code/CtVariableAccessImpl.java
src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java

@surli 
I removed some redundant casts as promised.

refactor remove: redundant casts

---

src/main/java/spoon/support/reflect/reference/CtExecutableReferenceImpl.java
src/test/java/spoon/generating/CtBiScannerGenerator.java
src/test/java/spoon/test/arrays/ArraysTest.java
src/test/java/spoon/test/executable/ExecutableRefTest.java

Casts from 'X' to 'X' (the same).

refactor: remove redundant casts

---

src/main/java/spoon/pattern/Pattern.java

Fix SonarQube *Remove this unused "parameters" local variable.*

refactor: remove unused variable in Pattern.java (SonarQube fix)

---

src/main/java/spoon/support/visitor/ClassTypingContext.java

Fix null deference (https://github.com/INRIA/spoon/issues/2483 Warning 1)

fix: Null dereference

---

src/test/java/spoon/MavenLauncherTest.java

fix(MavenLauncherTest): Remove fixed numbers and improves classpath testing

---

src/main/java/spoon/pattern/PatternBuilder.java
src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
src/main/java/spoon/support/reflect/declaration/CtEnumImpl.java

Fix invalid checks for null (dereferenced before checked) (#2483 Warnings 5)

fix: Checks for null

---

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
src/test/java/spoon/test/imports/ImportScannerTest.java
src/test/java/spoon/test/imports/testclasses/ToBeModified.java

review: fix: ImportScanner javadoc link scanning

---

src/main/java/spoon/support/compiler/SnippetCompilationHelper.java
src/test/java/spoon/test/serializable/SerializableTest.java
src/test/java/spoon/test/snippets/SnippetTest.java

review: fix: compiled snippets have no parent

---

src/main/java/spoon/support/reflect/code/CtCommentImpl.java
src/main/java/spoon/support/visitor/java/reflect/RtMethod.java

Use simpler logic thanks to standard method.

refactor: use Object.equals()

---

src/main/java/spoon/metamodel/MMMethodKind.java

Fix unreachable code (#2483 Warning 4)
This fix is proposed by @pvojtechovsky.

fix: Unreachable code

---

src/main/java/spoon/metamodel/MetamodelProperty.java
src/main/java/spoon/pattern/PatternParameterConfigurator.java
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
src/test/java/spoon/generating/RoleHandlersGenerator.java

Eliminate some dead code (#2483 Warnings 6)

fix: Eliminate some dead code

---

src/main/java/spoon/reflect/factory/ExecutableFactory.java

Fix warning V6026 (https://github.com/INRIA/spoon/issues/2483)

fix: Suspicious assignment

---

src/main/java/spoon/metamodel/MetamodelProperty.java
src/test/java/spoon/test/api/MetamodelTest.java

It helps to detect metadata of spoon model implementation method.

feature: MetamodelProperty#getMethodBySignature(String)

---

src/main/java/spoon/reflect/visitor/ImportScannerImpl.java

Fix SonarQube *This block of commented-out lines of code should be removed.*

refactor: fix SonarQube - remove commented code

---

src/test/java/spoon/test/position/PositionTest.java
src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
src/test/java/spoon/test/snippets/SnippetTest.java

extracted from https://github.com/INRIA/spoon/pull/2508

refactor: remove unused exceptions from tests

---

src/test/java/spoon/test/serializable/SerializableTest.java

extracted from https://github.com/INRIA/spoon/pull/2508

refactor: remove unused imports in test - SerializableTest.java

---

src/test/java/spoon/test/prettyprinter/PrinterTest.java

What is the reason that this test is commented? Should it be enabled? It passes for me locally.

refactor: enable commented test in PrinterTest.java

---

src/main/java/spoon/reflect/declaration/CtElement.java
src/main/java/spoon/reflect/path/CtRole.java
src/main/java/spoon/support/reflect/declaration/CtModuleImpl.java
src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/test/java/spoon/test/role/TestCtRole.java

It is often needed to detect type of sub role. So CtRole can do it now.

feature: CtRole#getSubRole(Object)

---

src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java

refactor: remove static imports of enums in CtFieldImpl.java

---

src/main/java/spoon/support/reflect/declaration/CtElementImpl.java

refactor: remove static imports of enums in CtElementImpl.java

---

src/main/java/spoon/refactoring/Refactoring.java

Fix SonarQube: *Use a StringBuilder instead.*

sonarqube: use StringBuilder in Refactoring.java

---

src/main/java/spoon/support/compiler/SpoonPom.java
src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java

Reintroduced https://github.com/INRIA/spoon/pull/2512

checkstyle: fix checkstyle violations in TestSniperPrinter.java

---

src/main/java/spoon/support/reflect/declaration/CtParameterImpl.java

refactor: remove static imports of enums in CtParameterImpl.java

---

src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java

refactor: remove static imports of enums in CtMethodImpl.java

---

src/main/java/spoon/support/reflect/code/CtLocalVariableImpl.java

refactor: remove static imports of enums in CtLocalVariableImpl.java

---

src/main/java/spoon/support/reflect/declaration/CtConstructorImpl.java

refactor: remove static imports of enums in CtConstructorImpl.java

---

src/main/java/spoon/support/reflect/code/CtCommentImpl.java

refactor: remove static imports of enums in CtCommentImpl.java

---

src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java

refactor: remove static imports of enums in CtCatchVariableImpl.java

---

src/main/java/spoon/support/reflect/code/CtCaseImpl.java

refactor: remove static imports of enums in CtCaseImpl.java

---

src/main/java/spoon/support/compiler/SpoonPom.java

Fix SonarQube: *Cast one of the operands of this multiplication operation to a "long".*

sonarqube: Fix SonarQube: add 'L' in SpoonPom.java

---

src/main/java/spoon/support/compiler/SpoonPom.java
src/test/java/spoon/MavenLauncherTest.java

* Fix #2584
* Adds a test (MavenLauncher#testGuessMavenHome)

fix(SpoonPom): Add support for windows for guessMavenHome()

---

src/test/java/spoon/test/refactoring/CtRenameLocalVariableRefactoringTest.java

refactor: release resource in CtRenameLocalVariableRefactoringTest.java

---

src/test/java/spoon/test/api/MetamodelTest.java

refactor: remove static imports MetaModelTest.java 2018 09 30

---

src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java

refactor: remove static imports of enums in CtPackageImpl.java

---

src/main/java/spoon/metamodel/Metamodel.java

Isn't that baby step too small?

feature: added Metamodel.MODEL_CLASS_PACKAGES

---

src/test/java/spoon/LauncherTest.java
src/test/java/spoon/processing/CtGenerationTest.java
src/test/java/spoon/processing/ProcessingTest.java
src/test/java/spoon/reflect/ast/AstCheckerTest.java
src/test/java/spoon/reflect/ast/CloneTest.java
src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java
src/test/java/spoon/reflect/declaration/UnknownDeclarationTest.java
src/test/java/spoon/reflect/visitor/CtInheritanceScannerMethodsTest.java
src/test/java/spoon/reflect/visitor/CtInheritanceScannerTest.java
src/test/java/spoon/reflect/visitor/CtIteratorTest.java
src/test/java/spoon/reflect/visitor/CtScannerTest.java
src/test/java/spoon/reflect/visitor/CtVisitorTest.java
src/test/java/spoon/reflect/visitor/processors/CheckScannerTestProcessor.java
src/test/java/spoon/reflect/visitor/processors/CheckVisitorTestProcessor.java
src/test/java/spoon/support/compiler/classpath/ComputeClasspathTest.java
src/test/java/spoon/testing/AbstractAssertTest.java
src/test/java/spoon/testing/CtElementAssertTest.java
src/test/java/spoon/testing/CtPackageAssertTest.java
src/test/java/spoon/testing/FileAssertTest.java
src/test/java/spoon/testing/processors/FooToBarProcessor.java

- add some missing copyright notices
- correct old notices (2015->2018)

refactor: add some missing copyright notices, correct old notices

---

src/main/java/spoon/metamodel/Metamodel.java

Now one can create Metemodel using own Factory and then refactor the Spoon itself - this is needed in #2615

refactor: constructor Metamodel(Factory) is protected

---

src/main/java/spoon/MavenLauncher.java
src/main/java/spoon/compiler/Environment.java
src/main/java/spoon/reflect/path/impl/AbstractPathElement.java
src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/PrintingContext.java
src/main/java/spoon/support/StandardEnvironment.java
src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java
src/test/java/spoon/test/prettyprinter/QualifiedThisRefTest.java

@pvojtechovsky could you look how to remove the deprecated methods in `PatternParameterConfigurator`? Thanks!

remove deprecated methods after release 

---

CONTRIBUTING.md

We need to better explain the different kinds of pull-requests in the project. Here is a first draft. WDYT?

contributing: explain the different kinds of pull-requests

---

checkstyle-test.xml
chore/travis/travis-verify.sh
pom.xml

the idea is that we would add rules, one after the other, together with the required changes to make it pass, starting with #2609

review: chore: prepares checkstyle checking for src/test/java

---

src/test/java/spoon/test/imports/ImportAndExtendWithPackageNameTest.java

Simplify assertSame to assertEquals.

refactor: change assertion from assertSame to assertEquals

---

src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java

SonarQube: *Use the opposite operator ("!=") instead.*

refactor: remove negation (fix SonarQube)

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java
src/test/java/spoon/test/condition/ConditionalTest.java
src/test/java/spoon/test/template/TemplateReplaceReturnTest.java

fix #2527 and fix #2610
```java
if (something) {
}/*The space here was missing*/else {}
```

fix(printer): space before `else` of `if` statement

---

src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
src/test/java/spoon/test/prettyprinter/testclasses/ArrayRealVector.java
src/test/resources/noclasspath/ArrayRealVector.java

fix #2381 (the bug cannot be reproduced so far)

test: constructor with this(xxx) replaced by super(xxx)?

---

doc/path.md

Fixed some simple spelling and updated the markdown formatting to work correctly in the html page and in markdown.

Doc: Updated spelling and formatting of path page

---

src/main/java/spoon/reflect/factory/ExecutableFactory.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/generics/testclasses4/C.java

fix: CtExecutableReference cannot use CtTypeParameterReference

---

doc/first_analysis_processor.md

doc: fix broken link in doc

---

src/main/java/spoon/reflect/code/CtComment.java
src/main/java/spoon/support/reflect/code/CtCommentImpl.java
src/test/java/spoon/test/comment/CommentTest.java

Alternative to getRawContent related changes in #2172.

feature: CtComment#getRawContent()

---

src/test/java/spoon/test/template/PatternTest.java

*Reports any type parameters and wildcard type arguments explicitly declared to extend java.lang.Object.*

refactor: fix code inspection: type parameter extends Object

---

README.md

doc: Edit getting started for external dependency

---

src/test/java/spoon/test/filters/FilterTest.java

Removes useless logging of FilterTest

fix(test): minimize logs in FilterTest

---

src/test/java/spoon/test/serializable/ModelStreamerTest.java

*Reports on declarations whose modifiers are not in the canonical preferred order (as stated in the Java Language Specification).*

refactor: sort modifiers in ModelStreamerTest.java

---

doc/agent.md
doc/launcher.md
spoon-decompiler/pom.xml

fix(spoon-decompiler/pom.xml): fix#2783

---

doc/jenkins/build.sh

Update build.sh to use the correct snapshot repo in Jenkins

---

spoon-pom/pom.xml
src/main/java/spoon/javadoc/internal/Javadoc.java
src/main/java/spoon/javadoc/internal/JavadocBlockTag.java
src/main/java/spoon/javadoc/internal/JavadocDescription.java
src/main/java/spoon/javadoc/internal/JavadocDescriptionElement.java
src/main/java/spoon/javadoc/internal/JavadocInlineTag.java
src/main/java/spoon/javadoc/internal/JavadocSnippet.java
src/main/java/spoon/javadoc/internal/Pair.java
src/main/java/spoon/reflect/code/CtJavaDoc.java
src/main/java/spoon/support/reflect/code/CtJavaDocImpl.java
src/test/java/spoon/generating/CloneVisitorGenerator.java
src/test/java/spoon/test/api/MetamodelTest.java
src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
src/test/java/spoon/test/javadoc/JavaDocTest.java
src/test/java/spoon/test/javadoc/testclasses/Bar.java

feat: add support for javadoc inline tags

---

src/main/java/spoon/reflect/declaration/CtCompilationUnit.java
src/main/java/spoon/support/reflect/declaration/CtCompilationUnitImpl.java
src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
src/main/java/spoon/support/visitor/replace/ReplaceListListener.java
src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java
src/test/java/spoon/generating/replace/ReplaceScanner.java
src/test/java/spoon/test/position/TestSourceFragment.java

Compilation unit and all its parts are now integrated in SourceFragment model. It is necessary step before compilation unit stuff (package decl, imports, comments) can be handled well by sniper printer.
It is ready for review.

refactor: CompilationUnit and building of origin SourceFragment

---

src/main/java/spoon/IncrementalLauncher.java

Optimization for incremental launcher.

fix: Optimize incremental launcher

---

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
src/test/java/spoon/test/position/PositionTest.java
src/test/java/spoon/test/position/testclasses/Kokos.java

```java
/* word public confused position builder */
public class A {}
```

fix(position): position of type modifier after comment

---

pom.xml

chore(pom.xml): fix#2852 by updating commons-io and commons-lang3

---

src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java
src/test/java/spoon/test/compilation/CompilationTest.java
src/test/resources/compilation/ClassWithStaticFields.java
src/test/resources/compilation/subpackage/ClassUsingStaticFields.java

To support the resolution of #2780

fix: fix wildcard imports 

---

doc/doc_homepage.md
pom.xml

chore: bump to 7.4.0-snapshot

---

src/main/java/spoon/reflect/factory/TypeFactory.java

fix: raise exception for inconsistent model created with createTypeParameterReference

---

src/main/java/spoon/support/reflect/code/CtCommentImpl.java
src/test/java/spoon/test/comment/CommentTest.java

feature: add _setRawContent to be able to bypass cleanComment

---

src/main/java/spoon/support/reflect/eval/EvalHelper.java
src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/eval/EvalTest.java
src/test/java/spoon/test/eval/testclasses/Foo.java

fix: improve getCorrespondingRuntimeObject/convertElementToRuntimeObject to handle shadow fields

---

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java

fix(JDTCommentBuilder): improve error message with position of offending comment

---

src/main/java/spoon/javadoc/internal/JavadocDescription.java
src/main/java/spoon/support/reflect/eval/EvalHelper.java

this should have been caught by CI, see #2911

doc: fix remaining Javadoc issues

---

doc/filter.md
src/main/java/spoon/reflect/declaration/CtElement.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/ctElement/ElementTest.java

feature(CtElement): add a method to get direct children of an element

---

CONTRIBUTING.md

doc: CONTRIBUTING.md mentions our architectural rules

---

README.md

Add the Quality Gate badge from Sonar. Currently failing so it might push us to improve the code :)

chore: Add Sonar Quality Gate badge

---

src/main/java/spoon/reflect/declaration/CtType.java
src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/test/java/spoon/test/ctClass/CtClassTest.java

feat: add CtType#toStringWithImports

---

src/main/java/spoon/reflect/factory/CodeFactory.java

fix https://ci.inria.fr/sos/job/Website%20Deployer/1229/console
fix #2967

doc: fix broken documentation

---

pom.xml

We have already 100+ Maven artifacts depending on spoon-7.4.0-beta, it's time to release.
With our new release pipeline, a release is meant to be as simple as this single pull-request.
The final release of Spoon 7.4.0 will be the commit just before that one at the time it's merged.

Release Spoon 7.4.0

---

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/test/java/spoon/test/module/TestModule.java

Add meaningful module compliance exception for #2861

---

src/main/java/spoon/Launcher.java
src/main/resources/log4j.properties

fix #2672
I'd rather not to have the initialization in Launcher, but I don't see another way to do that.

Add configurable log path

---

doc/doc_homepage.md

Nobody in the community monitors and answers on stackoverflow, see unanswered questions on https://stackoverflow.com/tags/inria-spoon

doc: remove stackoverflow

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/test/java/spoon/test/lambda/LambdaTest.java
src/test/java/spoon/test/lambda/testclasses/Foo.java
src/test/java/spoon/test/lambda/testclasses/Intersection.java
src/test/java/spoon/test/prettyprinter/PrinterTest.java

Fix(DefaultJavaPrettyPrinter): handle implicit type reference to intersection type

---

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/comment/testclasses/LambdaComments.java

fix #2801.
Better handling for comments in lambdas (comments should be properly added to the AST).

Fix comments in lambdas

---

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/comment/testclasses/CatchComments.java

Fix #2894
Fix bug with comments in catch from #2894.

fix: Comments in catch

---

src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/comment/testclasses/AnnotationTypeComments.java

Fix #2894. Fix bug with comments in annotation type from #2894.

Fix comments in annotation types

---

doc/matcher.md

Fix matcher documentaion

---

src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
src/test/java/spoon/test/generics/GenericsTest.java
src/test/java/spoon/test/generics/testclasses6/A.java

fix: ClassCastException in getTypeParameterDeclaration

---

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
src/test/java/spoon/test/api/APITest.java
src/test/java/spoon/test/imports/ImportTest.java

Needed after an horror debug session due to silenced messages.

fix: compilation errors are made visible

---

src/test/java/spoon/test/filters/FilterTest.java

doc: add example for snippet filtering

---

src/main/java/spoon/support/compiler/jdt/ParentExiter.java
src/test/java/spoon/test/prettyprinter/LoopSniperJavaPrettyPrinterTest.java
src/test/java/spoon/test/prettyprinter/testclasses/loop/ForEachNoBraces.java
src/test/java/spoon/test/prettyprinter/testclasses/loop/ForNoBraces.java
src/test/java/spoon/test/prettyprinter/testclasses/loop/WhileNoBraces.java
src/test/java/spoon/test/prettyprinter/testclasses/loop/WhileWithBraces.java

add tests provided by @edouard-gillet in #2938
and fix#2938

fix:(ParentExiter.java): set position for implicit loop body block

---

src/main/java/spoon/experimental/CtUnresolvedImport.java
src/main/java/spoon/reflect/visitor/CtAbstractImportVisitor.java
src/main/java/spoon/reflect/visitor/CtImportVisitor.java
src/main/java/spoon/reflect/visitor/TypeNameScope.java
src/test/java/spoon/test/imports/ImportTest.java

CtImportVisitor visits CtUnresolvedImport in method visitUnresolvedImport now.

review feat: CtImportVisitor#visitUnresolvedImport

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java
src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
src/test/java/spoon/test/condition/ConditionalTest.java
src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
src/test/resources/noclasspath/A6.java

fix(DefaultJavaPrettyPrinter): inline else if

---

src/main/java/spoon/compiler/builder/SourceOptions.java

fix: close the output stream in SourceOptions

---

chore/travis/travis-extra.sh

Fix https://travis-ci.org/INRIA/spoon/jobs/583151696

chore: fix CI "The job exceeded the maximum log length"

---

doc/ecosystem.md
spoon-visualisation/README.md

Updating the website (plus a small fix in the doc) to mention the new visualisation tool.
As discussed in:
https://github.com/INRIA/spoon/pull/3072#issuecomment-524192501

doc(visualisation): mention the visualisation tool on the website

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/ForceFullyQualifiedProcessor.java
src/main/java/spoon/reflect/visitor/ImportAnalyzer.java
src/main/java/spoon/reflect/visitor/ImportCleaner.java
src/main/java/spoon/reflect/visitor/LexicalScopeScanner.java
src/main/java/spoon/reflect/visitor/PrettyPrinter.java
src/main/java/spoon/support/StandardEnvironment.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/imports/ImportTest.java
src/test/java/spoon/test/initializers/InitializerTest.java
src/test/java/spoon/test/loop/LoopTest.java
src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java

indeed call the preprocessors in toString/autoimports, not in only when printing to file
we're stabilizing even more, towards fixing the client builds

fix: indeed call the preprocessors in toString/autoimports

---

ROADMAP.md

I moved all the remaining points as issue.

doc: ROADMAP.md 100% points to issues

---

src/main/java/spoon/reflect/visitor/ForceImportProcessor.java
src/test/java/spoon/test/loop/LoopTest.java

required to save the build of NpeFix

fix: fix regression in auto-import

---

doc/launcher.md
spoon-decompiler/src/main/java/spoon/DecompiledResource.java
spoon-decompiler/src/test/java/spoon/DecompiledResourceTest.java

 feat(DecompiledResource): add a SpoonResource that can be used in any launcher

---

src/main/java/spoon/reflect/visitor/ImportAnalyzer.java
src/main/java/spoon/reflect/visitor/ImportCleaner.java

fix last regressions in NpeFix
TLDR: complex transformations yield original and unexpected models :-)

fix: fix more regressions after auto-import refactoring

---

src/main/java/spoon/support/reflect/declaration/CtCompilationUnitImpl.java

this should fix the regression in https://github.com/Spirals-Team/casper

fix regression after auto-import refactoring

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
src/main/java/spoon/reflect/visitor/ForceFullyQualifiedProcessor.java
src/main/java/spoon/support/StandardEnvironment.java
src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
src/test/java/spoon/test/imports/ImportTest.java
src/test/java/spoon/test/reference/TypeReferenceTest.java
src/test/java/spoon/test/variable/AccessFullyQualifiedFieldTest.java

Plus: `CtElement#toString` is much more regular
(contributes to fixing gumtree-spoon)

fix: fix regression (default DJPP is fully qualified)

---

src/main/java/spoon/reflect/visitor/AstParentConsistencyChecker.java
src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java
src/main/java/spoon/support/reflect/declaration/CtImportImpl.java

fixes build of AssertJ https://ci.inria.fr/sos/job/AssertJ/

fix: fix regression after import refactoring

---

src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java
src/main/java/spoon/support/visitor/equals/CloneHelper.java
src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java

I modified the 2 methods which appeared on the test case, not 3 like the title says

doc: add API documentation to public methods

---

pom.xml

fix(pom.xml): upgrade commons-compress to 1.19

---

src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
src/test/java/spoon/processing/ProcessingTest.java
src/test/resources/compilation3/A.java
src/test/resources/compilation3/subpackage/B.java

fix: fix for #3133, based on test of #3136

---

doc/first_transformation.md
src/main/java/spoon/refactoring/CtRenameGenericVariableRefactoring.java
src/test/java/spoon/test/refactoring/CtRenameGenericVariableRefactoringTest.java

Simply takes out the main functions of the local variable refactoring class and changes the type to be a generic CtVariable. Useful for research purposes.

feat: add new variable refactoring class

---

src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java

Fixes https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&resolved=false&severities=CRITICAL&types=BUG
Alternative to #3182

refactor: disable sonar for false positives

---

src/test/java/spoon/generating/CorrectIdentifierTest.java

Just a few more checks to ensure UTF-8 names are properly accepted.

test: Improve CorrectIdentifierTest to check with UTF8 names

---

doc/message-for-the-future.md

add a message for the future generations before being stored in the [GitHub Arctic Code Vault](https://archiveprogram.github.com/).

doc: add a message for the future generations

---

src/main/java/spoon/reflect/visitor/LiteralHelper.java
src/test/java/spoon/test/literal/UnicodeBugTest.java
src/test/java/spoon/test/strings/StringLiteralTest.java

fix: fix pretty-printing of special characters in literals

---

src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
src/test/java/spoon/test/prettyprinter/SniperInnerTypeTest.java
src/test/java/spoon/test/prettyprinter/testclasses/innertype/InnerTypeCrash.java
src/test/java/spoon/test/prettyprinter/testclasses/innertype/InnerTypeOk.java
src/test/java/spoon/test/prettyprinter/testclasses/innertype/InnerTypeOk2.java

Testcase for #3204 
+ fix #3204

REVIEW fix: fix crash with SpoonException in sniper mode

---

src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java
src/main/java/spoon/support/util/ModelSet.java
src/test/java/spoon/test/imports/ImportTest.java
src/test/java/spoon/test/parent/ParentTest.java

one test with incorrect contracts has to be changed

fix: ModelSet only keeps the latest version of the element

---

src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentContext.java
src/main/java/spoon/support/sniper/internal/PrinterEvent.java
src/main/java/spoon/support/sniper/internal/SourceFragmentContextPrettyPrint.java

for better maintenance and debugging :-)

refactor: simplify Sniper architecture

---

src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentContext.java
src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentContextCollection.java
src/main/java/spoon/support/sniper/internal/ElementPrinterEvent.java
src/main/java/spoon/support/sniper/internal/PrinterEvent.java
src/main/java/spoon/support/sniper/internal/SourceFragmentContextPrettyPrint.java
src/main/java/spoon/support/sniper/internal/SourceFragmentPrinter.java
src/main/java/spoon/support/sniper/internal/TokenPrinterEvent.java
src/test/java/spoon/test/prettyprinter/SniperDefaultMethodTest.java
src/test/java/spoon/test/prettyprinter/testclasses/DefaultMethod.java

fix: fix bug in sniper mode

---

src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentContextCollection.java
src/main/java/spoon/support/sniper/internal/SourceFragmentContextNormal.java

refactor: we can count on the mutabletokenwriter

---

src/test/java/spoon/test/prettyprinter/SniperDoubleForInitializerTest.java
src/test/java/spoon/test/prettyprinter/testclasses/DoubleForInitializer.java

test: add test for sniper (double for initializers)

---

src/main/java/spoon/reflect/factory/TypeFactory.java
src/test/java/spoon/test/prettyprinter/SniperDoubleBoundTest.java
src/test/java/spoon/test/prettyprinter/testclasses/DoubleBound.java

fix: fragments can be computed for IntersectionTypeReference and used in sniper

---

src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentContextCollection.java
src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentPrinter.java
src/main/java/spoon/support/sniper/internal/DefaultSourceFragmentPrinter.java
src/main/java/spoon/support/sniper/internal/SourceFragmentContextList.java
src/main/java/spoon/support/sniper/internal/SourceFragmentContextNormal.java

ref: better names for sniper classes and methods

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
src/test/java/spoon/processing/ProcessingTest.java
src/test/java/spoon/test/parent/ParentTest.java
src/test/resources/compilation4/A.java

fix:avoid crash in hasImplicitAncestor

---

doc/ecosystem.md

doc: add lsif-java in ecosystem

---

src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java

fix https://github.com/sourcegraph/lsif-java/issues/17

fix: comments should not crash the full process

---

chore/travis/travis-jdk8.sh
src/test/java/spoon/MavenLauncherTest.java
src/test/resources/maven-launcher/pac4j/pac4j-cas/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-config/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-core/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-couch/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-gae/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-http/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-jwt/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-kerberos/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-ldap/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-mongo/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-oauth/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-oidc/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-openid/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-saml/pom.xml
src/test/resources/maven-launcher/pac4j/pac4j-sql/pom.xml
src/test/resources/maven-launcher/pac4j/pom.xml

test: fix broken test & broken CI

---

doc/_release/deploy_production.sh

See https://ci.inria.fr/sos/job/Website+Deployer/

chore: sync website deployment script with the current version on Jenkins 

---

doc/faq.md
spoon-decompiler/README.md
spoon-pom/pom.xml

+ remove false info for spoon-decompiler which has never been deployed as snapshot

security: use https for snapshots

---

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
src/test/java/spoon/test/annotation/AnnotationTest.java
src/test/java/spoon/test/spoonifier/SpoonifierTest.java

review: annotations & full-qualified names 

---

pom.xml

* Add support for Java 12 (PR: #3259)
* Add support for parallel processor. (PR: #3280)
* Add fluent API for Launcher. (PR: #3258)
* Add support for slf4j  (PR: #3217)
* CtDeprecatedRef: Removes only unused deprecated methods. (PR: #3200)
* ModelSet: ModelSet only keeps the latest version of the element. (PR: #3232)
* Template matching ignores casts. (PR: #3028)
* Avoid crash in hasImplicitAncestor. (PR: #3247)
* Fragments can be computed for IntersectionTypeReference and used in sniper. (PR: #3225)
* Fix crash with SpoonException in sniper mode. (PR: #3205)
* Do not print implicit changes with sniper. (PR: #3210)
* Fix position of asserts (and refactor sniper). (PR: #3215)
* Fix pretty-printing of special characters in literals. (PR: #3209)
* Adds support to for the NEG Unary Operator in …

Release Spoon 8.1.0

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
src/test/java/spoon/test/targeted/TargetedExpressionTest.java
src/test/resources/spoon/test/noclasspath/targeted/StaticFieldReadOnly.java

fix: fix missing CtTypeAccess reported in #3329

---

.github/workflows/lsif.yml

As per https://github.com/INRIA/spoon/pull/3319#issuecomment-617686170

chore: generate LSIF only for pushes to master

---

src/main/java/spoon/support/compiler/SpoonPom.java
src/test/java/spoon/support/compiler/SpoonPomTest.java
src/test/resources/maven-launcher/null-build/pom.xml

Fixes #3328
Adds a couple of tests for `SpoonPom#getSourceVersion()`

fix(SpoonPom): getSourceVersion should not throw exceptions

---

pom.xml
src/test/java/spoon/test/issue3321/CtClassProcessor.java
src/test/java/spoon/test/issue3321/SniperPrettyPrinterJavaxTest.java
src/test/java/spoon/test/issue3321/SomeObjectDto.java
src/test/java/spoon/test/issue3321/source/JavaxImportTestSource.java

Added failing test for issue #3321

added test for issue #3321

---

src/test/java/spoon/test/UnresolvedBugTest.java

Each unit test was working separatly, but running the whole class skipped two of them...

test(UnresolvedBugTest): do not override the content of testMethods

---

chore/travis/travis-extra.sh

Fixing https://travis-ci.org/github/INRIA/spoon/jobs/683288854

fix flaky CI

---

README.md

doc: add supported java versions

---

src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
src/test/java/spoon/test/position/TestSourceFragment.java

refactor: improve clarity of ElementSourceFragment

---

src/main/java/spoon/reflect/declaration/CtVariable.java
src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java
src/main/java/spoon/support/reflect/code/CtLocalVariableImpl.java
src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java
src/main/java/spoon/support/reflect/declaration/CtParameterImpl.java
src/test/java/spoon/test/field/FieldTest.java
src/test/java/spoon/test/field/testclasses/A.java

feat: add CtVariable#isPartOfJointDeclaration

---

src/main/java/spoon/support/reflect/code/CtLocalVariableImpl.java
src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
src/test/java/spoon/test/variable/VariableTest.java
src/test/resources/spoon/test/var/Main.java

Second workaround for @fermadeiral's #3386 for local variables.

fix: sniper of local variables with joint declarations

---

src/main/java/spoon/reflect/factory/CompilationUnitFactory.java
src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java

this new method comes from a refactoring, so it is already called and tested.
preliminary work for #3097

feat: add method to add new CompilationUnits to be pretty-printed

---

src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
src/test/java/spoon/test/prettyprinter/testclasses/OneLineMultipleVariableDeclaration.java

Fix https://github.com/INRIA/spoon/issues/3386#issuecomment-643161444

fix: sniper of local variables

---

src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java
src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
src/test/java/spoon/test/field/FieldTest.java
src/test/java/spoon/test/position/TestSourceFragment.java

Still working on sniper of joint fields

fix: fix regression in isPartOfJointDeclaration

---

src/main/java/spoon/refactoring/Refactoring.java
src/main/java/spoon/reflect/factory/CompilationUnitFactory.java
src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
src/test/java/spoon/test/prettyprinter/testclasses/OneLineMultipleVariableDeclaration.java
src/test/java/spoon/test/refactoring/RefactoringTest.java
src/test/java/spoon/test/refactoring/processors/ThisTransformationProcessor.java

fix #3097 from @tdurieux 
depends on #3416 to be merged first

fix: fix sniper-mode after type rename

---

src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
src/test/java/spoon/reflect/ast/CloneTest.java
src/test/resources/JavaCode.java

fix: fix type member ordering

---

pom.xml

Changelog of 8.2.0
=========
* Add method to add new CompilationUnits to be pretty-printed. (PR: #3411)
* Add CtVariable#isPartOfJointDeclaration. (PR: #3392)
* Add notNullable property for processor properties. (PR: #3342)
* Add support for java 14 switch/yield. (PR: #3314)
* SameFilter: Add utility class SameFilter. (PR: #3391)
* Unqualified static method calls should be implicit. (PR: #3371)
* Sniper of local variables with joint declarations. (PR: #3398)
* Use input classloader for import resolution. (PR: #3454)
* Fix duplicate imports in sniper mode. (PR: #3388)
* Qualified name in catch clause resolved incorrectly (noclasspath). (PR: #3373)
* Fix type member ordering. (PR: #3421)
* Ensure unqualified member access remains unqualified. (PR: #3364)
* Rename refactoring impacts …

chore: release of 8.2.0

---

src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java

fix ConcurrentModificationException

---

doc/ecosystem.md

Added an entry for spork.
Which is an AST based structured merge tool for Java.

Update ecosystem.md with a new entry for spork

---

src/test/java/spoon/reflect/visitor/CtScannerTest.java

test: add test for CtDequeScanner

---

src/test/java/spoon/test/template/TemplateInvocationSubstitutionTest.java

working on having 100\% of classes covered :-)

test: add test for UndefinedParameterException

---

pom.xml
spoon-pom/pom.xml

1) make it work for both Travis and OW2 Sonarqube
2) exclude all GUI classes

chore: improve jacoco configuration

---

src/main/java/spoon/template/AbstractTemplate.java
src/main/java/spoon/template/Template.java
src/main/java/spoon/template/TemplateBuilder.java
src/test/java/spoon/test/template/TemplateArrayAccessTest.java
src/test/java/spoon/test/template/TemplateTest.java
src/test/java/spoon/test/template/testclasses/SimpleTemplate.java
src/test/java/spoon/test/template/testclasses/SubstituteArrayLengthTemplate.java

in order to comply with the principle of least surprise

refactor: template engine does not partially evaluate by default

---

src/main/java/spoon/pattern/PatternParameterConfigurator.java
src/main/java/spoon/pattern/internal/parameter/AbstractParameterInfo.java
src/main/java/spoon/support/template/Parameters.java
src/main/java/spoon/template/TemplateBuilder.java
src/test/java/spoon/test/template/core/ParameterInfoTest.java

required work for #3588, ready to merge

refactor: clarify template engine

---

src/main/java/spoon/MavenLauncher.java
src/main/java/spoon/support/compiler/SpoonPom.java

Related https://github.com/INRIA/spoon/pull/3569

Added missing constructors to MavenLauncher and SpoonPom for profile module filtering

---

src/test/java/spoon/test/textBlocks/TextBlockTest.java
src/test/resources/textBlock/TextBlockTestClass.java

Testcases from examples at https://openjdk.java.net/jeps/378
With this, the only other language changes for Java 15 will be preview features and hence Spoon can fully support Java 15.
Related  #3605

test: Add testcases for Text Blocks introduced in Java 15

---

README.md

Jekyll is confused by {{...}}} see http://spoon.gforge.inria.fr/

doc: fix bug in rendering of home page

---

src/main/java/spoon/metamodel/MetamodelProperty.java
src/main/java/spoon/support/visitor/MethodTypingContext.java
src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java

Low hanging fruit related to #3631. Lets first finish the related issue and then review this. 
Next low hanging fruit after this is reduce the needed model builds to 1.

test: add test case for checking if all private methods are used.

---

src/main/java/spoon/javadoc/internal/Pair.java

internal code for Javadoc parsing

chore: remove uncovered, unnecessary code

---

pom.xml

* Support for building Spoon models from modules declared in maven profiles. (PR: #3569)
* Add CtStatement#comment to comment code. (PR: #3494)
* CtLineElementComparator: One can add two values to an annotation. (PR: #3640)
* IncrementalLauncher: Fix incorrect assumption in IncrementalLauncher#saveCache. (PR: #3557)
* SpoonPom: Use shell command to detect Maven home version on Mac systems. (PR: #3533)
* VisitorPartialEvaluator: Fix ConcurrentModificationException. (PR: #3526)
* Use real name of the tag if it is unknwon. (PR: #3513)
* Fixed identifier correctness check when simplenamePart == "". (PR: #3550)
* Intersection types with wildcard "?" are allowed as simplename. (PR: #3568)
* Fix Maven source and test source directory resolving. (PR: #3562)
* Fix NullPointerException  (#3515). …

chore: release 8.3.0

---

src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
src/test/java/spoon/test/sourcePosition/SourcePositionTest.java
src/test/resources/spoon/test/sourcePosition/ClassWithAnnotation.java
src/test/resources/spoon/test/sourcePosition/TestAnnotation.java

Fix: source position when there is a comment character in annotation

---

pom.xml
src/main/java/spoon/Launcher.java
src/main/java/spoon/MavenLauncher.java
src/main/java/spoon/support/compiler/SpoonPom.java
src/test/java/spoon/test/logging/LogTest.java

fix: classpath mode logging in MavenLauncher

---

.github/workflows/tests.yml
src/test/java/spoon/MavenLauncherTest.java
src/test/java/spoon/test/SpoonTestHelpers.java
src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/compilationunit/TestCompilationUnit.java
src/test/java/spoon/test/field/FieldTest.java
src/test/java/spoon/test/imports/ImportScannerTest.java
src/test/java/spoon/test/imports/ImportTest.java
src/test/java/spoon/test/model/IncrementalLauncherTest.java
src/test/java/spoon/test/pkg/PackageTest.java
src/test/java/spoon/test/position/PositionTest.java
src/test/java/spoon/test/position/TestSourceFragment.java
src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
src/test/java/spoon/test/statementComment/StatementCommentTest.java
src/test/java/spoon/test/template/PatternTest.java
src/test/java/spoon/test/template/TemplateTest.java
src/test/java/spoon/test/textBlocks/TextBlockTest.java

fix #3691 
Trying to add a Windows build.

chore: Add a windows build for Java 1.8

---

doc/jenkins/build.sh

This is a duplicate PR of spoonlabs/spoonlabs.github.io#1, see the description there.
Related to #3775

chore: Add new snapshot repository as pluginRepository in build.sh

---

pom.xml

Fix https://github.com/INRIA/spoon/issues/3831

fix: dependency rg.tukaani:xz should have a test scope

---

README.md

Restore license information accidentally removed in 16b2fa6ff187fa940acc7768d6c3195bc7fd050e

fix: add license information

---

pom.xml

The current URL is not reachable (timeout).
Closes #3891

chore: fixed license URL in pom.xml

---

src/test/java/spoon/processing/CtGenerationTest.java

#3919
This PR just migrates CtGenerationTest to Junit5, pure refactoring.

test: Migrate CtGenerationTest to junit5

---

src/test/java/spoon/processing/ProcessingTest.java

#3919
This PR just migrates ProcessingTest to Junit5, pure refactoring.
Also, I have replaced the string message in assertArrayEquals with a supplier (I believe this is part of refactoring right?)

test: Migrate ProcessingTest to Juit5

---

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java

#3965 
While trying to wrap my head around the ReferenceBuilder, I found some unused code. This PR removes it.

refactor(ReferenceBuilder): Remove dead code

---

spoon-pom/pom.xml

The parent pom file was poorly formatted, primarily due to weird indentation (including mixed tabs and spaces). I just ran IntelliJ's XML formatter on it for this PR.

chore: Format parent pom

---

spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowBuilder.java
spoon-control-flow/src/test/java/fr/inria/controlflow/ForwardFlowBuilderVisitorTest.java
spoon-control-flow/src/test/resources/control-flow/ControlFlowArithmetic.java

fix(spoon-control-flow): fix disconnected graphs for switch statements

---

src/main/java/spoon/pattern/PatternParameterConfigurator.java

This pull request fixes [1 violation](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&open=AWtJlStabu-R5OS58r29&resolved=false&rules=java%3AS3824&types=CODE_SMELL) of [Sonar rule S3824](https://rules.sonarsource.com/java/RSPEC-3824) ("Map.get" and value test should be replaced with a single method call).
This patch was generated automatically using [Logifix](https://github.com/lyxell/logifix).

review: fix: Simplify code using Map.computeIfAbsent

---

src/test/java/spoon/test/template/SubstitutionTest.java
src/test/java/spoon/test/template/TemplateTest.java
src/test/java/spoon/test/template/testclasses/SimpleTemplate.java

This pr resolves the error made in #4016 while extracting tests.

review: refactor: refactor-the-wrongly-extracted-test

---

src/test/java/spoon/testing/utils/CheckTest.java

#1818
Hi, I have added some new tests for  methods of the `Check` class : 
These tests are intended to kill these mutations:
Link to #3967

review: test: add tests for the check class

---

src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/ctElement/ElementTest.java
src/test/java/spoon/test/ctElement/MetadataTest.java
src/test/java/spoon/test/ctType/CtTypeParameterTest.java
src/test/java/spoon/test/ctType/CtTypeTest.java

#3919
Hi, this PR involves pure refactoring.
I may be adding new tests in some of these tests classes.
link to #3967

review : test: migrate tests to junit-5

---

src/test/java/spoon/test/ctCase/CtCaseTest.java

Hi, I have added new tests for the class `CtCase`, I had written them much earlier but pushing them now.
These tests are intended to kill these mutations
1)
2)
3)
4)
Link to #3967

review: test: add-test-for-CtCase

---

src/test/java/spoon/reflect/visitor/CacheBasedConflictFinderTest.java
src/test/java/spoon/reflect/visitor/testclasses/simpleNestedClassWithFields.java

Hi, I have added new tests for the the class `CacheBasedConflictFinder`
These tests are intended to kill these two mutations
Link to #3967

review: test: add test for CacheBasedConflictFinder

---

pom.xml

* Add mode ignore-syntax-errors. (PR: #4054)
* Add API method CtAbstractSwitch.addCaseAt. (PR: #4015)
* Add OFF log level to StandardEnvironment. (PR: #3904)
* Add CtFormalTypeDeclarer.addFormalCtTypeParameterAt. (PR: #3896)
* Add CtExecutable.addParameterAt. (PR: #3902)
* Add CtAbstractInvocation.addArgumentAt method. (PR: #3885)
* noclasspath: Handle type resolution of anonymous class with unresolved constructor. (PR: #3971)
* spoon-control-flow: Fix disconnected graphs for switch statements. (PR: #4004)
* spoon-visualiser: Bump Interacto to use the latest version on Central. (PR: #3861)
* Fix type parameter contract of setParent. (PR: #4099)
* Make lambda type implicit to avoid auto-importing type targeted in lambda. (PR: #4093)
* Fix sniper bug delated to source position of super …

release  Spoon 9.1.0

---

README.md

Added new releases to README, so they are also shown on the homepage.

review: doc: add new releases to README

---

doc/comments.md
doc/filter.md

Fixed a variable name, and removed an extra parenthesis.

review: doc: fix two typos

---

.github/ISSUE_TEMPLATE/bug_report.md

Hi all,
Following @slarse suggestion in #4220, I suggest adding a template for bug report to encourage people to give us the steps for reproduction.
WDYT?

community(bug_report.md): Create a template for bug reports

---

src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
src/test/resources/ArithmeticExpression.java

Adds a failing test case to reproduce #3911

review: test: Add failing test case for round bracket pretty-printing

---

CONTRIBUTING.md

reference: https://github.com/INRIA/spoon/issues/4233#issuecomment-945473311

community: add Martin Witt as integrator

---

README.md

doc: Document Java version requirement

---

CONTRIBUTING.md

We take care of being trustable in Spoon (see #4300)
@MartinWitt is that your real name? 
if yes, please merge :)

doc: add real name for @MartinWitt

---

CONTRIBUTING.md

I have always wondered why there is an `é` in your name even though this alphabet is not part of the Swedish lexicon.
Anyway, please proceed to merge if this is indeed the correct spelling. :)

doc: fix spelling of @slarse 's surname

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
src/main/java/spoon/support/reflect/reference/CtFieldReferenceImpl.java
src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java

Removes old commented out code. If code wasn't needed for 3+ years, I dont think we need it anymore.

refactor: remove commented out code

---

src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java

Replace for loop with new bulk operation

refactor: replace with bulk operation

---

src/main/java/spoon/testing/utils/ModelUtils.java

refactor: move initCause to constructor

---

src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java

Fixes another qodana issue. I'm unsure if I should create one PR for each code smell type, one for each file, or one for each smell categorie in one file?

refactor: remove unneeded continue

---

src/main/java/spoon/reflect/visitor/PrinterHelper.java

For this refactoring i`m unsure if it's better readable. Some opinions?

refactor: use String#repeat

---

src/main/java/spoon/support/util/ModelSet.java

refactor: remove useless defensive programming

---

.github/workflows/tests.yml

Saw that you are using the latest version by the commit SHA :)

Update Qodana Scan action version

---

src/test/java/spoon/MavenLauncherTest.java

#3919
Replaced @Ignore annotation with @Disabled from method testTypeResolution
Replaced junit 4 test annotation with junit 5 test annotation in testTypeResolution
Replaced junit 4 test annotation with junit 5 test annotation in spoonMavenLauncherTest
Replaced junit 4 test annotation with junit 5 test annotation in multiModulesProjectTest
Replaced junit 4 test annotation with junit 5 test annotation in testSystemDependency
Replaced junit 4 test annotation with junit 5 test annotation in testForceRefresh
Replaced junit 4 test annotation with junit 5 test annotation in testRebuildClasspath
Replaced junit 4 test annotation with junit 5 test annotation in mavenLauncherTestWithVerySimpleProject
Replaced junit 4 test annotation with junit 5 test annotation …

test:  migrate MavenLauncherTest to Junit 5

---

src/test/java/spoon/test/visitor/VisitorTest.java

#3919
Replaced junit 4 test annotation with junit 5 test annotation in testRecursiveDescent
Transformed junit4 assert to junit 5 assertion in testRecursiveDescent

test: migrate VisitorTest to Junit 5

---

src/test/java/spoon/test/properties/PropertiesTest.java

#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testNonExistingDirectory`
- Transformed junit4 assert to junit 5 assertion in `testNonExistingDirectory`

test: migrate PropertiesTest to JUnit 5

---

src/test/java/spoon/test/model/AnonymousExecutableTest.java

#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testStatements`
- Transformed junit4 assert to junit 5 assertion in `testStatements`

refactor(AnonymousExecutableTest):

---

src/test/java/spoon/test/parent/SetParentTest.java

test: migrate SetParentTest to JUnit 5

---

src/test/java/spoon/test/intercession/OneCanCallSetterWithNullParameterizedTest.java

test: migrate OneCanCallSetterWithNullParameterizedTest to JUnit 5

---

SECURITY.md

Update to the security policy with the addition of Security Advisory instructions, and more detailed instructions in general.
Thanks @intrigus-lgtm for the suggestion.

review: doc: Update security policy with Security Advisories

---

doc/_release/README.md

Our versioning convention is not documented. Here it is.

doc: document our versioning process

---

pom.xml

Don't merge before https://github.com/SpoonLabs/spoon-deploy/pull/5

chore: bump snapshot version to 10.1.0

---

doc/spoon_smpl.md

Change some links in the spoon-smpl doc to point to the INRIA repo instead of mine.

doc: update links to spoon-smpl repo

---

src/test/java/spoon/test/comment/CommentTest.java
src/test/java/spoon/test/ctType/CtTypeTest.java
src/test/java/spoon/test/pkg/PackageTest.java
src/test/java/spoon/testing/utils/ModelTest.java
src/test/java/spoon/testing/utils/ModelTestParameterResolver.java

See #4691 for more information. This is a PR introducing just the core classes and migrating a handful of tests.

review: test: Add ModelSet annotation for testing

---

src/test/java/spoon/test/javadoc/JavaDocTest.java

`noClassPath` and `commentEnabled` are the default.

review: test: Add ModelTest annotation to spoon.test.javadoc

---

src/test/java/spoon/test/imports/ImportScannerTest.java
src/test/java/spoon/test/imports/ImportTest.java

It never reads from the source output directory, so it shouldn't be required.

test: Add ModelTest annotation to spoon.test.imports

---

README.md

- pull-request -> pull request
- Februray -> February
- prefered -> preferred

doc(readme): Fix typos in README.md

---

src/main/java/spoon/reflect/declaration/CtExecutable.java

review: doc: Remove return type in sample getSignature() output

---

CONTRIBUTING.md

Related to #4233 
@SirYwell could you provide an email address?

governance: Add SirYwell as integrator

---

.mvn/gradle-enterprise.xml
chore/ci-extra.sh

See #4269 for discussion
See [this part of the docs](https://docs.gradle.com/enterprise/maven-extension/#publishing_on_demand) for on-demand publishing.

chore: Disable automatic Gradle Dashboard upload

---

pom.xml
spoon-decompiler/pom.xml
spoon-pom/pom.xml
spoon-smpl/pom.xml
spoon-visualisation/pom.xml

As discussed in #4911 I moved the plugin to the parent pom.

review: chore: move plugin to parent

---

src/main/java/spoon/reflect/factory/CodeFactory.java

Enumset for enum values is strictly better than set, and this fixes one of many locations with this bad smell.

review: style: change set to enumset

---

src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java

Instead of manually checking if a modifier is applicable to a `CtModifiable`, we can just use the masks provided by Java to only have the allowed bits set.

refactor: use modifier masks instead of additional checks

---

README.md

To my best knowledge, we support up to java 20, so we should update the doc.

doc: update supported java version in readme.md

---

src/main/java/spoon/reflect/factory/CodeFactory.java

doc: fix typos in CodeFactory class

---

renovate.json

If I understand https://github.com/INRIA/spoon/pull/5180 this correctly the action is "pinDigest".

chore: automerge pinDigest action from renovate

---

spoon-pom/pom.xml

Fixes one problem found by Renovate in https://github.com/INRIA/spoon/issues/4143
Could be considered as debloat @cesarsotovalero

deps: remove outdated dependency that cannot be resolved anymore

---

renovate.json

renovate.json is invalid, see https://github.com/renovatebot/renovate/issues/6894#issuecomment-1537121202

fix: fix renovate.json

---

README.md

How about we change this png to svg? The badge looks way better with this. For review look at the current badge and the markdown preview of this badge.
Old:
https://github.com/INRIA/spoon#readme
New: 
https://github.com/INRIA/spoon/blob/MartinWitt-patch-1/README.md

style: change badge from png to svg

---

src/main/java/spoon/Launcher.java
src/main/java/spoon/support/QueueProcessingManager.java
src/main/java/spoon/support/StandardEnvironment.java
src/test/java/spoon/test/logging/LogTest.java

fix: update the level of unwanted info logs to debug

---

src/main/java/spoon/reflect/reference/CtReference.java
src/main/java/spoon/reflect/visitor/filter/DirectReferenceFilter.java

Closes #5338. Does this clarify what you were asking @Luro02?

review: doc: Warn that reference equality might be different than expected in DirectReferenceFilter

---

pom.xml

review: fix: Filter resources to replace version placeholder

---

src/main/java/spoon/reflect/factory/CompilationUnitFactory.java
src/main/java/spoon/support/reflect/declaration/CtCompilationUnitImpl.java
src/test/java/spoon/test/refactoring/RefactoringTest.java

review: fix: Remove compilation unit by reference equality if it has no file

---

doc/jenkins/build.sh

this script drives our Jenkins regression server

chore: we now use Central for snapshots

---

doc/jenkins/build.sh

we don't need to fail by enforcer.
fix https://ci.inria.fr/sos/job/Commons-collections/ and maybe a few others

chore: update regression script

---

doc/jenkins/build.sh

fix Jenkins, validated ni pre-flight with https://github.com/SpoonLabs/SpoonLabs.github.io/commit/3f758073b1b252289cbb49b1a1011b0f7b438397

chore: fix regression testing pipeline

---

doc/jenkins/inject_spoon_snapshot.py

Update CI script inject_spoon_snapshot.py for using new snapshot repo.

Update CI script inject_spoon_snapshot.py

---

doc/jenkins/build.sh

Given the results of shell check, we should make a second PR trying to fix them afterward.

 fix: fix updating of spoon version in smoke test

---

spoon-decompiler/README.md
spoon-smpl/README.md

Hi there,
I'm a computer science student in the States working with your framework for a school project. I noticed some small grammar and typing things can could use some love while I was reading your documentation. 
Thanks again for such a cool framework!

Small ReadMe fixes for greater readability 

---

.github/workflows/tests.yml
chore/CheckJavadoc.java
chore/check-javadoc-regressions.py
flake.nix

Checkstyle still does not support `{@return}` inline tags :/

review: chore: Rewrite javadoc checkstyle in spoon 

---

src/main/java/spoon/reflect/code/CtExpression.java
src/main/java/spoon/reflect/code/CtRecordPattern.java
src/main/java/spoon/reflect/declaration/CtElement.java

This should make the javadoc quality check happy again

review: doc: Add javadoc for elements added in java 17 branch

---

flake.nix

These packages are not upstreamed and not covered by renovate, so we need to do this sometimes :tm: .

chore: Update custom packages in flake.nix

---

src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/test/model/SwitchCaseTest.java

review: fix: skip synthetic break from JDT

---

src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
src/test/java/spoon/test/api/NoClasspathTest.java
src/test/java/spoon/testing/assertions/SpoonAssert.java
src/test/resources/noclasspath/issue5591/DiamondConstructorCallTypeInference.java

review: fix: Trim apostrophes from JDT synthetic factory methods

---

README.md
pom.xml

to get a perfect 100% on https://www.bestpractices.dev/en/projects/7377

doc: https everywhere

---

CONTRIBUTING.md
jreleaser.yml
spoon-pom/pom.xml

Hello everyone!
It's been years since I made any meaningful contribution to Spoon. I've been meaning to get back into it for the longest time, but it's time to face the fact that it's simply not going to happen. Given my other interests, I just can't make the time for it anymore.
So, this is making my resignation as an integrator official. I should have handed it in a long time ago, but it's simply going to have to be a "better late than never" kind of PR :)
Best of luck!
Ps. Don't forget to remove my write privileges to the repository!

chore: Remove slarse as integrator

---

renovate.json

fix #5952 
ref doc: https://docs.renovatebot.com/semantic-commits/

change renovate commit message

---

.github/workflows/tests.yml
chore/check-reproducible-builds.sh
flake.nix
spoon-pom/pom.xml

It is broken for a year, maybe we should remove it instead of skipping it.

review: chore: remove depclean

---

src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java

fix https://github.com/SpoonLabs/gumtree-spoon-ast-diff/issues/338

fix: protect against NPE

---

.github/workflows/release-manual.yml

we had two workflows named "Release"

disambiguate workflows

---

doc/_release/changelog_generator/changelog.js

fix deprecated dependency problem from the [Dependency Dashboard](https://github.com/INRIA/spoon/issues/4143
)

chore: fix deprecated package in changelog_generator

---

pom.xml
src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java

See https://github.com/INRIA/spoon/pull/6220 for context and discussion
cc @monperrus @I-Al-Istannen @algomaster99 @frankreyesgarcia

chore: update jdt.core to v3.41.0

---

doc/_release/changelog_generator/package.json

finish the job of https://github.com/INRIA/spoon/pull/5198

remove unused dependency
