INRIA/spoon

- src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
- src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentContext.java
- src/main/java/spoon/support/sniper/internal/ChangeResolver.java
This fixes 3 Sonarqube violations of rule S4973:
https://rules.sonarsource.com/java/RSPEC-4973
> fix(equality): Use .equals() when comparing Strings and Boxed types.

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/main/java/spoon/reflect/visitor/PrettyPrinter.java
- src/main/java/spoon/support/modelobs/ChangeCollector.java
- src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
- src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
- src/main/java/spoon/support/visitor/equals/CloneHelper.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/java/spoon/test/prettyprinter/testclasses/ElementScan.java
Since recent changes, `CtElement#toString()` calls the default prettyprinter which can be a `SniperPrinter`. 
AFAIU, this fails for two reasons:
* `toString()` clone the element before printing it, and `SniperPrinter` use `getRoleInCompilationUnit()`. But `getRoleInCompilationUnit()` implement a Scanner that look for the exact element in its parent children. Of course the clone has a parent but is not among the children of its parent.
* `SniperPrinter` require some `SourceFragmentContext` to be pushed on a stack to print an arbitrary element that is not a `CompilationUnit`. This must be initialized before.
This PR implement a POC that solves these two problems. But I am not sure if that's the direction we want to take. (Currently it makes an ugly check in `toString()`'s body to check what …
> fix(CtElementImpl#toString): fix toString for SniperPrinter

- pom.xml
this PR will trigger the official release of Spoon 8.0.0
* Add new variable refactoring class. (PR: #3162)
* Add role EMODIFIER for extended modifier. (PR: #3098)
* CtImportVisitor#visitUnresolvedImport. (PR: #3086)
* DecompiledResource: Add a SpoonResource that can be used in any launcher. (PR: #3124)
* SpoonifierVisitor: A visitor that generates the spoon code to recreate a spoon model. (PR: #3105)
* decompiler: Add support for procyon. (PR: #3123)
* visualisation
* Panel added to show Spoon objects' properties. (PR: #3107)
* Spoon visualiser improvement for accessing JavaDoc. (PR: #3101)
* spoon-visualisation: Spoon AST visualisation tool. (PR: #3072)
* CreateVariableAssignment now creates a CtVariableWrite. (PR: #3157)
* Fixes the toString() call on an array. (PR: #3134)
* …
> release of Spoon 8.0.0

- pom.xml
Spoon depends direclty on `org.eclipse.jdt.core`. However, the dependencies `org.eclipse.core.resources`, `org.eclipse.core.runtime`, `org.eclipse.core.filesystem`, and  `org.eclipse.text` are not used by Spoon and can be excluded safely. 
These transitive dependencies with compile scope introduce bloat in the Spoon library as we can see in the current dependency tree:
```
+- org.eclipse.jdt:org.eclipse.jdt.core:jar:3.16.0:compile
|  +- org.eclipse.platform:org.eclipse.core.resources:jar:3.13.500:compile
|  |  +- org.eclipse.platform:org.eclipse.core.expressions:jar:3.6.500:compile
|  |  |  \- (org.eclipse.platform:org.eclipse.core.runtime:jar:3.16.0:compile - omitted for duplicate)
|  |  +- (org.eclipse.platform:org.eclipse.core.filesystem:jar:1.7.500:compile - omitted for duplicate)
| …
```
> Exclude unused transitive dependencies

- src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java
- src/main/java/spoon/support/compiler/jdt/JDTConstants.java
- src/main/java/spoon/support/compiler/jdt/TreeBuilderCompiler.java
All uses of constants defined in `org.eclipse.jdt.internal.compiler.lookup.TypeConstants`, which is an internal class, are replaced by custom defined constants. Closes #3185.
> fix:Removing the use of 3rd party internal constants

- src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
- src/test/java/spoon/test/comment/CommentTest.java
- src/test/java/spoon/test/comment/testclasses/EmptyStatementComments.java
Hi )
I offer the pull request, which fixes NullPointerException in JDTCommentBuilder.java.
It occurred in the case, when spoon gathered comments in an empty switch statement.
> fix: NullPointerException in the 'insertCommentInAST' method for an empty switch statement.

- src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java
- src/test/java/spoon/generating/CorrectIdentifierTest.java
- src/test/java/spoon/test/api/MetamodelTest.java
- src/test/java/spoon/test/arrays/ArraysTest.java
- src/test/java/spoon/test/compilationunit/TestCompilationUnit.java
- src/test/java/spoon/test/imports/ImportTest.java
- src/test/java/spoon/test/parent/ContractOnSettersParametrizedTest.java
- src/test/java/spoon/test/template/TemplateTest.java
fix #2237
this should fix issue #2237. But a lot of Code uses CtReferenceImpl::setSimpleName for creating illegal references. This code must be changed for this small issue. Like CodeFactory::createClassAccess creates a fieldReference with simpleName "class", which is a illegal identifier.
> review: fix: issue #2237 reject invalid names

- src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java
- src/test/java/spoon/test/eval/EvalTest.java
Adds support to the VisitorPartialEvaluator for the NEG UnaryOperator. Adds test for the operator.
Before this when a NEG UnaryOperator was encountered by the VisitorPartialEvaluator it would throw the unsupported operator Runtime Exception.
> fix: adds support to the VisitorPartialEvaluator for the NEG UnaryOperator

- pom.xml
- src/main/java/spoon/Launcher.java
- src/main/java/spoon/compiler/Environment.java
- src/main/java/spoon/processing/AbstractProcessor.java
- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/main/java/spoon/reflect/visitor/ModelConsistencyChecker.java
- src/main/java/spoon/support/RuntimeProcessingManager.java
- src/main/java/spoon/support/StandardEnvironment.java
- src/main/java/spoon/support/compiler/SpoonPom.java
- src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
- src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
- src/main/java/spoon/testing/utils/ProcessorUtils.java
- src/test/java/spoon/test/logging/LogTest.java
- src/test/java/spoon/test/processing/ProcessingTest.java
- src/test/java/spoon/test/processing/processors/TestProcessor.java
`log4j:log4j` is stuck to `1.2.7`, which contains a security vulnerability. 
The new artifact for log4j is now `org.apache.logging.log4j:log4j-core`.
The api has slightly changed for version `2.x`, see [this page](https://logging.apache.org/log4j/2.x/manual/migration.html) for migration information.
> refactor: migrate to org.apache.logging.log4j:log4j-core:2.13.0

- src/main/java/spoon/support/modelobs/ChangeCollector.java
- src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
This extracts the interesting changes of #3194, which was hard to debug.
Changes in IMPLICIT are ignored in `#getChanges()`, it's less dangerous because well, less ... implicit :-)
Fix #3176
> fix: be more protective to avoid wrong usages of sniper mode

- checkstyle.xml
- pom.xml
- spoon-control-flow/pom.xml
- spoon-decompiler/pom.xml
Fix for #3186. Spoon has a lot of jdt.internal imports so we cant reject them in checkstyle.
But the regex `^(?!.*(spoon|jdt)).*internal.*$` should catch all other unwanted internal imports.
The update of the checkstyle version from 3.0.0 to 3.1.0 is necessary, because 3.0.0 does not contain regex property.
> chore(checkstyle): add check for internal imports

- src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
otherwise a debugger session is a nightmare (the debugger always calls toString :-)
> ref: toString() in sniper return toStringDebug()

- src/main/java/spoon/support/compiler/SpoonPom.java
- src/test/java/spoon/MavenLauncherTest.java
- src/test/resources/maven-launcher/source-directory/pom.xml
- src/test/resources/maven-launcher/source-directory/source/code/Test.java
- src/test/resources/maven-launcher/source-directory/test/Test.java
In Maven POM, the standard directory layout for sources and test sources can be overridden from the standard `src/main/java` and `src/test/java` as follows:
```xml
<build>
<sourceDirectory>source/code</sourceDirectory>
<testSourceDirectory>test</testSourceDirectory>
</build>
```
The description for the field `sourceDirectory` states:
>This element specifies a directory containing the source of the project. The generated build system will compile the source in this directory when the project is built. **The path given is relative to the project descriptor.**
Previously, when using MavenLauncher, if this value is defined it will be used instead of the standard directory structure when searching for sources. The issue is that this relative path is not prefixed with the absolute path to the …
> fix: not finding sources in non-standard directories

- src/main/java/spoon/reflect/visitor/ImportScanner.java
- src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
- src/test/java/spoon/test/imports/ImportScannerTest.java
(required for dspot and for astor)
they were incorrectly deprecated
> ref: restore classes used by clients (ImportScanner and impl)

- src/main/java/spoon/support/compiler/SpoonPom.java
As per #3262 I'd like to propose adding a getter to `SpoonPom` so that information about the (maven) modules declared in that POM can be retrieved. Currently only the top level `SpoonPom` is accessible from `MavenLauncher`.
> refactor: adding getter for modules to SpoonPom

- src/main/java/spoon/MavenLauncher.java
- src/test/java/spoon/MavenLauncherTest.java
The class `MavenLauncher` has constructors with parameter `forceRefresh`, with the JavaDoc comment:
> @param forceRefresh force the regeneration of classpath
However the value was actually never passed through to the `SpoonPom` method responsible for generating the classpath, as it was hardcoded to false. This is fixed and a method `rebuildClasspath` is added to `MavenLauncher` to enable rebuilding of the classpath without instantiating a new launcher (or directly calling the `SpoonPom` method). Tests for both use cases also added.
> fix(MavenLauncher): allowing rebuilding of classpath

- spoon-control-flow/pom.xml
- spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowBuilder.java
currently the ControlFlowBuilder doesn't override the method `	public <T, S> void visitCtSwitchExpression(CtSwitchExpression<T, S> switchExpression)`. With this fix the CI should work again, as soon as the latest snapshot with the merged switchexpressions #3259 is published on mavencentral. As soon as the new version is published this patch should compile. Updated version of spoon dependency, because CI is using the newest anyway.
Edit: Seems like the CI already has the newest version.
> fix(spoon-control-flow): add switchExpression to visitor

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java
- src/test/java/spoon/test/targeted/TargetedExpressionTest.java
- src/test/resources/spoon/test/noclasspath/targeted/Outer.java
Fix #3334
Hi!
This is a suggested fix for #3334. To the best of my knowledge, this does the same thing that @Egor18  implemented with #3331, but using the JDT tree instead.
Please see #3334 for a detailed description of the problem. I'm also running some tests locally with [Spork](https://github.com/kth/spork) to see if this solves the problems I encountered, will check back once those have completed.
> fix: fix nested class field read problem

- .github/workflows/lsif.yml
- doc/faq.md
Hi Spoon folks! Let me know your thoughts on this PR for adding code intel with LSIF (@monperrus has some context, but this PR provides a complete picture for anyone interested). 
**Background**: [LSIF](https://code.visualstudio.com/blogs/2019/02/19/lsif#_language-server-index-format) is a file format for precomputed code intelligence data. An LSIF dump can be used to provide things like jump-to-definition, hover information, and find-references. 
I work at [Sourcegraph](https://github.com/sourcegraph) and we've added first class support for LSIF, and created [lsif-java](https://github.com/sourcegraph/lsif-java) to generate LSIF data for Java. The fun part is we use Spoon to generate this LSIF data! (thanks for this great project 😉). This makes it possible to use Spoon to generate code …
> chore: add LSIF GitHub action for sourcegraph augmentation

- pom.xml
- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/test/java/spoon/test/imports/ImportTest.java
- src/test/java/spoon/test/imports/testclasses/badimportissue3320/source/TestSource.java
- src/test/java/spoon/test/imports/testclasses/badimportissue3320/source/other/SomeObjectDto.java
- src/test/java/spoon/test/imports/testclasses/badimportissue3320/source/other/TestAnnotation.java
> fix: fix wrong import on annotated parameter #3320

- src/main/java/spoon/processing/Property.java
- src/main/java/spoon/testing/utils/ProcessorUtils.java
- src/test/java/spoon/test/processing/ProcessingTest.java
See #3339 for discussion why. I would add a simple boolean field to the property annotation because:
- Change the null to a nullObject like in SourcePosition would be backwards breaking
- Doesn't pollute the namespace with a new method.
Maybe a open issue issue is where to document it? 
Edit: need to fix git sry
Edit2: git fixed
> Feat: add notNullable property for processor properties

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/test/java/spoon/test/pkg/PackageTest.java
- src/test/resources/noclasspath/TypeAccessStarImport.java
Fix #3337 
Hello!
This is an attempt to fix Spoon incorrectly guessing the package of a type in noclasspath mode. See #3337 for details.
I need some help with this PR, see the comments.
> fix: correct package assumption when there is a star import

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/test/java/spoon/test/reference/TypeReferenceTest.java
- src/test/java/spoon/test/spoonifier/SpoonifierTest.java
- src/test/resources/noclasspath/QualifiedArrayType.java
Fix #3336 
This is an attempt to fix the problem discussed in the aforementioned issue. I don't know why the package reference is to implicit where it is, but removing it with edf9700 fixed my problems. This also causes some changes in generated code, so I had to update `testGeneratedSpoonifyCode` with 8acb899.
I really don't know if this PR is reasonable. It works for me and does not appear to cause any breakage other than `testGeneratedSpoonifyCode`. Accidentally setting an explicit reference to implicit is in my opinion much worse than the other way around, as the former can cause compile errors, and has done so for me multiple times.
> fix: Remove incorrect implicitness for package reference

- src/main/java/spoon/support/util/QualifiedNameBasedSortedSet.java
- src/main/java/spoon/support/visitor/equals/CloneHelper.java
- src/test/java/spoon/support/util/QualifiedNameBasedSortedSetTest.java
- src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
- src/test/java/spoon/test/api/MetamodelTest.java
- src/test/java/spoon/test/comment/CommentTest.java
- src/test/java/spoon/test/ctType/CtTypeTest.java
- src/test/java/spoon/test/ctType/testclasses/MultiInterfaceImplementation.java
Fix #3354 
This is a rough draft to fix #3554. Currently, this fails the `testGenerateRoleHandler` test as a new role handler `CtType_MODIFIER_RoleHandler` is generated. I'm not quite sure why that is, but it has something to do with elements being ordered by insertion order instead of by name order.
I'm not quite sure how to proceed with this, or even if we want to proceed with this. Perhaps it is more trouble than its worth.
> fix: sort type references by position and qualified name (may be BREAKING)

- src/main/java/spoon/reflect/factory/TypeFactory.java
- src/main/java/spoon/reflect/reference/CtTypeReference.java
- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/test/java/spoon/test/constructorcallnewclass/ConstructorCallTest.java
- src/test/resources/noclasspath/GenericTypeEmptyDiamond.java
Fix #3360 
This is an attempt to fix the problem discussed in #3360 
What I do here is essentially to try to recover the type arguments from the `AllocationExpression`'s expected type. To the best of my knowledge, empty diamonds are only allowed on constructor calls, so I only have an assert that the stack's top element is an `AllocationExpression`. It shouldn't be possible for it to be anything else.
If the constructor call occurs inside of an unresolved method, or another constructor call, then the `AllocationExpression` doesn't have an expected type (because it can't be resolved). In that case, I add the new `OMITTED_TYPE_ARG_TYPE` (name could use some work) to the type argument list so at least Spoon can detect that the constructor is in fact parameterized, and will then print `<>`. …
> fix: Fix dropping diamonds on constructor calls

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/test/java/spoon/test/reference/TypeReferenceTest.java
- src/test/resources/noclasspath/UnqualifiedExternalTypeMemberAccess.java
Fix #3363 
This is a fix for the aforementioned issue. The approach I've taken here is outlined in #3363. If I'm not mistaken, this fix is simple and does not break anything.
> fix: Ensure unqualified member access remains unqualified

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/test/java/spoon/test/targeted/TargetedExpressionTest.java
- src/test/resources/noclasspath/UnqualifiedStaticMethodCall.java
Fix #3370 
This is a suggestion for solving #3370. It is a unified solution for both this and #3363 , as the fix I implement for the latter in #3364 was apparently only a partial solution to the problem.
I decided to add the `setImplicitPackageOrDeclaringType` to complement `setPackageOrDeclaringType` as the latter seems to be used in places where it's not obvious that the package/declaring type should be implicit. But in this particular case, we know we want it to be implicit as the `createTypeAccessNoClasspath(SingleNameReference)` is called with a `SingleNameReference` (i.e. not qualified).
> fix: Unqualified static method calls should be implicit

- doc/_data/sidebar_doc.yml
- doc/architecture_test.md
- doc/command_line.md
- doc/comments.md
- doc/examples.md
- doc/factories.md
- doc/faq.md
- doc/filter.md
- doc/first_analysis_processor.md
- doc/first_transformation.md
- doc/gradle.md
- doc/launcher.md
- doc/maven.md
- doc/path.md
- doc/pattern.md
- doc/processor.md
- doc/processor_annotations.md
- doc/references.md
- doc/template_definition.md
- doc/testing_quickstart.md
Unify documentation headers to achieve a beautiful table of contents
* Introduction
* Getting started
* Core concepts
* Abstract Syntax Tree
* Code Analysis
* Code Transformation
* Using Spoon for Architecture Enforcement
* Example rule: never use the TreeSet constructor
* Example rule: all test classes must start or end with "Test"
* Example rule: all public methods must be documented
* Related work in architecture enforcement
* Using Spoon as a Better Runtime Reflection API
* More about Spoon Processors
* Examples of Analysis Processors
* Parallel Processor
* FAQ
* Where is the Javadoc?
* Are there snapshots versions deployed somewhere?
* How to access Spoon's source code repository?
* What is the meaning of each digit in the version X.Y.Z of spoon?
* Where is the Spoon metamodel?
* How …
> doc: unify headers

- .github/workflows/lsif.yml
Hi @monperrus I noticed that GH was showing a red ❌  for the build due to a setting for that uploading LSIF data in the GH action (sorry about that!). 
It's unfortunate that we can't tell GH to ignore the status of failed actions (and so give a nice ✅  instead of X even if this action fails). There is already an upstream fix for the action, but this PR will also stop any other spurious causes that may show a red ❌  for the build if it is LSIF upload related.
> chore: allow LSIF upload action to pass even if upload fails

- src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
- src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
We have duplication of code, which hinders understandability and maintainability, this PR fixes that: only isFragmentModified (not shown in the diff) is responsible for computing fragment modification status
> ref(sniper): only isFragmentModified is responsible for computing fragment modification

- src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
- src/main/java/spoon/support/sniper/internal/SourceFragmentContextNormal.java
Remove unnecessarily complex code and confusing exceptions!
> refactor: simplify sniper code in ElementSourceFragment#addChild

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/test/java/spoon/test/trycatch/TryCatchTest.java
- src/test/resources/noclasspath/CatchQualifiedReference.java
This is a test case to reproduce #3372 
I haven't yet had the time to look into solutions.
update fixes #3372
> fix: Qualified name in catch clause resolved incorrectly (noclasspath)

- src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java
- src/test/java/spoon/support/compiler/jdt/JDTImportBuilderTest.java
This PR addresses the problem observed in https://github.com/INRIA/spoon/issues/3420
If an input classloader is specified in Environment it should be used to resolve imports. 
Otherwise only imported classes on the same class loader as JDTImportBuilder are found.
To reproduce the problem see tests in spoon.support.compiler.jdt.JDTImportBuilderTest
> fix: use input classloader for import resolution

- src/main/java/spoon/support/compiler/SpoonPom.java
This is a fix for bug #3530.
The fallback command that retrieves Maven home using a `mvn -version` command only works on Unix-based systems.
For it to work on MacOS systems it requires a shell execution that will search for Maven executable in the PATH environment variable: `sh -c "mvn -version"`.
> fix: Use shell command to detect Maven home version on Mac systems without failure

- src/main/java/spoon/support/reflect/code/CtLambdaImpl.java
- src/test/java/spoon/test/lambda/LambdaTest.java
- src/test/java/spoon/test/lambda/testclasses/Intersection.java
> fix: fix handling of intersection types for lambda parameters

- src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
- src/test/java/spoon/test/position/PositionTest.java
- src/test/java/spoon/test/position/testclasses/FooGeneric.java
The following line would result in `o2` being of a value that would cause `modifierName` to include the generic type param, causing the looking into `explicitModifiersByName` to return null. https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/ParameterizedTypeFixtures.java#L129
If a space would be between `static` and `<T>`, the modifier position is extracted properly.
> fix: fix PositionBuilder if modifier is followed by generic with out whitespace e.g public static<T>

- src/test/java/spoon/test/factory/TypeFactoryTest.java
- src/test/java/spoon/test/model/TypeTest.java
- src/test/java/spoon/test/reference/ExecutableReferenceTest.java
As i wrote in issue #3547 we have some testcase, which are jdk dependent. Goal of this patch is to fix them all and as always refactor the testcase to reach a higher quality standard. Looking into the older testcases, there is still alot of refactoring work needed unrelated to bugs. I try to create as minimal diffs as possible while still refactoring the code to a newer style.
> test: fix assertions for newer jdks and refactor old test code.

- src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java
- src/test/java/spoon/test/compilation/CompilationTest.java
- src/test/resources/simple-module/module-info.java
- src/test/resources/simple-module/spoonmod/TestClass.java
Hi, I'm a new code intel SWE at Sourcegraph, and I'll be owning the https://github.com/sourcegraph/lsif-java project for the foreseeable time :) 
We came across an issue with Java 9 modules (tracking [here](https://github.com/sourcegraph/lsif-java/issues/8#issuecomment-666879764)), and I discovered a relevant `TODO` https://github.com/INRIA/spoon/blob/d7da4c6684/src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java#L94
The following screenshot gives some insight into the state leading up to the exception, where it seems to extract the wrong module name from the file folder
<details>
<summary>VSCode Java Debugger state</summary>
</details>
I havent tested this PR in multi-module scenarios, this was the simpler path instead of sorting `this.filenames` and `this.modNames` and …
> fix: fetchin module from the JDT compiler

- .gitignore
As requested in https://github.com/INRIA/spoon/pull/3549#issuecomment-682325394
> chore: added vscode files to .gitignore

- src/main/java/spoon/support/compiler/SpoonPom.java
- src/test/java/spoon/support/compiler/SpoonPomTest.java
- src/test/resources/maven-launcher/profiles/always/pom.xml
- src/test/resources/maven-launcher/profiles/pom.xml
- src/test/resources/maven-launcher/profiles/profile-only/pom.xml
By default with the existing constructors, all profiles are ignored to retain previous behaviour.
> feat: support for building Spoon models from modules declared in maven profiles

- src/main/java/spoon/support/compiler/SpoonPom.java
- src/test/java/spoon/support/compiler/SpoonPomTest.java
- src/test/resources/maven-launcher/hierarchy/child/pom.xml
- src/test/resources/maven-launcher/hierarchy/child/src/Test.java
- src/test/resources/maven-launcher/hierarchy/pom.xml
By climbing the pom.xml hierarchy to find the nearest ancestor that declares the source directory rather than immediately falling back to src/(main|test)/java if not declared in this immediate pom.
Also added interpolating (project|pom|'').basedir which is not uncommonly found in projects.
> fix: fix Maven source and test source directory resolving

- src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java
- src/test/java/spoon/generating/CorrectIdentifierTest.java
- src/test/resources/identifier/InliningImplementationMatcher.java
Sometimes intersectiontypes set simplename for a typereference to "?". We should allow this. Sadly we are cutting more and more corners in this check, because we have 1 check for all `setSimplename `methods. Now spoon would accept `int a? =3;`, which isn't problematic for analyzing code, but for transformations. More problematic is that we have at least 2 implementations for the identifier check, see [here](https://github.com/INRIA/spoon/blob/1de9318fcb97fa99ba18c3fd40025163a55df89b/src/main/java/spoon/reflect/visitor/JavaIdentifiers.java). But maybe we should continue step by step fixing the issue and after that find a solution for the problem described above.
> fix: intersection types with wildcard "?" are allowed as simplename

- src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java
- src/test/java/spoon/generating/CorrectIdentifierTest.java
Exception when indexing https://github.com/google/gson library in module mode (with `module-info.java` and `package-info.java`s) with https://github.com/sourcegraph/lsif-java with #3549 applied.
Exception does not occur when the library is not a module (with `module-info.java` and `package-info.java`s removed) (Note, need to double check the behaviour in each scenario: gson-module+3549, gson-not-module+3549, gson-module, gson-not-module)
Occurs with `TypeToken<List<String>[]>` @ https://github.com/google/gson/blob/master/gson/src/test/java/com/google/gson/GenericArrayTypeTest.java#L45
Debug state screenshots for context:
<details>
<summary>Stacktrace</summary>
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at …
```
> fix: fixed identifier correctness check when simplenamePart == ""

- src/main/java/spoon/support/QueueProcessingManager.java
This finally block is super confusing when stepping in the debugger, and not necessary.
> refactor: removing confusing finally block

- src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
- src/test/java/spoon/test/position/PositionTest.java
- src/test/java/spoon/test/position/testclasses/AnnotationWithAngleBracket.java
PositionBuilder would get caught in the `<` in the annotation string, resulting in `o2` == `o1` and no advancement being made.
This fix ignores the opening angle bracket if it comes at the start of the search space
> fix: fix non terminating PositionBuilder

- src/main/java/spoon/support/DefaultCoreFactory.java
- src/main/java/spoon/support/reflect/reference/CtWildcardReferenceImpl.java
to avoid creating a factory that we throw away just after
> refactor: call setBoundingType after we have a factory

- src/main/java/spoon/LovecraftException.java
- src/main/java/spoon/support/reflect/code/CtLambdaImpl.java
"It was from the artists and poets that the pertinent answers came"
In Spoon, we do believe that poetry has a place in software.
This class counters the dark side of the force which won at https://github.com/rust-lang/rust/issues/13871
> fix: poetry has a place in software

- src/main/java/spoon/IncrementalLauncher.java
- src/test/java/spoon/test/model/IncrementalLauncherTest.java
- src/test/resources/incremental/saveCacheIssue3404/A.java
Fix #3404 
I am not sure if this should treated as a bug or not, since essentially the source jar file is not present/visible to spoon.
> Review fix: fix incorrect assumption in IncrementalLauncher#saveCache

- src/main/java/spoon/reflect/cu/SourcePositionHolder.java
- src/main/java/spoon/reflect/declaration/CtElement.java
- src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
- src/test/java/spoon/test/position/TestSourceFragment.java
it's a good design practice that interfaces only depends on other interfaces, not on concrete implementation classes, so `getOriginalSourceFragment` returns a `SourceFragment`
Plus this removes untestable code in `SourcePositionHolder`, see https://sonarqube.ow2.org/component_measures?id=fr.inria.gforge.spoon%3Aspoon-core&metric=coverage&view=list
> refactor: SourcePositionHolder depends on SourceFragment

- pom.xml
- src/test/java/spoon/test/comment/CommentTest.java
- src/test/java/spoon/test/model/SwitchCaseTest.java
Some testcase needed a small fix before updating the jdt version. Mostly removing the preview flag for java13.
> chore: bump to jdt 3.23

- src/main/java/spoon/support/compiler/SpoonPom.java
- src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
Related to #3623 .
This test check that spoon sources parsed by spoon and pretty printed with the DefaultPrettyPrinter passes the rules from `checkstyle.xml`. 
Note that it is simple to define a different rule set if we want to.
This test is probably not meant to be run with the rest of unit tests (too slow) but can help to isolate more precise violations.
Output:
```
Violations: 
V: [WhitespaceAfter] -> 77
Ex: src/main/java/spoon/testing/utils/ModelUtils.java:23:59:
V: [NoWhitespaceBefore] -> 99
Ex: src/main/java/spoon/support/gui/SpoonModelTree.java:9:94:
V: [RightCurly] -> 2
Ex: src/main/java/spoon/metamodel/MetamodelProperty.java:391:17:
V: [ParenPad] -> 167
Ex: src/main/java/spoon/refactoring/MethodInvocationSearch.java:38:37:
V: [WhitespaceAround] -> 61
Ex: …
```
> test(DefaultPrettyPrinter): Check that DefaultPrettyPrinter is checkstyle compliant

- doc/architecture_test.md
- src/main/java/spoon/metamodel/MMMethod.java
- src/main/java/spoon/metamodel/MMMethodKind.java
- src/main/java/spoon/reflect/path/CtPathStringBuilder.java
- src/main/java/spoon/reflect/visitor/PrinterHelper.java
- src/main/java/spoon/support/StandardEnvironment.java
- src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
- src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java
- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/main/java/spoon/support/reflect/cu/CompilationUnitImpl.java
- src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
As discussed in #3628, here is a test case checking that every private field has a read. We dont need to check for writes, because a fieldRead without a fieldWrite before will never happen. Will writing this test case i found 8 unused fields. 
- One was a constructor parameter and i added a comment
- One is for later use and i commented it out
- 6 were simply unused.
> refactor: remove unused fields + corresponding architectural test

- src/main/java/spoon/support/comparator/CtLineElementComparator.java
- src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java
- src/test/java/spoon/test/annotation/AnnotationValuesTest.java
- src/test/java/spoon/test/annotation/testclasses/Summary.java
fix #3639 .
I seems that the entry set of the values contained an CtAnnotationImpl are ordered based on their source position. The issue is that so far `CtLineElementComparator#compare()` returns 0 if both element have `NoSourcePosition`. But this is the case when both elements are constructed programmatically. Hence the entry set arbitrarily retains only one of them.
My proposed solution is to make `CtLineElementComparator#compare()` returns 0 only if both elements have the same exact position or if both elements have `NoSourcePosition` and are equals. Otherwise we return -1 (i.e. order them aribtrarily). This way our entry set is pseudo order but does not delete unequals elements.
> fix(CtLineElementComparator): one can add two values to an annotation

- chore/travis/travis-jdk10.sh
- chore/travis/travis-jdk8.sh
- pom.xml
- src/main/java/Foo.java
We should break the build if a class is not covered.
According to https://sonarqube.ow2.org/component_measures?id=fr.inria.gforge.spoon%3Aspoon-core&metric=coverage&view=list all classes are covered.
Yet, here Jacoco says that 8 classes are not covered: https://travis-ci.com/github/monperrus/spoon/jobs/396558655
check (check-coverage) on project spoon-core: Coverage checks have not been met. See log for details
which ones?
> chore: break build if a class is not covered 

- spoon-pom/pom.xml
- spoon-visualisation/pom.xml
Fix #3648 
This also requires the credentials in the Jenkins Spoon-Snapshot-Deployer job to be updated with the OW2 credentials (hence titled as wip), but I think that should be all.
I'm not sure about the ID for the repository, is there some convention for that?
> chore: Use ow2-nexus as the snapshot repository

- spoon-decompiler/src/test/java/spoon/decompiler/test/architecture/DecompilerArchitectureTest.java
- src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
A few lines above the code states: 
// contract: Spoon's code never uses TreeSet constructor, because they implicitly depend on Comparable (no static check, only dynamic checks)
So lets fulfil the contract. Simply TreeSet -> HashSet. Shouldn't change anything.
> refactor(ArchitectureEnforcer): replace treeSet with hashset

- src/main/java/spoon/reflect/factory/TypeFactory.java
- src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
- src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
- src/test/java/spoon/support/visitor/java/testclasses/NPEInStaticInit.java
- src/test/java/spoon/support/visitor/java/testclasses/UnsatisfiedLinkErrorInStaticInit.java
Hello everyone,
We develop a static code analyzer and to do it we need to build models using Spoon for a lot of projects.
Some background information.
_This is how it was before:_
JDTImportBuilder::getOrLoadClass tried to get imported class through getClass().getClassLoader().loadClass(className) ... it didn't manage to find anything ('null', ClassNotFoundException, ...).
This led to the situation when JDTImportBuilder::getOrLoadClass returned 'null'. We couldn't get it and that was OK.
_This is how it is now:_
Recently JDTImportBuilder::getOrLoadClass tries to load class using JDTImportBuilder::loadClass.
That is, if 'factory.getEnvironment().getInputClassLoader' existed, we tried to get it from there, otherwise we got class, same as before.
So through the factory environment you are …
> fix: more resilient wrt to errors during shadow class building

- src/main/java/spoon/Launcher.java
- src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
A common issue that I get while analysing big projects is that the analysis fails just because a few files contain issues, or special characters that are not allowed by the Java compiler: like for example archetype resource files:
```Java
#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
import ${package}.path.to.Clazz;
```
This very simple modification ensures that Spoon provides a best-effort attempt at parsing a certain project without failing just because of one malformed file. In case an error occurs, a message is printed on the console, so the user is notified.
I am not very practical of Spoon's internals, so there might be better solutions to this. If that's the case, pointers on how to implement a better one are welcome :)
> refactor: add support for malformed files through inheritance

- src/main/java/spoon/reflect/declaration/CtModifiable.java
- src/main/java/spoon/support/reflect/CtModifierHandler.java
- src/main/java/spoon/support/reflect/code/CtCatchVariableImpl.java
- src/main/java/spoon/support/reflect/code/CtLocalVariableImpl.java
- src/main/java/spoon/support/reflect/declaration/CtAnonymousExecutableImpl.java
- src/main/java/spoon/support/reflect/declaration/CtConstructorImpl.java
- src/main/java/spoon/support/reflect/declaration/CtFieldImpl.java
- src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java
- src/main/java/spoon/support/reflect/declaration/CtParameterImpl.java
- src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
- src/test/java/spoon/test/modifiers/ModifiersTest.java
- src/test/java/spoon/test/modifiers/testclasses/AbstractClass.java
fix #3651 
Implemented modifiers from ModifierKind (`Transient`, `Volatile`, `Synchronized`, `Native`, `Strictfp`) for  CtModifiable class.
> feature: add CtModifiable#isTransient and related methods

- src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
Fix #3675 
This PR fixes the problem explained in #3675 by overriding `printTypes` in `SniperJavaPrettyPrinter`, and trying to resolve a compilation unit from the types passed in. If no compilation unit can be found, or the types have mismatching compilation units, it raises an exception. Two new tests verify the behavior within a reasonable amount of certainty.
> fix: Fix NullPointerException in SniperJavaPrettyPrinter.printTypes

- pom.xml
One cannot use the Jar in Java 11, this crashes as follows, see [bug report](https://github.com/INRIA/spoon/issues/3514#issuecomment-667580825) from @layornos
```
$ java -jar target/spoon-core-8.4.0-SNAPSHOT-jar-with-dependencies.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/StackLocator$FqcnCallerLocator
at org.apache.logging.log4j.util.StackLocator.<clinit>(StackLocator.java:37)
at org.apache.logging.log4j.util.StackLocatorUtil.<clinit>(StackLocatorUtil.java:33)
at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:588)
at spoon.Launcher.<clinit>(Launcher.java:589)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.StackLocator$FqcnCallerLocator
at …
```
> fix Jar execution on Java 11

- src/main/java/spoon/support/reflect/code/CtCaseImpl.java
- src/test/java/spoon/test/model/SwitchCaseTest.java
Potential fix for #3680. I'm unsure why the problem lived for so long, but setting the parent in `addCaseExpression` should fix it. Is there any other place the parent should have been set?
> Review: Fix(CtCase): add fix for missing parents

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java
- src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentPrinter.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/ClassWithSingleImport.java
Fix #3698 
This is ready for review, see comments further down :)
> fix: Fix Sniper printer failing to put added import statement on separate line

- src/main/java/spoon/reflect/factory/ExecutableFactory.java
- src/test/java/spoon/test/parameters/ParameterTest.java
- src/test/resources/parameter/ParameterResource.java
> fix: fix incorrect parent for type reference of a CtParameter

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java
- src/test/java/spoon/test/model/TypeTest.java
- src/test/resources/duplicates-in-submodules/README.md
- src/test/resources/duplicates-in-submodules/moduleA/duplicates/Duplicate.java
- src/test/resources/duplicates-in-submodules/moduleA/duplicates/Main.java
- src/test/resources/duplicates-in-submodules/moduleA/duplicates/WithNestedEnum.java
- src/test/resources/duplicates-in-submodules/moduleB/duplicates/Duplicate.java
Fix #3707 
This crash occurs very rarely. The requirement is that there is a _package private_ class B with a nested type C, and have some other class A import B.C and then make an unqualified access to some member C.someMember. At the samie time, there must be a duplicated class in the same package and `setIgnoreDuplicateDeclarations(true)` must be active. The import + access in type A forces Spoon to search for type C with `JDTTreeBuilderQuery::searchTypeBinding`, in which a `NullPointerException` would occur if there was a duplicated class that was processed before finding the sought type. The reason is that a duplicated class will have `binding = null`.
This does not happen if Spoon is not ignoring duplicates, because then an appropriate error on finding duplicate declarations is …
> fix: Fix NullPointerException when allowing duplicate classes

- src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
- src/main/java/spoon/support/sniper/internal/IndentationDetector.java
- src/main/java/spoon/support/sniper/internal/MutableTokenWriter.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/indentation/FourSpaces.java
- src/test/resources/indentation/NoTypeMembers.java
- src/test/resources/indentation/Tabs.java
- src/test/resources/indentation/TwoSpaces.java
Fix #3715 
This PR introduces indentation style inference to the sniper printer. It's simple in principle: look at the whitespace preceding the top-level type members and make a best guess as to what the indentation style is out of 1, 2 or 4 spaces/tabs. The original set of source code fragments are used to detect indentation.
If for any given compilation unit no top-level elements can be found, indentation detection defaults to tabs.
We will start using this ASAP in Sorald, preferably with the new beta release this Saturday if we can get it merged by then. Therefore, we should be able to detect any obvious issues this might introduce relatively quickly.
Note: This will crash and burn if you try to sniper print a compilation unit that does not have an origin source (e.g. if you add a CU …
> review: feat: Make sniper printer infer indentation style of compilation unit

- src/main/java/spoon/support/sniper/internal/IndentationDetector.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/indentation/singletypemember/FourSpaces.java
- src/test/resources/indentation/singletypemember/Tabs.java
- src/test/resources/indentation/singletypemember/TwoSpaces.java
This fixes a rather silly rounding error in the indentation detection: if there's a single type member, `usesTabs = 1 / 2 = 0`. Therefore, a single type member will always be regarded as indented with tabs, regardless of actual indentation. It's extra silly because it affected the particular use case that I implemented the indentation detection for in the first place. Now explicitly uses doubles instead for the comparison.
Tiny rounding errors don't really matter here, in the general case there will either be 0 tabs or all tabs. It was just the massive rounding error of integer division of `1 / 2` that was problematic.
> review: fix(sniper): Fix rounding error in indentation detection on single type member

- src/main/java/spoon/reflect/visitor/ImportCleaner.java
- src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
- src/test/java/spoon/test/prettyprinter/testclasses/ClassUsingStaticMethod.java
- src/test/java/spoon/test/prettyprinter/testclasses/ClassWithStaticMethod.java
Hello, 
I'm opening this pull-request that contains a test to reproduce the bug reported in #3618 and #3214.
Thank you
> Fix: fix pretty-printing of imports for static methods

- src/main/java/spoon/reflect/visitor/ImportCleaner.java
- src/test/java/spoon/reflect/visitor/ImportCleanerTest.java
- src/test/resources/unresolved/UnresolvedImport.java
Fix #3729 
This is ready for review. As explained in #3729, the problem here is that unresolved imports and "regular" imports never compare equal, even if they are textually identical (which is what actually matters here), causing `ImportCleaner` to duplicate them. With this PR, imports computed by the `ImportCleaner` are only added to the CU if they are unequal to any existing imports, both in terms of object equality and textual equality.
> fix: Avoid import duplication on unresolved imports

- doc/custom-pretty-printing.md
- doc/launcher.md
the info about pretty-printing is better in custom-pretty-printing.md than in launcher.md.
> doc: centralizes info about pretty-printing

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/test/java/spoon/test/methodreference/MethodReferenceTest.java
- src/test/resources/ReferenceBuilder-null-pointer/Foo.java
`ReferenceBuilder#tryRecoverTypeArguments` doesn't check whether `expectedType.typeArguments()` is null and crashes with an NPE. Could be a bug in JDT, but the check nevertheless should be there - [ParameterizedTypeBinding](https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.tests.model/workspace/Compiler/src/org/eclipse/jdt/internal/compiler/lookup/ParameterizedTypeBinding.java) has a lot of null-checks for this field.
> fix: fix NPE in ReferenceBuilder#tryRecoverTypeArguments

- src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentPrinter.java
- src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
- src/test/java/spoon/test/position/TestSourceFragment.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/TypeMemberComments.java
Fix #3697 
~This is heavily WIP, I don't have a fix yet. The problems are thoroughly described in #3697~
This PR introduces a fix for the problem of disappearing whitespace between comments and type members with modified modifier lists. For example, given the following commented type member:
```java
// this is a type member
private static int number = 2;
```
Adding a `final` modifier to the modifier list would result in the following print-out:
```java
// this is a type memberprivate static int number = 2;
```
The source fragments will look something like so:
```
"// this is a type member"
["\n\t", "private", "static"]
...
```
Where the comment is a normal `ElementSourceFragment` and the list is a `CollectionSourceFragment`. The reason the whitespace isn't printed is that the it becomes …
> fix: Fix sniper printing of comments when changing modifiers

- src/main/java/spoon/support/util/ModelSet.java
Reading the model sometimes leads to it's modification: for example, `CtTypeReferenceImpl.getTypeDeclaration()` may start building a shadow type which is then added to the model. This causes modification of the `types` ModelSet in CtPackageImpl, which is backed by a TreeSet (which is in turn backed by a TreeMap). Thus a TreeMap can be modified concurrently when multiple threads try to get a type declaration (or an executable declaration), which sometimes [causes an infinite loop](https://ivoanjo.me/blog/2018/07/21/writing-to-a-java-treemap-concurrently-can-lead-to-an-infinite-loop-during-reads/).
This fix is mostly "treating the symptoms" and it doesn't provide sufficient synchronization across the library so ConcurrentModificationException is still possible, but it at least prevents the …
> perf: handle some concurrency in ModelSet

- src/main/java/spoon/support/visitor/AbstractTypingContext.java
Semi-fix for #3734. Doesn't fix the cause of the issue, but at least fixes invalid element cloning logic. Though I'm not 100% sure whether no-parent elements should be handled or not. Anyway, in case they are supposed to be rejected there should be a separate check.
> fix: ParentNotInitializedException in AbstractTypingContext

- pom.xml
- src/test/java/spoon/test/comment/CommentTest.java
fixes #3731 
The fix was already as a todo there. JDT allows only for the latest java version preview features. Updating to version 15 and disabling preview features works for now. As soon as we implement java 15 preview features, we need to reenable them. 
As we discussed somewhere, some testhelpers could be super useful. 
```java
class JDTVersions {
/**
* Returns the latest jdt supported java version.
*/
String getLatestSupportedJavaVersion()
/**
* Checks if a jdt version supports preview features
*/
boolean String isPreviewSupported(String/int version)
}
```
This could remove a lot of hard coded versions from the test code. In many cases a latest version is what we want, but we simply write the latest current version. The supported jdt versions has some kind of api see …
> chore(jdt): bump jdt version and fix testcase accordingly

- src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentPrinter.java
- src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
Fix #3732 
This PR fixes the bug described in #3732 by keeping track of the last printed element, and allowing the backwards search for previous whitespace to bypass modifier lists that have not been printed. To illustrate the effect of the fix, here's the initial test case file:
```java
public class TypeMemberComments {
// field comment
public static int NON_FINAL_FIELD = 42;
// method comment
public void nonStaticMethod() {
}
// nested type comment
private class NonStaticInnerClass {
}
}
```
The test case removes all of the modifiers from all of the type members. Before the fix, the sniper-printed result was the following:
```java
public class TypeMemberComments {
int NON_FINAL_FIELD = 42;
void nonStaticMethod() {
}
class NonStaticInnerClass {
}
}
```
Note that the comments have …
> fix: correctly sniper-print type member comments after removal of all modifiers

- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
#3752 
A branch that was developed in parallel with the Windows build being added had a test that does not pass on Windows. This PR disables that test for Windows. It should be fixed along with the other failing sniper tests, they all likely suffer from the same or similar issues.
> test Disable failing test on Windows build

- src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/MultipleTopLevelTypes.java
Fix #3760 
See #3760 for a description of the problem. I think it's more work than it's worth to try to allow for sniper printing of a subset of a compilation unit's types. There's an initial problem in that DJPP clones the CU if it discovers that one is trying to print only a subset of the types (this is where the current crash described in #3760 comes from). Even working around that, there's still a bit of trickery involved in printing just a subset of the types. A couple more hours on this and I could _probably_ solve it, but I just don't think it's worth it.
This PR just throws a more informative exception that looks like this:
```
java.lang.IllegalArgumentException: Can only sniper print exactly all declared types of the compilation unit. Given types: [MultipleTopLevelTypes]. …
```
> refactor: throw informative exception when sniper printing cannot be done

- spoon-control-flow/pom.xml
Change made by @monperrus. If I understood correctly it solves an issue with Maven repository deployment of spoon-control-flow.
> chore: add SNAPSHOT tag to spoon-control-flow pom.xml artifact version

- src/main/java/spoon/reflect/factory/PackageFactory.java
- src/test/java/spoon/test/compilationunit/TestCompilationUnit.java
- src/test/java/spoon/test/ctType/CtTypeTest.java
- src/test/java/spoon/test/factory/FactoryTest.java
- src/test/java/spoon/test/module/TestModule.java
Fix #3769 
The issue describes the symptoms and the root cause of them. The tl;dr is that `PackageFactory.get(String)` only searches for packages in the unnamed module, causing type resolution in named modules to not work correctly. This PR fixes that by searching for packages in all modules.
As noted in #3769, there's probably a whole lot of code that assumes that there's only the unnamed module, and therefore use `CtModel.getRootPackage()` (which returns the root package of the unnamed module) as the definitive root package, which as of Java 9 is not appropriate.
> fix: Search for packages in all available Java modules

- src/main/java/spoon/reflect/reference/CtTypeReference.java
`CtTypeReference.getDeclaration()` says that `CtTypeReference.getTypeDeclaration()` is great because it _never returns null_. That's actually not the case: `getTypeDeclaration()` does return null if the referenced type is neither in the input source nor on the classpath. It even says so in the doc for `getTypeDeclaration()`. For completeness, here's a way to make that happen:
```java
Launcher launcher = new Launcher();
CtTypeReference<?> ref = launcher.getFactory().Type().createReference("SomeType");
assert ref.getTypeDeclaration() == null;
```
This PR simply changes "never" to "less often". The reason I'm changing this is because I ran into some (to me) inexplicable `NullPointerException`s due to a method I thought would never return null :)
> doc: Correct doc about getTypeDeclaration returning null

- src/main/java/spoon/reflect/visitor/ImportCleaner.java
- src/test/java/spoon/reflect/visitor/ImportCleanerTest.java
- src/test/resources/inherit-static-method/Base.java
- src/test/resources/inherit-static-method/Derived.java
- src/test/resources/inherit-static-method/pkg/Base.java
Fix #3797 
This PR prevents the ImportCleaner from importing static methods that are inherited from a parent class. Such imports cause compile errors if the static method is defined in a class in the default package. At best, they do absolutely nothing.
> fix: Prevent ImportCleaner from importing inherited static methods

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/test/java/spoon/test/trycatch/TryCatchTest.java
- src/test/java/spoon/test/trycatch/testclasses/CatchWithUnqualifiedType.java
Fix #3799 
Fixes the problem by building the type reference with a higher-level method in the JDTTreeHelper, where this particular problem is already addressed. I had to adapt the signature of `JDTTreeBuilderHelper.createCatchVariable()` to also accept a scope for this, but I think this is more correct than it was previously.
> fix: Fix unqualified type reference in catch block becoming qualified

- src/main/java/spoon/Launcher.java
- src/main/java/spoon/compiler/Environment.java
- src/main/java/spoon/processing/AbstractProcessor.java
- src/main/java/spoon/reflect/visitor/ModelConsistencyChecker.java
- src/main/java/spoon/support/Level.java
- src/main/java/spoon/support/LogLevel.java
- src/main/java/spoon/support/RuntimeProcessingManager.java
- src/main/java/spoon/support/StandardEnvironment.java
- src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
- src/test/java/spoon/test/logging/LogTest.java
- src/test/java/spoon/test/processing/ProcessingTest.java
- src/test/java/spoon/test/processing/processors/TestProcessor.java
#3775 
This PR introduces a self-defined `LogLevel` enum that can be used to get or set the logging level. The reason we need this is that `org.slf4j.event.Level` makes Spoon backwards-incompatible with libraries that uses `slf4j-api < 1.7.15`. Which is not good. I've tested this locally and it fixes the test errors in Casper, as mentioned in #3775.
**This is a breaking change**, as the return type of `Environment.getLevel()` is changed. #I purposefully changed the name of the type from `Level` to `LogLevel` to make this more evident. #3755 was in fact also breaking, as the `org.slf4j.event.Level` is not the same as the previous `Level` type from `log4j`. With this change, however, we won't have breakage again, as we now define the type ourselves.
I have two more thoughts on this.
1. Do …
> fix: Use self-defined logging level instead of org.slf4j.event.Level

- spoon-visualisation/README.md
with the list of the current modules I get:
java.lang.module.FindException: Module annotations not found
By updating to --add-modules=ALL-MODULE-PATH, the error is gone and the UI start correctly
> doc: fix command line to launch visualization

- .github/workflows/tests.yml
Fix #3745 
This PR disables HTTP connection pooling in CI, which is known to cause issues with Azure (which GitHub Actions runs on).
> chore: Disable Maven HTTP connection pooling for all workflows

- src/main/java/spoon/support/compiler/jdt/FileCompilerConfig.java
Moved invariant variable outside of loop.  Will hopefully give performance boost on projects with lots of source files.
> perf: move code outside loop in FileCompilerConfig.initializeCompiler

- src/test/java/spoon/test/processing/processors/ParallelProcessorTest.java
#3806 
This PR just adds assertions that produce more informative output than the current ones for ParallelProcessorTest. For example, this is the current output from an `assertTrue` in `compareWithSingleThreaded3`:
```
Error:  spoon.test.processing.processors.ParallelProcessorTest.compareWithSingleThreaded3  Time elapsed: 0.171 s  <<< FAILURE!
java.lang.AssertionError
at spoon.test.processing.processors.ParallelProcessorTest.compareWithSingleThreaded3(ParallelProcessorTest.java:166)
```
Whereas with this PR, we get something like this instead (note that I faked the numbers here to get an error!):
```
[ERROR] spoon.test.processing.processors.ParallelProcessorTest.compareWithSingleThreaded3  Time elapsed: 0.056 s  <<< FAILURE!
java.lang.AssertionError: 
Expected: <180>
but: was <181>
at …
```
> test: improve the assertions in ParallelProcessorTest

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
The docs for DJPP get/setPreprocessors currently contain a broken link to some (probably very) old type that is no longer available, and aren't particularly clear about how DJPP actually uses the preprocessors. This PR removes the broken link and clarifies how the preprocessors are used.
> doc: Improve documentation for the DJPP get/setPreprocessors methods

- .github/workflows/tests.yml
Fix #3840
This PR adds a cache for Maven dependencies in the primary build matrix. The cache is dependent on the current date, and so will never be used for more than 24 hours. This makes the risk of stale dependencies causing trouble relatively small, and at worst the problem will go away the next day.
The speedup is significant, e.g. for `Tests with Java 1.8 on ubuntu-latest`:
* Before cache: [12m31s](https://github.com/INRIA/spoon/runs/2111403925)
* After cache: [9m9s](https://github.com/INRIA/spoon/pull/3842/checks?check_run_id=2111720116)
All-in-all, we see roughly a 3-minute reduction across all jobs individually, as well as the total wall time for CI (not counting CPU time, but actual time a developer has to wait), which is down from ~14 to ~11 minutes.
Unfortunately, I couldn't …
> review: chore: Add daily cache of Maven dependencies

- .github/workflows/tests.yml
Fix #3839 
This PR significantly cleans up the CI output of the primary build matrix by building the project and fetching dependencies in a separate step, before running the tests. Fetching _all_ test dependencies requires a little hack (start running tests, then abort after 20 seconds), because no matter what you do Maven will not fetch certain dependencies needed for test execution before-hand. Even when using something like `dependency:go-offline`.
If you have a look at the [test step of the current build (NOTE: You may need to refresh after clicking this link)](https://github.com/INRIA/spoon/pull/3838/checks?check_run_id=2111450564#step:7:1), the output actually starts with tests, and not with thousands of lines of "download progress", as was previously the case.
> review: chore: Clean up output in GitHub Actions workflows

- src/main/java/spoon/LovecraftException.java
Hi,
This PR fixes 1 violations of [Sonar Rule 1444: '"public static" fields should be constant'](https://rules.sonarsource.com/java/RSPEC-1444).
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 1444](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#public-static-fields-should-be-constant-sonar-rule-1444).
> refactor: Fix violation of Sonar rule 1444

- src/main/java/spoon/processing/AbstractParallelProcessor.java
- src/test/java/spoon/test/processing/processors/ParallelProcessorTest.java
Fix #3806 
~Currently just a test to reproduce the problem. Want to see if it works on GitHub Actions machines, which I believe have 2 cores. So it should work.~
This PR fixes a race condition in AbstractParallelProcessor. 67c8aa3 introduces a test that reproduces the problem, and 40a9602 fixes the problem by keeping track of the last job submitted for each processor and then waiting (indefinitely) for these to terminate. We only need to keep track of the latest job, as each processor only handles one job at a time.
We could also busy-wait on the processors queue to fill back up, which is somewhat less complex, but less efficient and less explicit. I prefer the current solution.
> fix: fix a race condition in AbstractParallelProcessor

- src/main/java/spoon/support/compiler/SpoonPom.java
Hi,
This PR fixes 1 violations of [Sonar Rule 2142: '"InterruptedException" should not be ignored'](https://rules.sonarsource.com/java/RSPEC-2142).
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 2142](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#interruptedexception-should-not-be-ignored-sonar-rule-2142).
> fix: Fix 1 violation of Sonar rule 2142

- src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentPrinter.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/EmptyClass.java
Fix #3855 
This fixes a bug causing the sniper printer to not prepend whitespace to type members and local variables added at the start of a non-empty collection. For example, given this class:
```java
class Cls {
private int someInt = 2;
}
```
adding a new field `private int otherInt = 3` at the top would be printed like so:
```java
class Cls {private int otherInt = 3;
private int someInt = 3;
```
The same thing applies to local variables in non-empty statement lists.
The bug is caused by the sniper printer looking the source fragment of any `CtModifiable` or `ModifierKind` only by role, which causes _any_ source fragment belonging to a `CtModifiable` to match any other `CtModifiable`. This itself is required to avoid other corner cases, it appears. Thus, the sniper always thinks it …
> fix: Fix sniper printer failing to prepend whitespace to top-added CtModifiable

- spoon-visualisation/pom.xml
- spoon-visualisation/src/main/java/module-info.java
- spoon-visualisation/src/main/java/spoon/visualisation/instrument/SpoonCodeInstrument.java
- spoon-visualisation/src/main/java/spoon/visualisation/spoon/TreePrinter.java
- spoon-visualisation/src/test/java/spoon/visualisation/instrument/SpoonCodeInstrumentTest.java
Related to #3860
Interacto is the graphical lib used by Spoon Visualiser.
Available on maven central since the 4.0 version (see https://search.maven.org/artifact/io.github.interacto/interacto-javafx/4.3.1/jar) it was before on the Inria Maven repo.
We have to update Interacto to its latest version to get from Maven Central.
This is the goal of this PR.
> fix(spoon-visualiser): bump Interacto to use the latest version on Central

- doc/CNAME
#3759 
The CNAME record is required for the custom URL to work, and currently it has been added manually over in spoonlabs.github.io.
We could also generate the CNAME file in the deployment script, but it seems simpler to just have it in the repo.
> chore: Add website CNAME

- doc/_data/sidebar_doc.yml
#3759 
Changes the URL to the apidocs to be site-relative, rather than absolute. This makes it easier to do local development of the site.
I don't quite understand why it has to be an `external_url`, but if you try just `url` all of the forward slashes are filtered out and the url ends up being `<DOMAIN>/mvnsitesspoon-coreapidocs`, which isn't what we want. I was unable to find any relevant documentation about this on the Jekyll website, so I just went with what works: a site-relative URL defined as `external_url`.
> chore: Make URL to apidocs site relative

- doc/_config.yml
#3759 
The `redcarpet` processor isn't supported by Jekyll 4.0+, see https://github.com/jekyll/jekyll/issues/7838#issuecomment-537254511.
> chore: Use the kramdown Markdown processor for Spoon's website

- src/main/java/spoon/pattern/PatternBuilder.java
- src/main/java/spoon/reflect/visitor/PrinterHelper.java
- src/main/java/spoon/support/visitor/java/reflect/RtMethod.java
- src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
Hi,
Added documentation for 3 undocumented public methods and lowered the threshold for documentation to 32
issue: #1876
I hope the documentations makes some sense :P
Best,
Rohitesh
> doc: Add API documentation to 3 undocumented public methods

- src/main/java/spoon/javadoc/internal/Javadoc.java
- src/main/java/spoon/javadoc/internal/JavadocBlockTag.java
- src/main/java/spoon/javadoc/internal/JavadocDescription.java
- src/main/java/spoon/javadoc/internal/JavadocInlineTag.java
- src/main/java/spoon/javadoc/internal/JavadocSnippet.java
- src/main/java/spoon/support/comparator/CtLineElementComparator.java
- src/main/java/spoon/support/comparator/DeepRepresentationComparator.java
- src/main/java/spoon/support/reflect/CtExtendedModifier.java
- src/main/java/spoon/support/util/ModelList.java
Hi,
This PR fixes 9 violations of [Sonar Rule 2057: '"Serializable" classes should have a "serialVersionUID"'](https://rules.sonarsource.com/java/RSPEC-2057).
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 2057](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#serializable-classes-should-have-a-serialversionuidsonar-rule-2057).
> fix: Fix violations of Sonar rule 2057

- doc/faq.md
- doc/jenkins/build.sh
- spoon-visualisation/pom.xml
> REVIEW remove outdated instances of maven.inria.fr

- spoon-pom/pom.xml
- spoon-smpl/pom.xml
#3216 
See my latest comments in #3216. I don't see any reason to declare the snapshot repository for anything but distribution management. In Jenkins jobs, we inject the snapshot repository into pom files of other projects.
If we agree to merge this, I'll (after merge) go over all Jenkins jobs and make sure that they correctly pull the latest snapshot (I already know of several that pull from the old snapshot repository).
EDIT: Apparently, `spoon-smpl` depends on a SNAPSHOT version of `spoon-control-flow`, so it does need the snapshot repository enabled by default. But that's the concern of `spoon-smpl`, and not _all_ of the Spoon Maven modules, and so we define it only in `spoon-smpl`.
> review: chore: Remove snapshot repository from parent pom

- doc/spoon_smpl.md
- spoon-smpl/README.md
- spoon-smpl/smpl_grammar.txt
Adds a table listing some of the currently supported SmPL features to the spoon-smpl README and fixes minor issues in related docs.
> doc: update spoon-smpl README and related docs

- src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
- src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java
- src/test/java/spoon/test/generics/GenericsTest.java
- src/test/java/spoon/test/generics/testclasses3/UpperBoundedWildcard.java
- src/test/java/spoon/test/generics/testclasses3/UpperBoundedWildcardUser.java
> refactor: implement check for recursive type bound without using Object

- doc/jenkins/inject_spoon_snapshot.py
This PR adds a Python script that updates the Spoon version in a pom.xml file to the latest snapshot version. It does so by 1) injecting the snapshot repository into the pom file (if it's not already there), and 2) running `mvn versions:use-latest-versions` with snapshots enabled to update the version of Spoon, and 3) running `mvn dependency:purge-local-repository` to avoid using an old snapshot of the same version.
The script works with Python 3.5+ and requires the `defusedxml` package. We will use this for the smoke tests in the Jenkins pipeline where a project uses Spoon (i.e. Spoon is already a dependency), and we want to run its test suite with the latest snapshot.
> chore: Add script for SNAPSHOT version injection in CI

- .github/workflows/tests.yml
Fix #3872 
This PR updates the Actions workflow to use the latest version of setup-java.
> chore: update github action to use setup-java v2.0.0

- doc/_release/WEBSITE.md
This PR documents how the website is currently deployed, and how one can build it locally.
> doc: Add website deployment documentation

- src/main/java/spoon/reflect/code/CtAbstractInvocation.java
- src/main/java/spoon/support/reflect/code/CtConstructorCallImpl.java
- src/main/java/spoon/support/reflect/code/CtInvocationImpl.java
- src/test/java/spoon/test/constructorcallnewclass/ConstructorCallTest.java
- src/test/java/spoon/test/invocations/InvocationTest.java
#3884
This PR adds the method `CtAbstractInvocation.addArgumentAt(int, CtExpression<?>)` to the public API, as discussed in #3884.
This PR will determine whether we go with the `addX` naming convention, or the `addXAt` naming convention. Both are already present in the project, but we should adopt one as the predominant style. I favor `addXAt(int,CtElement)` because it makes it easier to see that the method is distinct, but `addX(int,CtElement)` is also valid as that is a common overload in the Java standard library collections.
> feat: Add CtAbstractInvocation.addArgumentAt method

- src/main/java/spoon/reflect/declaration/CtAnonymousExecutable.java
- src/main/java/spoon/reflect/declaration/CtExecutable.java
- src/main/java/spoon/support/reflect/code/CtLambdaImpl.java
- src/main/java/spoon/support/reflect/declaration/CtAnonymousExecutableImpl.java
- src/main/java/spoon/support/reflect/declaration/CtExecutableImpl.java
- src/test/java/spoon/test/constructor/ConstructorTest.java
- src/test/java/spoon/test/lambda/LambdaTest.java
- src/test/java/spoon/test/method/MethodTest.java
#3884 
This PR provides an API to add a parameter in `CtExecutable`s at a specified position. Since there are few classed which inherit from `CtExecutableImpl`, we should test this API for all those classes.
~- CtAnonymousExecutable~ (cannot add parameters to an anonymous class in Java)
> feat: Add CtExecutable.addParameterAt

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/test/java/spoon/test/ctClass/CtClassTest.java
Fix #3903 
This PR fixes the infinite loop described in #3903 by assuming that any qualified name that contains a type parameter reference is fully qualified. I'm pretty sure that assumption is valid, as one can only reference a type parameter from within the class or method that defines it.
In any case, it's better than an infinite loop :)
> fix: Fix infinite loop on type parameter in qualified name

- pom.xml
Required to make #3907 green before merging, related to #3906
This PR moves the hard-coded Checkstyle config location into the [`checkstyle.config.location` property](https://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html#configLocation) (default user property for the `<configLocation>` element). This provides a default that can be overridden from the command line by specifying `-Dcheckstyle.config.location=path/to/some/checkstyle.xml`. This in turn is necessary for #3906 to be able to run with all the configuration in the pom for Checkstyle, but a different Checkstyle config.
> chore: Move Checkstyle config location into property

- .github/workflows/tests.yml
- src/main/java/spoon/FluentLauncher.java
Fix #3788 
This PR adds a workflow job that runs https://github.com/spoonlabs/sorald-buildbreaker on Spoon, and fails the build if the changed lines (relative to master) contains any repairable violations. Here's an example of where it finds a violation in the diff: https://github.com/INRIA/spoon/pull/3912/checks?check_run_id=2543019363#step:3:123. Note that the final commit in this PR, which just removes the artificial rule violation, causes the build to go green!
Currently, it's a separate job, but once we deem buildbreaker to be stable enough we can simply incorporate it into the `extras` job by adding this step:
```yml
- name: Run Sorald Buildbreaker
uses: SpoonLabs/sorald-buildbreaker@35c1a784848bd3182cfcc8a584cff90560fa6371 # dev version
with:
source: 'src/main/java'
ratchet-from: …
```
> chore: Add job for sorald-buildbreaker

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/test/java/spoon/test/trycatch/TryCatchTest.java
- src/test/java/spoon/test/trycatch/testclasses/CatcherWithQualifiedAndUnqualifiedTypeRefs.java
- src/test/java/spoon/test/trycatch/testclasses/MultipleUnqualifiedTypesInSingleCatcher.java
Fix #3917 
This PR fixes a problem where simply qualified type references in union types inside of catchers are parsed as fully qualified.
> ix: Fix unqualified type becoming qualified in union type catch

- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
#3919 
This is the first PR to start the migration to JUnit5. It's a pure refactoring.
I intend to use some JUnit5 features in this test class in the coming weeks, which is why I wanted to start the migration with this particular class :)
> test: Migrate TestSniperPrinter to JUnit5

- .github/workflows/tests.yml
- chore/ci-checkstyle-javadoc.sh
Fix #3922 
This PR improves the usability of the method Javadoc quality script, and links to the issue related to using it #3923. Additionally, non-POSIX-compliant comparisons have been removed to make the script compatible with more shells.
In terms of output, if the script failed in CI it would previously just print the amount of errors, but now ALSO prints this:
```
Run the chore/ci-checkstyle-javadoc.sh script locally to find errors
See https://github.com/inria/spoon/issues/3923 for details
```
Local use has also been improved, here's the help output:
```
$ ./chore/ci-checkstyle-javadoc.sh
usage: ci-checkstyle-javadoc.sh [<regex>|COMPARE_WITH_MASTER]
<regex>: A regex to filter output lines by (typically just a file path)
COMPARE_WITH_MASTER: Compare the amount of errors on the current …
```
> chore: Improve ci-checkstyle-javadoc.sh usability

- src/main/java/spoon/processing/AbstractParallelProcessor.java
Hi,
This PR fixes 1 violation of [Sonar Rule 2142: '"InterruptedException" should not be ignored'](https://rules.sonarsource.com/java/RSPEC-2142).
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 2142](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#interruptedexception-should-not-be-ignored-sonar-rule-2142).
The concerned violation can viewed on the [OW2 SonarQube instance](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&issues=AXh4mEuvLwoiZThdxVl5&open=AXh4mEuvLwoiZThdxVl5), and is [the only new bug violation introduced in the past... long time](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spo …
> fix: Fix violation of Sonar rule 2142

- chore/ci-checkstyle-javadoc.sh
Related to #3923 
I had accidentally left an early exit at the top of the script causing it to be unusable if checked out to the master branch. That's not desirable as very likely, someone first looking into #3923 will be checkout out to the master branch, and may just give up as the script ostensibly doesn't work.
This PR just moves that early exit into the appropriate place (when running the compare command).
> chore: Fix incorrect early exit in Javadoc quality script

- src/main/java/spoon/reflect/visitor/CtScanner.java
#3923 
This PR adds 11 `@param` tags to existing Javadoc comments in `CtScanner`, improving the Javadoc quality score for the project by 11.
```
JAVADOC QUALITY SCORE (lower is better)
Compare: 2652
Current: 2641
```
All _existing_ javadoc in `CtScanner` are now up-to-snuff, but there are still a lot of undocumented public methods (which is not the concern of #3923).
> doc: Add missing Javadoc tags to documented public methods in CtScanner

- src/test/java/spoon/test/logging/LogTest.java
#3919 
The `LogTest` has long been a pet-peeve of mine, because it _always fails_ when I run all tests in IntelliJ IDEA. Running it alone is fine, and running it with Maven is also fine. I think it's something with the JUnit4 parameterized test runner (which never made it past the experimental stage) that doesn't work well with my particular version of IDEA.
This PR migrates LogTest to JUnit5 and its much better parameterized test support. And finally I can run all tests and not have this one fail.
**Ignore whitespace changes in diff:** This PR has a _lot_ of indentation changes. To view the diff without whitespace changes, append `?w=1` to the GitHub URL (or click this link: https://github.com/INRIA/spoon/pull/3939/files?w=1)
> test: Migrate LogTest to JUnit5

- src/main/java/spoon/support/reflect/code/CtForImpl.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/ForLoop.java
Fix #3940 
The `setForInit` and `setForUpdate` does not call change listeners if the value set was the empty list or null. Note that deleting the last element in a e.g. a for init is implemented such that `setForInit` is called with an empty list, and so the last deletion is not registered. This causes problems for the sniper printer, as a patch that only deletes the final element in a for update or init does not register any changes, and so the sniper just prints the original source code.
This PR simply moves the `onDeletAll()` call to the change listeners to the top of the `setForInit` and `setForUpdate` methods, such that they are always called. This is valid, as setting an empty list or `null` is equivalent to clearing the list.
> fix: Ensure that for init/update are registered in listeners

- src/test/java/spoon/test/filters/FilterTest.java
#3919
This PR migrates FilterTest to Junit5, pure refactoring.
> test: Migrate FilterTest to Junit5

- src/test/java/spoon/generating/CorrectIdentifierTest.java
#3919
This PR just migrates CorrectIdentifierTest to Junit5, pure refactoring.
I have decided to do the migration sequentially hence, selected this test. I plan to migrate a lot of tests before the official start of the GSoC coding period.
I will be migrating sequentially but if org have priorities for some other tests, I will be happy to migrate them first : )
> test: Migrate CorrectIdentifierTest to JUnit5

- src/test/java/spoon/reflect/ast/AstCheckerTest.java
#3919
This PR just migrates AstCheckerTest to Junit5, pure refactoring.
> test: Migrate AstCheckerTest to Junit5

- src/main/java/spoon/compiler/Environment.java
#3923 
The `Environment` interface is arguably one of the most important ones in the entire Spoon library, and it's fairly underdocumented. This PR improves the documentation by adding all missing `@param` and `@return` tags, fixing errors and adding missing explanations of what things actually do.
Javadoc method quality score increases like so:
```
JAVADOC QUALITY SCORE (lower is better)
Compare: 2641
Current: 2584
```
There are still improvements to be made here, especially in explaining what the options you can set actually do, but I felt like this was enough for a single PR.
> doc: Improve Javadoc quality in Environment interface

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
#3965 
First PR in refactoring `ReferenceBuilder.getTypeReference()`.
This PR extracts the creation of parameterized type references into a set of three smaller helper methods. This will make it easier for me to later handle #3964
> refactor(ReferenceBuilder): Extract parameterized type reference creation into helpers

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java
- src/test/java/spoon/test/model/TypeTest.java
- src/test/resources/duplicates-in-submodules/moduleA/duplicates/AlsoWithNestedEnum.java
- src/test/resources/duplicates-in-submodules/moduleB/duplicates/AlsoWithNestedEnum.java
Fix #3950 
Fix #3572 
This PR fixes a crash that occurs when Spoon is forced to search for type bindings, and there's a _duplicated type with nested types that are also duplicated_. It's a very fringe thing that only occurs when running with `setIgnoreDuplicateDeclarations(true)`.
> fix: Fix crash on null type binding in nested type during search

- src/main/java/spoon/support/compiler/FileSystemFile.java
PULL REQUEST TITLE: 
Hi,
This PR fixes 1 violation of [Sonar Rule 2097: '"equals(Object obj)" should test argument type'](https://rules.sonarsource.com/java/RSPEC-2097).
The patch was generated automatically with the tool [Sorald](https://github.com/SpoonLabs/sorald). For details on the fix applied here, please see [Sorald's documentation on rule 2097](https://github.com/SpoonLabs/sorald/blob/master/docs/HANDLED_RULES.md#equalsobject-obj-should-test-argument-type-sonar-rule-2097).
The violation can be seen in [Spoon's SonarQube dashboard](https://sonarqube.ow2.org/project/issues?id=fr.inria.gforge.spoon%3Aspoon-core&issues=AWhzp_HYOQZh-5uoMgNg&open=AWhzp_HYOQZh-5uoMgNg).
> fix: Fix violation of Sonar rule 2097

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java
- src/test/resources/noclasspath/BadAnonymousClassOfNestedType.java
Fix #3913 
This PR fixes a problem in resolving generic types in noclasspath mode. The symptoms are specifically evident when creating an anonymous subclass of a generic type while using a constructor that does not exist. It can probably occur elsewhere as well, but this is where it was found to be easily reproducible.
See #3913 for further details.
> fix(noclasspath): Handle type resolution of anonymous class with unresolved constructor

- spoon-pom/pom.xml
- src/test/java/spoon/reflect/reference/CtTypeReferenceTest.java
#3919
This PR migrates FilterTest to Junit5.
Hi @slarse,
I tried to replace```Rule``` with ```ExtendWith```, but wasn't able to replace it successfully.
I would be glad if someone may help me perform this replacement.
I am unable to understand  [MockitoExtension](https://www.javadoc.io/doc/org.mockito/mockito-junit-jupiter/2.23.4/org/mockito/junit/jupiter/MockitoExtension.html) isn't getting resolved despite adding dependencies. (references : [baeldung](https://www.baeldung.com/mockito-junit-5-extension) & [stackoverflow](https://stackoverflow.com/questions/40961057/how-to-use-mockito-with-junit5)).
> test: migrate CtTypeReferenceTest to Junit5

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/test/java/spoon/test/trycatch/TryCatchTest.java
- src/test/resources/NonClosableGenericInTryWithResources.java
Fix #3951 
The problem is described in the issue. It's very rare for JDT to parse a parameterized type reference to a ProblemReferenceBinding (even when the actual referenced type can't be resolved). In the particular case of error code 15 (using a type that isn't closable on a try-with-resources), it does however resolve the reference to a ProblemReferenceBinding with type parameters in the name, which caused the crash.
This PR does _not_ attempt to parse the type arguments, it only fixes the crash and lets the pre-existing logic for creating type references from problem bindings do its thing. In other words, a type reference is created with the correct simple name, and that's about it. A warning that the type arguments are ignored is also issued.
I found a way to actually resolve the …
> fix: Fix crash on handling parameterized ProblemReferenceBinding

- src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
Related to the discussion in #1846 
I found a completely redundant unchecked cast in a method (`getParent(Class)`) where we actually have the runtime type to cast to! Using `Class.cast()` is _safe_, as it actually performs a cast at runtime.
It should be noted that in this method it doesn't actually matter, because the unchecked cast is preceded by a call to `Class.isAssignableFrom()`, which makes it "safe". But still, I think it's a nicer design to just avoid unchecked casts altogether when possible, because the not every Java developer is intimately familiar with what's safe and not when it comes to casting and type parameters.
> refactor: Remove unnecessary unchecked cast in getParent(Class)

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
#3965 
This PR extracts all of the "sufficiently small subroutines" in `getTypeReference` into methods of their own.
I can create one PR for each little helper, but as they edit code very close to each other I'd need to do them sequentially (wait for one to get merged before opening the next), so I figured I'd submit like this to begin with.
@monperrus  Let me know if you want me to break it up into smaller PRs (perhaps split into 3 PRs with 3 extractions each?), or if this size is OK.
> refactor(ReferenceBuilder): Extract small reference-building subroutines into helpers

- src/test/java/spoon/processing/ProcessingTest.java
Hi, I have improved the mutation strength from 0% to 100% for the SpoonTagger class.
Here's the report before improvement.
Actually, the test was poorly written, it had overlooked the scenario when the Spoon.java file already exists. I have taken care of that scenario and have manually tested the mutation "Removed all instructions in the method", and it is getting killed now.
I feel the PR is ready for merging.
> test: improve the test for SpoonTagger class

- src/test/java/spoon/test/filters/FilterTest.java
#1818
This PR aims to improve the code coverage of the class [NameFilter](https://github.com/INRIA/spoon/blob/2fff4c50266f79bc06b961e3b01ca6c6e0fcc1ab/src/main/java/spoon/legacy/NameFilter.java).
Link to #3967
> test: improve tests for NameFilter class.

- CONTRIBUTING.md
It's been a long time we haven't updated the integrator list.
Per our governance guidelines, the integrators are those of us who have significantly contributed and/or merged over the past year.
Per the past year's contributions, we would thus have the following new list of integrators:
- Simon Larsen @slarse (welcome Simon and thanks for your great [recent contributions](https://github.com/INRIA/spoon/commits?author=slarse))
- Nicolas Harrand @nharrand 
- Martin Monperrus @monperrus 
And this is the opportunity to thank again @pvojtechovsky @tdurieux @danglotb @surli for the outstanding effort and care put in Spoon!
> community: update the integrator list

- src/test/java/spoon/test/template/TemplateTest.java
#1818
Hi, I have improved both the test strength and mutation coverage from 75% to 100%  class.
Here's the report before improvement.
This PR was actually supposed to be raised in week 1, but I had to wait for tests to get converted in Junit5.
What I believe is, unhappy path test was missing for `isWellFormed` function which led to poor test strength in Descartes report, so I wrote a test for an unhappy path to fix that.
Next, for this week I will be working on the `Substitution.java` which is 660 lines of codes with many methods, so I believe I will raise another PR for that after a couple of days.
Link to #3967
> review: test: improve tests for abstractTemplate

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
#3965 
Extracts getting a type reference from a TypeVariableBinding into a separate method. This is pretty incredibly complicated, so I aim to also simplify the process.
This is the final significant PR in refactoring `ReferenceBuilder.getTypeReference`, but I intend to do one final PR after this to slightly refactor the top-level method. Then I'm happy.
UPDATE: I've now finished this refactoring. It was _hard_, it took me several hours to sort out which part was doing what. In the end, I managed to significantly flatten the structure, and even remove the `bounds` field entirely (which I initially had a really hard time understanding the purpose of). Note that I didn't put it in a local variable instead, the value just isn't needed anymore.
On a side note, I'm really proud of the fact …
> refactor(ReferenceBuilder): Refactor getting type refeference from TypeVariableBinding

- src/test/java/spoon/test/template/SubstitutionTest.java
#1818
Hi, I have added a new test for `insertAllNestedFilelds` method of the `Substitution` class, this test improves code coverage, mutation converge and test strength all from 0% to 100%.
Here's the report before improvement.
The exception added in this test, is able to kill the mutation but, probably isn't the strongest assertion, I wan't able to make it stronger.
> review: test: add test for SubstituionInsertAllNestedTypes

- src/test/java/spoon/test/template/SubstitutionTest.java
#1818
Hi, I have added a new test for `insertAllConstructor` method of the `Substitution` class, following are the features of this test:
1) This new test is killing this mutation : 
2) This method had some code coverage but, the test strength and mutation coverage was zero, now code coverage has improved and the mutation has been killed by this new test.
3)  this test improves code coverage, mutation converge and test strength all from 0% to 100% for `insertConstructor` method.
Link to #3967
> review: test: add test for Substitution.insertAllConstructors

- src/test/java/spoon/test/refactoring/CtRenameGenericVariableRefactoringTest.java
- src/test/java/spoon/test/refactoring/CtRenameLocalVariableRefactoringTest.java
- src/test/java/spoon/test/refactoring/MethodsRefactoringTest.java
- src/test/java/spoon/test/refactoring/RefactoringTest.java
#3919
Hi, this PR involves pure refactoring.
I will be working on `spoon.refactoring` next hence raised the PR for migration.
This PR just involves these two types of changes: 
1) changing imports
2) In some assertions due to the Junit5 rules, the order of the parameters changed with the output message parameter moved as the last parameter.
link to #3967
> review : test: Migrate all refactoring tests to Junit5

- src/test/java/spoon/support/compiler/SpoonPomTest.java
- src/test/java/spoon/support/compiler/classpath/ComputeClasspathTest.java
- src/test/java/spoon/support/compiler/jdt/ExtendedStringLiteralTest.java
- src/test/java/spoon/support/compiler/jdt/JDTBasedSpoonCompilerTest.java
- src/test/java/spoon/support/compiler/jdt/JDTBatchCompilerTest.java
- src/test/java/spoon/support/compiler/jdt/JDTBuilderTest.java
- src/test/java/spoon/support/compiler/jdt/JDTImportBuilderTest.java
- src/test/java/spoon/support/util/QualifiedNameBasedSortedSetTest.java
- src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
- src/test/java/spoon/testing/AbstractAssertTest.java
- src/test/java/spoon/testing/CtElementAssertTest.java
- src/test/java/spoon/testing/CtPackageAssertTest.java
- src/test/java/spoon/testing/FileAssertTest.java
#3919
While waiting for review on #4005 and #4006, I thought it will be nice to finish up the migration of the spoon.support.
Migration of testing tests is important because I will later work on it in the latter weeks plus, tests in the testing package can't be migrated automatically or by some tool, somebody needs to migrate them manually.
This PR just involves these two types of changes:
1)   changing imports
2)  In Junit5, assertThrows have been introduced so `@Test(expected = IndexOutOfBoundsException.class)` isn't supported anymore.
> review: test: Migrate support and testing tests to Junit5

- src/test/java/spoon/support/gui/SpoonTreeBuilderTest.java
#1818
Hi, I have created a new class `SpoonTreeBuilderTest` for the `SpoonTreeBuilder` class, as per Descartes's report the testing for this class was zero in all parameters hence tests were to be written from scratch.
Report before these tests : 
These tests improve the line coverage from 0 to 60% and improve mutation coverage and strength to 60% as well.
There are testing methods `enter`, `exit`, `create` node.
Link to #3967
> review: test: add tests for the SpoonTreeBuilder class

- src/test/java/spoon/test/template/SubstitutionTest.java
#1818
Hi, I have added a new test for `insertAllSuperInterfaces` method of the `Substitution` class, following are the features of this test:
1) The test kills this mutation
2) It is killing this mutation as well
Link to #3967
> reveiw: test: add test for Substituion.insertAllSuperInterfaces

- src/main/java/spoon/support/reflect/reference/CtIntersectionTypeReferenceImpl.java
When the underlying data structure in CtIntersectionTypeReferenceImpl was changed (#659), one reference check wasn't changed. From what I've seen that didn't introduce any behavioral changes other than the parameters passed to `onListDeleteAll`. 
I didn't find any contracts for that method, that's why I consider it to be a refactoring instead of a bug fix. If that's wrong, please let me know.
> review: refactor: reference comparison between List and Set

- CONTRIBUTING.md
IMO it's pretty confusing to leave feedback on a PR, and then have the author of that PR force-push changes to it such that the parts that were reviewed are no longer even part of the PRs commit history.
This PR adds a note to the CONTRIBUTING.md about avoiding force-pushing when collaborating on a PR (e.g. after receiving a review).
@monperrus @nharrand Thoughts on the general idea and potentially the phrasing in the docs?
> doc: Add note in CONTRIBUTING.md about force-pushing

- src/main/java/spoon/support/visitor/MethodTypingContext.java
- src/test/java/spoon/test/ctType/CtTypeTest.java
- src/test/resources/npe/Hm.java
- src/test/resources/npe/SneakyCrashy.java
- src/test/resources/npe/SneakySubclass.java
This PR fixes the `CtType#getAllExecutable` method for so called sneaky throws constructs.
> Review: bug: NPE while querying sneaky throws

- src/main/java/spoon/reflect/code/CtAbstractSwitch.java
- src/main/java/spoon/support/reflect/code/CtSwitchExpressionImpl.java
- src/main/java/spoon/support/reflect/code/CtSwitchImpl.java
- src/test/java/spoon/test/model/SwitchCaseTest.java
Reference: https://github.com/INRIA/spoon/issues/3884#issuecomment-869403561.
> feat: Add API method CtAbstractSwitch.addCaseAt

- src/test/java/spoon/test/template/SubstitutionTest.java
#1818
Hi, I have added 3 new tests for  methods of the `Substitution` class : 
1) `testSubstituteMethodBody` should kill this mutation : 
2) `testSubstituteStatement` should kill this mutation :
3) `testSubstituteFieldDefaultExpression`should kill this mutation :
Link to #3967
> review: test: add tests for substitution class

- src/main/java/spoon/support/visitor/equals/EqualsChecker.java
- src/test/java/spoon/test/snippets/SnippetTest.java
Fix #4022
This PR fixes equality between `CtCodeSnippet` instances. Previously, two code snippets would be considered equal regardless of their contained snippet (i.e. the raw string). With this PR, the raw snippet is now also considered part of the equality of code snippets (both statements and expressions).
> fix: Fix equality for CtCodeSnippet

- .github/workflows/tests.yml
- chore/ci-checkstyle-javadoc.sh
- chore/find_javadoc_regression.py
Before this patch the CI Javadoc regression check would only look at the amount of violations and fail the build if they increased:
```
JAVADOC QUALITY SCORE (lower is better)
Compare: 2584
Current: 2592
Javadoc quality has deteriorated!
Run the chore/ci-checkstyle-javadoc.sh script locally to find errors
See https://github.com/inria/spoon/issues/3923 for details
```
This wasn't really helpful when actually finding the errors, as you would need to run the checkstyle command locally on both branches and diff the output yourself. 
This patch adds a small python script that tries to (*somewhat* intelligently) perform this diff in the CI and print a more useful failure message.
The line numbers in the output will not be correct if the exact same violation message appears multiple times in a …
> review: chore: Try to list new errors in javadoc regression check

- src/main/java/spoon/pattern/internal/node/ElementNode.java
- src/main/java/spoon/reflect/visitor/CommentHelper.java
- src/main/java/spoon/reflect/visitor/ImportScannerImpl.java
- src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
This pull request fixes 4 violations of [Sonar rule S1481](https://rules.sonarsource.com/java/RSPEC-1481) (Unused local variables should be removed).
This patch was generated automatically using [Logifix](https://github.com/lyxell/logifix).
> refactor: Remove unused local variable declarations

- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/superCall/SuperCallSniperTestClass.java
A simple unit test reproducing issue #4021, comment out the `Disabled` annotation and the test should fail with a `SpoonException`.
The issue seems to be triggered by a `super` invocation with a unary operator as argument (`-x`)
> test: Test reproducing issue #4021

- src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
When working on my other pull request, I came about this confusing output:
```cs
[ERROR] Failures: 
[ERROR]   SpoonArchitectureEnforcerTest.testInterfacesAreCtScannable:358 The following methods are missing in CtScanner: 
scanCtPattern
```
I wondered why it would expect me to add this method to the CtScanner as there are no other methods like that. Looking closer at the test revealed that the method is expected in CtInheritanceScanner instead. This PR uses the simple class name instead, so `CtInheritanceScanner` is now printed correctly.
It also seems like the CtScanner is not required as input resource. I guess that is a leftover from when this test was implemented.
**Note**: I'm not sure about this, but it the test case itself is probably named badly, indicating that it is about the …
> review: fix(test): error output for CtInheritanceScanner test prints wrong class name

- src/test/java/spoon/support/JavaOutputProcessorTest.java
#1818
Hi, I have added some new tests for  methods of the `JavaOutputProcessor` class : 
These tests are intended to kill these 2 mutations:
Link to #3967
> review: test: add tests for JavaOutputProcessor class

- src/test/java/spoon/test/comment/CommentTest.java
#1818
Hi, I have added some new tests for methods of the JavaOutputProcessor class :
These tests are intended to kill this mutation:
Link to #3967
> review: test: add tests for CtCommentIMmpl class

- src/main/java/spoon/support/compiler/jdt/JDTBatchCompiler.java
- src/test/java/spoon/test/module/TestModule.java
> fix: set correct names to modules in JDTBatchCompiler

- src/main/java/spoon/support/reflect/CtModifierHandler.java
Found some wonky indentation in `CtModifierHandler.setModifiers`, this PR just fixes that.
> refactor: Fix wonky indentation in CtModifierHandler.setModifiers

- src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java
- src/test/java/spoon/test/ctType/CtTypeTest.java
- src/test/resources/keywordCompliance/enum/Foo.java
This PR fixes #4067
Added a test case similar to the problem encountered with the example from `astor`.
> fix: Fix compliance level support for old code

- renovate.json
Related to https://github.com/INRIA/spoon/pull/4046#issuecomment-881218494
Currently, Renovate is updating the SHA digests of GitHub Actions to the latest one on the primary branch, but we only want stable releases. Based on [the docs over here](https://docs.renovatebot.com/modules/manager/github-actions/), I think that this PR should fix that problem.
I'm not _entirely_ sure, as the docs are a little bit ambiguous, and there's a possibility that they mean that they'll just stick to that specific tag and update the digest if the tag is updated, but not update to later tags. If that's the case, then we should specify `tag=vX` (only the major version) for each action, as that tag is by GHA conventions moved to the latest iteration of that major version each time there's a new release.
> chore: Add tag pinning to GHA digest update

- src/test/java/spoon/test/factory/MethodFactoryTest.java
- src/test/java/spoon/test/factory/testclasses/Bar.java
- src/test/java/spoon/test/factory/testclasses4/Bar.java
Hi, I have added a new test for the method ```createRefernce``` :
This test is intended to kill these mutations:
Link to #3967
> review: test: add test for createReference

- src/main/java/spoon/support/reflect/code/CtJavaDocImpl.java
- src/test/java/spoon/test/comment/CommentTest.java
- src/test/java/spoon/test/comment/testclasses/JavaDocWithLink.java
> review: fix: get correct descriptions from CtJavaDocImpl

- src/main/java/spoon/support/reflect/code/CtStatementListImpl.java
- src/test/java/spoon/test/ctStatementList/CtStatementListImplTest.java
- src/test/java/spoon/test/ctStatementList/CtStatementListTest.java
fix:#4060
#4060
In #4063, I fixed `CtCaseImpl.insertBegin`, this PR aims to fix `CtStatementListImpl.insertBegin`. They have a similar bug and a similar fix, so I thought it's best to fix them simultaneously, so that we are able to close #4060 in concrete terms.
Also, this test is killing this mutation
link to #3967
> review: fix: Fix the insertion order for CtStatementListImpl.insertBegin 

- src/test/java/spoon/test/ctStatementList/CtStatementListTest.java
Hi, I have added new tests for the class `CtStatementList`, I had written them earlier but to avoid working on conflicting branches I am pushing them now, this PR is similar to #4082, so I will automatically implement changes based on reviews on that PR.
These tests are intended to kill these mutations
1)
2)
3)
4)
Link to #3967
> review: test: add tests for CtStatementList

- src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
Fix #4021 
See https://github.com/INRIA/spoon/issues/4021#issuecomment-897634177 for a description of the problem.
The tl;dr is that the end position of a super reference is incorrect from JDT when it's followed by a unary operator. This PR simply sets the end position of a super reference relative to it's start position, which is possible as `super` always has the same amount of characters.
> fix: fix sniper bug delated to source position of super reference

- src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java
This PR just replaces the stream set creations with `Collections#singleton` - the `Set.of` for poor sods still using java 8.
I don't expect this to have any impact on correctness or performance.
> review: refactor: Simplify Set creation in CtReferenceImpl

- src/main/java/spoon/ContractVerifier.java
- src/main/java/spoon/pattern/internal/matcher/TobeMatched.java
- src/main/java/spoon/reflect/visitor/ImportCleaner.java
- src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java
- src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
- src/main/java/spoon/support/sniper/internal/ChangeResolver.java
- src/main/java/spoon/support/visitor/ClassTypingContext.java
Resolves Sonar violations of rules S3740 and S1596 and fixes compiler warnings about unchecked conversions.
This patch was generated automatically using [Logifix](https://github.com/lyxell/logifix).
> refactor: Fix unchecked type conversions

- src/main/java/spoon/support/reflect/code/CtLambdaImpl.java
- src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java
- src/test/resources/target-functional-interface-in-lambda/HasFunctionalInterface.java
- src/test/resources/target-functional-interface-in-lambda/TargetsFunctionalInterface.java
Fix #4079 
See #4079 for a description of the problem.
> fix: Make lambda type implicit to avoid auto-importing type targeted in lambda

- src/main/java/spoon/reflect/declaration/CtCompilationUnit.java
- src/main/java/spoon/reflect/declaration/CtElement.java
- src/main/java/spoon/support/reflect/code/CtTypeAccessImpl.java
- src/main/java/spoon/support/reflect/declaration/CtCompilationUnitImpl.java
- src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
- src/main/java/spoon/support/reflect/declaration/CtModuleImpl.java
Fix #4098 (see issue for description of problem)
**Breaking change!**
This PR implements option 2 presented in #4098. It's a _purely statically_ breaking change, meaning that some compilation may be affected, but behavior is not. However, compilation is pretty unlikely to be affected, and it should really only be the case if the parameterization of the method is explicitly provided.
> review: fix: Fix return type of setParent

- doc/factories.md
> doc: fix wrong variable in example snippet

- .github/workflows/tests.yml
As all but one of the PRs opened by renovate on GHA versions have _not_ pinned to a tag, I'm now manually pinning to tags [as suggested by the docs here](https://docs.renovatebot.com/modules/manager/github-actions/). The auto-pinning simply does not work, at least not reliably.
> chore: Manually set the renovate GHA tags

- .github/workflows/tests.yml
Fix #4144 
sorald-buildbreaker has had more false positives than true positives, and so we'll need to remove it. I just don't have time to maintain buildbreaker anymore. Instead of disabling the job, I'm going to just remove it, as otherwise I fear we may have it disabled indefinitely. The job is pretty trivial and clearly described in [the buildbreaker README](https://github.com/spoonlabs/sorald-buildbreaker), so there's really no need to keep it.
@algomaster99 If you get around to resuming work on buildbreaker, see this PR for the workflow config.
> chore: Remove sorald-buildbreaker job

- spoon-pom/pom.xml
This patch upgrades the maven jar plugin to 3.2.0 and disables timestamps in maven to make the spoon-core (and maybe others) build reproducible.
See https://maven.apache.org/guides/mini/guide-reproducible-builds.html
Partially addresses #4151.
> chore: setup reproducible builds for spoon-core

- .github/workflows/tests.yml
#4156 showed that I'd missed pinning one of the setup-java actions to a tag. This PR fixes that, which makes renovate only suggest updates when a new version is available (as opposed to on every new push to the main branch of the action).
> chore: Pin setup-java action to tag

- src/main/java/spoon/javadoc/internal/Javadoc.java
- src/test/java/spoon/test/javadoc/JavaDocTest.java
An inline tag does *not* end at the next `}` bracket but at the next
*matching* `}` bracket. This can be especially noticeable in code tags:
```
Tag doesn't end here
|
v
{@code public class Foo {}}
^
Tag ends here
```
Closes #4154.
> review: fix: Handle nested `}` in inline tag

- .gitignore
The old git ignore was missing some Gradle build artifacts, I added them to the git ignore. The input was created by [https://www.toptal.com/developers/gitignore/api/gradle](https://www.toptal.com/developers/gitignore/api/gradle)
> review: chore(gitignore): improve gitignore

- src/main/java/spoon/javadoc/internal/JavadocInlineTag.java
- src/test/java/spoon/javadoc/internal/JavadocInlineTagTest.java
Spoon previously expected e.g. `docRoot` to be `doc_root`, which is not correct. This PR fixes this in a backwards-compatible way by setting the keyword to its actual value.
> review: Correctly parse inline tag names

- src/test/java/spoon/reflect/ast/AstCheckerTest.java
#4100
This is a refactor of `AstCheckerTest#isSurcharged()`. It should be noted that I don't understand what "surcharged" means in the context, and I also don't understand the intent of the function. The mechanics are however clear to me, see the invariants in 32de37d.
An invocation `v` is a potential surcharge delegate if it:
* Is an invocation that is the only statement in the body.
* Is an invocation that is the first statement in the body, and the last statement is a return _without_ an invocation.
* Is an invocation in a return occurring as the last statement in the body.
`v` is determined to be a surcharge delegate if it fulfills any of the 3 above points, and returns false for `isToBeProcessed(v)`.
> test(AstCheckerTest): Refactor isSurcharged

- src/main/java/spoon/support/visitor/java/reflect/RtMethod.java
I found a spot where reflections where used to call Java 8 methods, for source compatibility with Java 7. This is no longer relevant and can be simplified.
> review: refactor: Remove Java 7 specific code

- .github/workflows/tests.yml
- pom.xml
- spoon-control-flow/pom.xml
- spoon-pom/pom.xml
Reverts INRIA/spoon#4169
Because I did not think ahead, we need to install JDK 11 on both Jenkins agents before upgrading.
> Revert "review: chore: upgrade to java 11"

- src/main/java/spoon/metamodel/Metamodel.java
- src/main/java/spoon/metamodel/MetamodelConcept.java
- src/main/java/spoon/metamodel/MetamodelProperty.java
In #4158 I removed the utility class and its usages, but it seems like the code was duplicated and used in the Metamodel too, I refactored the code to use computeIfAbsent there now too.
> review: refactor: Replace getOrCreate in Metamodel with computeIfAbsent

- pom.xml
- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
Supersedes #4161.
This JDT release adds support for Java 17. There was one breaking change with spoon that was simple to fix as the representation was just unified.
**Edit**: Oh well, that worked locally because I'm running it with Java 16. Seems like JDT now requires Java 11 as minimum version. How do we want to deal with that? @monperrus 
Blocked by ~~#4169~~ #4173
> wip: chore(deps): update jdt to Java 17

- lgtm.yml
This PR adds a `lgtm.yml` file to force LGTM to use java 11 to analyze spoon. The current default seems to be 8 (or it didn't properly recognize the version in our pom files).
> review: chore: Add lgtm.yml to set java version

- src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
This PR tries to remove some old code and improve the code style. The method has the same behavior as before, but doesn’t need to build a model for array types anymore. In a feature PR there should be an enum for primitive types, but this is out of scope for this PR.
> refactor(getActualClass): Improve design and reability

- src/main/java/spoon/IncrementalLauncher.java
- src/main/java/spoon/support/gui/SpoonModelTree.java
This PR fixes an issue with potential resource leaks. In both cases a try-with-resources fixed the problem. See
[LGTM-Link](https://lgtm.com/projects/g/INRIA/spoon?mode=tree&id=java%2Fcontradictory-type-checks%2Cjava%2Fdereferenced-value-may-be-null%2Cjava%2Finconsistent-equals-and-hashcode%2Cjava%2Findex-out-of-bounds%2Cjava%2Foutput-resource-leak%2Cjava%2Funchecked-cast-in-equals%2Cjava%2Funknown-javadoc-parameter%2Cjava%2Funused-container%2Cjava%2Fuseless-type-test%2Cjava%2Fzipslip&tag=external%2Fcwe%2Fcwe-022%2Cexternal%2Fcwe%2Fcwe-193%2Cexternal%2Fcwe%2Fcwe-404%2Cexternal%2Fcwe%2Fcwe-476%2Cexternal%2Fcwe%2Fcwe-561%2Cexternal%2Fcwe%2Fcwe-581%2Cexternal%2Fcwe%2Fcwe-772&ruleFocus=2980072)
> refactor: fix potential resource leaks

- src/main/java/spoon/metamodel/MetamodelProperty.java
While fixing #4198 my IDE was quite unhappy for not using an `enummap` here. Small fix for the sonarlint issue [link](https://rules.sonarsource.com/java/tag/performance/RSPEC-1640)
> refactor(MetamodelProperty): fix static analysis warning

- src/main/java/spoon/support/visitor/ClassTypingContext.java
This PR fixes an issue with an unneeded `instanceof` check. A `CtMethod` is always `instanceof` `CtMethod`. See https://lgtm.com/projects/g/INRIA/spoon/snapshot/af0caa74d58ecec12adf3cb64df0da3681c13544/files/src/main/java/spoon/support/visitor/ClassTypingContext.java?sort=name&dir=ASC&mode=heatmap#x6d177e115261d850:1
> refactor(ClassTypingContext): remove unneeded type check, fix LGTM warning

- src/main/java/spoon/metamodel/MetamodelConcept.java
- src/main/java/spoon/metamodel/MetamodelProperty.java
This PR removes 2 never accessed containers and fixes a LGTM alert. @monperrus are these field import to keep or needed for a future feature?
See [LGTM-link](https://lgtm.com/projects/g/INRIA/spoon?mode=tree&id=java%2Fcontradictory-type-checks%2Cjava%2Fdereferenced-value-may-be-null%2Cjava%2Finconsistent-equals-and-hashcode%2Cjava%2Findex-out-of-bounds%2Cjava%2Foutput-resource-leak%2Cjava%2Funchecked-cast-in-equals%2Cjava%2Funknown-javadoc-parameter%2Cjava%2Funused-container%2Cjava%2Fuseless-type-test%2Cjava%2Fzipslip&tag=external%2Fcwe%2Fcwe-022%2Cexternal%2Fcwe%2Fcwe-193%2Cexternal%2Fcwe%2Fcwe-404%2Cexternal%2Fcwe%2Fcwe-476%2Cexternal%2Fcwe%2Fcwe-561%2Cexternal%2Fcwe%2Fcwe-581%2Cexternal%2Fcwe%2Fcwe-772&ruleFocus=890083)
> refactor: fix LGTM warning by removing unaccessed fields

- src/main/java/spoon/support/compiler/ZipFolder.java
This PR fixes an issue with zip slips
> refactor(ZipFolder): fix zip slip issue

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
- src/test/java/spoon/test/enums/EnumsTest.java
Previously, the enum values' modifiers were read from the declaring class by both the JDTTreeBuilder and the JavaReflectionTreeBuilder. This does not match the produced bytecode. For more context, see #4138.
> review: fix: extract enum constant modifiers from the right place

- doc/jenkins/build.sh
required to well handle Java 11 and fix all the failing jobs on https://ci.inria.fr/sos/
> chore: Jenkins uses the latest spoon-maven-plugin

- src/main/java/spoon/support/reflect/reference/CtReferenceImpl.java
While looking at LGTM issues my IDE was a bit unhappy for the not needed interface and already in a superclass declared abstract method. This PR removes both.
> refactor(CtReferenceImpl): remove not needed abstract method and interface declaration

- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
This fix allows testing the SniperPrettyPrinter with types that are not classes (Interfaces, AnnotationTypes, etc). (As for example #4219)
> test(TestSniperPrinter): make the method testSniper able to handle non class types

- .mvn/extensions.xml
- .mvn/gradle-enterprise.xml
Adds the following lines at the end of the Spoon build:
```
[INFO] Publishing build scan...
[INFO] https://gradle.com/s/XXXXXXXXX
```
Where `XXXXXXXXX` is a randomly generated string for the URL, where one can see a lot of information about the Spoon build.
See https://github.com/INRIA/spoon/issues/4269
> chore: add support for Gradle build dashboard

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/test/java/spoon/test/record/CtRecordTest.java
- src/test/resources/records/GenericRecord.java
Fix #4281 
This PR moves the type argument to the correct location when printing generic record declarations. A new unit test is included.
> fix: printing of generic records (issue #4281)

- src/test/java/spoon/test/module/TestModule.java
This fixes #4285. The test relied on the order of entries returned by `File#listFiles()`, which is unspecified (thank you @SirYwell ).
> fix: Test failure in TestModule.testModuleNames() (#4285)

- src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentPrinter.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/sniperPrint/SpaceAfterFinal.java
Fixes #4220 
I haven't fixed this till now, but I have found the cause, where this bug, might emanate from.
While trying to print the modified `CtField` instance in this test, one of the functions called is [`getGroupedChildrenFragments`](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java#L490). It generates `flatChildren` of the field as follows:
```java
0 = {ElementSourceFragment@4115} "|58, 65|private|"
1 = {TokenSourceFragment@4128} "| |"
2 = {ElementSourceFragment@4129} "|66, 72|static|"
3 = {TokenSourceFragment@4130} "| |"
4 = {ElementSourceFragment@4131} "|73, 78|final|"
5 = {TokenSourceFragment@4132} "| |"
6 = {ElementSourceFragment@4133} "java.lang.String|79, 95|java.lang.String|"
7 = {TokenSourceFragment@4134} "| |" …
```
> fix: add missing space after modifiers in sniper mode

- .github/workflows/tests.yml
- src/main/java/spoon/Launcher.java
This PR just ignores failures in the qodana action (as its exit codes were a bit weird) and instead relies on the jq buildbreaker.
> review: fix: Ignore Qodana action exit code

- lgtm.yml
As we no longer use the bot, we don't need it any more.
> review: chore(lgtm): remove LGTM File

- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/sniperPrinter/SpaceAfterFinal.java
`sniperPrinter` directory is already there for test resources related to testing sniper printer.
> refactor: make a single test resource package for testing sniper printer

- src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentContextCollection.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/sniperPrinter/TryWithResource.java
- src/test/resources/sniperPrinter/tryWithResource/PrintOnce.java
- src/test/resources/sniperPrinter/tryWithResource/RetainSemiColon.java
Reference: https://github.com/SpoonLabs/sorald/issues/600
The second resource in the catch block, `BufferedWriter writer = newBufferedWriter(outputFilePath, charset)`, is printed twice. For example,
```java
try (ZipFile zf = new ZipFile(zipFileName);
BufferedWriter writer = newBufferedWriter(outputFilePath, charset)) { }
```
is changed to
```java
try (ZipFile zf = new ZipFile(zipFileName);
BufferedWriter writer = newBufferedWriter(outputFilePath, charset);BufferedWriter writer = newBufferedWriter(outputFilePath, charset)) { }
```
when printed using the sniper printer.
I think it is happening because we add a separator, `;`, after first `BufferedWriter writer = newBufferedWriter(outputFilePath, charset)` which changes `muted` from `true` to `false`. Although the separator is not needed …
> fix: print each resource in `CtTryWithResource` exactly once and retain separator

- src/main/java/spoon/pattern/internal/matcher/TobeMatched.java
Because we finally have Java 11, we can use the newer API. Fixes 2 qodana warnings.
> refactor: replace Collections.unmodifiableList with List.of to fix Qodana warnings

- src/main/java/spoon/reflect/visitor/ImportCleaner.java
- src/test/java/spoon/reflect/visitor/ImportCleanerTest.java
- src/test/resources/fieldImport/StaticFieldImport.java
- src/test/resources/fieldImport/UtilityLibrary.java
The failing test case reproduces https://github.com/SpoonLabs/sorald/issues/602.
> fix: prevent removal of static field import

- src/main/java/spoon/support/compiler/SpoonPom.java
The way Spoon build the class path for a Maven project in `MavenLauncher` is to launch `mvn dependencies:build-classpath` to generate a text file containing class path. However, for multi-module projects, when there is a module whose dependencies can not be resolved, Maven will skip the remaining modules and report an error.
In this PR, I added the `-fn` flag to the Maven invocation request such that Maven can continue to resolve dependencies for the remaining modules even though there is an error occurred. This can help resolve as many libraries as possible.
> fix(MavenLauncher): maximum recovery from missing libraries

- src/test/java/spoon/test/GitHubIssue.java
This annotation should also be valid for applying to types because there are cases when developers write `@Nested` classes for writing tests for a particular issue—for example, #4341 .
> test: use GitHub issue annotation for types

- src/main/java/spoon/reflect/visitor/PrintingContext.java
Because the diff is kinda hard to read, here is what I did:
I refactored the old long vector for states into an inner `Enum` and `Enumset` as replacement. This is way better readable and should deliver the same performance. 
I moved the type members in the natural Java ordering of members. This means fields, methods and  inner classes. Fields spread all over the class are really hard to read. 
I tried to add at least some doc to the class. But it's still for the full class, because I don't understand all of this magic.
> review: refactor: refactor printingContext

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java
- src/test/java/spoon/test/generics/GenericsTest.java
Previously, generic parameters where neither present in the model nor printed. For example,
```java
BiFunction<Integer[], Integer, Integer> field = Arrays::<Integer>binarySearch;
```
was printed as
```java
BiFunction<Integer[], Integer, Integer> field = Integer::binarySearch;
```
> review: fix: support type parameters on method references

- src/main/java/spoon/reflect/visitor/ImportCleaner.java
- src/test/java/spoon/reflect/visitor/ImportCleanerTest.java
- src/test/resources/importCleaner/DoNotRemoveSubType.java
- src/test/resources/importCleaner/TypeImportButUseSubType.java
Reference: https://github.com/SpoonLabs/sorald/issues/598
Type `B` in `A.B x = new A.B()` was not being resolved to `import somePackage.A` even though this import statement was present in the compilation unit.
I apologise for the bad test case. I wasn't able to reproduce the bug in a smaller test file. The reason was that whenever it used to visit `B` in `A.B x`, the visit was ended due to this [condition](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/AstParentConsistencyChecker.java#L21). However, this line didn't interfere with the original test resource which brought about this bug.
> fix(ImportCleaner): resolve imports of parent types

- .github/workflows/tests.yml
With v4, the way how the linter is defined was changed. I adapted this manually.
Supersedes #4361.
> review: chore: update qodana action to v4

- .github/workflows/tests.yml
Because JetBrains releases doesn't seem that polished(see 6 hour CI runs), we should stop using latest and pin versions.
> chore(qodana): pin version

- src/main/java/spoon/support/compiler/jdt/ContextBuilder.java
Field Initializer  false for field isBuildLambda in type spoon.support.compiler.jdt.ContextBuilder was redundant and was removed.
Field Initializer  false for field isBuildTypeCast in type spoon.support.compiler.jdt.ContextBuilder was redundant and was removed.
Field Initializer  false for field ignoreComputeImports in type spoon.support.compiler.jdt.ContextBuilder was redundant and was removed.
Empty String check was written as String.equals("") and refactored to String.isEmpty()
Because I'm kind of lazy, I'm currently writing a tool for auto generation of these commits. This is the first result and should fix for ContextBuilder some issues.
> refactor(ContextBuilder): remove Qodana warnings

- src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
- src/main/java/spoon/support/visitor/java/internal/PackageRuntimeBuilderContext.java
- src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
- src/test/java/spoon/test/pkg/cyclic/Outside.java
- src/test/java/spoon/test/pkg/cyclic/direct/Cyclic.java
- src/test/java/spoon/test/pkg/cyclic/direct/package-info.java
- src/test/java/spoon/test/pkg/cyclic/indirect/Indirect.java
- src/test/java/spoon/test/pkg/cyclic/indirect/package-info.java
Fixes #4351.
This is a very unfortunate situation that only happens in combination of annotations on packages. When visiting the type reference of an annotation, we're also visiting its package, and if this package is annotated, we'll do the same again.
With this fix, packages are only visited if the contexts don't not already hold a reference to the package.
The tests cover some more complex situations that would have caused similar issues.
> fix: prevent stackoverflow when visiting of cyclic annotation/package structures

- src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java
- src/test/java/spoon/generating/ReplacementVisitorGenerator.java
- src/test/java/spoon/generating/replace/ReplaceScanner.java
- src/test/java/spoon/generating/replace/ReplacementVisitor.java
- src/test/java/spoon/processing/CtGenerationTest.java
Change generation to produce static inner classes and remove useless catch. Add quality of life to ReplacementVisitorGeneration adding a newline after generation to the file, because checkstyle enforces it.
> refactor: produce static inner classes and remove useless catch for ReplacementVisitor

- src/main/java/spoon/support/reflect/declaration/CtRecordImpl.java
- src/main/java/spoon/support/visitor/equals/CloneHelper.java
- src/test/java/spoon/test/record/CtRecordTest.java
- src/test/resources/records/MultiParameter.java
Instead of creating a new test case, I added the missing checks to the existing one. The most important one is the one with the `head(records).toString()`: changing the Set to LinkedHashSet makes all the other checks pass, but the output is still in reverse order.
The fix in CloneHelper is less than ideal, but I cannot think of a better solution. IMHO the visitor pattern is overused in spoon, i. e. I cannot see a valid reason to use it for cloning. The visitor pattern is necessary for double dispatch, but if I didn't miss anything, cloning just needs a single dispatch.
Please review and comment.
> fix: fix pretty-printing ordering for record parameters

- .gitignore
This file doesn't look like it should be in the repo, let's add it to the gitignore.
> review: chore(git): add gradle enterprise ID to gitignore

- src/main/java/spoon/reflect/visitor/CommentHelper.java
As @I-Al-Istannen already pointed out, Java 11 has the nice `String#lines` method. Removes the regex and replaces it with this.
fixes #4105
> review: fix: add usage of String#lines

- src/test/java/spoon/test/strings/StringTest.java
#3919 
In type spoon.test.strings.StringLiteralTest:
- Replaced junit 4 test annotation with junit 5 test annotation in testSnippetFullClass
In type spoon.test.strings.StringTest:
- Replaced junit 4 test annotation with junit 5 test annotation in testModelBuildingInitializer
> review: refactor(*): Convert StringTests to junit5

- src/test/java/spoon/reflect/declaration/UnknownDeclarationTest.java
Replaced junit 4 test annotation with junit 5 test annotation in testUnknownCalls
Transformed junit4 assert to junt 5 assertion in testUnknownCalls
> test: migrate UnknownDeclarationTest to junit 5

- src/test/java/spoon/test/strings/StringLiteralTest.java
I split the PR in 2 as the guidelines say.
Replaced junit 4 test annotation with junit 5 test annotation in testSnippetFullClass
Transformed junit4 assert to junt 5 assertion in testSnippetFullClass
> test: refactor StringLiteralTest to Junit 5

- .github/workflows/tests.yml
In regards of #4189 and #4337, it would make sense to run tests in Java 17. Especially as the shadow model cannot be fully tested otherwise.
I just switched from Java 16 to Java 17, as Java 16 won't receive any more updates anyways.
As a side note, it might be cool for spoon to join the [Quality Outreach Program](https://wiki.openjdk.java.net/display/quality/Quality+Outreach).
> review: chore: run tests with Java 17

- src/test/java/spoon/test/arrays/ArraysTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testArrayReferences
Replaced junit 4 test annotation with junit 5 test annotation in testInitializeWithNewArray
Replaced junit 4 test annotation with junit 5 test annotation in testCtNewArrayInnerCtNewArray
Replaced junit 4 test annotation with junit 5 test annotation in testCtNewArrayWitComments
Replaced junit 4 test annotation with junit 5 test annotation in testParameterizedVarargReference
Replaced junit 4 test annotation with junit 5 test annotation in testParameterizedArrayReference
Replaced junit 4 test annotation with junit 5 test annotation in testParameterizedArrayVarargReference …
> review: refactor(ArraysTest): migrate to junit 5

- src/main/java/spoon/pattern/internal/node/ElementNode.java
- src/test/java/spoon/test/template/PatternTest.java
The metadata of the template element was ignored when its clone was generated. This was creating an issue for preserving the declaration style of arrays. See [this comment](https://github.com/INRIA/spoon/pull/4341#discussion_r776262782).
> fix: clone metadata for elements created via template

- src/main/java/spoon/pattern/internal/node/ElementNode.java
- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/main/java/spoon/support/reflect/reference/CtArrayTypeReferenceImpl.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/sniperPrinter/arrayInitialisation/AsLocalVariable.java
- src/test/resources/sniperPrinter/arrayInitialisation/FiveIntegers.java
- src/test/resources/sniperPrinter/arrayInitialisation/MultiDimension.java
- src/test/resources/sniperPrinter/arrayInitialisation/ToNull.java
- src/test/resources/sniperPrinter/arrayInitialisation/ToNullElements.java
> fix: print square brackets in array initalisation

- src/test/java/spoon/CompilationUnitPrintTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in test
Transformed junit4 assert to junit 5 assertion in test
> test: migrate CompilationUnitPrintTest to junit 5

- src/test/java/spoon/test/casts/CastTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testCast1
Replaced junit 4 test annotation with junit 5 test annotation in testCast2
Replaced junit 4 test annotation with junit 5 test annotation in testCast3
Replaced junit 4 test annotation with junit 5 test annotation in testCase4
Replaced junit 4 test annotation with junit 5 test annotation in testTypeAnnotationOnCast
Transformed junit4 assert to junt 5 assertion in testCast1
Transformed junit4 assert to junt 5 assertion in testCast2
Transformed junit4 assert to junt 5 assertion in testCast3
Transformed junit4 assert to junt 5 assertion in testCase4
Transformed junit4 assert to junt 5 assertion in testTypeAnnotationOnCast
> testCastTest): migrate to junit 5

- .github/workflows/tests.yml
- src/main/java/spoon/support/compiler/jdt/ContextBuilder.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/test/java/spoon/test/record/CtRecordTest.java
- src/test/resources/records/CompactConstructor.java
- src/test/resources/records/CompactConstructor2.java
I have created a second test case for record compact constructors to demostrate the problem. I have created a PR even if I don't have a fix yet to make reproducing easier: either run CtRecordTest.testCompactConstructor2() directly from your IDE (in IntelliJ it's possible to run disabled tests from the IDE, don't know about eclipse), or remove the "@Disabled" annotation from said method.
> fix(record): valid assignments in record compact constructors

- src/test/java/spoon/reflect/visitor/CtIteratorTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testCtElementIteration
Transformed junit4 assert to junit 5 assertion in testCtIterator
Transformed junit4 assert to junit 5 assertion in testAsIterable
Transformed junit4 assert to junit 5 assertion in testDescendantIterator
> test: migrate CtIteratorTest to junit 5

- src/test/java/spoon/reflect/visitor/CtInheritanceScannerMethodsTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testMethodsInInheritanceScanner
> test: migrate CtInheritanceScannerMethodsTest to junit 5

- src/test/java/spoon/reflect/visitor/CtBFSIteratorTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testCtElementIteration
Transformed junit4 assert to junit 5 assertion in testCtIterator
> test: migrate CtBFSIteratorTest to junit 5

- src/test/java/spoon/reflect/factory/GenerateParentlessPackageTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in generateParentlessPackage
Transformed junit4 assert to junit 5 assertion in generateParentlessPackage
> test: migrate GenerateParentlessPackageTest to junit 5

- src/test/java/spoon/reflect/declaration/CtTypeInformationTest.java
#3919
Replaced @Before annotation with @BeforeEach from method setUp
Replaced junit 4 test annotation with junit 5 test annotation in testClassTypingContextContinueScanning
Replaced junit 4 test annotation with junit 5 test annotation in testGetAllMethodsReturnsTheRightNumber
Replaced junit 4 test annotation with junit 5 test annotation in testGetSuperclass
Replaced junit 4 test annotation with junit 5 test annotation in testGetAllMethodsWontReturnOverriddenMethod
Transformed junit4 assert to junit 5 assertion in testClassTypingContextContinueScanning
Transformed junit4 assert to junit 5 assertion in testGetAllMethodsReturnsTheRightNumber
Transformed junit4 assert to junit 5 assertion in testGetSuperclass
Transformed junit4 assert to junit 5 …
> test : migrate CtTypeInformationTest to Junit 5

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/test/java/spoon/test/prettyprinter/PrinterTest.java
fix #4350
This should the fix issue #4350 . I tried to create an as small class as possible for the test case. The testcase seems pretty bad, any suggestions for an assertion checking if a String equals without newline characters? Otherwise, the new testcase is again Unix only.
> fix: correct type reference for ClassLiteralAccess

- src/test/java/spoon/reflect/ast/CloneTest.java
#3919 As always as clean as the sniper printer can produce.
Replaced junit 4 test annotation with junit 5 test annotation in testCloneMethodsDeclaredInAST
Replaced junit 4 test annotation with junit 5 test annotation in testCloneCastConditional
Replaced junit 4 test annotation with junit 5 test annotation in testCloneListener
Replaced junit 4 test annotation with junit 5 test annotation in testCopyMethod
Replaced junit 4 test annotation with junit 5 test annotation in testCopyType
Replaced junit 4 test annotation with junit 5 test annotation in testIssue3389
Replaced junit 4 test annotation with junit 5 test annotation in testCloneKeepsImplicitModifierState …
> test: migrate CloneTest to Junit 5

- src/test/java/spoon/reflect/visitor/CtVisitorTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testMethodsInVisitor
> test: migrate CtVisitorTest to junit 5

- src/test/java/spoon/support/compiler/jdt/TreeBuilderCompilerTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testIgnoreSyntaxErrorsCompilation
Replaced junit 4 test annotation with junit 5 test annotation in testIgnoreSyntaxErrorsLogging
Replaced junit 4 test annotation with junit 5 test annotation in testEveryInputHasSyntaxError
Replaced junit 4 test annotation with junit 5 test annotation in testIgnoreSyntaxErrorsCommandLine
Transformed junit4 assert to junit 5 assertion in testIgnoreSyntaxErrorsCompilation
Transformed junit4 assert to junit 5 assertion in testIgnoreSyntaxErrorsLogging
Transformed junit4 assert to junit 5 assertion in testEveryInputHasSyntaxError
Transformed junit4 assert to junit 5 assertion in testIgnoreSyntaxErrorsCommandLine
> test: migrate TreeBuilderCompilerTest to junit 5

- src/test/java/spoon/test/annotation/AnnotationLoopTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testAnnotationDeclaredInForInit
Transformed junit4 assert to junit 5 assertion in testAnnotationDeclaredInForInit
> test: migrate AnnotationLoopTest to junit 5

- src/test/java/spoon/test/OutputTypeTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testOutputTypeLoading
Transformed junit4 assert to junit 5 assertion in testOutputTypeLoading
> test: migrate OutputTypeTest to Junit 5

- src/test/java/spoon/test/api/FileSystemFolderTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in jarFileIsNotSubfolder
Replaced junit 4 test annotation with junit 5 test annotation in testLauncherWithWrongPathAsInput
Transformed junit4 assert to junit 5 assertion in jarFileIsNotSubfolder
Transformed junit4 assert to junit 5 assertion in testLauncherWithWrongPathAsInput
> test: migrate FileSystemFolderTest to junit 5

- src/test/java/spoon/test/api/APITest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testBasicAPIUsage
Replaced junit 4 test annotation with junit 5 test annotation in testOverrideOutputWriter
Replaced junit 4 test annotation with junit 5 test annotation in testDuplicateEntry
Replaced junit 4 test annotation with junit 5 test annotation in testDuplicateFolder
Replaced junit 4 test annotation with junit 5 test annotation in testDuplicateFilePlusFolder
Replaced junit 4 test annotation with junit 5 test annotation in testAddProcessorMethodInSpoonAPI
Replaced junit 4 test annotation with junit 5 test annotation in testOutputOfSpoon
Replaced junit 4 test annotation with junit 5 test annotation in testDestinationOfSpoon
Replaced junit 4 test annotation with junit 5 test …
> test: migrate APITest to Junit 5

- src/test/java/spoon/test/annotation/AnnotationValuesTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testValuesOnJava7Annotation
Replaced junit 4 test annotation with junit 5 test annotation in testValuesOnJava8Annotation
Replaced junit 4 test annotation with junit 5 test annotation in testCtAnnotationAPI
Replaced junit 4 test annotation with junit 5 test annotation in testAnnotationFactory
Replaced junit 4 test annotation with junit 5 test annotation in testAnnotateWithEnum
Replaced junit 4 test annotation with junit 5 test annotation in testAnnotationPrintAnnotation
Replaced junit 4 test annotation with junit 5 test annotation in testIssue3639
Transformed junit4 assert to junit 5 assertion in testAnnotateWithEnum
Transformed junit4 assert to junit 5 assertion in …
> test: migrate AnnotationValuesTest to Junit 5

- src/test/java/spoon/reflect/visitor/CtScannerTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testScannerContract
Replaced junit 4 test annotation with junit 5 test annotation in testScannerCallsAllProperties
Replaced junit 4 test annotation with junit 5 test annotation in testScan
Replaced junit 4 test annotation with junit 5 test annotation in testDequeSCanner
Transformed junit4 assert to junit 5 assertion in testScannerCallsAllProperties
Transformed junit4 assert to junit 5 assertion in testScan
Transformed junit4 assert to junit 5 assertion in testDequeSCanner
> test: migrate CtScannerTest to junit 5

- src/test/java/spoon/test/constructor/ConstructorTest.java
#3919
Replaced @Before annotation with @BeforeEach from method setUp
Replaced junit 4 test annotation with junit 5 test annotation in testImplicitConstructor
Replaced junit 4 test annotation with junit 5 test annotation in testTransformationOnConstructorWithInsertBegin
Replaced junit 4 test annotation with junit 5 test annotation in testTransformationOnConstructorWithInsertBefore
Replaced junit 4 test annotation with junit 5 test annotation in callParamConstructor
Replaced junit 4 test annotation with junit 5 test annotation in testConstructorCallFactory
Replaced junit 4 test annotation with junit 5 test annotation in testTypeAnnotationOnExceptionDeclaredInConstructors …
> test: migrate ConstructorTest to JUnit 5

- .github/workflows/tests.yml
We had some problems with stuck qodana runs, but it seems that jetbrains rolled some updates out. Let's see if this works.
> chore(qodana): bump Qodana version

- src/test/java/spoon/test/api/MetamodelTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testGetAllMetamodelInterfacess
Replaced junit 4 test annotation with junit 5 test annotation in testRuntimeMetamodel
Replaced junit 4 test annotation with junit 5 test annotation in testGetterSetterForRole
Replaced junit 4 test annotation with junit 5 test annotation in testRoleOnField
Replaced junit 4 test annotation with junit 5 test annotation in testMetamodelWithoutSources
Replaced junit 4 test annotation with junit 5 test annotation in testMetamodelCachedInFactory
Replaced junit 4 test annotation with junit 5 test annotation in spoonMetaModelTest
Replaced junit 4 test annotation with junit 5 test annotation in testGetRoleHandlersOfClass
Replaced junit 4 test annotation with …
> test: migrate MetamodelTest to Junit 5

- src/test/java/spoon/LauncherTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testInitEnvironmentDefault
Replaced junit 4 test annotation with junit 5 test annotation in testInitEnvironment
Replaced junit 4 test annotation with junit 5 test annotation in testLauncherInEmptyWorkingDir
Replaced junit 4 test annotation with junit 5 test annotation in testLLauncherBuildModelReturnAModel
Replaced junit 4 test annotation with junit 5 test annotation in testPrettyPrintWithVirtualFileInput
Replaced junit 4 test annotation with junit 5 test annotation in testClasspathURLWithSpaces
Transformed junit4 assert to junit 5 assertion in testInitEnvironmentDefault
Transformed junit4 assert to junit 5 assertion in testInitEnvironment
Transformed junit4 assert to junit 5 …
> test: migrate LauncherTest to Junit 5

- src/test/java/spoon/test/api/NoClasspathTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in test
Replaced junit 4 test annotation with junit 5 test annotation in testBug20141021
Replaced junit 4 test annotation with junit 5 test annotation in testGetStaticDependency
Replaced junit 4 test annotation with junit 5 test annotation in testIssue1747
Replaced junit 4 test annotation with junit 5 test annotation in testInheritanceInNoClassPathWithClasses
Transformed junit4 assert to junit 5 assertion in test
Transformed junit4 assert to junit 5 assertion in testBug20141021
Transformed junit4 assert to junit 5 assertion in testGetStaticDependency
Transformed junit4 assert to junit 5 assertion in testInheritanceInNoClassPathWithClasses
> test: migrate NoClasspathTest to Junit 5

- src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in statelessFactory
Replaced junit 4 test annotation with junit 5 test annotation in testFactorySubFactory
Replaced junit 4 test annotation with junit 5 test annotation in testSrcMainJava
Replaced junit 4 test annotation with junit 5 test annotation in metamodelPackageRule
Replaced junit 4 test annotation with junit 5 test annotation in testGoodTestClassNames
Replaced junit 4 test annotation with junit 5 test annotation in testStaticClasses
Replaced junit 4 test annotation with junit 5 test annotation in testInterfacesAreCtScannable
Replaced junit 4 test annotation with junit 5 test annotation in testSpecPackage
Transformed junit4 assert to junit 5 assertion in statelessFactory …
> test: migrate SpoonArchitectureEnforcerTest to Junit 5

- src/test/java/spoon/test/compilationunit/TestCompilationUnit.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testIsoEncodingIsSupported
Replaced junit 4 test annotation with junit 5 test annotation in testGetUnitTypeWorksWithDeclaredType
Replaced junit 4 test annotation with junit 5 test annotation in testGetUnitTypeWorksWithDeclaredPackage
Replaced junit 4 test annotation with junit 5 test annotation in testGetUnitTypeWorksWithCreatedObjects
Replaced junit 4 test annotation with junit 5 test annotation in testCompilationUnitDeclaredTypes
Replaced junit 4 test annotation with junit 5 test annotation in testCompilationUnitInNamedModuleHasDeclaredTypes
Replaced junit 4 test annotation with junit 5 test annotation in testCompilationUnitSourcePosition
Replaced junit 4 test annotation with …
> test: migrate TestCompilationUnit to Junit 5

- src/test/java/spoon/test/change/ChangeCollectorTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testChangeCollector
Transformed junit4 assert to junit 5 assertion in testChangeCollector
> test: migrate ChangeCollectorTest to Junit 5

- src/test/java/spoon/test/visibility/VisibilityTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testMethodeWithNonAccessibleTypeArgument
Replaced junit 4 test annotation with junit 5 test annotation in testVisibilityOfClassesNamedByClassesInJavaLangPackage
Replaced junit 4 test annotation with junit 5 test annotation in testFullyQualifiedNameOfTypeReferenceWithGeneric
Replaced junit 4 test annotation with junit 5 test annotation in testName
Replaced junit 4 test annotation with junit 5 test annotation in testInvocationVisibilityInFieldDeclaration
Transformed junit4 assert to junit 5 assertion in testMethodeWithNonAccessibleTypeArgument
Transformed junit4 assert to junit 5 assertion in testVisibilityOfClassesNamedByClassesInJavaLangPackage
Transformed junit4 assert to junit …
> test: migrate VisibilityTest to Junit 5

- src/test/java/spoon/toStringBugTest/ToStringBugTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testIssue3382
Transformed junit4 assert to junit 5 assertion in testIssue3382
> test: migrate ToStringBugTest to Junit 5

- src/test/java/spoon/test/visitor/AssignmentsEqualsTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testEquals
Transformed junit4 assert to junit 5 assertion in testEquals
Replaced assertTrue checking equals with assertEquals
Replaced assertFalse checking equals with assertNotEquals
Replaced assertFalse checking equals with assertNotEquals
Replaced assertFalse checking equals with assertNotEquals
Replaced assertFalse checking equals with assertNotEquals
Replaced assertTrue checking same with assertSame
> test: migrate AssignmentsEqualsTest to junit 5

- src/test/java/spoon/test/spoonifier/SpoonifierTest.java
#3919
Replaced @Ignore annotation with @Disabled from method testOnAllTestClasses
Replaced @Ignore annotation with @Disabled from method testSpoonifierElement
Replaced junit 4 test annotation with junit 5 test annotation in testOnAllTestClasses
Replaced junit 4 test annotation with junit 5 test annotation in testSpoonifier
Replaced junit 4 test annotation with junit 5 test annotation in testSpoonifierElement
Replaced junit 4 test annotation with junit 5 test annotation in testGeneratedSpoonifierCode
Transformed junit4 assert to junit 5 assertion in testSpoonifierWith
Transformed junit4 assert to junit 5 assertion in testGeneratedSpoonifierCode
> test: migrate SpoonifierTest to JUnit 5

- src/test/java/spoon/test/staticFieldAccess/StaticAccessTest.java
#3919
Replaced @Before annotation with @BeforeEach from method setUp
Replaced junit 4 test annotation with junit 5 test annotation in testReferences
Replaced junit 4 test annotation with junit 5 test annotation in testProcessAndCompile
Transformed junit4 assert to junit 5 assertion in testReferences
Transformed junit4 assert to junit 5 assertion in testProcessAndCompile
> test: migrate StaticAccessTest to JUnit 5

- src/test/java/spoon/test/staticFieldAccess2/ImplicitStaticFieldReferenceTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testImplicitStaticFieldReference
Replaced junit 4 test annotation with junit 5 test annotation in testImplicitStaticFieldReferenceAutoImport
Replaced junit 4 test annotation with junit 5 test annotation in testImplicitFieldReference
Replaced junit 4 test annotation with junit 5 test annotation in testImplicitFieldReferenceAutoImport
Replaced junit 4 test annotation with junit 5 test annotation in testAmbiguousImplicitFieldReference
Replaced junit 4 test annotation with junit 5 test annotation in testAmbiguousImplicitFieldReferenceAutoImport
Replaced junit 4 test annotation with junit 5 test annotation in testImplicitStaticClassAccess
Replaced junit 4 test annotation with junit 5 …
> test: migrate ImplicitStaticFieldReferenceTest to JUnit 5

- src/test/java/spoon/test/support/ResourceTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testEqualsFileSystemFile
Replaced junit 4 test annotation with junit 5 test annotation in testFileSystemFolder
Replaced junit 4 test annotation with junit 5 test annotation in testVirtualFolder
Replaced junit 4 test annotation with junit 5 test annotation in testFilteringFolder
Replaced Assert.assertThat with MatcherAssert.assertThat in testFileSystemFolder()
Replaced Assert.assertThat with MatcherAssert.assertThat in testFileSystemFolder()
Transformed junit4 assert to junit 5 assertion in testEqualsFileSystemFile
Transformed junit4 assert to junit 5 assertion in testFileSystemFolder
Transformed junit4 assert to junit 5 assertion in testVirtualFolder
Transformed junit4 assert to …
> test: migrate ResourceTest to JUnit 5

- src/test/java/spoon/test/targeted/TargetedExpressionTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testCtSuperAccess
Replaced junit 4 test annotation with junit 5 test annotation in testCtThisAccess
Replaced junit 4 test annotation with junit 5 test annotation in testTargetOfFieldAccess
Replaced junit 4 test annotation with junit 5 test annotation in testNotTargetedExpression
Replaced junit 4 test annotation with junit 5 test annotation in testCastWriteWithGenerics
Replaced junit 4 test annotation with junit 5 test annotation in testTargetsOfFieldAccess
Replaced junit 4 test annotation with junit 5 test annotation in testTargetsOfStaticFieldAccess
Replaced junit 4 test annotation with junit 5 test annotation in testTargetsOfFieldAccessInInnerClass
Replaced junit 4 test …
> test: migrate TargetedExpressionTest to JUnit 5

- src/test/java/spoon/test/trycatch/TryCatchTest.java
#3919 
Replaced junit 4 test annotation with junit 5 test annotation in testModelBuildingInitializer
Replaced junit 4 test annotation with junit 5 test annotation in testFullyQualifiedException
Replaced junit 4 test annotation with junit 5 test annotation in testCatchOrder
Replaced junit 4 test annotation with junit 5 test annotation in testExceptionJava7
Replaced junit 4 test annotation with junit 5 test annotation in testRethrowingExceptionsJava7
Replaced junit 4 test annotation with junit 5 test annotation in testTryWithOneResource
Replaced junit 4 test annotation with junit 5 test annotation in testTryWithResources
Replaced junit 4 test annotation with junit 5 test annotation in testMultiTryCatchWithCustomExceptions
Replaced junit 4 test …
> test: migrate TryCatchTest to JUnit 5

- src/test/java/spoon/test/varargs/VarArgsTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testModelBuildingInitializer
Transformed junit4 assert to junit 5 assertion in testModelBuildingInitializer
> test: migrate VarArgsTest to JUnit 5

- src/test/java/spoon/test/serializable/SourcePositionTest.java
- src/test/java/spoon/test/sourcePosition/SourcePositionTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testSourcePosition
Replaced junit 4 test annotation with junit 5 test annotation in test_sourcePositionOfTypeInFieldExists
Replaced junit 4 test annotation with junit 5 test annotation in equalPositionsHaveSameHashcode
Replaced junit 4 test annotation with junit 5 test annotation in testSourcePositionOfSecondPrimitiveType
Replaced junit 4 test annotation with junit 5 test annotation in testSourcePositionStringFragment
Replaced junit 4 test annotation with junit 5 test annotation in testSourcePositionWhenCommentInAnnotation
Transformed junit4 assert to junit 5 assertion in testSourcePosition
Transformed junit4 assert to junit 5 assertion in test_sourcePositionOfTypeInFieldExists …
> test: migrate SourcePositionTest to JUnit 5

- src/test/java/spoon/test/variable/AccessFullyQualifiedFieldTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testCheckAssignmentContracts
Replaced junit 4 test annotation with junit 5 test annotation in testNoFQNWhenShadowedByField
Replaced junit 4 test annotation with junit 5 test annotation in testNoFQNWhenShadowedByLocalVariable
Replaced junit 4 test annotation with junit 5 test annotation in testNoFQNWhenUsedInInnerClassAndShadowedByLocalVariable
Replaced junit 4 test annotation with junit 5 test annotation in testNoFQNWhenUsedInTryCatch
Replaced junit 4 test annotation with junit 5 test annotation in testNoFQNWhenUsedInLoop
Replaced junit 4 test annotation with junit 5 test annotation in testStaticImportWithAutoImport …
> test: migrate AccessFullyQualifiedFieldTest  to JUnit 5

- src/test/java/spoon/test/variable/AccessTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testCanVisitVariableAccessAndSubClasses
Replaced junit 4 test annotation with junit 5 test annotation in testCanVisitFieldAccessAndSubClasses
Replaced junit 4 test annotation with junit 5 test annotation in testCanVisitArrayAccessAndSubClasses
Replaced junit 4 test annotation with junit 5 test annotation in testStackedAssignments
Replaced junit 4 test annotation with junit 5 test annotation in testRHS
Replaced junit 4 test annotation with junit 5 test annotation in testFieldWriteDeclaredInTheSuperclass
Replaced junit 4 test annotation with junit 5 test annotation in testVariableAccessInNoClasspath …
> test: migrate AccessTest to Junit 5

- src/test/java/spoon/test/annotation/AnnotationTest.java
#3919
Replaced Assert.assertThat with MatcherAssert.assertThat in testGetAnnotationFromParameter()
Replaced Assert.assertThat with MatcherAssert.assertThat in testGetAnnotationFromParameter()
Replaced Assert.assertThat with MatcherAssert.assertThat in testGetAnnotationFromParameter()
Replaced Assert.assertThat with MatcherAssert.assertThat in testGetAnnotationFromParameter()
Replaced Assert.assertThat with MatcherAssert.assertThat in testGetAnnotationFromParameter()
Replaced Assert.assertThat with MatcherAssert.assertThat in testGetAnnotationFromParameter()
Replaced Assert.assertThat with MatcherAssert.assertThat in testGetAnnotationFromParameter()
Replaced Assert.assertThat with MatcherAssert.assertThat in testGetAnnotationFromParameter()
Replaced …
> test: migrate AnnotationTest to junit 5

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/sniperPrinter/arrayInitialisation/GenericTypeArray.java
Fixes #4421
I missed attaching metadata to generic types in array type references in https://github.com/INRIA/spoon/pull/4341 which resulted in #4421. The changes in this PR fix it.
Also, I slightly changed the test case to modify the source position of type reference instead of the entire field because the former is more precise.
> fix: Fix square bracket printing in array field declarations

- src/main/java/spoon/reflect/visitor/LiteralHelper.java
- src/test/java/spoon/test/textBlocks/TextBlockTest.java
- src/test/resources/textBlock/TextBlockTestClass.java
Fixes #4408
Besides adding the (currently disabled) test case, I changed the Junit imports and fixed the parameter order of the assertEquals calls.
> fix: escape sequences in text-blocks are kept

- src/test/java/spoon/test/reference/ExecutableReferenceGenericTest.java
#3919
- Replaced `@Before` annotation with @BeforeEach from method `setUp`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReferencesBetweenConstructors`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReferencesBetweenConstructorsInOtherClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testOneReferenceBetweenMethodsInSameClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMultiReferenceBetweenMethodsWithGenericInSameClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMultiReferencesBetweenMethodsWithoutGenericInSameClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMethodWithoutReferences`
- Replaced junit 4 test annotation with junit …
> test: migrate ExecutableReferenceGenericTest to JUnit 5

- src/test/java/spoon/test/reference/ElasticsearchStackoverflowTest.java
- Replaced junit 4 test annotation with junit 5 test annotation in `testStackOverflow`
- Transformed junit4 assert to junit 5 assertion in `testStackOverflow`
> test: migrate ElasticsearchStackoverflowTest to JUnit 5

- src/test/java/spoon/test/reference/CloneReferenceTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetDeclarationAfterClone`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetDeclarationOfFieldAfterClone`
- Transformed junit4 assert to junit 5 assertion in `testGetDeclarationAfterClone`
- Transformed junit4 assert to junit 5 assertion in `testGetDeclarationOfFieldAfterClone`
> test: migrate CloneReferenceTest to JUnit 5

- src/test/java/spoon/test/reference/AnnotationFieldReferenceTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testAnnotationFieldReference`
- Transformed junit4 assert to junit 5 assertion in `testAnnotationFieldReference`
> test: migrate AnnotationFieldReferenceTest to JUnit 5

- src/test/java/spoon/test/processing/ProcessingTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testInsertBegin`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInsertEnd`
- Replaced junit 4 test annotation with junit 5 test annotation in `testProcessorNotFoundThrowAnException`
- Replaced junit 4 test annotation with junit 5 test annotation in `testProcessorWithNoArgumentsInConstructor`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInitProperties`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInitPropertiesWithWrongType`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInitPropertiesWithStringType`
- Replaced junit 4 test annotation with junit 5 test annotation in `testProcessorWithGenericType`
- Replaced junit …
> test: migrate ProcessingTest to JUnit 5

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/test/java/spoon/test/lambda/LambdaTest.java
- src/test/java/spoon/test/prettyprinter/PrinterTest.java
Before the fix DJPP printed  `((Predicate<Person>) (( p) -> p.age > 10))` and now `((Predicate<Person>) (p -> p.age > 10))`
The removed whitespace and parentheses for single parameter lambdas without type is much closer to normal style.
> fix: no parentheses for single lambda parameters

- src/test/java/spoon/test/replace/ReplaceTest.java
#3919
- Replaced `@Before` annotation with @BeforeEach from method `setup`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReplaceSet`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReplaceBlock`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReplaceReplace`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReplaceStmtByList`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReplaceStmtByListStatements`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReplaceStmtByListStatementsAndNull`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReplaceField` …
> test: migrate ReplaceTest to Junit 5 

- src/test/java/spoon/test/reflect/visitor/ReferenceQueryTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `getAllTypeReferencesInEnum`
- Transformed junit4 assert to junit 5 assertion in `getAllTypeReferencesInEnum`
> test: migrate ReferenceQueryTest to Junit 5

- src/test/java/spoon/test/reference/TypeReferenceTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetAllExecutablesForInterfaces`
- Replaced junit 4 test annotation with junit 5 test annotation in `loadReferencedClassFromClasspath`
- Replaced junit 4 test annotation with junit 5 test annotation in `doNotCloseLoader`
- Replaced junit 4 test annotation with junit 5 test annotation in `testNullReferenceSubtype`
- Replaced junit 4 test annotation with junit 5 test annotation in `unboxTest`
- Replaced junit 4 test annotation with junit 5 test annotation in `testToStringEqualityBetweenTwoGenericTypeDifferent`
- Replaced junit 4 test annotation with junit 5 test annotation in `testRecursiveTypeReference`
- Replaced junit 4 test annotation with junit 5 test annotation in `testRecursiveTypeReferenceInGenericType`
- …
> test: migrate TypeReferenceTest to Junit 5

- src/test/java/spoon/test/query_function/testclasses/VariableReferencesModelTest.java
#3919
- Replaced `@Before` annotation with @BeforeEach from method `setup`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCheckModelConsistency`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCatchVariableReferenceFunction`
- Replaced junit 4 test annotation with junit 5 test annotation in `testLocalVariableReferenceFunction`
- Replaced junit 4 test annotation with junit 5 test annotation in `testParameterReferenceFunction`
- Replaced junit 4 test annotation with junit 5 test annotation in `testVariableReferenceFunction`
- Replaced junit 4 test annotation with junit 5 test annotation in `testVariableScopeFunction`
- Replaced junit 4 test annotation with junit 5 test annotation in `testFieldScopeFunction`
- Replaced junit 4 test annotation …
> test: migrate VariableReferencesModelTest to JUnit 5

- src/test/java/spoon/test/path/PathTest.java
- Replaced junit 4 test annotation with junit 5 test annotation in `testBuilderMethod`
- Replaced junit 4 test annotation with junit 5 test annotation in `testBuilder`
- Replaced junit 4 test annotation with junit 5 test annotation in `testPathFromString`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMultiPathFromString`
- Replaced junit 4 test annotation with junit 5 test annotation in `testIncorrectPathFromString`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetPathFromNonParent`
- Replaced junit 4 test annotation with …
> test: migrate PathTest to JUnit 5

- src/test/java/spoon/reflect/visitor/CtInheritanceScannerTest.java
Now we are reaching some testclasses where even a human has a hard time to refactor. From my JUnit 5 understanding, the author wanted to use dynamic tests with `TestFactory` and implemented it with JUnit 4 `Parameterized`. This PR only migrates the testcase to JUnit 5 style, I still believe the testcase needs a rewrite in the future.
> test: migrate CtInheritanceScannerTest to JUnit 5

- src/test/java/spoon/test/reference/ExecutableReferenceTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testCallMethodOfClassNotPresent`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSuperClassInGetAllExecutables`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetAllExecutablesMethodForInterface`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetAllExecutablesMethodForClasses`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCreateReferenceForAnonymousExecutable`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInvokeEnumMethod`
- Replaced junit 4 test annotation with junit 5 test annotation in `testLambdaNoClasspath` …
> test: migrate ExecutableReferenceTest to Junit 5

- src/test/java/spoon/test/reference/VariableAccessTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testVariableAccessDeclarationInAnonymousClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDeclarationArray`
- Replaced junit 4 test annotation with junit 5 test annotation in `testParameterReferenceInConstructorNoClasspath`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDeclarationOfVariableReference`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDeclaringTypeOfALambdaReferencedByParameterReference`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetDeclarationAfterClone`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReferences` …
> test: migrate VariableAccessTest to Junit 5

- src/test/java/spoon/test/role/TestCtRole.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetCtRoleByName`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCtRoleGetSubRolesNotNull`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCtRoleSubRoleMatchesWithSuperRole`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCtRoleGetSubRole`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCtRoleGetSubRoleFailsOnOthers`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCtRoleGetSubRoleFailsOnNull`
- Transformed junit4 assert to junit 5 assertion in `testGetCtRoleByName`
- Transformed junit4 assert to junit 5 assertion in `testCtRoleGetSubRolesNotNull`
- Transformed junit4 assert to junit 5 assertion …
> test: migrate TestCtRole to JUnit 5

- src/test/java/spoon/test/type/TypeTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testTypeAccessForDotClass
Replaced junit 4 test annotation with junit 5 test annotation in testTypeAccessOnPrimitive
Replaced junit 4 test annotation with junit 5 test annotation in testTypeAccessForTypeAccessInInstanceOf
Replaced junit 4 test annotation with junit 5 test annotation in testTypeAccessOfArrayObjectInFullyQualifiedName
Replaced junit 4 test annotation with junit 5 test annotation in testTypeAccessImplicitIsDerived
Replaced junit 4 test annotation with junit 5 test annotation in test
Replaced junit 4 test annotation with junit 5 test annotation in testIntersectionTypeReferenceInGenericsAndCasts …
> test: migrate TypeTest to Junit 5

- src/test/java/spoon/test/snippets/SnippetTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testSnippetFullClass
Replaced junit 4 test annotation with junit 5 test annotation in testSnippetWihErrors
Replaced junit 4 test annotation with junit 5 test annotation in testCompileSnippetSeveralTimes
Replaced junit 4 test annotation with junit 5 test annotation in testCompileSnippetWithContext
Replaced junit 4 test annotation with junit 5 test annotation in testCompileStatementWithReturn
Replaced junit 4 test annotation with junit 5 test annotation in testIssue981
Replaced junit 4 test annotation with junit 5 test annotation in testCompileAndReplaceSnippetsIn
Replaced junit 4 test annotation with junit 5 test annotation in testCompileSnippetsWithCtComment
Replaced junit 4 test …
> test: migrate SnippetTest to JUnit 5

- src/test/java/spoon/test/signature/SignatureTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testNullSignature
Replaced junit 4 test annotation with junit 5 test annotation in testNullSignatureInUnboundVariable
Replaced junit 4 test annotation with junit 5 test annotation in testLiteralSignature
Replaced junit 4 test annotation with junit 5 test annotation in testMethodInvocationSignatureStaticFieldsVariables
Replaced junit 4 test annotation with junit 5 test annotation in testMethodInvocationSignatureWithVariableAccess
Replaced junit 4 test annotation with junit 5 test annotation in testUnboundFieldSignature
Replaced junit 4 test annotation with junit 5 test annotation in testArgumentNotNullForExecutableReference
Replaced junit 4 test annotation with junit 5 test …
> test: migrate SignatureTest to Junit 5 

- src/test/java/spoon/test/serializable/SerializableTest.java
#3919
Replaced junit 4 test annotation with junit 5 test annotation in testSerialCtStatement
Replaced junit 4 test annotation with junit 5 test annotation in testSerialFile
Replaced junit 4 test annotation with junit 5 test annotation in testSerializationModelStreamer
Transformed junit4 assert to junit 5 assertion in testSerialCtStatement
Transformed junit4 assert to junit 5 assertion in testSerializationModelStreamer
> test: migrate SerializableTest to JUnit 5

- src/test/java/spoon/test/serializable/ModelStreamerTest.java
#3919
Replaced @BeforeClass annotation with @BeforeAll from method setUp
Replaced @After annotation with @AfterEach from method tearDown
Replaced junit 4 test annotation with junit 5 test annotation in testDefaultCompressionType
Replaced junit 4 test annotation with junit 5 test annotation in testGZipCompressionType
Replaced junit 4 test annotation with junit 5 test annotation in testBZip2CompressionType
Replaced junit 4 test annotation with junit 5 test annotation in testNoneCompressionType
Replaced junit 4 test annotation with junit 5 test annotation in testLZMACompressionType
Transformed junit4 assert to junit 5 assertion in compareFactoryModels
> test: migrate ModelStreamerTest to JUnit 5

- src/test/java/spoon/test/secondaryclasses/ClassesTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testClassWithInternalPublicClassOrInterf`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAnonymousClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testIsAnonymousMethodInCtClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testTopLevel`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInnerClassContruction`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAnonymousClassInStaticField`
- Transformed junit4 assert to junit 5 assertion in `testClassWithInternalPublicClassOrInterf`
- Transformed junit4 assert to junit 5 assertion in `testAnonymousClass`
- Transformed junit4 assert to junit 5 assertion …
> test: migrate ClassesTest to JUnit 5

- src/test/java/spoon/test/parameters/ParameterTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testParameterInNoClasspath`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetParameterReferenceInLambdaNoClasspath`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMultiParameterLambdaTypeReference`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetParentAfterGetParameterReference`
- Transformed junit4 assert to junit 5 assertion in `testParameterInNoClasspath` …
> test: migrate ParameterTest to JUnit 5

- src/test/java/spoon/test/parent/ParentTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testParent`
- Replaced junit 4 test annotation with junit 5 test annotation in `testParentSet`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAddType`
- Replaced junit 4 test annotation with junit 5 test annotation in `testParentOfCtPackageReference` …
> test: migrate ParentTest to JUnit 5

- src/main/java/spoon/reflect/cu/position/NoSourcePosition.java
- src/main/java/spoon/reflect/declaration/CtConstructor.java
- src/main/java/spoon/reflect/declaration/CtMethod.java
- src/main/java/spoon/reflect/declaration/CtType.java
- src/main/java/spoon/reflect/visitor/filter/AbstractReferenceFilter.java
- src/main/java/spoon/support/reflect/cu/position/BodyHolderSourcePositionImpl.java
- src/main/java/spoon/support/reflect/cu/position/CompoundSourcePositionImpl.java
- src/main/java/spoon/support/reflect/cu/position/DeclarationSourcePositionImpl.java
- src/main/java/spoon/support/reflect/cu/position/SourcePositionImpl.java
- src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
Removed a lot of not needed supertypes in the code, where other supertypes already have the interface as supertype.
Removed interface java.io.Serializable from type spoon.reflect.cu.position.NoSourcePosition, because it's redundant
Removed interface spoon.reflect.declaration.CtTypeMember from type spoon.reflect.declaration.CtConstructor, because it's redundant
Removed interface spoon.reflect.declaration.CtTypeMember from type spoon.reflect.declaration.CtMethod, because it's redundant
Removed interface java.io.Serializable from type spoon.support.reflect.cu.position.BodyHolderSourcePositionImpl, because it's redundant
Removed interface java.io.Serializable from type spoon.support.reflect.cu.position.CompoundSourcePositionImpl, because it's redundant …
> review: refactor(*): Remove redundant supertypes

- src/test/java/spoon/test/comparison/EqualTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testEqualsEmptyException`
- Replaced junit 4 test annotation with junit 5 test annotation in `testEqualsComment`
- Replaced junit 4 test annotation with junit 5 test annotation in `testEqualsMultitype`
- Replaced junit 4 test annotation with junit 5 test annotation in `testEqualsActualTypeRef`
- Replaced junit 4 test annotation with junit 5 test annotation in `testEqualsDetails`
- Transformed junit4 assert to junit 5 assertion in `testEqualsEmptyException`
- Transformed junit4 assert to junit 5 assertion in `testEqualsComment`
- …
> test: migrate EqualTest to JUnit 5

- src/test/java/spoon/test/condition/ConditionalTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testConditional`
- Replaced junit 4 test annotation with junit 5 test annotation in `testConditionalWithAssignment`
- Replaced junit 4 test annotation with junit 5 test annotation in `testBlockInConditionAndLoop`
- Replaced junit 4 test annotation with junit 5 test annotation in `testNoBlockInConditionAndLoop`
- Replaced junit 4 test annotation with junit 5 test annotation in `testNoThenBlock`
- Replaced junit 4 test annotation with junit 5 test annotation in `testNoThenBlockBug` …
> test: migrate ConditionalTest to JUnit 5

- src/test/java/spoon/test/constructorcallnewclass/ConstructorCallTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testConstructorCallStringWithoutParameters`
- Replaced junit 4 test annotation with junit 5 test annotation in `testConstructorCallStringWithParameters`
- Replaced junit 4 test annotation with junit 5 test annotation in `testConstructorCallObjectWithoutParameters`
- Replaced junit 4 test annotation with junit 5 test annotation in `testConstructorCallObjectWithParameters` …
> test: migrate ConstructorCallTest to JUnit 5

- src/test/java/spoon/test/control/ControlTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testModelBuildingFor`
- Replaced junit 4 test annotation with junit 5 test annotation in `testModelBuildingDoWhile`
- Transformed junit4 assert to junit 5 assertion in `testModelBuildingFor`
- Transformed junit4 assert to junit 5 assertion in `testModelBuildingDoWhile`
> test: migrate ControlTest to JUnit 5

- src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testNewClassWithObjectClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testNewClassWithInterface`
- Replaced junit 4 test annotation with junit 5 test annotation in `testNewClassWithInterfaceGeneric`
- Replaced junit 4 test annotation with junit 5 test annotation in `testNewClassInterfaceWithParameters`
- Replaced junit 4 test annotation with junit 5 test annotation in `testNewClassInEnumeration`
- Replaced junit 4 …
> test: migrate NewClassTest to JUnit 5

- src/test/java/spoon/test/compilationunit/GetBinaryFilesTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testSingleBinary`
- Replaced junit 4 test annotation with junit 5 test annotation in `testExistingButNotBuiltBinary`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMultiClassInSingleFile`
- Replaced junit 4 test annotation with junit 5 test annotation in `testNestedTypes`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAnonymousClasses`
- Transformed junit4 assert to junit 5 assertion in `testSingleBinary` …
> test: migrate GetBinaryFilesTest to JUnit 5

- src/test/java/spoon/test/ctClass/CtClassTest.java
#3919
`AssertThat` in Junit 4 is deprecated. Use `AssertThat` in Hamcrest instead.
- Replaced junit 4 test annotation with junit 5 test annotation in `getConstructor`
- Replaced junit 4 test annotation with junit 5 test annotation in `testParentOfTheEnclosingClassOfStaticClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testNoClasspathWithSuperClassOfAClassInAnInterface`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAllTypeReferencesToALocalTypeShouldNotStartWithNumber` …
> test: migrate CtClassTest to JUnit 5

- src/test/java/spoon/test/ctBodyHolder/CtBodyHolderTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testConstructor`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMethod`
- Replaced junit 4 test annotation with junit 5 test annotation in `testTryCatch`
- Replaced junit 4 test annotation with junit 5 test annotation in `testForWithStatement`
- Replaced junit 4 test annotation with junit 5 test annotation in `testForWithBlock`
- Replaced junit 4 test annotation with junit 5 test annotation in `testWhileWithBlock`
- Transformed junit4 assert to junit 5 assertion in `testConstructor`
- Transformed junit4 …
> test: migrate CtBodyHolderTest to JUnit 5

- src/test/java/spoon/test/delete/DeleteTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testDeleteAStatementInAnonymousExecutable`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDeleteAStatementInStaticAnonymousExecutable`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDeleteAStatementInConstructor`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDeleteAStatementInMethod`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDeleteReturn` …
> test: migrate DeleteTest to JUnit 5

- src/test/java/spoon/test/eval/EvalTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testStringConcatenation`
- Replaced junit 4 test annotation with junit 5 test annotation in `testArrayLength`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDoNotSimplify`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDoNotSimplifyCasts`
- Replaced junit 4 test annotation with junit 5 test annotation in `testScanAPartiallyEvaluatedElement`
- Replaced junit 4 test annotation with junit 5 test annotation in `testTryCatchAndStatement`
- Replaced junit 4 test annotation with junit 5 …
> test: migrate EvalTest to JUnit 5

- src/test/java/spoon/test/prettyprinter/QualifiedThisRefTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testQualifiedThisRef`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCloneThisAccess`
- Replaced junit 4 test annotation with junit 5 test annotation in `testPrintCtFieldAccessWorkEvenWhenParentNotInitialized`
- Replaced `@Before` annotation with `@BeforeEach` at method `setup`
- Transformed junit4 assert to junit 5 assertion in `testQualifiedThisRef` …
> test: migrate QualifiedThisRefTest

- src/test/java/spoon/test/ctBlock/TestCtBlock.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testRemoveStatement`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAddStatementInBlock`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAddStatementInCase`
- Transformed junit4 assert to junit 5 assertion in `testRemoveStatement`
- Transformed junit4 assert to junit 5 assertion in `testAddStatementInBlock`
- Transformed junit4 assert to junit 5 assertion in `testAddStatementInCase`
> test: migrate TestCtBlock to JUnit 5

- src/test/java/spoon/test/compilationunit/GetBinaryFilesTest.java
Yesterday, I had a small conversation with @slarse, and we agreed we should refactor `@TempDir` as method parameter when possible. Removing fields from test classes and converting them into method parameters makes test way easier to read.
> style: refactor `@TempDir` to method parameter in GetBinaryFilesTest

- src/test/java/spoon/test/query_function/VariableReferencesTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testCheckModelConsistency`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCatchVariableReferenceFunction`
- Replaced junit 4 test annotation with junit 5 test annotation in `testLocalVariableReferenceFunction`
- Replaced junit 4 test annotation with junit 5 test annotation in `testParameterReferenceFunction`
- Replaced junit 4 test annotation with junit 5 test annotation in `testVariableReferenceFunction`
- Replaced …
> test: migrate VariableReferencesTest to JUnit 5

- src/test/java/spoon/test/prettyprinter/PrinterTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testPrettyPrinter`
- Replaced junit 4 test annotation with junit 5 test annotation in `testChangeAutoImportModeWorks`
- Replaced junit 4 test annotation with junit 5 test annotation in `testFQNModeWriteFQNConstructorInCtVisitor`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAutoimportModeDontImportUselessStatic`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAutoimportModeDontImportUselessStaticNoClassPath` …
> test: migrate PrinterTest JUnit 5

- src/test/java/spoon/test/prettyprinter/LoopSniperJavaPrettyPrinterTest.java
#3919 
The JUnit 4 `@BeforeClass` annotation should be replaced with JUnit 5 `@BeforeAll` annotation.
`AssertThat` in Junit 4 is deprecated. Use `AssertThat` in Hamcrest instead.
- Replaced `@BeforeClass` annotation with `@BeforeAll` at method `setup`
- Replaced junit 4 test annotation with junit 5 test annotation in `forNoBraces`
- Replaced junit 4 test annotation with junit 5 test annotation in `forEachBraces`
- Replaced junit 4 test annotation with junit 5 test annotation in `whileNoBraces`
- Replaced junit 4 test annotation with junit 5 test annotation in `whileWithBraces`
- …
> test: migrate LoopSniperJavaPrettyPrinterTest to JUnit 5

- src/test/java/spoon/test/prettyprinter/LinesTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testPrettyPrinterWithLines`
- Replaced junit 4 test annotation with junit 5 test annotation in `testIdenticalPrettyPrinter`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCompileWhenUsingLinesArgument`
- Replaced `@Before` annotation with `@BeforeEach` at method `setup`
- Transformed junit4 assert to junit 5 assertion in `testPrettyPrinterWithLines` …
> test: migrate LinesTest to JUnit 5

- src/test/java/spoon/test/position/TestSourceFragment.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testSourceFragmentField`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSourcePositionFragment`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSourceFragmentAddChild`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSourceFragmentAddChildBeforeOrAfter`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSourceFragmentWrapChild`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSourceFragmentWrapChildrenAndSiblings`
- …
> test: migrate TestSourceFragment to JUnit 5

- src/test/java/spoon/test/position/PositionTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testPositionClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testPositionClassWithComments`
- Replaced junit 4 test annotation with junit 5 test annotation in `testPositionParameterTypeReference`
- Replaced junit 4 test annotation with junit 5 test annotation in `testPositionInterface`
- Replaced junit 4 test annotation with junit 5 test annotation in `testPositionAnnotation`
- Replaced junit 4 test annotation with junit 5 test annotation in `testPositionField`
- Replaced junit 4 test annotation with …
> test: migrate PositionTest to JUnit 5

- src/test/java/spoon/test/pkg/PackageTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testPackage`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAnnotationOnPackage`
- Replaced junit 4 test annotation with junit 5 test annotation in `testPrintPackageInfoWhenNothingInPackage`
- Replaced junit 4 test annotation with junit 5 test annotation in `testHandlesDuplicatePackageInfo`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAnnotationInPackageInfoWhenTemplatesCompiled`
- Replaced junit 4 test annotation with junit 5 test annotation in `testRenamePackageAndPrettyPrint` …
> test: migrate PackageTest JUnit 5

- src/test/java/spoon/test/parent/TopLevelTypeTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testTopLevelType`
- Replaced `@Before` annotation with `@BeforeEach` at method `setup`
- Transformed junit4 assert to junit 5 assertion in `testTopLevelType`
> test: migrate TopLevelTypeTest to JUnit 5

- src/test/java/spoon/test/intercession/RemoveTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testRemoveAllStatements`
- Transformed junit4 assert to junit 5 assertion in `testRemoveAllStatements`
> test: migrate RemoveTest to JUnit 5

- src/test/java/spoon/test/imports/testclasses/StaticNoOrdered.java
#3919 
- Transformed junit4 assert to junit 5 assertion in `testMachin`
Is this even a testclass?
> test: migrate StaticNoOrdered to JUnit 5

- src/test/java/spoon/test/generics/GenericsTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testBugComparableComparator`
- Replaced junit 4 test annotation with junit 5 test annotation in `testModelBuildingTree`
- Replaced junit 4 test annotation with junit 5 test annotation in `testModelBuildingGenericConstructor`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDiamond2`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDiamond1`
- Replaced junit 4 test annotation with junit 5 test annotation in `testModelBuildingSimilarSignatureMethods`
- Replaced junit 4 test annotation …
> test: migrate GenericsTest to JUnit 5

- src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testModelBuildingFieldAccesses`
- Replaced junit 4 test annotation with junit 5 test annotation in `testBCUBug20140402`
- Replaced junit 4 test annotation with junit 5 test annotation in `testBUG20160112`
- Replaced junit 4 test annotation with junit 5 test annotation in `testTargetedAccessPosition`
- Replaced junit 4 test annotation with junit 5 test annotation in `testFieldAccess`
- Replaced junit 4 test annotation with junit 5 test annotation in `testFieldAccessInLambda` …
> test: migrate FieldAccessTest to JUnit 5

- src/test/java/spoon/test/factory/FieldFactoryTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testCreate`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCreateFromSource`
- Transformed junit4 assert to junit 5 assertion in `testCreate`
- Transformed junit4 assert to junit 5 assertion in `testCreateFromSource`
> test: migrate FieldFactoryTest to JUnit 5

- src/test/java/spoon/test/factory/ExecutableFactoryTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testCreateReference`
- Transformed junit4 assert to junit 5 assertion in `testCreateReference`
> test: migrate ExecutableFactoryTest to JUnit 5

- src/test/java/spoon/FluentLauncherTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testSimpleUsage`
- Replaced junit 4 test annotation with junit 5 test annotation in `testProcessor`
- Replaced junit 4 test annotation with junit 5 test annotation in `testConsistency`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSettings`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMavenLauncher`
- Transformed junit4 assert to junit 5 assertion in `testSimpleUsage`
- Transformed junit4 assert to junit 5 assertion in `testProcessor`
- Transformed junit4 assert to junit 5 …
> test: migrate FluentLauncherTest to JUnit 5

- src/test/java/spoon/test/enums/EnumsTypeTest.java
@SirYwell
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testEnumsType`
- Replaced junit 4 test annotation with junit 5 test annotation in `testEnumsFromInterface`
- Transformed junit4 assert to junit 5 assertion in `testEnumsType`
- Transformed junit4 assert to junit 5 assertion in `testEnumsFromInterface`
> test: migrate EnumsTypeTest to JUnit 5

- src/test/java/spoon/test/exceptions/ExceptionTest.java
#3919 
The expected annotation value should be removed from test methods, and replaced with JUnit 5 `assertThrows`.
- Replaced junit 4 test annotation with junit 5 test annotation in `testExceptionIfNotCompilable`
- Replaced junit 4 test annotation with junit 5 test annotation in `testExceptionNoFile`
- Replaced junit 4 test annotation with junit 5 test annotation in `testExceptionInSnippet`
- Replaced junit 4 test annotation with junit 5 test annotation in `testExceptionInvalidAPI`
- Replaced junit 4 test annotation with junit 5 test annotation in `testExceptionDuplicateClass`
- Replaced junit 4 test …
> test: migrate to ExceptionTest to JUnit 5

- src/test/java/spoon/test/executable/ExecutableRefTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `methodTest`
- Replaced junit 4 test annotation with junit 5 test annotation in `constructorTest`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetActualClassTest`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSameTypeInConstructorCallBetweenItsObjectAndItsExecutable`
- Replaced junit 4 test annotation with junit 5 test annotation in `testOverridingMethod`
- Transformed junit4 assert to junit 5 assertion in `methodTest` …
> test: migrate ExecutableRefTest to JUnit 5

- src/test/java/spoon/test/executable/ExecutableTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testInfoInsideAnonymousExecutable`
- Replaced junit 4 test annotation with junit 5 test annotation in `testBlockInExecutable`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetReference`
- Replaced junit 4 test annotation with junit 5 test annotation in `testShadowValueOf`
- Transformed junit4 assert to junit 5 assertion in `testInfoInsideAnonymousExecutable`
- Transformed junit4 assert to junit 5 assertion in `testBlockInExecutable`
- Transformed junit4 assert to junit 5 assertion in `testGetReference`
- …
> test: migrate to ExecutableTest to JUnit 5

- src/test/java/spoon/test/factory/AnnotationFactoryTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testAnnotate`
- Transformed junit4 assert to junit 5 assertion in `testAnnotate`
> test: migrate AnnotationFactoryTest to JUnit 5

- src/test/java/spoon/test/factory/ClassFactoryTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testDeclaringClass`
- Replaced junit 4 test annotation with junit 5 test annotation in `testTopLevelClass`
- Transformed junit4 assert to junit 5 assertion in `testDeclaringClass`
- Transformed junit4 assert to junit 5 assertion in `testTopLevelClass`
> test: migrate ClassFactoryTest to JUnit 5

- src/test/java/spoon/test/factory/CodeFactoryTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testThisAccess`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCreateVariableAssignement`
- Transformed junit4 assert to junit 5 assertion in `testThisAccess`
- Transformed junit4 assert to junit 5 assertion in `testCreateVariableAssignement`
> test: migrate CodeFactoryTest to JUnit 5

- src/test/java/spoon/test/factory/ConstructorFactoryTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testCreate`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCreateDefault`
- Transformed junit4 assert to junit 5 assertion in `testCreate`
- Transformed junit4 assert to junit 5 assertion in `testCreateDefault`
> test: migrate ConstructorFactoryTest to JUnit 5

- src/test/java/spoon/test/initializers/InitializerTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testModelBuildingStaticInitializer`
- Replaced junit 4 test annotation with junit 5 test annotation in `testModelBuildingInitializer`
- Replaced junit 4 test annotation with junit 5 test annotation in `testModelBuildingInitializerNoclasspath`
- Transformed junit4 assert to junit 5 assertion in `testModelBuildingStaticInitializer`
- Transformed junit4 assert to junit 5 assertion in `testModelBuildingInitializer`
- Transformed junit4 assert to junit 5 assertion in `testModelBuildingInitializerNoclasspath`
> test: migrate InitializerTest to JUnit 5

- src/main/java/spoon/support/compiler/SnippetCompilationHelper.java
Checking if a string is empty should be done by `String#isEmpty` instead of `String.equals("")`
- Empty String check was written as `pkg.equals("")` and refactored to `pkg.isEmpty()`
> refactor: String.equals("") instead  of String.isEmpty()

- src/test/java/spoon/test/intercession/insertBefore/InsertMethodsTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testInsertBefore`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInsertAfter`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInsertBeforeWithoutBrace`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInsertBeforeWithBrace`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInsertAfterWithoutBrace` …
> test: migrate InsertMethodsTest to JUnit 5

- src/test/java/spoon/test/intercession/IntercessionTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testInsertBegin`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInsertEnd`
- Replaced junit 4 test annotation with junit 5 test annotation in `testEqualConstructor`
- Replaced junit 4 test annotation with junit 5 test annotation in `test_setThrownExpression`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInsertIfIntercession` …
> test: migrate IntercessionTest to JUnit 5

- src/test/java/spoon/test/imports/name_scope/NameScopeTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testNameScopeScanner`
- Transformed junit4 assert to junit 5 assertion in `testNameScopeScanner`
- Transformed junit4 assert to junit 5 assertion in `checkThatScopeContains`
> test: migrate NameScopeTest to JUnit 5

- src/test/java/spoon/test/factory/TypeFactoryTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testCreateTypeRef`
- Replaced junit 4 test annotation with junit 5 test annotation in `reflectionAPI`
- Replaced junit 4 test annotation with junit 5 test annotation in `reflectionAPIWithTypeParameter`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetClassInAnInterface`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetClassWithDollarAndNestedClass`
- Transformed junit4 assert to junit 5 assertion in `testCreateTypeRef` …
> test: migrate TypeFactoryTest to JUnit 5

- src/test/java/spoon/test/filters/CUFilterTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testWithoutFilters`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSingleExcludeWithFilter`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSingleExcludeWithoutFilter`
- Transformed junit4 assert to junit 5 assertion in `testWithoutFilters`
- Transformed junit4 assert to junit 5 assertion in `testSingleExcludeWithFilter`
- Transformed junit4 assert to junit 5 assertion in `testSingleExcludeWithoutFilter`
> test: migrate CUFilterTest to JUnit 5

- src/test/java/spoon/test/factory/FactoryTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testClone`
- Replaced junit 4 test annotation with junit 5 test annotation in `testFactoryOverriding`
- Replaced junit 4 test annotation with junit 5 test annotation in `testClassAccessCreatedFromFactories`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCtModel`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetPackageFromNamedModule`
- Replaced junit 4 test annotation with junit 5 test annotation in `specificationCoreFactoryCreate`
- Replaced junit 4 test annotation with junit 5 …
> test: migrate FactoryTest to JUnit 5

- src/main/java/spoon/reflect/factory/FactoryImpl.java
Lambda is used instead of executable reference
- https://rules.sonarsource.com/java/RSPEC-1612
`ThreadLocal` with initialValue override shall be replaced by `ThreadLocal.withInitialValue`
- https://rules.sonarsource.com/java/RSPEC-4065
- `ThreadLocal` with initialValue `new spoon.reflect.factory.FactoryImpl.Dedup()` was replaced by `ThreadLocal.withInitialValue(java.lang.ThreadLocal.withInitial(() -> new spoon.reflect.factory.FactoryImpl.Dedup()))`
- `ThreadLocal` with initialValue `new spoon.reflect.factory.FactoryImpl.Dedup()` was replaced by `ThreadLocal.withInitialValue(java.lang.ThreadLocal.withInitial(() -> new spoon.reflect.factory.FactoryImpl.Dedup()))`
- Replaced lambda `() -> new spoon.reflect.factory.FactoryImpl.Dedup()` with executable …
> refactor(FactoryImpl): use ThreadLocal.initialValue

- src/main/java/spoon/support/reflect/declaration/CtClassImpl.java
Checking if a string is empty should be done by `String#isEmpty` instead of `String.equals("")`
- Empty String check was written as `getSimpleName().equals("")` and refactored to `getSimpleName().isEmpty()`
> refactor: empty String check

- src/test/java/spoon/test/methodreference/MethodReferenceTest.java
#3919 
`AssertThat` in Junit 4 is deprecated. Use `AssertThat` in Hamcrest instead.
- Replaced junit 4 test annotation with junit 5 test annotation in `testReferenceToAStaticMethod`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReferenceToAnInstanceMethodOfAParticularObject`
- Replaced junit 4 test annotation with junit 5 test annotation in `testReferenceToAnInstanceMethodOfMultiParticularObject` …
> test: migrate MethodReferenceTest to JUnit 5

- src/test/java/spoon/test/model/BlockTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testIterationStatements`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAddEmptyBlock`
- Transformed junit4 assert to junit 5 assertion in `testIterationStatements`
- Transformed junit4 assert to junit 5 assertion in `testAddEmptyBlock`
> test: migrate BlockTest to JUnit 5

- src/test/java/spoon/test/modifiers/ModifiersTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testMethodWithVarargsDoesNotBecomeTransient`
- Replaced junit 4 test annotation with junit 5 test annotation in `testCtModifiableAddRemoveReturnCtModifiable`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSetVisibility`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetModifiersHelpers`
- Replaced junit 4 test annotation with junit 5 test annotation in `testClearModifiersByEmptySet`
- Replaced junit 4 test annotation with junit 5 test annotation in `testClearModifiersByNull`
- …
> test: migrate ModifiersTest to JUnit 5

- src/test/java/spoon/test/module/TestModule.java
#3919 
The expected annotation value should be removed from test methods, and replaced with JUnit 5 `assertThrows`.
The JUnit 4 `@AfterClass` annotation should be replaced with JUnit 5 `@AfterAll` annotation.
The JUnit 4 `@BeforeClass` annotation should be replaced with JUnit 5 `@BeforeAll` annotation.
- Replaced `@BeforeClass` annotation with `@BeforeAll` at method `setUp`
- Replaced `@After` annotation with `@AfterEach` at method `tearDown` …
> test: migrate TestModule to JUnit 5

- src/test/java/spoon/test/processing/processors/ParallelProcessorTest.java
> test: migrate ParallelProcessorTest to JUnit 5

- src/test/java/spoon/test/replace/ReplaceParametrizedTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testContract`
- Transformed junit4 assert to junit 5 assertion in `testContract`
The parameterized was obviously refactored by hand.
> test: migrate ReplaceParametrizedTest

- src/test/java/spoon/test/literal/LiteralTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testCharLiteralInNoClasspath`
- Replaced junit 4 test annotation with junit 5 test annotation in `testLiteralInForEachWithNoClasspath`
- Replaced junit 4 test annotation with junit 5 test annotation in `testBuildLiternal`
- Replaced junit 4 test annotation with junit 5 test annotation in `testFactoryLiternal`
- Replaced junit 4 test annotation with junit 5 test annotation in `testEscapedString`
- Replaced junit 4 test annotation with junit 5 test annotation in `testLiteralBase` …
> test: migrate LiteralTest to JUnit 5

- src/test/java/spoon/test/literal/UnicodeBugTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testUnicodeBug`
- Transformed junit4 assert to junit 5 assertion in `testUnicodeBug`
> test: migrate UnicodeBugTest to JUnit 5

- src/test/java/spoon/test/loop/LoopTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testAnnotationInForLoop`
- Replaced junit 4 test annotation with junit 5 test annotation in `testForeachShouldHaveAlwaysABlockInItsBody`
- Replaced junit 4 test annotation with junit 5 test annotation in `testEmptyForLoopExpression`
- Transformed junit4 assert to junit 5 assertion in `testAnnotationInForLoop`
- Transformed junit4 assert to junit 5 assertion in `testForeachShouldHaveAlwaysABlockInItsBody`
- Transformed junit4 assert to junit 5 assertion in `testEmptyForLoopExpression`
> test: migrate LoopTest to JUnit 5

- src/test/java/spoon/test/method/MethodTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testClone`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSearchMethodWithGeneric`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMethodSignature`
- Replaced junit 4 test annotation with junit 5 test annotation in `testAddSameMethodsTwoTimes`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetAllMethods`
- Replaced junit 4 test annotation with junit 5 test annotation in `testGetAllMethodsAdaptingType` …
> test: migrate MethodTest to JUnit 5

- src/test/java/spoon/test/method_overriding/MethodOverriddingTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testShadowInterfaceMethodsCanOverrideObjectMethods`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInterfaceMethodsCanOverrideObjectMethods`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMethodOverride`
- Replaced junit 4 test annotation with junit 5 test annotation in `testMethodOverrideByReference`
- Transformed junit4 assert to junit 5 assertion in `testShadowInterfaceMethodsCanOverrideObjectMethods` …
> test: migrate MethodOverriddingTest to JUnit 5

- src/test/java/spoon/test/limits/utils/InternalTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testInternalClasses`
- Replaced junit 4 test annotation with junit 5 test annotation in `testStaticFinalFieldInAnonymousClass`
- Transformed junit4 assert to junit 5 assertion in `testInternalClasses`
- Transformed junit4 assert to junit 5 assertion in `testStaticFinalFieldInAnonymousClass`
> test: migrate InternalTest to JUnit 5

- src/test/java/spoon/test/lambda/LambdaTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testLambdaExpressionWithExpressionBodyAndWithoutParameter`
- Replaced junit 4 test annotation with junit 5 test annotation in `testTypeAccessInLambdaNoClassPath`
- Replaced junit 4 test annotation with junit 5 test annotation in `testFieldAccessInLambdaNoClassPath`
- Replaced junit 4 test annotation with junit 5 test annotation in `testFieldAccessInLambdaNoClassPathExternal1Example` …
> test: migrate LambdaTest to JUnit 5

- src/test/java/spoon/test/jar/JarTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testJarResources`
- Replaced junit 4 test annotation with junit 5 test annotation in `testJar`
- Replaced junit 4 test annotation with junit 5 test annotation in `testFile`
- Replaced junit 4 test annotation with junit 5 test annotation in `testResource`
- Transformed junit4 assert to junit 5 assertion in `testJarResources`
- Transformed junit4 assert to junit 5 assertion in `testJar`
- Transformed junit4 assert to junit 5 assertion in `testFile`
- Transformed junit4 assert to junit 5 assertion in `testResource`
> test: migrate JarTest to JUnit 5

- src/test/java/spoon/test/issue3321/SniperPrettyPrinterJavaxTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testThatCanGenerateSniperPrettyPrintedSourceForJavaxAnnotatedClasses`
I removed the useless comment about authorship and 2 newlines
> test: migrate SniperPrettyPrinterJavaxTest to JUnit 5

- src/test/java/spoon/test/issue3321/AnnotationPositionTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testUsageOfTypeAnnotationOnParameterInMethod`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSneakyAnnotationsOnParameters`
- Replaced `@Ignore` annotation with `@Disabled` at method `testUsageOfTypeAnnotationOnParameterInMethod`
- Replaced `@Ignore` annotation with `@Disabled` at method `testSneakyAnnotationsOnParameters` …
> test: migrate AnnotationPositionTest to JUnit 5

- src/test/java/spoon/test/invocations/InvocationTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testTypeOfStaticInvocation`
- Replaced junit 4 test annotation with junit 5 test annotation in `testTargetNullForStaticMethod`
- Replaced junit 4 test annotation with junit 5 test annotation in `testIssue1753`
- Replaced junit 4 test annotation with junit 5 test annotation in `test_addArgumentAt_addsArgumentAtSpecifiedPosition`
- Transformed junit4 assert to junit 5 assertion in `testTypeOfStaticInvocation`
- Transformed junit4 assert to junit 5 assertion in `testTargetNullForStaticMethod`
- Transformed junit4 assert to junit 5 …
> test: migrate InvocationTest to JUnit 5

- src/test/java/spoon/test/parent/ContractOnSettersParametrizedTest.java
#3919
while refactoring, I removed an unused field and moved the fields to the top
> test: migrate ContractOnSettersParametrizedTest to JUnit 5

- src/test/java/spoon/test/main/MainTest.java
#3919 
This is by far the hardest test to migrate. Testing against `System.exit` is more or less dying. For this, we need a Security Manager or a lib providing it for us, like https://todd.ginsberg.com/post/testing-system-exit/. But Security Manager is getting removed real fast in a near version of java https://openjdk.java.net/jeps/411 and the lib can't test for the message. We could only test if the exit code `-1` is set. Therefore, I would simply remove this testcase otherwise we have to remove it in JDK 19 or something because spoon can't compile any more(calling methods from a removed API is hard :) ).
> test: migrate Maintest to JUnit 5

- src/test/java/spoon/test/lambda/AnonymousInLambdaTest.java
#3919
- Replaced junit 4 test annotation with junit 5 test annotation in `testAnonymousInLambda`
- Transformed junit4 assert to junit 5 assertion in `testAnonymousInLambda`
> test: migrate AnonymousInLambdaTest to JUnit 5

- src/test/java/spoon/test/labels/TestLabels.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testLabelsAreDetected`
- Transformed junit4 assert to junit 5 assertion in `testLabelsAreDetected`
> test: migrate TestLabels to JUnit 5

- src/test/java/spoon/test/jdtimportbuilder/ImportBuilderTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testWithNoImport`
- Replaced junit 4 test annotation with junit 5 test annotation in `testWithSimpleImport`
- Replaced junit 4 test annotation with junit 5 test annotation in `testWithSimpleImportNoAutoimport`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInternalImportWhenNoClasspath`
- Replaced junit 4 test annotation with junit 5 test annotation in `testSimpleStaticImport`
- Replaced junit 4 test annotation with junit 5 test annotation in `testWithStaticStarredImportFromInterface`
- Replaced junit 4 …
> test: migrate ImportBuilderTest to JUnit 5

- src/test/java/spoon/test/interfaces/TestInterfaceWithoutSetup.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testModifierFromInterfaceFieldAndMethod`
- Replaced junit 4 test annotation with junit 5 test annotation in `testInterfacePrettyPrinting`
- Transformed junit4 assert to junit 5 assertion in `testModifierFromInterfaceFieldAndMethod`
- Transformed junit4 assert to junit 5 assertion in `testInterfacePrettyPrinting`
> test: migrate TestInterfaceWithoutSetup to JUnit 5

- src/test/java/spoon/test/interfaces/InterfaceTest.java
#3919 
- Replaced junit 4 test annotation with junit 5 test annotation in `testDefaultMethodInInterface`
- Replaced junit 4 test annotation with junit 5 test annotation in `testDefaultMethodInConsumer`
- Replaced junit 4 test annotation with junit 5 test annotation in `testExtendsDefaultMethodInSubInterface`
- Replaced junit 4 test annotation with junit 5 test annotation in `testRedefinesDefaultMethodInSubInterface` …
> test: migrate InterfaceTest to JUnit 5 

- src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
`array.toString()` is not the best way to print an array. Use `Arrays.toString(array)` instead.
- https://rules.sonarsource.com/java/RSPEC-2116
- Replaced `str.toString()` with `Arrays.toString(str)`.
> fix: fix qodana warning with proper call to Array.toString()

- .github/workflows/tests.yml
- src/main/java/spoon/support/sniper/internal/TokenSourceFragment.java
Qodana got a new flag `changes` which as you (don't) expect `Inspect uncommitted changes and report new problems.`. Uncommitted means here uncommitted and not the expected behaviour changed files in the PR. Therefore, we reset the git branch with `git reset --soft master`. This reduces the qodana runtime in less than half.
Qodana has an annotator included. We don't need @I-Al-Istannen JQ magic any more and use the included from now. See https://github.com/INRIA/spoon/pull/4584/files#annotation_2688909324.
The only risk is that for some reason `git reset --soft master` fails.
Edit: The bad smell and failing CI is currently only there for showcasing and gets removed after approval.
> chore(qodana): use new flag "changes"

- .github/workflows/tests.yml
- .gitignore
- pom.xml
- spoon-pom/pom.xml
- src/test/java/spoon/test/TestExecutionLogger.java
Goal: we want to have the list of all executed test cases in the CI log.
Bonus: this gives us execution time in the logs for performance analysis
> chore: improve CI logs with test case names

- src/main/java/spoon/metamodel/Metamodel.java
- src/main/java/spoon/reflect/code/CtLocalVariable.java
- src/main/java/spoon/reflect/code/CtResource.java
- src/main/java/spoon/reflect/code/CtTryWithResource.java
- src/main/java/spoon/reflect/code/CtVariableRead.java
- src/main/java/spoon/reflect/meta/impl/ModelRoleHandlers.java
- src/main/java/spoon/reflect/visitor/AccessibleVariablesFinder.java
- src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java
- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/main/java/spoon/support/reflect/code/CtTryWithResourceImpl.java
- src/test/java/spoon/generating/CloneVisitorGenerator.java
- src/test/java/spoon/test/trycatch/TryCatchTest.java
> feature: add support for first class resource in try-with-resource

- spoon-smpl/src/test/java/spoon/smpl/C4JGetColorTest.java
- spoon-smpl/src/test/java/spoon/smpl/C4JGetHeightTest.java
- spoon-smpl/src/test/java/spoon/smpl/C4JOnConsoleMessageTest.java
- spoon-smpl/src/test/java/spoon/smpl/C4JSetTextSizeTest.java
- spoon-smpl/src/test/java/spoon/smpl/C4JShouldVibrateTest.java
- spoon-smpl/src/test/java/spoon/smpl/C4JStickyBroadcastTest.java
- spoon-smpl/src/test/java/spoon/smpl/CFGModelTest.java
- spoon-smpl/src/test/java/spoon/smpl/CombinationsGeneratorTest.java
- spoon-smpl/src/test/java/spoon/smpl/EndToEndTests.java
- spoon-smpl/src/test/java/spoon/smpl/EnvironmentTest.java
- spoon-smpl/src/test/java/spoon/smpl/FormulaCompilerTest.java
- spoon-smpl/src/test/java/spoon/smpl/FormulaOptimizerTest.java
- spoon-smpl/src/test/java/spoon/smpl/FormulaTest.java
- spoon-smpl/src/test/java/spoon/smpl/IntegrationBugsTest.java
- spoon-smpl/src/test/java/spoon/smpl/MetavarsTest.java
- spoon-smpl/src/test/java/spoon/smpl/MethodHeaderMatchingTest.java
- spoon-smpl/src/test/java/spoon/smpl/ModelCheckerTest.java
- spoon-smpl/src/test/java/spoon/smpl/PatternMatchingTest.java
- spoon-smpl/src/test/java/spoon/smpl/SmPLGrepTest.java
- spoon-smpl/src/test/java/spoon/smpl/SmPLLexerTest.java
- spoon-smpl/src/test/java/spoon/smpl/SmPLMethodCFGTest.java
- spoon-smpl/src/test/java/spoon/smpl/SmPLParserTest.java
- spoon-smpl/src/test/java/spoon/smpl/SmPLProblemDetectorTest.java
- spoon-smpl/src/test/java/spoon/smpl/SubstitutorTest.java
- spoon-smpl/src/test/java/spoon/smpl/TestUtils.java
- spoon-smpl/src/test/java/spoon/smpl/TransformerTest.java
- spoon-smpl/src/test/java/spoon/smpl/TriConsumerTest.java
- spoon-smpl/src/test/java/spoon/smpl/VariableUseScannerTest.java
- spoon-smpl/src/test/java/spoon/smpl/WitnessesTest.java
- spoon-smpl/src/test/java/spoon/smpl/ZippedCodeBaseTestContext.java
Let me try to reduce the diff first, before anyone reviews. ~~And fix my git usage....~~
Edit 1: Git usage fixed.
> test(smpl): migrate SMPL tests to JUnit5

- CONTRIBUTING.md
- SECURITY.md
Fix #4603 
Here's a proposal for a security policy.
I also added emails and the PGP key fingerprints hat I know of in the CONTRIBUTING.md file. I refer to them as GPG keys, though,  because I think that's more common nowadays, even though it's technically incorrect. I mean, even I say GPG key, and I'm pretty uptight about being correct ...
@monperrus @nharrand @MartinWitt please have a look.
> doc: Add security policy

- src/main/java/spoon/ContractVerifier.java
- src/main/java/spoon/experimental/SpoonifierVisitor.java
- src/main/java/spoon/metamodel/MetamodelProperty.java
- src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
This removes not needed toString calls. I'm still unsure about when a `toString()` call is not needed, but these changes seem correct. The detection was done by Qodana and this fixes 4 issues. Calling `toString` in String concatenation adds zero value to the code and should be removed.
> review: refactor: remove useless toString calls

- spoon-pom/pom.xml
[Beta deployment of spoon failed again](https://github.com/SpoonLabs/spoon-deploy/runs/5267921572?check_suite_focus=true). I am confident it is because of some issue in the plugin. One of the maintainers of nexus has also recommended avoiding `1.6.9`, `1.6.10`, and `1.6.11` versions of the plugin. See https://issues.sonatype.org/browse/NEXUS-31214?focusedCommentId=1140935&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1140935.
> At this time, it's best to avoid 1.6.9/1.6.10/1.6.11 releases of the plugin. We are triaging this internally and will see it through to completion. I can't provide an ETA on completion date until we dive deeper.
> chore: downgrade nexus-staging-maven-plugin because of deployment regression

- pom.xml
- spoon-decompiler/pom.xml
This can be achieved by just updating the assembly plugin.
This is preparation for #4151 and #4614.
> chore: Ensure assembly jar with dependencies is reproducible

- .github/workflows/tests.yml
- chore/check-reproducible-builds.sh
This PR supersedes #4614 once it works. While the linked PR tried to check against maven central using the artifact compare plugin, this PR just builds twice and throws diffoscope at the results.
We should wait for #4652 before merging to not have a red CI in master :)
> chore: Check reproducible state in CI

- src/main/java/spoon/compiler/SpoonFile.java
- src/main/java/spoon/compiler/builder/SourceOptions.java
- src/main/java/spoon/support/compiler/ZipFolder.java
- src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
I found places where spoon manually read from an input stream just to write to an output stream. Since Java 9, there is a [InputStream#transferTo](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/InputStream.html#transferTo(java.io.OutputStream)) method that provides the same functionality and is easier to read.
To make it more consistent, I also replaced usages of `IOUtils#copy`, as it does the same than the new method.
> refactor: make use of InputStream#transferTo where appropriate

- src/test/java/spoon/test/comment/CommentTest.java
- src/test/java/spoon/test/imports/ImportTest.java
- src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
I replaced remaining usages of IOUtils with modern Java APIs.
From what I've seen, `commons-io` isn't in use anymore, so we can probably remove it in a following PR.
> review: refactor: replace usages of IOUtils with Java NIO API

- src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
Fix #4668
This is a quick-fix to avoid the cross-thread race condition when invalidating the cache and then doing a lookup in it. This is a problem as the current lock is per-instance but the cache is static, so in theory a thread A could check the cache integrity and state that it's fine, then there's a context switch to thread B which does the same thing and invalidates the cache and inserts something into the cache, and then we're back to thread B which does a lookup on a "bad cache" (according to thread A's view of the world).
By using thread-local storage, this situation cannot occur.
> review: fix: Use thread-local caching for actual class lookup

- src/main/java/spoon/support/reflect/declaration/CtCompilationUnitImpl.java
This was discovered while fixing #4672. I don't believe the `available` method makes any guarantees about its length, this looks like it could silently truncate the read source code.
> review: refactor: Use NIO to read compilation unit source code

- src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
The method contained some duplicated code and didn't make use of modern file system APIs. 
There also was a list which had no practical use as the elements were only added (with a contains check to prevent duplicates). I'm not sure if there were any intentions behind that, but removing it does not change behavior.
> review: refactor: clean up `generateProcessedSourceFilesUsingCUs` method

- pom.xml
Now that 10.1.0 is live, we start building 10.2.0.
> chore: kickstart next snapshot 10.2.0

- src/main/java/spoon/reflect/path/impl/AbstractPathElement.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
Using StringJoiner allows to simplify a few places in code and make them more clear.
> refactor: use StringJoiner where appropriate

- src/main/java/spoon/reflect/meta/impl/RoleHandlerHelper.java
This array was used like an enum map, so I replaced it.
> refactor: use EnumMap instead of dealing with ordinals for array indexes

- src/main/java/spoon/reflect/visitor/filter/PotentialVariableDeclarationFunction.java
- src/test/java/spoon/test/model/SwitchCaseTest.java
The naive approach for searching variable declarations only considered siblings and parents, which is not enough for switch statements. There, we need to look through all preceding cases as well.
Fixes #4696
> review: fix: search in previous cases for variable declarations

- spoon-smpl/pom.xml
This fix stops depclean complaining about unused dependencies when building the spoon-smpl submodule. Running tests still works. I guess junit gets pulled in from the parent `../spoon-pom/pom.xml`?
I also removed a commented-out dependency which I should not have committed in the first place.
> fix: remove unnecessary junit dep from spoon-smpl pom.xml

- spoon-smpl/src/main/java/spoon/smpl/SmPLMethodCFG.java
- spoon-smpl/src/test/java/spoon/smpl/SmPLMethodCFGTest.java
This adds `CtFor` and `CtForEach` to the set of elements swapped out by spoon-smpl's `UnsupportedElementSwapper` along with a warning log message for each replaced element.
Should be a slight improvement on the current user experience (see #4716).
> fix: add for-loop elements to UnsupportedElementSwapper and add warning messages (issue #4716)

- src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
- src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
- src/test/java/spoon/test/role/TestCtRole.java
After two *way* too long debugging sessions, I ended up with this **one** line fix for #4698. The ReflectionTreeBuilder unconditionally scanned the enclosing class, bypassing the shadow class cache. This resulted in two different `CtClass` instances for `ArrayList`, causing the role reference equality check to fail.
The problem here is, that scanning a class only results in *that* class to be added to the shadow cache - but no nested classes. The `ImportConflictDetector`, added by default as a preprocessor for the pretty printer, then caused a nested class to be scanned (which was never added to the shadow cache), which promptly re-scanned the enclosing `ArrayList`. This new instance was then added to the package, overwriting the original class present in the shadow cache. Role lookups …
> fix: Respect shadowCache in JavaReflectionTreeBuilder for enclosing classes

- src/main/java/spoon/support/DefaultCoreFactory.java
- src/main/java/spoon/support/reflect/declaration/CtRecordImpl.java
- src/test/java/spoon/reflect/ast/CloneTest.java
- src/test/java/spoon/test/enums/EnumsTest.java
- src/test/java/spoon/test/interfaces/InterfaceTest.java
- src/test/java/spoon/test/interfaces/TestInterfaceWithoutSetup.java
- src/test/java/spoon/test/trycatch/TryCatchTest.java
I replaced remaining usages of the CtExtendedModifier constructor that takes a boolean. This makes the code easier to read.
> review: refactor: replace usages of CtExtendedModifier constructor

- src/main/java/spoon/reflect/factory/ModuleFactory.java
- src/main/java/spoon/support/DefaultCoreFactory.java
- src/test/java/spoon/test/module/TestModule.java
This issue was discovered while trying to reproduce #4746. Printing a module caused it to be cloned, leading to a duplicate insertion into the global module list. This in turn triggered the "overlapping modules found" sanity check (thankfully!).
> review: fix: Stop adding duplicated modules when cloning them

- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/test/java/spoon/test/pattern/TypePatternTest.java
- src/test/resources/patternmatching/InstanceofPatternMatch.java
Fixes #4723.
As the CtTypePattern instance basically only wraps the CtLocalVariable, we should also use its SourcePosition.
> review: fix: set source position of type pattern

- src/test/java/spoon/test/prettyprinter/SniperAssertTest.java
- src/test/java/spoon/test/prettyprinter/SniperDefaultMethodTest.java
- src/test/java/spoon/test/prettyprinter/SniperDoubleBoundTest.java
- src/test/java/spoon/test/prettyprinter/SniperDoubleForInitializerTest.java
- src/test/java/spoon/test/prettyprinter/SniperInnerTypeTest.java
Following the discussion on https://github.com/INRIA/spoon/pull/4780 the new unit test I've added was copied from other existing JUnit 4 tests.
This PR upgrades these similar tests to JUnit 5
> test: upgrade sniper unit tests to JUnit 5

- src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java
- src/test/java/spoon/reflect/factory/PackageFactoryTest.java
Fix #4764 
The problem was a check that I can't quite make sense of, see comment in code.
> fix: Enable creation of packages with repeated simple names in qualified name

- README.md
We still get a lot of issues using JDK 8 and old versions of Spoon. I think we should clarify that we don't intend to support JDK 8 or older versions of Spoon that uses it.
The new bug report template I've added in #4793 also takes some steps in this direction.
> doc: Clarify stance on supported versions

- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/test/java/spoon/reflect/ast/AstCheckerTest.java
- src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java
- src/test/java/spoon/test/comment/CommentTest.java
Fixes #4807
I have tried to reproduce #4807 with a related test case.
```
Expected: java.lang.System.out.println("1" + "2" + "3" + "4")
Actual: java.lang.System.out.println("1" + ("2" + "3" + "4"))
```
I have noticed that the test pass when I change each operand in the above expression to an integer, thanks to #3823.
> fix: minimise bracket printing in case of string operands of binary operator

- spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowBuilder.java
- spoon-control-flow/src/test/java/fr/inria/controlflow/ControlFlowGraphTests.java
fixes #4803.
Tbh it is just a band-aid fix because I have zero clue about the `ControlFlowBuilder`.
> review: fix: handle null bodies of while statements.

- doc/launcher.md
Closes #4804.
As mentioned in the issue, it's not clear from the current examples that the user needs to configure the compliance level.
I think adding it to that copy-paste example is a good way to make users aware of it.
> review: doc: add information about the compliance level to the launcher doc

- src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
- src/test/java/spoon/reflect/ast/AstCheckerTest.java
- src/test/java/spoon/test/fieldaccesses/FieldAccessTest.java
- src/test/resources/comment/CommentsOnCaseExpression.java
I was trying to reproduce https://github.com/INRIA/spoon/issues/4727 and I came across another possible bug in the Spoon model builder. It seems that when comments  are added to `CtCaseExpression`s, they are not parsed and stored in the model. Is this a bug or does Spoon has some configuration that I need to enable to include comments in the model? Note that I already set one in my knowledge - `launcher.getEnvironment().setCommentEnabled(true);`.
> fix: attach comment to `CtLiteral` nodes

- src/main/java/spoon/support/StandardEnvironment.java
A local variable is declared and in the next line returned. This can be replaced by an instant return.
- Inlined return statement return new spoon.reflect.visitor.DefaultJavaPrettyPrinter(this)
> refactor: fix bad smell "Unnecessary Local Variable"

- src/main/java/spoon/reflect/visitor/LiteralHelper.java
A local variable is declared and in the next line returned. This can be replaced by an instant return.
- Inlined return statement return `("\"\"\"\n" + literal.getValue().replace("\\", "\\\\")) + "\"\"\""`
> refactor: fix bad smell "Unnecessary Local Variable" (#4847)

- src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
Checking if a string is empty should be done by `String#isEmpty` instead of `String.length==0`
- Replaced string.length empty check with string.isEmpty
> review: refactor: SizeReplaceableByIsEmpty

- src/main/java/spoon/support/util/internal/ElementNameMap.java
This was discovered after rebasing for #4848.
#4832 caused a severe regression due to the way `get` in `AbstractMap` works. Before, `AbstractMap#entrySet()` just delegated to the underlying map, but with the patch, it first has to build the map. For `get`, this isn't needed at all, therefore we should override the method.
This brings down this test https://github.com/INRIA/spoon/blob/0fcb28878671d90daede513326bff96274068b32/src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java#L157
from ~1m 17s to ~52s. There might be more methods that should be overridden now, I'll investigate that. One that takes a lot of time is `values()` which is called heavily at the moment, but we can avoid many calls with #4848, so both PRs combined seem to achieve even better performance than …
> review: perf: override AbstractMap#get in ElementNameMap

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/test/java/spoon/test/generics/GenericsTest.java
If no explicit type arguments are given, the type arguments JDT inferred are now used for getActualTypeArguments.
This addresses #4834, but I am not sure we actually want to use the inferred information. It seems quite useful, but it may also be incomplete if JDT is not able to infer things correctly.
> feat: Use inferred generic type in invocations

- README.md
spoon-user-manual.pdf is not regularly updated, it was more an experiment.
this (+deleting the file) will avoid confusion due to outdated doc.
> doc: remove spoon-user-manual.pdf link

- src/main/java/spoon/support/comparator/DeepRepresentationComparator.java
Inequality conditions that, according to data flow analysis, can be satisfied only for a single operand value. Such conditions could be replaced with equality conditions to make the code clearer.
- Replaced inequality with simpler equality
> refactor: fix bad smell "Non-Strict-Comparison-Can-Be-Equality"

- src/main/java/spoon/MavenLauncher.java
- src/main/java/spoon/support/compiler/SpoonPom.java
- src/test/java/spoon/MavenLauncherTest.java
- src/test/resources/maven-launcher/with-environment-variables/pom.xml
Some maven builds might need environment variables to complete successfully and we should offer an API for this.
As the methods I overloaded are part of the public API, I enclosed the environment variables in an opaque settings object. This should allow us to add more options later without another overload layer per feature. I am not sure if this is a good idea, but it might ease the burden a bit.
Closes: #4817
> feat: Allow passing environment variables in maven launcher invocations

- src/main/java/spoon/IncrementalLauncher.java
- src/main/java/spoon/reflect/declaration/CtPackage.java
- src/main/java/spoon/reflect/factory/PackageFactory.java
- src/main/java/spoon/support/reflect/declaration/CtPackageImpl.java
- src/main/java/spoon/support/util/internal/ElementNameMap.java
I saw that when running this test https://github.com/INRIA/spoon/blob/0fcb28878671d90daede513326bff96274068b32/src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java#L157
most of the time is spent on `CtMethodImpl#getTopDefintions()`. I did some profiling and encountered this:
That's an immense amount of time of copying elements just to check if the set is empty. As a solution, I propose to introduce a `CtPackage#hasTypes()` method. This way, we can ask the ElementNameMap directly instead of doing costly copying.
In my first measurements, this reduced the runtime of the mentioned test from ~20s to ~16s.
(I rebased after that, and the runtime of the test on the current master takes >1m on my machine. With this patch, it is still faster, but I have a second PR ready to get …
> review: perf: avoid collection copy in CtPackageImpl

- spoon-pom/pom.xml
- src/test/java/spoon/support/compiler/jdt/JDTBatchCompilerTest.java
- src/test/java/spoon/test/SpoonTestHelpers.java
- src/test/java/spoon/test/field/FieldTest.java
- src/test/java/spoon/test/imports/ImportTest.java
- src/test/java/spoon/test/model/IncrementalLauncherTest.java
- src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
- src/test/java/spoon/test/prettyprinter/PrinterTest.java
- src/test/java/spoon/test/prettyprinter/testclasses/ImportStatic.java
- src/test/java/spoon/test/query_function/VariableReferencesTest.java
- src/test/java/spoon/test/query_function/testclasses/VariableReferencesFromStaticMethod.java
- src/test/java/spoon/test/refactoring/testclasses/CtRenameLocalVariableRefactoringTestSubject.java
- src/test/java/spoon/test/statementComment/StatementCommentTest.java
- src/test/java/spoon/test/variable/VariableTest.java
- src/test/resources/imports/StaticNoOrdered.java
- src/test/resources/spoon/test/imports/testclasses2/apachetestsuite/LangTestSuite.java
- src/test/resources/spoon/test/imports/testclasses2/apachetestsuite/enum2/EnumTestSuite.java
- src/test/resources/spoon/test/imports/testclasses2/apachetestsuite/enums/EnumTestSuite.java
- src/test/resources/spoon/test/imports/testclasses2/apachetestsuite/staticcollision/AllLangTestSuite.java
- src/test/resources/spoon/test/imports/testclasses2/apachetestsuite/staticjava3/AllLangTestJava3.java
- src/test/resources/spoon/test/imports/testclasses2/apachetestsuite/staticmethod/AllLangTestSuiteStaticMethod.java
You can go ahead and absorb the patches into #4792 and close this, if you want @slarse.
I believe they do not change semantics, but that is honestly a bit hard to tell. I built spoon 5.7.0 in a docker container (*roughly*)
```Dockerfile
FROM openjdk:8
RUN apt update && apt install maven vim -y
RUN git clone https://github.com/surli/spoon.git
WORKDIR /spoon
RUN git checkout 9b38f48bf72c4a911029985c012f9b067c40a649
RUN sed -i 's/<version>1.4/2.0/' pom.xml # replace commons-io with 2.0 which is java 7 compatible
RUN mvn test
```
to understand the intent of the tests and I *believe* it is okay, but I am not fully certain.
> review: test: Remove last traces of JUnit4 [cont]

- pom.xml
- spoon-control-flow/pom.xml
- spoon-decompiler/pom.xml
- spoon-smpl/pom.xml
Reverts INRIA/spoon#4859
Apparently this did not play well with the javadoc style script.
> Revert "chore(deps): update dependency org.apache.maven.plugins:maven-checkstyle-plugin to v3.2.0"

- chore/check-javadoc-regressions.py
- pom.xml
- spoon-control-flow/pom.xml
- spoon-decompiler/pom.xml
- spoon-smpl/pom.xml
It seems like I added a nicer error message (as you can see in the screenshot) but did not print it for comparison failures. Judging by slarse opening an issue, this indeed was the case and I still failed :P
```py
```
Following that suggestion, the error message was
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:check (default-cli) on project spoon-core: Failed during checkstyle configuration: cannot initialize module TreeWalker - cannot initialize module JavadocMethod - Property 'scope' does not exist, please check the documentation -> [Help 1]
```
---
Note that the CI status will not be significant as it runs with the version on master. Also note that running `COMPARE_WITH_MASTER` will *fail* on this PR, as the master state was reverted and …
> review: chore: Fix javadoc regression script with newer checkstyle version

- src/main/java/spoon/support/reflect/declaration/CtMethodImpl.java
- src/test/java/spoon/test/filters/FilterTest.java
- src/test/java/spoon/test/method/MethodTest.java
- src/test/java/spoon/test/method/testclasses/Hierarchy.java
With multiple independent interfaces declaring the same method, `getTopDefinitions()` returned wrong results.
The filtering was broken due to `TypeAdaptor#isOverriding(m, m) == true` *and* the wrong initialization of the method (as all methods were already added to the result).
> fix: fix top definitions filtering

- CONTRIBUTING.md
Related to #4233 
@I-Al-Istannen Judging by your profile here on GitHub I get the feeling you may want to be anonymous. We haven't historically allowed integrators to be anonymous, so that'd require a discussion between current integrators.
If that's not the case and just happens to be the way you set up your account, then please fill in the blanks in this PR (with PR comments).
> governance: Add I-Al-Istannen as integrator

- src/main/java/spoon/support/reflect/reference/CtArrayTypeReferenceImpl.java
- src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java
Fixes #4887 
The changes modify the constructor of `CtArrayTypeReferenceImpl` to set the declaration style as [`TYPE`](https://github.com/INRIA/spoon/blob/43a5b9a6983a808948ae490dceb02fbe83c3b505/src/main/java/spoon/support/reflect/reference/CtArrayTypeReferenceImpl.java#L135) by default.
> fix: print square brackets for manually created array references

- src/main/java/spoon/support/Internal.java
- src/main/java/spoon/support/compiler/ZipFile.java
- src/main/java/spoon/support/compiler/ZipFolder.java
- src/test/java/spoon/support/compiler/ZipFileTest.java
Previously, zip files were flattened and stored as `<name><random number>.java`. This caused all methods that retrieve code
at runtime, such as `getOriginalSourceFragment` or `getRawJavadoc,` to fail.
This patch keeps the structure of the zip file intact while extracting it into a temporary folder. Consequently, the aforementioned methods are now able to find the source files.
There were multiple ways to proceed here. As JDT needs a copy anyways, I chose to proactively copy the files to disk instead of storing them in memory and copying them when the sources are prepared. Then I set `isActualFile` to true, tricking the relevant parts of spoon into treating the zip file as a regular file (which it mostly is by now, as it has an on-disk representation). The old constructor is kept in place …
> fix: Fix getOriginalSourceFragment and getRawJavadoc for zip file inputs

- src/main/java/spoon/support/adaption/TypeAdaptor.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/sniperPrinter/Overriding.java
Cloning is quite slow and method bodies can be large - this results in the `isOverriding` check taking quite a bit longer than needed.
Removing the type adaption is not possible as the javadoc explains: If we do not adapt the method, we have no `CtTypeParameter` declaration lying around our references can attach to. This results in `getTypeErasure()` potentially entering an infinite recursion.
There are some more gains to be had if one really wants to, but I currently don't see the need. This one is quite unobtrusive and doesn't really make the code more confusing.
This creates an unnecessary change event for the Sniper printer (body changed), but it seems to ignore that and properly print it anyways.
> perf: Don't clone method body when adapting it for isOverriding

- src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
A non-protected constructor in an abstract class is not needed because only subclasses can be instantiated
- Constructor `spoon.support.reflect.declaration.CtTypeImpl()` is now protected instead of public
> refactor: fix bad smell "Non-Protected-Constructor-in-Abstract-Class"

- src/test/java/spoon/MavenLauncherTest.java
- src/test/java/spoon/test/TemporaryDirectoryExecutionListener.java
- src/test/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
Adds a test execution listener that maintains a `spooned` temporary directory. This is intended as a replacement to the normal Junit `@TempDir`, which fails to clean up files due to file locking on Windows.
- The temporary folder will be created before *every test*, which doesn't sound pleasant. Maybe we should only delete it if it actually contains files?
We need to update every test using `@TempDir` or `"spooned"` directly to use it. This could be directly done in this PR.
Closes #4877.
> test: Introduce a custom temp dir to work around windows file locking

- src/main/java/spoon/pattern/internal/ResultHolder.java
A non-protected constructor in an abstract class is not needed because only subclasses can be instantiated
- Constructor `spoon.pattern.internal.ResultHolder(java.lang.Class)` is now protected instead of public
> refactor: fix bad smell Non-Protected-Constructor-in-Abstract-Class

- src/main/java/spoon/reflect/factory/PackageFactory.java
The `toString()` method is not needed in cases the underlying method handles the conversion.
Unnecessary `toString()` call
in `spoon.reflect.factory.PackageFactory`
> style: fix bad smells in spoon.reflect.factory.PackageFactory

- src/main/java/spoon/processing/Processor.java
- src/main/java/spoon/reflect/visitor/CtScanner.java
- src/main/java/spoon/support/visitor/ProcessingVisitor.java
Just fixing a small typo in a couple of Javadoc comments. Methods just _call_ each other 😉
> doc: change "upcall" to "call"

- src/main/java/spoon/support/util/ImmutableMapImpl.java
The `toString()` method is not needed in cases the underlying method handles the conversion. Also calling toString() on a String is redundant. Removing them simplifies the code.
* Remove redudant `toString()` call in `parent.toString()`
> style: fix Bad Smells in spoon.support.util.ImmutableMapImpl

- src/main/java/spoon/support/reflect/declaration/CtElementImpl.java
The `toString()` method is not needed in cases the underlying method handles the conversion. Also calling toString() on a String is redundant. Removing them simplifies the code.
* Remove redudant `toString()` call in `this.toString()`
* Remove redudant `toString()` call in `o.toString()`
> style: fix Bad Smells in spoon.support.reflect.declaration.CtElementImpl

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java
- src/test/resources/patternmatching/InstanceofGenerics.java
Since Java 16, it is allowed to have type parameters other than `<?>` in instanceof checks. This is allowed in cases where the generic type can be carried over from the type on the left side.
I added a test with three such examples, one with pattern matching (the main reason this feature was added), one normal instanceof check with a type parameter as type argument and one with String as type argument.
The current solution is to not enforce wildcard in the printer for compliance mode >= 16. I would personally prefer to not change the printing output there at all, but there are tests relying on it - namely this one:
https://github.com/INRIA/spoon/blob/59990fe39101fdb7fcb13d4ad6bbaf0085cb8509/src/test/java/spoon/test/template/TemplateTest.java#L1096
And it also might break existing code. …
> fix: properly print type parameter reference in instanceof

- qodana.yml
All violations of this rule are fixed in #4903. I see zero cases where we want code like `.. == true` or `... == false`, so we should stop such code in the quality check. As a reminder, we only run the checks on `src/main/java`.
> chore: Add PointlessBooleanExpression rule to qodana checks

- .lift.toml
we want to suppress the useless warnings.
We need a `.lift.toml` for this. Looking at the doc at https://help.sonatype.com/lift/configuring-lift/build-and-.toml-details, the godclass warning is due to`refactor-first`
> The refactor-first tool is an implementation of an open source project created and maintained by Jim Bethancourt. The fundamentals of the tool are based on the paper [Prioritizing Design Debt Investment Opportunities](https://dl.acm.org/doi/10.1145/1985362.1985372) by Nico Zazworka, Carolyn Seaman and Forrest Shull.
> chore: disable comments from sonarlift and refactor-first

- .github/workflows/tests.yml
- src/test/java/spoon/test/model/TypeTest.java
This PR adds two new check runs in the CI. One for newest stable JDK(19) and early access JDK(20-ea). The goal is to know earlier if something will break in the future. Furthermore, a goal of this PR is to finally send a mail to [quality-outreach-programm](https://wiki.openjdk.org/display/quality/Quality+Outreach#QualityOutreach-HowtojointheQualityOutreachProgram) from openjdk. One test case was simply broken in future JDKs because we test against internal methods, and they got changed over the time.
I'm unsure if we should allow failure for these test runs. Allowing failure means we simply move the problem 6/12 months in the future.
1) Pinning of action hashes should be done by renovate after the merge, or shall I search for the hashes?
2) This checks need to be updated every 6 month to …
> review: test: add two test runs for newest and ea jdk

- src/main/java/spoon/reflect/visitor/ImportAnalyzer.java
Enumset for enum values is strictly better than set, and this fixes one of many locations with this bad smell.
> review: style: convert set to enumset

- src/test/java/spoon/test/main/MainTest.java
This test seems to be outdated. It used compliance level 8 on spoon.
Additionally, there are files which are filtered as they caused bugs before, but it seems like that's not the case for most of them anymore.
I also removed the manual launcher args as it's cleaner to do that in code directly (and most options are not needed).
> test: clean up MainTest#testGenericContract

- pom.xml
- spoon-decompiler/pom.xml
- spoon-pom/pom.xml
- spoon-visualisation/pom.xml
We used some truly ancient versions of a few default plugins and renovate did not pick them up. Now we specify them explicitly and renovate will hopefully keep them up to date in the future.
It will be interesting to see whether CI accepts this PR.
> chore: Specify version of default plugins explicitly

- src/main/java/spoon/reflect/factory/CodeFactory.java
- src/test/java/spoon/test/factory/CodeFactoryTest.java
This should fix the regression produced in #4940. I also applied at least some formatting to the long call chain and removed a random unused field in the test case.
Edit: I created this PR inside VSC, and the developer thought it would be nice to always create the branch in the main repo if possible. We should delete the branch afterwards.
> fix: handle empty modifers in CodeFactory#createCatchVariable correctly

- src/main/java/spoon/support/reflect/declaration/CtAnnotationImpl.java
The checks are (assumingly(?)) meant to avoid cost of toString + parse when the object is already of the expected type. As we'll never have primitive instances, the class comparison will never be true.
Not sure if this is rather a bug fix then a refactoring, but as there is no case in which the *result* will differ (besides checking the actual instance), it's hard to write an appropriate test so I'd rather label it as refactoring.
> refactor: Object#getClass will never be <primitive>.class

- src/main/java/spoon/support/reflect/declaration/CtRecordImpl.java
- src/test/java/spoon/test/record/CtRecordTest.java
- src/test/resources/records/WithStaticInitializer.java
Fixes #4961
While instance initializers are forbidden, static initializers are allowed.
> fix: records can have static initializers

- .github/workflows/sbom.yml
This new workflow creates a software bill of materials (SBOM) formatted as an in-toto attestation. This covers the content of the source tree, as well as the compiled files. The SBOM is pushed to a remote repository under the chains-project organisation for long-term storage.
**NOTE:** To work, this requires that a secret called `SBOM_DEPLOY_SSH` is added to the Spoon repo. It must contain the private part of an SSH key, where the public key is added as a deploy key to the [chains-project/sbom-files](https://github.com/chains-project/sbom-files) repository.
This should not be merged before the note above has been addressed.
> chore: add workflow for creating and storing SBOM

- pom.xml
Last release was in April 2022.
* Add support for sealed classes (JEP 409). (PR: #4337)
* Allow passing environment variables in maven launcher invocations. (PR: #4830)
* Use inferred generic type in invocations. (PR: #4844)
* Fix getOriginalSourceFragment and getRawJavadoc for zip file inputs. (PR: #4850)
* Print square brackets for manually created array references. (PR: #4888)
* Fix top definitions filtering. (PR: #4873)
* Attach comment to `CtLiteral` nodes. (PR: #4836)
* Maintain insertion of types in a package. (PR: #4832)
* Handle null bodies of while statements. (PR: #4813)
* Build AST with left associative string concatenation. (PR: #4809)
* Clearer message when cannot compare fragments. (PR: #4795)
* Enable creation of packages with repeated simple names in qualified name. (PR: …
> release of Spoon 10.2.0

- doc/_release/README.md
The release documentation was outdated. Here is a refreshment.
For the record, the CD task is at https://github.com/INRIA/spoon/issues/3890
> doc: improve release doc

- src/main/java/spoon/reflect/code/CtTry.java
- src/main/java/spoon/support/reflect/code/CtTryImpl.java
- src/test/java/spoon/test/trycatch/TryCatchTest.java
Reference: #3884 
The order of catchers is important because the thrown exception is matched with the parameters of the catchers in the order they appear, hence it is semantically important.
> feat: Add `CtTry.addCatcherAt`

- src/main/java/spoon/reflect/declaration/CtType.java
- src/main/java/spoon/reflect/reference/CtTypeReference.java
`getActualClass` was deprecated (I may even be the author of the deprecation).
But:
1. we use it all over the place
2. I used it myself naturally in a transformation I recently wrote.
So it is indeed very useful, and we should undeprecate it.
> doc: undeprecate method getActualClass

- src/main/java/spoon/reflect/visitor/TypeNameScope.java
Simple clean up, avoiding unnecessary `containsKey` calls
> review: refactor: use putIfAbsent in TypeNameScope

- .github/workflows/sbom.yml
- .github/workflows/tests.yml
We currently have warnings in our GH CI, caused by the changes described in https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
Example: https://github.com/INRIA/spoon/actions/runs/3341083524 and https://github.com/INRIA/spoon/actions/runs/3341083525
I updated our scripts to use the replacement.
> review: chore: replace deprecated set-output command in GHA

- src/main/java/spoon/support/gui/SpoonObjectFieldsTable.java
- src/main/java/spoon/support/reflect/declaration/CtClassImpl.java
Inner classes that do not reference their enclosing instances can be made static.
This prevents a common cause of memory leaks and uses less memory per instance of the class.
* InnerClassMayBeStatic (2)
> refactor: Refactor bad smell InnerClassMayBeStatic

- src/test/java/spoon/support/util/compilation/ClassFileManager.java
- src/test/java/spoon/support/util/compilation/InMemoryClassLoader.java
- src/test/java/spoon/support/util/compilation/InMemoryInputObject.java
- src/test/java/spoon/support/util/compilation/InMemoryOutputObject.java
- src/test/java/spoon/support/util/compilation/JavacFacade.java
- src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
- src/test/java/spoon/test/main/MainTest.java
This PR adds a — deliberately simple(istic) — facade to the system Javac compiler. This allows us to compile certain classes using Javac and ensure our reflection tree builder handles it correctly.
We could also use JDT (probably) to compile the files instead. I opted to use Javac as it is a lot more widely used and should also use different java versions in our CI.
> test: Add javac facade to test reflection tree builder

- src/main/java/spoon/ContractVerifier.java
The `toString()` method is not needed in cases the underlying method handles the conversion. Also calling toString() on a String is redundant. Removing them simplifies the code.
* UnnecessaryToStringCall (2)
> refactor: refactor bad smell UnnecessaryToStringCall

- src/main/java/spoon/support/visitor/replace/ReplacementVisitor.java
- src/test/java/spoon/generating/ReplacementVisitorGenerator.java
- src/test/java/spoon/generating/replace/ReplaceScanner.java
- src/test/java/spoon/generating/replace/ReplacementVisitor.java
This PR fixes:
- generate array with zero instead of fixed size.
- use new license header
- remove raw types `src/test/java/spoon/generating/replace/ReplaceScanner.java`
> refactor: remove some warnings in replacement package

- src/main/java/spoon/support/compiler/jdt/TreeBuilderCompiler.java
The performance of the empty array version is the same, and sometimes even better, compared
to the pre-sized version. Also, passing a pre-sized array is dangerous for a concurrent or
synchronized collection as a data race is possible between the <code>size</code> and <code>toArray</code>
calls. This may result in extra <code>null</code>s at the end of the array if the collection was concurrently
shrunk during the operation.</p>
See https://shipilev.net/blog/2016/arrays-wisdom-ancients/ for more details.
* ToArrayCallWithZeroLengthArrayArgument (1)
> refactor: refactor bad smell ToArrayCallWithZeroLengthArrayArgument

- src/main/java/spoon/support/StandardEnvironment.java
- src/test/java/spoon/test/logging/LogTest.java
- src/test/resources/logging/TestCase2.java
> fix: inner types without file should not crash Environment#report

- src/main/java/spoon/support/reflect/declaration/CtRecordImpl.java
JLS [9.6.4.1](https://docs.oracle.com/javase/specs/jls/se19/html/jls-9.html#jls-9.6.4.1) states:
>  If an annotation of type java.lang.annotation.Target is not present on the declaration of an annotation interface A, then A is applicable in all declaration contexts and in no type contexts. 
Previously the code crashed with a NPE.
> fix: model building when annotation on record has no @Target

- .github/workflows/tests.yml
- chore/check-links-in-doc.py
- chore/ci-extra.sh
Github recently updated their `ubuntu-latest` image to 22.04. This broke setup-python as it no python 3.6 tarball is provided (https://github.com/actions/setup-python/issues/544). 
This PR fixes the issue by just updating the CI to use python 3.9. It does not adjust the ci scripts to take advantage of possible new python features introduced since then.
This breakage is responsible for the current red master (as the PR run was executed *before* the Github runner change but the master action ran *after* it) and unblocks some PRs.
----
I also needed to update commonmark. Note that commonmark is **deprecated** for **over a year** now: https://github.com/readthedocs/commonmark.py/issues/308. We might to want migrate away from it in a future PR, though we don't really *need* to. The source code …
> chore: Update CI python version from 3.6 to 3.11

- src/main/java/spoon/support/reflect/code/CtFieldAccessImpl.java
- src/main/java/spoon/support/reflect/code/CtSuperAccessImpl.java
- src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
Returning null in a fluent setter kind of defeats the purpose: Using the fluent API crashes with a NPE.
The first location was found because it crashed on me :'(. The other location was found by:
```java
@ModelTest("src/main/java")
void foo(CtModel model, Factory factory) {
CtTypeReference<?> element = factory.Type().get(CtElement.class).getReference();
for (CtModule module : model.getAllModules()) {
module.accept(new CtScanner() {
@Override
public <T> void visitCtMethod(CtMethod<T> m) {
if (!TypeAdaptor.isSubtype(m.getDeclaringType(), element)) {
return;
}
if (m.getSignature().equals("S()")) {
return;
}
if (!m.getSimpleName().startsWith("set")) {
return;
}
m.accept(new CtScanner() {
@Override
public <R> void visitCtReturn(CtReturn<R> returnStatement) {
if …
```
> fix: Do not return null in fluent API setters

- spoon-pom/pom.xml
Reverts INRIA/spoon#5055
@MartinWitt @SirYwell @I-Al-Istannen Need to roll this back as depclean apparently moved to Java 17 causing our deploy job to fail. Unbeknownst to me, our extra CI checks here run on Java 17, I just assumed they would run on our lowest supported version. I'll try Java 11 for that to see if it works after this has been merged, anything that's running checks should either run on all supported versions or on the lowest supported version (the latter usually being sufficient when it comes to Java).
> Revert "chore(deps): update dependency se.kth.castor:depclean-maven-plugin to v2.0.4"

- .github/workflows/tests.yml
We should run our extra checks on the least supported version. It's significantly more likely to have breakage because of backwards-incompatible changes (e.g. Depclean moving to Java 17) than forwards-incompatible changes.
> chore: Use Java 11 for extra CI checks

- src/main/java/spoon/reflect/factory/AnnotationFactory.java
Creating an empty array for calling varargs methods is redundant. You can call the method directly without the array. The fix is to remove the empty array.
* RedundantArrayCreation (1)
> refactor: refactor bad smell RedundantArrayCreation

- src/main/java/spoon/reflect/visitor/LiteralHelper.java
- src/main/java/spoon/support/reflect/code/CtLiteralImpl.java
- src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java
`float` and `double` can represent ~~three~~ *many* values you can not write using a floating literal. Some examples are `Infinity`, `-Infinity` and then the whole family of `NaN` values.
As they can not be written down directly, the current printer creates invalid code for them. Forbidding such values in `CtLiteral` is not an option, as we can no longer represent `get(Double.class).getField("POSITIVE_INFINITY")`. 
Alternatively, we could also adjust the printer to *handle* (and not *reject*) such literals, by producing either reads of `Double.POSITIVE_INFINITY` or emitting `1d/0`.
I think we should probably offer a convenience method somewhere, which translates a `float` or `double` to a Literal or appropriate field read (`Double.POSITIVE_INFINITY`). Something to think about here is …
> review: fix: Reject invalid float/double literals

- src/main/java/spoon/support/visitor/java/reflect/RtParameter.java
- src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
This feature allows Spoon to read the parameter name from Java 8 and later byte code that has been built with the "-parameters" flag such that CtParameter objects representing code from the class path contain the "real" parameter name instead of "argX".
> feat: read parameter names from bytecode if possible

- src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java
- src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
While constructors of non-static inner classes have an *implicit* parameter of the enclosing class's type, static classes *do not*. This should be reflected in the model.
> fix: enclosing class parameters being ignored for static inner classes

- src/main/java/spoon/reflect/factory/TypeFactory.java
- src/main/java/spoon/support/reflect/reference/CtTypeReferenceImpl.java
- src/test/java/spoon/reflect/reference/CtTypeReferenceTest.java
The additional dimensions of multi-dimensional arrays were dropped by `getActualClass`.
> fix: getActualClass() for multi-dimensional arrays

- src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java
- src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
If we did, we would overwrite potential top-level classes in the package. This happened with `java.util.ArrayList` and `java.util.Arrays$ArrayList` in a project of mine. As a consequence, lookups for `java.util.ArrayList$ListIter` fail: The now-overwritten `ArrayList` has no member classes and the lookup returns null.
The problem cost me a few hours to find and fix, but I hope the fix seems reasonable enough.
> fix: Do not visit package for nested classes

- src/main/java/spoon/reflect/factory/CodeFactory.java
- src/test/java/spoon/test/factory/CodeFactoryTest.java
Creating `CtTypeReference`s from java classes was a bit too ad-hoc for my usecase. This PR adds support for array types and anonymous classes. Anonymous classes do not appear in the shadow model but can still be useful when dealing with arbitrary objects. They are also supported by the source model.
Notable changes: This PR switches from `CLass#getDeclaringClass` to `Class#getEnclosingClass` to properly work with anonymous classes. This seems to be closer to what the source model uses as well.
> fix: creation of CtTypeReferences from java classes

- src/main/java/spoon/reflect/visitor/ImportConflictDetector.java
- src/main/java/spoon/reflect/visitor/LexicalScopeScanner.java
- src/test/java/spoon/test/imports/ImportTest.java
- src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
Previously, spoon would turn
```java
package bar;
public class User {
public static void foo() {
System.out.println(foo.bar.baz.Locale.HELLO);
System.out.println(java.util.Locale.GERMANY);
}
}
```
into
```java
package bar;
import foo.bar.baz.Locale;
import java.util.Locale;
public class User {
public static void foo() {
System.out.println(Locale.HELLO);
System.out.println(Locale.GERMANY);
}
}
```
which is *not ideal*. There was a test case verifying this does not happen, but as far as I can see the assertions in the test are wrong. I also have no idea what code was supposed to implement it.
> fix: Do not import two types with the same simple name

- src/main/java/spoon/support/adaption/TypeAdaptor.java
- src/test/java/spoon/support/TypeAdaptorTest.java
This fixes a small oversight where the cloned throws clause was adapted instead of the original. As the cloned method does not have a parent, lookup of the enclosing type failed and an exception was thrown.
It would likely also be possible to use a method context for the adaption and then try to adapt formal type parameters to the submethod, but that does not make a difference for the overriding check as far as I can see. It would complicate the implementation and be slower though, so I did not do this here.
Closes #5115.
> fix: isOverriding check with generic throws clause

- README.md
- src/main/java/spoon/reflect/visitor/LiteralHelper.java
- src/test/java/spoon/test/literal/LiteralTest.java
Currently, spoon escapes every `'` in a `CtLiteral<String>` without a source position. In a `string `escaping `'` is not necessary.
> fix: Remove escaping of ' in a CtLiteral<String>

- pom.xml
*Beep boop, this action was performed manually.*
I guess I am cosplaying as renovate now… The release was 3 days ago, maybe renovate would have come around in the future. But this fails the 20-ea CI on other PRs, so we should fix it.
> chore(deps): update dependency org.jacoco:jacoco-maven-plugin to version 0.8.9

- spoon-smpl/src/test/java/spoon/smpl/C4JShouldVibrateTest.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/test/java/spoon/reflect/visitor/CtScannerTest.java
- src/test/java/spoon/test/imports/ImportTest.java
In no classpath mode, JDT only gives us a ProblemBinding with a QualifiedNameReference. We then have to figure out whether this is a type, field, inner class, package or anything else ourselves. Previously, every child of an invocation was treated as a type. This patch changes it to favor fields and only falls back to a type access, if it appeared somewhere in an import.
This is still far from perfect, but it at least produces better guesses.
Closes #5151
> fix: Use a better heuristic for guessing type/field references in no classpath mode

- .github/ISSUE_TEMPLATE/bug_report.yaml
We're already outdated by 2 versions here, so I think it is reasonable to allow any input for this field.
> chore: Allow any input for jvm versions in bug report template

- src/main/java/spoon/support/compiler/SpoonPom.java
This fixes property extraction for poms with `<something>${first}${second}</something>`.
> fix: Support back-to-back properties and file.separator in SpoonPom

- renovate.json
After discussion with @monperrus this renovate config enables automerge of green PR updates from renovate. I have changed the master protection rules to let renovate bypass them. I removed some old mockito rule which seems useless.
> chore: Enable renovate automerge for non-major updates

- .github/workflows/tests.yml
replaces #5189 Somehow the GitHub API allows creating branches which destroy GitHub. Having a `/` leading your branch name is not the best idea.
Had a lengthy discussion with @I-Al-Istannen and @SirYwell about our failing master and how to fix this. We concluded to switch to mavens new http transport and increase the timeout. This should reduce/remove the failing of mavens dependency resolution on master. The timeout is still set to a reasonable number, but we will monitor it closely and increase if we see we still need a large.
Add system properties to Maven options to set the native dependency transport for Aether connector. This will improve the speed of dependency resolution by using the native transport layer over HTTP. Also, the request timeout and connection timeout are increased …
> chore: Use native transport configuration for Maven in CI

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/test/java/spoon/test/field/FieldTest.java
Step 1 addressing #5199.
Previously, spoon set the declaring type to the type of the field if JDT didn't provide a declaring type. From running all tests, this seems to be only the case for access to the `length` field of arrays. Instead of setting the declaring type to `int` then, we now use the type binding provided by JDT that holds the actual declaring type.
Note that this does not fully fix the bug, but we get `The field java.lang.String[]#length not found` instead of `The field int#length not found`.
> review: fix: set declaring type for array field accesses

- doc/type_adaption.md
- src/main/java/spoon/support/adaption/DeclarationNode.java
- src/main/java/spoon/support/adaption/TypeAdaptor.java
- src/test/java/spoon/support/TypeAdaptorTest.java
Type adaption did not handle using generics inherited from enclosing classes. In these cases, a type hierarchy from the innermost class to its parent class was built, causing the generic resolution to fail.
This PR fixes this by adjusting building a hierarchy between the *declaring* types instead.
This closes #5226.
> review: fix: Correctly adapt type parameters inherited from enclosing classes

- CONTRIBUTING.md
- src/test/java/spoon/reflect/factory/PackageFactoryTest.java
- src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java
- src/test/java/spoon/support/TypeAdaptorTest.java
- src/test/java/spoon/support/visitor/java/JavaReflectionTreeBuilderTest.java
- src/test/java/spoon/test/comment/CommentTest.java
- src/test/java/spoon/test/enums/EnumsTest.java
- src/test/java/spoon/test/factory/CodeFactoryTest.java
- src/test/java/spoon/test/issue3321/AnnotationPositionTest.java
- src/test/java/spoon/test/literal/LiteralTest.java
- src/test/java/spoon/test/logging/LogTest.java
- src/test/java/spoon/test/model/SwitchCaseTest.java
- src/test/java/spoon/test/prettyprinter/SniperAnnotatedEnumTest.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/java/spoon/test/role/TestCtRole.java
- src/test/java/spoon/testing/utils/GitHubIssue.java
I also moved the class to a better package where the rest of our util classes is. Fixes #5229
> test: Move GitHub issue to correct package and fix problem with multiple @Test annotations

- src/main/java/spoon/support/reflect/reference/CtFieldReferenceImpl.java
- src/test/java/spoon/test/field/FieldTest.java
Fixes the use case described in #5199, `getModifiers()` now works for the `length` field in arrays.
`getActualField()` still throws the exception, but this modelling is just similar to the reflection api.
I also added a contract and renamed the test method from my previous work on this...
> review: fix: special-case getModifiers for array.length accesses

- src/main/java/spoon/Launcher.java
Simplify file iteration loop in `Launcher.java` by changing the `resources` collection to be a `Collection<File>`, and using `File` instead of `Object` in the loop, which removes the requirement of casting it before converting it to a `Path`.
> refactor: remove cast by narrowing type

- src/main/java/spoon/support/compiler/jdt/ContextBuilder.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java
- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
Replaces repetitive code with methods that simplify the code. This also helps to get rid of NPE warnings.
> review: refactor: replace direct access to ContextBuilder#stack with methods

- src/main/java/spoon/support/compiler/jdt/ContextBuilder.java
- src/test/java/spoon/test/type/TypeTest.java
- src/test/resources/noclasspath/issue5208/p20/ClassT1.java
- src/test/resources/noclasspath/issue5208/p20/ClassT2.java
- src/test/resources/noclasspath/issue5208/p20/ClassT3.java
Fixes #5208 
Looking up a field in noclasspath mode should not replace an existing type.
> review: fix: do not replace types when looking up fields from supertypes

- src/main/java/spoon/support/StandardEnvironment.java
I removed the unneeded variable and converted it to a directly thrown Exception.
> review: refactor: reduce complexity of setInputClassLoader

- src/main/java/spoon/reflect/factory/PackageFactory.java
- src/test/java/spoon/reflect/factory/PackageFactoryTest.java
The check is 17 years old and $ is allowed in packages. Interesting that we had no bug reports earlier.
The check for the `CtType.INNERTTYPE_SEPARATOR` that caused runtime exceptions has been removed so that valid packages with `CtType.INNERTTYPE_SEPARATOR` can be found.
A new test has been added to verify that a package with a name containing a dollar sign can be successfully retrieved using the `PackageFactory`.
Fixes #5140
> review: fix: Refactor code to fix runtime exception caused by package name with CtType.INNERTTYPE_SEPARATOR

- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
Narrow instanceof from CtVariable to CtLocalVariable aligning it with the cast afterwards.
Improve if, else construct with else at the end.
> review: fix: refactor visitCtForEach method

- .github/workflows/jreleaser.yml
This commit adds GPG private key and passphrase secrets to the workflow by setting `gpg-private-key` and `gpg-passphrase` fields respectively, enabling secure and automated signing of the release artifacts with JReleaser.
This should fix this error https://github.com/INRIA/spoon/actions/runs/5224090878/jobs/9431846062, see https://github.com/actions/setup-java#maven-options for the options.
> review: chore: Added GPG private key & passphrase secrets to JReleaser workflow.

- .github/workflows/jreleaser.yml
This commit includes the addition of a token in JReleaser's Github checkout. It also adds a run command that creates a new branch, commits the release version changes, and pushes the branch. Furthermore, `-Dgpg.skip=true` is added to the run command for skipping gpg verification. Lastly, the `Commit & Push changes` step is modified by removing the using action and adding commands for committing the changes and merging the branch with master.
> release: Skip GPG plugin and remove js git actions

- .github/workflows/qodana.yml
Uploading the sarif result with the CodeQL action works fine for us, so there's not much benefit having additional PR comments around.
> review: chore: disable Qodana PR comment

- .github/workflows/jreleaser.yml
The `jreleaser.yml` file was updated to set up the git user before committing changes. The `user.name` was set as "GitHub Actions Bot" with a blank `user.email`. This config does the job and we need nothing fancy.
> fix: Add configuration for git user on GitHub Actions.

- src/main/java/spoon/reflect/factory/TypeFactory.java
- src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
The normal spoon model is safe-ish under concurrent queries (*NOT* modifications), but as the shadow model is lazily build, querying *is* modification. Sadly, the tree builder even has internal side effects it relies on, making parallel use a game of chance. This PR proposes a pretty big, well worn duct-tape to paper over this by unquestionably serializing scans for one factory.
The performance impact should be okay (correct > fast) and each class is only looked up *once* before it is stored in the shadow cache.
----
This was debugged with the following JCStress test.
Before:
After:
```java
package org.openjdk.jcstress.tests.spoon;
import static org.openjdk.jcstress.annotations.Expect.ACCEPTABLE;
import static org.openjdk.jcstress.annotations.Expect.FORBIDDEN;
import …
```
> review: fix: Synchronize reflection tree builder entrypoint method on factory

- .github/workflows/qodana.yml
- .github/workflows/tests.yml
This commit updates the Github workflows configuration files to include the Java 17 branch in pull requests and push events.
> chore: Run tests for java17 branch

- .github/workflows/jreleaser.yml
- jreleaser.yml
This commit fixes the mvn commands to run for all modules.
Locally, I can produce snapshot releases with this config. The first changelog looks a bit doomed because JReleaser finds not matching git commit for the releases. Let's hope the GitHub API does not die.
> review: fix: fix releasing of spoon-core, parent and javadoc module

- pom.xml
unstable build is even worse than non-reproducible build
and FYI, Spoon 10.3.0 ingested Maven 4.0.0-alpha-4 components: did you really mean to inject alpha components?
see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/fr/inria/gforge/spoon/spoon-core/README.md
> avoid version range: makes build is not stable

- jreleaser.yml
Spoon has a pre2021 URL. Also the project name should be `spoon` instead of ´spoon-core´
> fix: use old sonatype url

- src/main/java/spoon/support/JavaOutputProcessor.java
- src/test/java/spoon/support/JavaOutputProcessorTest.java
This pull request is related to #5343.
With this commit, `JavaOutputProcessor` now uses `PrintStream​(File file, Charset charset)` instead of `PrintStream​(File file)`.
By default, `Charset.defaultCharset()`  is assigned to `charset`. So the default behavior remains the same.
> review: feat: configurable encoding of processed source code

- src/main/java/spoon/reflect/factory/CodeFactory.java
- src/main/java/spoon/reflect/factory/ConstructorFactory.java
- src/main/java/spoon/support/reflect/cu/position/SourcePositionImpl.java
Add a space after varargs(...) to follow the checkstyle rule.
> checkstyle: add a whitespace after varargs

- src/main/java/spoon/FluentLauncher.java
- src/main/java/spoon/compiler/Environment.java
There are typos "when *is* is hard..." in several classes, fixed them to "it is".
> doc: fix typos "is is..."

- src/main/java/spoon/experimental/SpoonifierVisitor.java
Unless there's particular reason, `Deque` should be used instead of `Stack` (like other part of spoon code).
> review: refactor(SpoonifierVisitor): `Deque` should be used instead of `Stack`

- .github/workflows/tests.yml
This commit removes `java` version 11 in the matrix of os and java versions in the tests.yml file. It sets the `java-version` to 17 in the `Set up JDK` step in both the `build` and `tests` jobs.
> review: chore:  Remove Java 11 from tests.yml

- src/main/java/spoon/reflect/visitor/filter/VariableAccessFilter.java
- src/test/java/spoon/test/filters/FilterTest.java
> fix(VariableAccessFilter): ensure all accesses are returned for generic fields

- .github/workflows/qodana-cloud.yaml
- .github/workflows/qodana.yml
- qodana.yaml
- src/main/java/spoon/support/reflect/code/CtInvocationImpl.java
This PR enables more or less all java rules. We could cut them down a bit if we see some we really hate. But as they are adding more and more nice rules, it is real hard to keep the file up-to-date otherwise.
> chore: convert qodana config to new format

- src/main/java/spoon/reflect/factory/TypeFactory.java
This fixes a concurrent modification exception when parallel queries try to look up the same anonymous types.
CC: @Luro02
> fix: Synchronize access to anonymous type cache

- pom.xml
- renovate.json
Reverts INRIA/spoon#5376
The ignore feature somehow failed. After fixing this we can do a patch release to test the nix release workflow.
> Revert "fix(deps): update dependency org.apache.maven:maven-model to v3.9.4"

- .github/workflows/update-flake.yml
Use the workflow token with appropriate permissions to ensure automerge can actually be enabled.
> chore: Use workflow token with permissions for automerge

- src/main/java/spoon/support/compiler/SpoonPom.java
- src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
This is a pull request for #5320 .
Applied `@Nullable` annotation to the classes of `spoon.support.compiler`.
> refactor: adopt jspecify to `spoon.support.compiler`

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/test/java/spoon/reflect/reference/CtTypeReferenceTest.java
This is still imperfect, but I don't feel like rewriting `getQualifiedTypeReference` right now.
> review: fix: Keep implicit status for more implicit enclosing class references

- src/main/java/spoon/compiler/Environment.java
Space indentation remained around Javadoc of `Environment`, so I replaced it with tab.
> doc(Environment): replace space indentation with tab

- doc/jenkins/build.sh
Maven 3 does not allow version ranges in plugin versions. This currently causes lots of failures in the SOS CI.
> chore: Replace version range with specific version

- renovate.json
According to this comment we also need the lockFileMaintenance https://github.com/renovatebot/renovate/issues/8000#issuecomment-1312289641
> review: chore: enable nix renovate correctly

- src/main/java/spoon/support/modelobs/ChangeCollector.java
- src/main/java/spoon/support/sniper/internal/ElementPrinterEvent.java
- src/main/java/spoon/support/sniper/internal/ElementSourceFragment.java
- src/main/java/spoon/support/sniper/internal/PrinterEvent.java
- src/main/java/spoon/support/sniper/internal/TokenPrinterEvent.java
See #5320.
Apply the `@Nullable` annotation to classes in `spoon.support`.
Specifically, for the following packages:
- `spoon.support.modelobs`
- `spoon.support.sniper.internal`
> refactor: Apply the `@Nullable` annotation to `spoon.support`

- src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java
`@clyde` Can you write a pull request description for this patch fixing a java 21 regression?
```patch
diff --git a/src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java b/src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java
index a7fd868a3..a995111df 100644
--- a/src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java
+++ b/src/main/java/spoon/reflect/visitor/chain/CtQueryImpl.java
@@ -377,7 +377,7 @@ public class CtQueryImpl implements CtQuery {
protected void onCallbackSet(String stackClass, String stackMethodName, Class<?> callbackClass, String callbackMethod, int nrOfParams, int idxOfInputParam) {
this.cceStacktraceClass = stackClass;
this.cceStacktraceMethodName = stackMethodName;
-                       if (callbackClass.getName().contains("$$Lambda$")) {
+ …
```
> review: fix: Fixing regression in CtQueryImpl caused by lambda names in Java 21

- src/main/java/spoon/support/adaption/TypeAdaptor.java
- src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java
- src/test/java/spoon/support/TypeAdaptorTest.java
This one was a bit of a doozy.
Array subtyping needs to be special cased, as Spoon is not able to build a `CtType` for source-level arrays. Similarly, once we are given a shadow `CtType` that refers to an array type, we need to unpack to find the real type to build our hierarchy for. We can not just fall back to the java `Class#isAssignableFrom`, as the super type reference might not be shadowable.
Closes #5462.
> review: fix: Subtyping relationships for arrays

- .github/workflows/tests.yml
- flake.nix
- pom.xml
- spoon-pom/pom.xml
We can now update the CI to use the (oracle) JDK 21 GA build.
> review: chore: Switch to oracle JDK 21 in CI until nixpkgs catches up

- flake.nix
- spoon-dataflow/README.md
- spoon-dataflow/build.gradle
Use z3-turnkey which extracts the native z3 libraries and loads them. This releases the user from compiling and installing the z3 binaries. We use 4.11.2 because it still supports glibc-2.31.
This should allow @I-Al-Istannen to remove z3 specific config from the nix packages which in turn should shorten CI duration on a cache miss.
> Use prebuilt z3 package/binary

- src/main/java/spoon/support/util/RtHelper.java
- src/main/java/spoon/support/util/internal/ElementNameMap.java
See #5320 .
Apply `@Nullable` annotation to classes in `spoon.support.util`.
> refactor: Apply `@Nullable` annotation to `spoon.support.util`

- .github/workflows/tests.yml
- flake.nix
- jreleaser.yml
- spoon-pom/pom.xml
- src/main/java/spoon/metamodel/Metamodel.java
- src/main/java/spoon/testing/utils/ModelUtils.java
This fully brings spoon to Java 17. Small adjustments to tests were needed.
> review: chore: compile spoon with Java 17

- flake.nix
- pom.xml
- spoon-pom/pom.xml
- spoon-smpl/src/test/java/spoon/smpl/ZippedCodeBaseTestContext.java
- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/test/java/spoon/FluentLauncherTest.java
- src/test/java/spoon/test/record/CtRecordTest.java
- src/test/resources/records/MultipleConstructors.java
- src/test/resources/records/NonCompactCanonicalConstructor.java
Supersedes #5570.
We require Java 17 to run this jdt version, and this jdt version is required for Java 21 feature support.
Note these changes contain bugfixes for issues due to changes in JDT.
> review: chore: update jdt to 3.36.0

- .lift.toml
Lift does not exist anymore, so we can delete this file.
> review: chore: Remove .lift.toml configuration file

- doc/spoon_javadoc.md
Jekyll apparently can not handle html elements in markdown.
> doc: Fix jekyll rendering of spoon_javadoc.md

- src/main/java/spoon/support/adaption/TypeAdaptor.java
This should fix #5619, but I am not sure if locking on a method parameter is more elegant than calling clone.
> fix: Add thread-safety to TypeAdaptor method adaptation

- doc/_data/sidebar_doc.yml
- doc/spoon_javadoc.md
Separated this part of the #5609 and switched target branch. We could also include gradle instructions.
> review: fix: Update spoon-javadoc installation instructions

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
This partly solves #4129 by adding an extra newline after printing the enum values.
So instead of printing this:
```java
public enum SimpleEnum {
CONSTANT;}
```
It now prints this:
```java
public enum SimpleEnum {
CONSTANT;
}
```
This does have a small impact on enums with members, as previously they would be printed like this:
```java
public enum EnumWithMembers {
ONE,
TWO,
THREE;
private static int len = -1;
public static void f() {
len = 44;
}
}
```
And now they will be printed like this:
```java
public enum EnumWithMembers {
ONE,
TWO,
THREE;
private static int len = -1;
public static void f() {
len = 44;
}
}
```
To be honest I prefer the second anyway.
> fix: Add extra newline after printing enum values

- chore/CheckJavadoc.java
- chore/check-javadoc-regressions.py
- flake.lock
Somehow `LATEST` often fails to resolve in CI (never locally). Many people in the issues of jbang use `RELEASE`, so maybe that one actually works.
> review: chore: Use `RELEASE` version for jbang instead of `LATEST`

- src/main/java/spoon/support/compiler/jdt/ASTPair.java
- src/main/java/spoon/support/compiler/jdt/ContextBuilder.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/main/java/spoon/support/compiler/jdt/PositionBuilder.java
- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
`ASTPair` is a perfect example of a class that should be a record. In theory it's breaking, but it's supposed to be used internally only anyways, and it's targeting the java17 branch.
> review: refactor: make ASTPair a record

- flake.nix
- spoon-pom/pom.xml
It is broken for java 21 classfiles since quite a while. See https://github.com/ASSERT-KTH/depclean/issues/272
If depclean is still broken in two months I will make a follow-up PR to completely remove it from spoon.
> review: chore: Disable depclean

- chore/release-beta.sh
- chore/release-nightly.sh
- chore/release.sh
- flake.nix
- src/test/java/spoon/testing/assertions/CtAnnotationMethodAssertInterface.java
- src/test/java/spoon/testing/assertions/CtAnonymousExecutableAssertInterface.java
- src/test/java/spoon/testing/assertions/CtLambdaAssertInterface.java
- src/test/java/spoon/testing/assertions/CtReceiverParameterAssertInterface.java
- src/test/java/spoon/testing/assertions/SpoonAssertions.java
This will set
- `set -o pipefail`: Set exit code of pipe to exit code of failing program within
- `set -e`: Fail if any command failed
- `set -u`: Fail if any variable is not defined
> review: chore: Set euo pipefail in all scripts

- spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowBuilder.java
- spoon-control-flow/src/test/java/fr/inria/controlflow/ForwardFlowBuilderVisitorTest.java
- spoon-control-flow/src/test/resources/control-flow/ControlFlowArithmetic.java
Currently, generating a control flow graph for a `CtConstructor` generates an "empty" CFG, consisting just of the `BEGIN` and `EXIT` node and an edge between them. With this PR they are processed the same as a `CtMethod`
> review: fix(control-flow): Proper generation of CFG for constructor

- .github/workflows/qodana.yml
This commit introduces a new Qodana scan for the 'spoon-control-flow' in the project's GitHub Actions workflow. The scan uses the JetBrains Qodana action and produces a SARIF result file that is subsequently uploaded using the CodeQL action.
> chore: Add spoon-control-flow scan to Qodana GitHub workflow

- src/main/java/spoon/reflect/declaration/CtElement.java
> Clarify that `CtElement#prettyprint` ignores environment settings

- .github/workflows/tests.yml
- chore/check-javadoc-regressions.py
- chore/run-with-spoon-javadoc-classpath.sh
- flake.nix
The downside is that we commit a lot of sins. This is a giant clusterfuck, but the nice way to run a java file with dependencies via jbang sporadically runs into dependency resolution failures...
> chore: Remove jbang. It falls apart randomly during dependency resolution

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/test/java/spoon/support/JavaOutputProcessorTest.java
- src/test/java/spoon/test/comment/CommentTest.java
- src/test/java/spoon/test/ctClass/CtClassTest.java
- src/test/java/spoon/test/field/FieldTest.java
- src/test/java/spoon/test/imports/ImportTest.java
- src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
- src/test/resources/spoon/test/module/simple_module/module-info-tpl
A newline has been added to the end of each file by convention. Additionally, the calculate method in DefaultJavaPrettyPrinter has been refactored. The type calculation logic is now cleaner and easier to understand, as unnecessary conditional checks have been removed.
> review: feat: Add newline at file end and refactor type calculation

- spoon-control-flow/src/main/java/fr/inria/controlflow/ControlFlowBuilder.java
- spoon-control-flow/src/test/java/fr/inria/controlflow/ForwardFlowBuilderVisitorTest.java
- spoon-control-flow/src/test/resources/control-flow/ControlFlowArithmetic.java
Currently, a standalone constructor call doesn't appear in the control flow graph. With this PR it is processed like any other statement
> review: fix(control-flow): Process constructor call in control flow graph

- src/main/java/spoon/support/compiler/SpoonPom.java
This PR replaces deprecated methods in `SpoonPom` with recommended ones.
| Deprecated | Recommended |
| ---- | ---- |
| Invoker.setWorkingDirectory | InvocationRequest.setBaseDirectory |
| Invoker.setErrorHandler | InvocationRequest.setErrorHandler |
| Invoker.setOutputHandler | InvocationRequest.setOutputHandler |
| InvocationRequest.setGoals | InvocationRequest.addArg |
Also it deletes `getOutputHandler` and `getErrorHandler`  because the values obtained are not used.
> refactor(SpoonPom): Replace deprecated methods

- spoon-javadoc/src/main/java/spoon/javadoc/api/parsing/LinkResolver.java
- spoon-javadoc/src/test/java/spoon/javadoc/api/parsing/JavadocParserTest.java
The spec mandates that members can be referred to without a leading pound (`#`) sign, so we should support that. This PR also adds support for "reflection" on java modules (at least for the boot layer), so module references can be resolved even if they are not present in the analyzed source.
> review: fix: Extend support for member references without a leading # and java modules

- spoon-javadoc/src/main/java/spoon/javadoc/api/parsing/InheritanceResolver.java
- spoon-javadoc/src/test/java/spoon/javadoc/api/parsing/InheritanceResolverTest.java
Previously, formal type parameters (e.g. `<T>`) were not inherited to child methods. This lead to false-positives in the Javadoc CI check (e.g. in #5801).
> review: fix: Inherit formal javadoc type parameters

- src/main/java/spoon/reflect/code/CtResource.java
- src/main/java/spoon/reflect/code/CtVariableRead.java
- src/main/java/spoon/reflect/declaration/CtField.java
- src/main/java/spoon/reflect/visitor/CtInheritanceScanner.java
- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/test/java/spoon/test/trycatch/TryCatchTest.java
- src/test/java/spoon/testing/assertions/CtResourceAssertInterface.java
- src/test/java/spoon/testing/assertions/CtVariableReadAssertInterface.java
Fields are allowed in try-with-resources statements now, so spoon should model this case. Before this patch, only `CtLocalVariable` implemented `CtResource`.
> review: fix: Make CtFieldRead inherit from CtResource

- jreleaser.yml
We should mark the beta releases as non-production ready pre-releases. Here is an automated way to do it based on [JReleaser configuration](https://jreleaser.org/guide/latest/reference/release/github.html#_configuration).
> chore: mark beta releases as pre-release

- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderHelper.java
- src/main/java/spoon/support/compiler/jdt/JDTTreeBuilderQuery.java
- src/test/java/spoon/test/prettyprinter/QualifiedThisRefTest.java
- src/test/java/spoon/test/targeted/TargetedExpressionTest.java
expected behavior: buf is a field access
actual behavior: buf is a typeaccess
cause: isResolvedField assumed that everything is source-available and returned false if a library class (binary only, ByteArrayOutputStream here)
> fix: fix modeling bug

- doc/jenkins/build.sh
- doc/jenkins/inject_spoon_snapshot.py
WIth that, the majority of non-regression jobs are up and running again: https://ci.inria.fr/sos/
> chore: refresh the Jenkins CI scripts

- doc/processor_annotations.md
- src/main/java/spoon/processing/AbstractAnnotationProcessor.java
- src/main/java/spoon/processing/AnnotationProcessor.java
- src/test/java/spoon/test/api/APITest.java
- src/test/java/spoon/test/reference/ExecutableReferenceTest.java
- mark misspelled method as deprecated
- add new method with correct spelling
- correct spelling of method in docs and test classes
> fix: correct spelling mistake in API, doc and tests (#5934)

- spoon-visualisation/README.md
- spoon-visualisation/pom.xml
- spoon-visualisation/src/main/java/spoon/visualisation/Launcher.java
- spoon-visualisation/src/main/java/spoon/visualisation/command/SpoonTreeCmdBase.java
This PR fixes the POM for spoon-visualization and radically simplifies the execution to `mvn javafx:run` or building a runnable fat jar with `mvn package`.
Fixes: #5795
> Fix and simplify packaging and running of `spoon-visualization`

- src/main/java/spoon/Launcher.java
- src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java
- src/test/java/spoon/test/compilation/CompilationTest.java
- src/test/java/spoon/test/ctClass/CtClassTest.java
- src/test/java/spoon/test/ctType/CtTypeTest.java
- src/test/java/spoon/test/imports/ImportTest.java
- src/test/java/spoon/test/prettyprinter/PrinterTest.java
- src/test/java/spoon/test/trycatch/TryCatchTest.java
- src/test/java/spoon/test/variable/AccessFullyQualifiedFieldTest.java
- src/test/java/spoon/test/visibility/VisibilityTest.java
In preparation for #5977, we need to make sure that tests only run with a compliance level >= 8.
I went through the affected tests trying to figure out if there is a specific reason why they used a lower language level. Those where it doesn't seem to make sense to run on higher language levels are disabled now with a comment. I'm not sure if we want to remove them directly.
Note: There are more failing tests in #5977, but the others have different reasons that we need to analyze more closely I guess. That's why I'd like to address them separately.
> review: test: only run tests with compliance level >=8

- .github/workflows/jreleaser.yml
- .github/workflows/release-nightly.yml
This makes it so all release pipelines attest the artifacts they build, by signing the corresponding checksums. Optionally release workflows may opt out of this behavior, which in this commit is done for `nightly` as specified by @monperrus on the linked issue.
Closes #5957
> review: Attest build artifacts

- src/main/java/spoon/reflect/factory/CodeFactory.java
- src/main/java/spoon/reflect/visitor/ModelConsistencyChecker.java
- src/main/java/spoon/support/compiler/jdt/ParentExiter.java
- src/test/java/spoon/reflect/ast/AstCheckerTest.java
- src/test/java/spoon/reflect/visitor/ModelConsistencyCheckerTestHelper.java
- src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java
- src/test/java/spoon/testing/utils/ModelTestParameterResolver.java
This PR might conflict with my other PR #5801
> review: fix: issue #5868 with invalid parents for elements in model

- src/test/java/spoon/test/type/TypeTest.java
- src/test/java/spoon/testing/utils/ByClass.java
- src/test/java/spoon/testing/utils/BySimpleName.java
- src/test/java/spoon/testing/utils/ModelTestParameterResolver.java
This is somewhat an experiment based on our `ModelTest` annotation. We can reduce *arrange* code by extracting required `CtType`s centrally and inject them via parameters. WDYT?
> review: test: easy type access for ModelTests

- src/main/java/spoon/reflect/visitor/CommentHelper.java
I encounter small problem when I tried to output processed classes to disk.
There are comments which I think have sort of bad syntax 
```java
/* (non-Javadoc)
@see com.some.package.SomeObject#getSomeField()
*/
@Transient
public Long getSomeField() {
.......
}
```
Due to missing 'star' in the middle line it is marked as BLOCK comment. Later during processing of printing of comments there is hardcoded CtComment.LINE_SEPARATOR for new lines which will not match rest of the class which is written with system specific new line symbol (windows \r\n\ in my case).
This will mark class as changed in Git due to this change in new line character.
Every where in comments in the code is written that these hardcoded new line \n should not affect how comments are rendered so I guess it is bug.
> review: fix: Use new line symbol from system also for BLOCK comments when printing

- src/main/java/spoon/support/StandardEnvironment.java
- src/test/java/spoon/MavenLauncherTest.java
- src/test/java/spoon/support/compiler/SpoonPomTest.java
- src/test/java/spoon/test/enums/EnumsTest.java
- src/test/java/spoon/test/template/TemplateTest.java
Maybe the current JVM version is a better default compared to 8 or?
> review: feat: read jvm version for default compliance level

- spoon-control-flow/pom.xml
The `junit` dependency is causing test compilation to fail.
> Remove junit dependency in spoon-control-flow

- src/main/java/spoon/support/util/SortedList.java
- src/test/java/spoon/support/util/SortedListTest.java
- Fixes #6034 
- SortedList.addAll(...) should return a boolean value indicating if the Collection was modified is any way as a result of the call
- Previously addAll(...) would return false if only partial changes occurred and would only return true if all elements had been inserted, or if adding an empty list which in not in accordance to the Java JLS/API as documented in https://docs.oracle.com/javase/8/docs/api/?java/util/Collections.html.
> fix: Make SortedList#add return value adhere to List contract

- src/main/java/spoon/reflect/visitor/ElementPrinterHelper.java
- src/main/java/spoon/support/compiler/jdt/JDTCommentBuilder.java
- src/test/java/spoon/test/comment/CommentTest.java
This fixes two or three different bugs:
- Comments inside lambda parameters crashed the comment builder
- Comments before the default expression of a local variable were never printed
- Inline comments appearing on the same line as their element (e.g. `/* foo */ System.exit();`) were never printed
Closes: #6069.
> review: fix: Improve comment handling in lambda parameters and local variables

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java
For the code `(string + string).contains(string)` will remove the parenthesis which results in `string + string.contains(string)`
> review: fix: Fix missing parens for `(string + string).contains(...)`

- flake.lock
- flake.nix
The existing PR by dependabot fails because either the LANG variable has changed, or how java interprets it. On the runner the lang var is `C.UTF-8`, which does not contain all unicode mappings required for the `JavaOutputProcessorTest`. This test creates a file with accents in its name, causing a java file malformed input exception.
Closes #6124
> chore: Update nix lockfile

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
TL;DR: The cast to `(TreeBulderCompiler)` is overly restrictive here.
For a specific use case, I would like Spoon to use a custom JDT parser/compiler. Specifically, I do not care about method bodies in the parsed code as I only focus on the extracted API, so passing `ignoreMethodBodies` to JDT is a _huge_ performance boost in terms of time and memory (30 to 70% faster `buildModel()` on my projects).
My understanding is that Spoon does not and will not provide an "easy" way for clients to provide their own JDT parser/compiler or their own parsing/compiling options to JDT, which is perfectly understandable.
My current solution involves injecting a custom `JDTBatchCompiler` into the `Launcher`. Because `JDTBatchCompiler` depends on the package-private `TreeBuilderCompiler`, one must …
> fix: avoid unnecessary downcast in ReferenceBuilder

- src/main/java/spoon/pattern/Pattern.java
https://github.com/INRIA/spoon/issues/2228
This fixes a few sonarqube warnings in the file `Pattern.java` that were pointed out by the [SonarQube for IDE Plugin](https://plugins.jetbrains.com/plugin/7973-sonarqube-for-ide). Namely, the issues were:
- **java:S1905** (Redundant casts should not be used)
- **java:S1612** (Lambdas should be replaced with method references)
- **java:S1602** (when a lambda expression uses block notation while expression notation could be used)
I believe removing the explicit cast to `Map<...,...>` also seems to get rid of one of the warnings during compile time, so..._yay!_ ?
> refactor: fixing sonarqube issues in Pattern.java

- src/main/java/spoon/ContractVerifier.java
https://github.com/INRIA/spoon/issues/4924
Not entirely sure if this is an acceptable fix because I don't feel _too_ good about using `SuppressWarnings` here (and we generally seem to be against doing that as seen in https://github.com/INRIA/spoon/pull/4925), but the unchecked cast issue here was caused by `(Collection<CtElement>) attributeOfParent...` and `(Map<String, ?>) attributeOfParent`. 
I wasn't sure how to go about fixing these, since they weren't really related to returning `this` or `super.clone()` and a quick Google search wasn't helpful either  (giving suggestions such as [this](https://stackoverflow.com/questions/75959553/how-to-cast-object-to-mapstring-object-avoiding-unchecked-cast-and-illegal-g))-- so I'm more than open to alternative ways of fixing this, if there are …
> refactor: Resolving unchecked-cast warnings in ContractVerifier

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
- src/test/java/spoon/support/compiler/jdt/ReferenceBuilderTest.java
Fix https://github.com/INRIA/spoon/issues/6068
The code is similar to and inspired from the local fix that was submitted in the Github issue/bug-report itself by @josple. 
I have also added a total of 5 test-cases: 1 of which (`testGetTypeReferenceComplexGenericsCase`) failed with the original code, but passes with the new version of the code. 
Included in the test cases are also 3 "sanity check" tests (the last 3) for some of the other things that `getTypeReference` should be doing based on my understanding, though they might not be strictly related to this change. 
Apart from the `null` return check (when the argument is not a type) and the `array` case, I _think_ there should be sanity checks for the other cases of input for `getReferenceType` here (more on why these 2 are absent in …
> fix: ReferenceBuilder.getTypeReference can handle complex type-params in generics

- src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java
- src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java
Whether a targeted expression requires additional parentheses got out of sync in two situations. By deduplicating the code, this can be avoided. This PR also addresses other expressions that need parentheses and adds tests for them.
> review: fix: consolidate and improve targeted expression precedence

- flake.nix
See discussion in https://github.com/INRIA/spoon/pull/6158 for context. 
Based on the [discussion](https://github.com/INRIA/spoon/pull/6158#issuecomment-2667121734) it looks like only the `extraChecks` runtime needs this bump. I've just manually changed that version to 22. Are there any other chores that need to be performed associated with this bump ? 
cc @monperrus @I-Al-Istannen
> chore: Update extraChecks JDK to v23 in flake.nix

- flake.nix
- spoon-pom/pom.xml
Previously spoon-pom used not-existent properties to configure the maven compiler, which tripped up intellij. This patch consistently uses maven.compiler.(test)Release.
> review: Use java 17 for tests

- src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/java/spoon/test/prettyprinter/testclasses/RefactorCast.java
Fix https://github.com/INRIA/spoon/issues/4335
When a piece of code involving a type-cast is refactored and then printed using `SniperJavaPrettyPrinter` (where the `cast` itself is to be printed from the source-code) , we seem to be printing extra parenthesis around the type-cast, leading to non-compilable java code. 
I believe this was occurring because when processing a `CAST` fragment specifically, we by default seem to add extra `(...)` pairs around it [here](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java#L311).
Then, when the `scan` between those 2 additions visits the `SniperJavaPrettyPrinter` scan [here](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/sniper/SniperJavaPrettyPrinter.java#L299), we …
> fix: Correct parenthesis around type-casting for refactored code when using SniperJavaPrettyPrinter

- src/main/java/spoon/refactoring/Refactoring.java
- src/main/java/spoon/support/reflect/declaration/CtCompilationUnitImpl.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
fix #5086 
This PR modifies the `Refactoring.changeTypeName` logic to prevent loss of information from the original class.
The current logic effectively creates a new compilation unit to house the renamed type. However, the type by itself only contains the source code elements for the class. All other `SourceFragment`s outside of the class block, such as imports, comments, and whitespace, are lost in this conversion. The most apparent issue is that `SniperJavaPrettyPrinter` does not have the source context to properly print the full class file after a rename.
This can easily be illustrated with the existing `TestSniperPrinter#testClassRename1` test (which currently does not have assertions for these external elements):
Original input:
```java
package spoon.test.prettyprinter.testclasses; …
```
> review: fix: Ensure CU-level elements are included when renaming a top-level type

- spoon-control-flow/pom.xml
It seems that `spoon-control-flow` was pointing to the wrong parent pom version. Sometimes builds will break. This should fix the versioning, consistent with the other modules.
> Fix spoon-control-flow pom version

- chore/release-beta.sh
- chore/release.sh
- chore/run-with-spoon-javadoc-classpath.sh
- pom.xml
- spoon-javadoc/pom.xml
reviving  #5395 
the top doc change in pom.xml is required by maven-enforcer-plugin
>  chore: ensure in CI that there is no dependency to snapshots

- src/main/java/spoon/support/sniper/internal/AbstractSourceFragmentPrinter.java
- src/test/java/spoon/test/prettyprinter/TestSniperPrinter.java
- src/test/resources/ArithmeticExpressionWithSpaces.java
fix https://github.com/INRIA/spoon/issues/3911
I've highlighted what I believe the issue was in this comment made on the issue: https://github.com/INRIA/spoon/issues/3911#issuecomment-2697135485
The fix here prevents printing spaces before the typecast (ie, something like `...(double)`) if there are no spaces in the original code. If there is a space in the original code, then that should be retained (I've added a new test case for that). Lmk if there are any additional test cases that need to be added too! 
Now, instead of _always_ printing spaces, we *do not* print spaces if *all* of the following conditions are met: 
1. The fragment to be printed after the last printed fragment (which I assume is indicated by `prevIndex` below) is a type-cast. 
2. The current fragment about to be …
> fix: Prevent printing spaces before a type-cast (SniperPrinter)

- src/main/java/spoon/Launcher.java
- src/test/java/spoon/reflect/visitor/DefaultJavaPrettyPrinterTest.java
See discussion here: https://github.com/INRIA/spoon/pull/6226#discussion_r2009030723
I believe this should set the compliance level of Launcher to 17 **always** if not provided, based on the `JSAPResult` documentation [here](https://www.martiansoftware.com/jsap/doc/javadoc/com/martiansoftware/jsap/JSAPResult#getInt(java.lang.String,%20int)).
cc @SirYwell
> chore: Set Launcher's compliance level to 17 for some default-pretty-printer tests

- src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java
Prevent NullPointerException in isIncorrectlyBoundExecutableInNoClasspath when ref.getType() returns null, which can occur in no-classpath mode when analyzing complex enum initializers involving lambdas.
Fixes INRIA/spoon#5579
> fix(noclasspath): Add null check for executable type in ReferenceBuilder

- README.md
Spoon 11 requires JDK17+: https://github.com/INRIA/spoon/pull/5588/files#diff-da6c5ffbf044fe3aff223deb941b61a7cb0506bbc2e2e82e4b15589ec02bbf83
This should be reflected in the documentation.
> Update Java version documentation

- .github/workflows/release-nightly.yml
This is required to test the new release workflow
> chore: Allow workflow dispatch for release-nightly

- jreleaser.yml
Because the [previous SNAPSHOT was released](https://central.sonatype.com/repository/maven-snapshots/fr/inria/gforge/spoon/spoon-core/11.2.2-SNAPSHOT/spoon-core-11.2.2-20250709.200721-1.jar) without even showing up on UI, I have a feeling these options are redundant. @I-Al-Istannen can we give these changes a try and release another SNAPSHOT?
> style: remove redundant options
